In [1]:
library("xgboost")
library("Matrix")
library('Ckmeans.1d.dp')
library('lightgbm')

载入程辑包：‘lightgbm’


The following object is masked from ‘package:xgboost’:

    slice

## Read data and process data labels

In [2]:
time_matrix <- matrix(0,ncol = 3, nrow =4)
colnames(time_matrix) <- c("user_time", "system_time", "elapsed_time")
start_time = Sys.time()

In [5]:
data=read.csv('Daily_features_matrix.csv')
data=data[,2:dim(data)[2]]

In [6]:
dim(data)

[1] 4227   23

In [7]:
head(data)

  frequency nperiods seasonal_period trend     spike        linearity curvature
1 1         0        1               0.9977307 2.180566e-11 31.265883  4.202931
2 1         0        1               0.9753638 2.434650e-09 24.625465 -1.039634
3 1         0        1               0.8937784 8.333451e-06  3.804175  4.843726
4 1         0        1               0.7424974 8.486237e-06  1.762132  6.219671
5 1         0        1               0.9764692 1.782445e-07 11.344076  0.859238
6 1         0        1               0.9963228 8.446153e-11 29.701579 10.112177
  e_acf1    e_acf10   entropy     ⋯ diff1_acf10 diff2_acf1 diff2_acf10 length
1 0.8853252 3.0007563 0.009502084 ⋯ 0.007626758 -0.5188252 0.2734535   1006
2 0.8973350 3.0475729 0.211225819 ⋯ 0.004072618 -0.5203490 0.2801685   1006
3 0.4029370 0.3356327 0.610410200 ⋯ 0.002531199 -0.4987115 0.2487157    130
4 0.4733951 0.4720488 0.740639635 ⋯ 0.058828311 -0.5022730 0.3038757    169
5 0.6058021 0.8285215 0.281090710 ⋯ 0.122022465 -0.4771979 0.3813929    156
6 0.8651846 3.0647427 0.043039068 ⋯ 0.076311068 -0.5852963 0.4167008   1006
  user_time  system_time elapsed_time user_time.1 system_time.1 elapsed_time.1
1 0.02104115 0.02104115  0.02104115   0           0             0
2 0.02027750 0.02027750  0.02027750   0           0             0
3 0.01750016 0.01750016  0.01750016   0           0             0
4 0.02131033 0.02131033  0.02131033   0           0             0
5 0.15410614 0.15410614  0.15410614   0           0             0
6 0.01933837 0.01933837  0.01933837   0           0             0

In [9]:
dlist= load('Daily_nnetar_datalist.RData')
datalist=eval(parse(text = dlist ))
res=datalist[[1]]
MASE=res[,,,6]
m=5

In [10]:
dim(MASE)

[1] 4227    5    4

In [11]:
whichmin<-function(x){
    minx=min(x[x>0])
    loc=which(x==minx)[1]-1
    loc
}

meanunique=function(x)
    {
    mean(unique(x))
}

In [12]:
nanum=c()
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    a=apply(count,1,min)
    if(sum(is.na(a))>0)
        {
        nanum=append(nanum,i)
    }
    }

In [13]:
nanum

NULL

In [14]:
realbestmin=matrix(0,dim(MASE)[1],1)
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    min_value=apply(count,1,min)
    if (max(min_value,na.rm = TRUE)==0){
        realbestmin[i,]=0
        }
    else
        {
        min_value[is.na(min_value)]=100 
        realbestmin[i,]= whichmin(min_value)
    }
    }

In [15]:
table(realbestmin)

realbestmin
   0    1    2    3    4
 637  588  520  604 1878

In [16]:
realbestmean=matrix(0,dim(MASE)[1],1)
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    mean_value=apply(count,1,meanunique)
    if (max(mean_value,na.rm = TRUE)==0){
        realbestmean[i,]=0
        }
    else
        {
        mean_value[is.na(mean_value)]=100 
        realbestmean[i,]= whichmin(mean_value)
    }
    }

In [17]:
realbestmean

      [,1]
 [1,] 4
 [2,] 2
 [3,] 1
 [4,] 3
 [5,] 0
 [6,] 4
 [7,] 4
 [8,] 2
 [9,] 2
[10,] 4
[11,] 4
[12,] 0
[13,] 1
[14,] 4
[15,] 4
[16,] 0
[17,] 0
[18,] 0
[19,] 4
[20,] 0
[21,] 4
[22,] 2
[23,] 1
[24,] 3
[25,] 1
[26,] 1
[27,] 1
[28,] 4
[29,] 4
[30,] 4
[31,] ⋮
[32,] 0
[33,] 4
[34,] 3
[35,] 4
[36,] 1
[37,] 3
[38,] 4
[39,] 2
[40,] 4
[41,] 4
[42,] 4
[43,] 4
[44,] 4
[45,] 4
[46,] 0
[47,] 0
[48,] 1
[49,] 0
[50,] 0
[51,] 3
[52,] 1
[53,] 0
[54,] 0
[55,] 3
[56,] 0
[57,] 0
[58,] 3
[59,] 0
[60,] 3
[61,] 4

In [18]:
head(data)

  frequency nperiods seasonal_period trend     spike        linearity curvature
1 1         0        1               0.9977307 2.180566e-11 31.265883  4.202931
2 1         0        1               0.9753638 2.434650e-09 24.625465 -1.039634
3 1         0        1               0.8937784 8.333451e-06  3.804175  4.843726
4 1         0        1               0.7424974 8.486237e-06  1.762132  6.219671
5 1         0        1               0.9764692 1.782445e-07 11.344076  0.859238
6 1         0        1               0.9963228 8.446153e-11 29.701579 10.112177
  e_acf1    e_acf10   entropy     ⋯ diff1_acf10 diff2_acf1 diff2_acf10 length
1 0.8853252 3.0007563 0.009502084 ⋯ 0.007626758 -0.5188252 0.2734535   1006
2 0.8973350 3.0475729 0.211225819 ⋯ 0.004072618 -0.5203490 0.2801685   1006
3 0.4029370 0.3356327 0.610410200 ⋯ 0.002531199 -0.4987115 0.2487157    130
4 0.4733951 0.4720488 0.740639635 ⋯ 0.058828311 -0.5022730 0.3038757    169
5 0.6058021 0.8285215 0.281090710 ⋯ 0.122022465 -0.4771979 0.3813929    156
6 0.8651846 3.0647427 0.043039068 ⋯ 0.076311068 -0.5852963 0.4167008   1006
  user_time  system_time elapsed_time user_time.1 system_time.1 elapsed_time.1
1 0.02104115 0.02104115  0.02104115   0           0             0
2 0.02027750 0.02027750  0.02027750   0           0             0
3 0.01750016 0.01750016  0.01750016   0           0             0
4 0.02131033 0.02131033  0.02131033   0           0             0
5 0.15410614 0.15410614  0.15410614   0           0             0
6 0.01933837 0.01933837  0.01933837   0           0             0

In [19]:
set.seed(100)
index = sample(2,nrow(data),replace = TRUE,prob=c(0.7,0.3))

In [20]:
train_data=data[index==1,]
test_data=data[index==2,]
train_label_min=realbestmin[index==1,]
test_label_min=realbestmin[index==2,]
train_label_mean=realbestmean[index==1,]
test_label_mean=realbestmean[index==2,]

In [21]:
head(train_data)

  frequency nperiods seasonal_period trend     spike        linearity curvature
1 1         0        1               0.9977307 2.180566e-11 31.265883  4.202931
2 1         0        1               0.9753638 2.434650e-09 24.625465 -1.039634
3 1         0        1               0.8937784 8.333451e-06  3.804175  4.843726
4 1         0        1               0.7424974 8.486237e-06  1.762132  6.219671
5 1         0        1               0.9764692 1.782445e-07 11.344076  0.859238
6 1         0        1               0.9963228 8.446153e-11 29.701579 10.112177
  e_acf1    e_acf10   entropy     ⋯ diff1_acf10 diff2_acf1 diff2_acf10 length
1 0.8853252 3.0007563 0.009502084 ⋯ 0.007626758 -0.5188252 0.2734535   1006
2 0.8973350 3.0475729 0.211225819 ⋯ 0.004072618 -0.5203490 0.2801685   1006
3 0.4029370 0.3356327 0.610410200 ⋯ 0.002531199 -0.4987115 0.2487157    130
4 0.4733951 0.4720488 0.740639635 ⋯ 0.058828311 -0.5022730 0.3038757    169
5 0.6058021 0.8285215 0.281090710 ⋯ 0.122022465 -0.4771979 0.3813929    156
6 0.8651846 3.0647427 0.043039068 ⋯ 0.076311068 -0.5852963 0.4167008   1006
  user_time  system_time elapsed_time user_time.1 system_time.1 elapsed_time.1
1 0.02104115 0.02104115  0.02104115   0           0             0
2 0.02027750 0.02027750  0.02027750   0           0             0
3 0.01750016 0.01750016  0.01750016   0           0             0
4 0.02131033 0.02131033  0.02131033   0           0             0
5 0.15410614 0.15410614  0.15410614   0           0             0
6 0.01933837 0.01933837  0.01933837   0           0             0

In [22]:
end_time = Sys.time()

In [23]:
time_matrix[1,]=end_time-start_time

In [24]:
end_time-start_time

Time difference of 3.256759 mins

## Target the interval where the actual error is minimum

In [25]:
start_time = Sys.time()

In [26]:
dtrain_xg_min_reg <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(train_label_min)) 
dtrain_xg_min_cl <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_min)) )

In [27]:
dtrain_lg_min_reg <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(train_label_min))
dtrain_lg_min_cl <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_min)))

In [28]:
xgb_min_reg <- xgboost(data = dtrain_xg_min_reg, nround=100)

[1]	train-rmse:2.027987
[2]	train-rmse:1.662826
[3]	train-rmse:1.440380
[4]	train-rmse:1.303442
[5]	train-rmse:1.210462
[6]	train-rmse:1.164064
[7]	train-rmse:1.119478
[8]	train-rmse:1.090350
[9]	train-rmse:1.064084
[10]	train-rmse:1.049398
[11]	train-rmse:1.026206
[12]	train-rmse:1.012451
[13]	train-rmse:1.006077
[14]	train-rmse:0.996633
[15]	train-rmse:0.986988
[16]	train-rmse:0.973306
[17]	train-rmse:0.963490
[18]	train-rmse:0.957566
[19]	train-rmse:0.947984
[20]	train-rmse:0.929107
[21]	train-rmse:0.913041
[22]	train-rmse:0.907202
[23]	train-rmse:0.891014
[24]	train-rmse:0.888458
[25]	train-rmse:0.865180
[26]	train-rmse:0.842907
[27]	train-rmse:0.826423
[28]	train-rmse:0.810687
[29]	train-rmse:0.797543
[30]	train-rmse:0.793984
[31]	train-rmse:0.790695
[32]	train-rmse:0.779022
[33]	train-rmse:0.762602
[34]	train-rmse:0.747908
[35]	train-rmse:0.735655
[36]	train-rmse:0.726606
[37]	train-rmse:0.713057
[38]	train-rmse:0.709224
[39]	train-rmse:0.699779
[40]	train-rmse:0.693095
[41]	train-rmse:0.687073
[42]	train-rmse:0.679459
[43]	train-rmse:0.669826
[44]	train-rmse:0.667136
[45]	train-rmse:0.661843
[46]	train-rmse:0.655131
[47]	train-rmse:0.644230
[48]	train-rmse:0.635833
[49]	train-rmse:0.633158
[50]	train-rmse:0.622503
[51]	train-rmse:0.619911
[52]	train-rmse:0.609949
[53]	train-rmse:0.602244
[54]	train-rmse:0.588802
[55]	train-rmse:0.579266
[56]	train-rmse:0.577234
[57]	train-rmse:0.571459
[58]	train-rmse:0.568164
[59]	train-rmse:0.564008
[60]	train-rmse:0.555902
[61]	train-rmse:0.545662
[62]	train-rmse:0.539875
[63]	train-rmse:0.529229
[64]	train-rmse:0.521965
[65]	train-rmse:0.513109
[66]	train-rmse:0.506878
[67]	train-rmse:0.503367
[68]	train-rmse:0.499512
[69]	train-rmse:0.497593
[70]	train-rmse:0.492378
[71]	train-rmse:0.483257
[72]	train-rmse:0.478169
[73]	train-rmse:0.474035
[74]	train-rmse:0.462572
[75]	train-rmse:0.460883
[76]	train-rmse:0.457569
[77]	train-rmse:0.454275
[78]	train-rmse:0.450178
[79]	train-rmse:0.440316
[80]	train-rmse:0.436413
[81]	train-rmse:0.433937
[82]	train-rmse:0.432155
[83]	train-rmse:0.430669
[84]	train-rmse:0.425777
[85]	train-rmse:0.420663
[86]	train-rmse:0.415679
[87]	train-rmse:0.411849
[88]	train-rmse:0.405135
[89]	train-rmse:0.399773
[90]	train-rmse:0.395214
[91]	train-rmse:0.392117
[92]	train-rmse:0.389053
[93]	train-rmse:0.383405
[94]	train-rmse:0.379589
[95]	train-rmse:0.376873
[96]	train-rmse:0.372879
[97]	train-rmse:0.366839
[98]	train-rmse:0.365647
[99]	train-rmse:0.362258
[100]	train-rmse:0.356968

In [29]:
xgb_min_cl <- xgboost(data = dtrain_xg_min_cl, nround=100, objective='multi:softmax',num_class=5)

[1]	train-mlogloss:1.410376
[2]	train-mlogloss:1.282364
[3]	train-mlogloss:1.189361
[4]	train-mlogloss:1.118990
[5]	train-mlogloss:1.062103
[6]	train-mlogloss:1.018212
[7]	train-mlogloss:0.982171
[8]	train-mlogloss:0.943813
[9]	train-mlogloss:0.912143
[10]	train-mlogloss:0.884694
[11]	train-mlogloss:0.864693
[12]	train-mlogloss:0.839466
[13]	train-mlogloss:0.823940
[14]	train-mlogloss:0.807229
[15]	train-mlogloss:0.790135
[16]	train-mlogloss:0.775282
[17]	train-mlogloss:0.752963
[18]	train-mlogloss:0.733967
[19]	train-mlogloss:0.713186
[20]	train-mlogloss:0.698253
[21]	train-mlogloss:0.681386
[22]	train-mlogloss:0.666680
[23]	train-mlogloss:0.652076
[24]	train-mlogloss:0.641488
[25]	train-mlogloss:0.631870
[26]	train-mlogloss:0.620209
[27]	train-mlogloss:0.606954
[28]	train-mlogloss:0.597773
[29]	train-mlogloss:0.588215
[30]	train-mlogloss:0.576998
[31]	train-mlogloss:0.565451
[32]	train-mlogloss:0.558973
[33]	train-mlogloss:0.548585
[34]	train-mlogloss:0.536610
[35]	train-mlogloss:0.525973
[36]	train-mlogloss:0.511632
[37]	train-mlogloss:0.497127
[38]	train-mlogloss:0.487667
[39]	train-mlogloss:0.479287
[40]	train-mlogloss:0.472122
[41]	train-mlogloss:0.461758
[42]	train-mlogloss:0.449166
[43]	train-mlogloss:0.441220
[44]	train-mlogloss:0.431827
[45]	train-mlogloss:0.424051
[46]	train-mlogloss:0.415290
[47]	train-mlogloss:0.404810
[48]	train-mlogloss:0.395226
[49]	train-mlogloss:0.387210
[50]	train-mlogloss:0.376849
[51]	train-mlogloss:0.367323
[52]	train-mlogloss:0.360464
[53]	train-mlogloss:0.355454
[54]	train-mlogloss:0.347312
[55]	train-mlogloss:0.341628
[56]	train-mlogloss:0.334851
[57]	train-mlogloss:0.324221
[58]	train-mlogloss:0.317626
[59]	train-mlogloss:0.313630
[60]	train-mlogloss:0.306582
[61]	train-mlogloss:0.301261
[62]	train-mlogloss:0.293417
[63]	train-mlogloss:0.288999
[64]	train-mlogloss:0.281545
[65]	train-mlogloss:0.276147
[66]	train-mlogloss:0.271574
[67]	train-mlogloss:0.268453
[68]	train-mlogloss:0.264309
[69]	train-mlogloss:0.259610
[70]	train-mlogloss:0.255746
[71]	train-mlogloss:0.251137
[72]	train-mlogloss:0.244872
[73]	train-mlogloss:0.239656
[74]	train-mlogloss:0.235223
[75]	train-mlogloss:0.231103
[76]	train-mlogloss:0.227092
[77]	train-mlogloss:0.222971
[78]	train-mlogloss:0.220171
[79]	train-mlogloss:0.215860
[80]	train-mlogloss:0.212685
[81]	train-mlogloss:0.209969
[82]	train-mlogloss:0.206742
[83]	train-mlogloss:0.201960
[84]	train-mlogloss:0.199473
[85]	train-mlogloss:0.195649
[86]	train-mlogloss:0.193286
[87]	train-mlogloss:0.191055
[88]	train-mlogloss:0.187778
[89]	train-mlogloss:0.184789
[90]	train-mlogloss:0.181551
[91]	train-mlogloss:0.177210
[92]	train-mlogloss:0.174129
[93]	train-mlogloss:0.171161
[94]	train-mlogloss:0.167711
[95]	train-mlogloss:0.165193
[96]	train-mlogloss:0.161124
[97]	train-mlogloss:0.157808
[98]	train-mlogloss:0.153990
[99]	train-mlogloss:0.150318
[100]	train-mlogloss:0.146689

In [30]:
lgb_min_reg <- lgb.train(data = dtrain_lg_min_reg, nrounds = 100)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007420 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4321
[LightGBM] [Info] Number of data points in the train set: 2968, number of used features: 17
[LightGBM] [Info] Start training from score 2.599057

In [31]:
params <- list(objective = "multiclass",
               num_class = 5, 
               metric = "multi_logloss")
lgb_min_cl <- lgb.train(data = dtrain_lg_min_cl,nrounds = 100,params=params)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002479 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4321
[LightGBM] [Info] Number of data points in the train set: 2968, number of used features: 17
[LightGBM] [Info] Start training from score -1.890850
[LightGBM] [Info] Start training from score -1.991757
[LightGBM] [Info] Start training from score -2.090282
[LightGBM] [Info] Start training from score -1.962557
[LightGBM] [Info] Start training from score -0.801958

In [32]:
end_time = Sys.time()
time_matrix[2,]=end_time-start_time

## Target the interval where the average error is minimum

In [33]:
start_time = Sys.time()

In [34]:
dtrain_xg_mean_reg <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(train_label_mean)) 
dtrain_xg_mean_cl <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_mean)) )

In [35]:
dtrain_lg_mean_reg <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(train_label_mean))
dtrain_lg_mean_cl <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_mean)))

In [36]:
xgb_mean_reg <- xgboost(data = dtrain_xg_mean_reg, nround=100)

[1]	train-rmse:1.869672
[2]	train-rmse:1.571892
[3]	train-rmse:1.379696
[4]	train-rmse:1.268615
[5]	train-rmse:1.192463
[6]	train-rmse:1.142021
[7]	train-rmse:1.100392
[8]	train-rmse:1.071533
[9]	train-rmse:1.052859
[10]	train-rmse:1.041077
[11]	train-rmse:1.017936
[12]	train-rmse:1.012150
[13]	train-rmse:1.007281
[14]	train-rmse:0.985220
[15]	train-rmse:0.976359
[16]	train-rmse:0.969913
[17]	train-rmse:0.958445
[18]	train-rmse:0.943752
[19]	train-rmse:0.930829
[20]	train-rmse:0.922388
[21]	train-rmse:0.912746
[22]	train-rmse:0.898744
[23]	train-rmse:0.885598
[24]	train-rmse:0.869420
[25]	train-rmse:0.860246
[26]	train-rmse:0.845617
[27]	train-rmse:0.835644
[28]	train-rmse:0.831253
[29]	train-rmse:0.821113
[30]	train-rmse:0.807212
[31]	train-rmse:0.801160
[32]	train-rmse:0.792933
[33]	train-rmse:0.779930
[34]	train-rmse:0.769462
[35]	train-rmse:0.760781
[36]	train-rmse:0.743212
[37]	train-rmse:0.728918
[38]	train-rmse:0.714716
[39]	train-rmse:0.708303
[40]	train-rmse:0.699530
[41]	train-rmse:0.694466
[42]	train-rmse:0.686142
[43]	train-rmse:0.678210
[44]	train-rmse:0.670675
[45]	train-rmse:0.663793
[46]	train-rmse:0.651287
[47]	train-rmse:0.641051
[48]	train-rmse:0.635330
[49]	train-rmse:0.626426
[50]	train-rmse:0.617801
[51]	train-rmse:0.611386
[52]	train-rmse:0.608950
[53]	train-rmse:0.607213
[54]	train-rmse:0.594101
[55]	train-rmse:0.591652
[56]	train-rmse:0.587941
[57]	train-rmse:0.574951
[58]	train-rmse:0.566685
[59]	train-rmse:0.558322
[60]	train-rmse:0.548658
[61]	train-rmse:0.545856
[62]	train-rmse:0.539832
[63]	train-rmse:0.534405
[64]	train-rmse:0.532978
[65]	train-rmse:0.530930
[66]	train-rmse:0.523030
[67]	train-rmse:0.515967
[68]	train-rmse:0.509312
[69]	train-rmse:0.501798
[70]	train-rmse:0.496760
[71]	train-rmse:0.487537
[72]	train-rmse:0.481301
[73]	train-rmse:0.474304
[74]	train-rmse:0.470862
[75]	train-rmse:0.467425
[76]	train-rmse:0.462485
[77]	train-rmse:0.459727
[78]	train-rmse:0.454377
[79]	train-rmse:0.450953
[80]	train-rmse:0.442839
[81]	train-rmse:0.438343
[82]	train-rmse:0.435641
[83]	train-rmse:0.431050
[84]	train-rmse:0.424942
[85]	train-rmse:0.423794
[86]	train-rmse:0.416637
[87]	train-rmse:0.411716
[88]	train-rmse:0.410007
[89]	train-rmse:0.406745
[90]	train-rmse:0.401456
[91]	train-rmse:0.393854
[92]	train-rmse:0.386913
[93]	train-rmse:0.382632
[94]	train-rmse:0.381358
[95]	train-rmse:0.380341
[96]	train-rmse:0.375007
[97]	train-rmse:0.368527
[98]	train-rmse:0.366249
[99]	train-rmse:0.364514
[100]	train-rmse:0.360806

In [37]:
xgb_mean_cl <- xgboost(data = dtrain_xg_mean_cl, nround=100, objective='multi:softmax',num_class=5)

[1]	train-mlogloss:1.443240
[2]	train-mlogloss:1.331990
[3]	train-mlogloss:1.246444
[4]	train-mlogloss:1.179185
[5]	train-mlogloss:1.117808
[6]	train-mlogloss:1.064281
[7]	train-mlogloss:1.016289
[8]	train-mlogloss:0.979897
[9]	train-mlogloss:0.942395
[10]	train-mlogloss:0.911975
[11]	train-mlogloss:0.888183
[12]	train-mlogloss:0.865912
[13]	train-mlogloss:0.848875
[14]	train-mlogloss:0.831375
[15]	train-mlogloss:0.813440
[16]	train-mlogloss:0.799178
[17]	train-mlogloss:0.781657
[18]	train-mlogloss:0.768463
[19]	train-mlogloss:0.749398
[20]	train-mlogloss:0.729440
[21]	train-mlogloss:0.718572
[22]	train-mlogloss:0.706553
[23]	train-mlogloss:0.688277
[24]	train-mlogloss:0.666778
[25]	train-mlogloss:0.649513
[26]	train-mlogloss:0.637823
[27]	train-mlogloss:0.621786
[28]	train-mlogloss:0.611763
[29]	train-mlogloss:0.600821
[30]	train-mlogloss:0.589723
[31]	train-mlogloss:0.575543
[32]	train-mlogloss:0.563179
[33]	train-mlogloss:0.549655
[34]	train-mlogloss:0.539016
[35]	train-mlogloss:0.528061
[36]	train-mlogloss:0.518266
[37]	train-mlogloss:0.507466
[38]	train-mlogloss:0.496213
[39]	train-mlogloss:0.489631
[40]	train-mlogloss:0.476950
[41]	train-mlogloss:0.464671
[42]	train-mlogloss:0.455468
[43]	train-mlogloss:0.445568
[44]	train-mlogloss:0.437285
[45]	train-mlogloss:0.424028
[46]	train-mlogloss:0.415077
[47]	train-mlogloss:0.404829
[48]	train-mlogloss:0.396730
[49]	train-mlogloss:0.389170
[50]	train-mlogloss:0.381657
[51]	train-mlogloss:0.371295
[52]	train-mlogloss:0.362680
[53]	train-mlogloss:0.357379
[54]	train-mlogloss:0.352325
[55]	train-mlogloss:0.346544
[56]	train-mlogloss:0.340764
[57]	train-mlogloss:0.333959
[58]	train-mlogloss:0.327055
[59]	train-mlogloss:0.319863
[60]	train-mlogloss:0.313553
[61]	train-mlogloss:0.305351
[62]	train-mlogloss:0.300099
[63]	train-mlogloss:0.293804
[64]	train-mlogloss:0.287722
[65]	train-mlogloss:0.281493
[66]	train-mlogloss:0.277381
[67]	train-mlogloss:0.271340
[68]	train-mlogloss:0.264188
[69]	train-mlogloss:0.259828
[70]	train-mlogloss:0.252400
[71]	train-mlogloss:0.244942
[72]	train-mlogloss:0.241360
[73]	train-mlogloss:0.236473
[74]	train-mlogloss:0.231310
[75]	train-mlogloss:0.227171
[76]	train-mlogloss:0.224282
[77]	train-mlogloss:0.220442
[78]	train-mlogloss:0.216140
[79]	train-mlogloss:0.210568
[80]	train-mlogloss:0.207106
[81]	train-mlogloss:0.205034
[82]	train-mlogloss:0.200253
[83]	train-mlogloss:0.195537
[84]	train-mlogloss:0.192103
[85]	train-mlogloss:0.188694
[86]	train-mlogloss:0.185469
[87]	train-mlogloss:0.181281
[88]	train-mlogloss:0.177973
[89]	train-mlogloss:0.174244
[90]	train-mlogloss:0.169404
[91]	train-mlogloss:0.166184
[92]	train-mlogloss:0.164210
[93]	train-mlogloss:0.160793
[94]	train-mlogloss:0.158648
[95]	train-mlogloss:0.155969
[96]	train-mlogloss:0.153155
[97]	train-mlogloss:0.149307
[98]	train-mlogloss:0.147161
[99]	train-mlogloss:0.144665
[100]	train-mlogloss:0.142231

In [38]:
lgb_mean_reg <- lgb.train(data = dtrain_lg_mean_reg,nrounds = 100)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007234 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4321
[LightGBM] [Info] Number of data points in the train set: 2968, number of used features: 17
[LightGBM] [Info] Start training from score 2.246294

In [39]:
params <- list(objective = "multiclass",
               num_class = 5, 
               metric = "multi_logloss")
lgb_mean_cl <- lgb.train(data = dtrain_lg_mean_cl,params=params,nrounds = 100)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002467 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4321
[LightGBM] [Info] Number of data points in the train set: 2968, number of used features: 17
[LightGBM] [Info] Start training from score -1.580547
[LightGBM] [Info] Start training from score -1.739894
[LightGBM] [Info] Start training from score -2.149205
[LightGBM] [Info] Start training from score -1.769107
[LightGBM] [Info] Start training from score -1.104018

In [40]:
end_time = Sys.time()
time_matrix[3,]=end_time-start_time

In [41]:
end_time-start_time

Time difference of 5.932424 secs

## predict

In [42]:
start_time = Sys.time()

In [43]:
alldatalgb <- lgb.Dataset(data = as.matrix(data))
alldataxgb <- xgb.DMatrix(data = as.matrix(data))

In [44]:
xgbregmin=predict(xgb_min_reg,alldataxgb)
xgbclsmin=predict(xgb_min_cl,alldataxgb)
lgbregmin=predict(lgb_min_reg,as.matrix(data))
lgbclsmin=predict(lgb_min_cl,as.matrix(data))

In [45]:
xgbregmin

   [1]  3.8050947189  2.9539706707  2.9009854794  2.1128444672  0.2093249559
   [6]  3.9554514885  3.1195542812  2.2763259411  2.1558077335  3.9081592560
  [11]  3.4743554592  1.9174026251  1.5356433392  3.8615937233  4.4298548698
  [16]  0.2475445867  0.6854084730  1.0544877052  3.9170591831  0.0215129126
  [21]  4.1619005203  1.5611861944  1.7255460024  1.5988490582  3.7279462814
  [26]  2.0625855923  2.4640426636  3.3732721806  4.1897306442  3.4421882629
  [31]  0.1159796268 -1.0288259983  3.8937888145  3.9593715668  3.0379383564
  [36]  4.6947488785  1.9985797405  3.7179219723  2.5038027763  0.2245841622
  [41]  3.9702107906  1.1118648052  2.4955604076  2.1406354904  0.5684389472
  [46]  3.0439021587  2.7377247810  4.6553254128  3.0625772476  3.9265530109
  [51]  3.8834211826  3.3439126015  0.7295902371  3.6342449188  0.3841051459
  [56]  3.1216142178  1.2646620274  2.8540012836  3.9212980270  2.8045797348
  [61]  1.4485447407  1.3101063967  3.3308172226  1.3142261505  2.5541739464
  [66]  3.6738271713  3.6224870682  2.1039509773  0.3449681401  4.0124206543
  [71]  2.9925587177  0.3487843275  3.8631832600  1.4761997461  2.8502659798
  [76]  3.8317558765  3.5476760864  3.6950354576  4.3641362190  2.2174148560
  [81]  3.8958210945  3.9885537624  3.5567314625  2.2007606030  3.7652387619
  [86]  3.7676787376  3.3970570564  3.9624183178  3.8531291485  3.2547268867
  [91]  2.8723175526  3.8246636391  3.9614138603  1.1135541201  2.4687488079
  [96]  3.7301933765  1.3650264740  3.7758142948  2.1796917915  3.4695072174
 [101]  3.8891482353  3.8740110397  3.6606204510  3.4400212765  0.5996722579
 [106]  1.8403687477  1.2205624580  2.8447530270  3.6661772728  3.8049731255
 [111]  3.3483190536  2.6692159176  3.7414577007  3.0220866203  2.0405004025
 [116]  3.0127506256  3.4121363163  1.4738326073  0.6312718987  2.8453738689
 [121]  3.5015327930  3.6724493504  2.5452516079  1.1787153482  0.2468389124
 [126]  0.5595763922  2.7446455956  3.3645699024  3.7888879776  1.3244317770
 [131]  3.0863845348  3.5686929226  3.6026096344  3.0211677551  2.9288091660
 [136]  3.8051166534  2.9043691158  4.0261740685  0.3617223501  2.0257363319
 [141]  2.8347733021  1.9705276489  1.3169766665  3.8052310944  3.6487469673
 [146]  0.2493648529  0.5206634998  2.3288404942  2.5179605484  3.0368216038
 [151]  2.7594015598  1.5656962395  3.4310591221  3.1423976421  2.3420557976
 [156]  1.7267899513  0.6067681313  0.8525158167  3.7633035183  1.9913452864
 [161]  1.0184620619  3.7990248203  1.5077055693  1.0388263464  1.2895313501
 [166]  4.0696377754  0.0756204054  1.7718856335  2.9550967216  1.9721970558
 [171]  0.4940018952  0.6073154211  0.2472689450  1.9521934986  2.9563982487
 [176]  3.7522664070  2.5890750885  4.0912275314  0.8008166552  2.0215709209
 [181]  2.2788116932  1.9473551512  1.8530443907  3.8812735081  3.9394969940
 [186]  3.8273227215  3.0452990532  3.8060066700  2.2649259567  1.0336900949
 [191]  1.9088591337  3.0776469707  2.2710504532  4.1765398979  3.6659789085
 [196]  4.6136121750  0.7797375321  0.4025285840  0.4419832230  3.0455424786
 [201]  3.8887674809  2.5988323689  3.1400480270  2.8472774029  1.0233656168
 [206]  3.6924803257  3.0388233662  3.9882607460  3.8451313972  4.0652499199
 [211]  3.9095888138  1.8094965219  3.4011166096  0.3371165395  3.2381844521
 [216]  3.4928781986  0.7172096968  3.1736104488  3.5805099010  1.3568288088
 [221]  0.0797620639  1.3935524225  3.8706982136  3.0526862144  3.9524605274
 [226]  0.4766156971  0.0912410915  0.4606320262  2.7342255116  3.9180822372
 [231]  4.1240935326  3.5269458294  1.8268767595  2.4070074558  2.9845068455
 [236]  3.1152892113  2.0242180824  3.9477031231  4.2341432571  4.0717921257
 [241]  0.7923899889  3.4991703033  3.1859626770  3.3330771923  2.9779980183
 [246]  3.9550554752  3.1427695751  1.7876358032  0.6035523415  0.1583186835
 [251] -0.0110440925  1.9568163157  1.8357012272  1.2738997936  2.3055155277
 [256]  4.4429492950  1.2092528343  1.5461955070  1.4677888155  1.8556555510
 [261]  3.5531561375  3.1217143536  2.4121978283  3.3237142563  2.4621922970
 [266]  2.9571864605  3.6488497257  3.4111378193  2.9897143841  3.4871008396
 [271] -0.1753366292  2.7484087944  0.0994547978  3.3946509361  2.6713595390
 [276]  3.4070007801  2.4820239544  3.6122717857  2.1445236206  3.6783144474
 [281]  3.8477218151  4.0070090294  3.9393253326  0.0878624320  2.8742225170
 [286]  3.8038520813  3.3216288090  3.4948251247  3.7485227585  3.4386863708
 [291]  3.9109067917  3.8660714626  3.5421562195  2.1755151749  0.7284340858
 [296]  0.2345988452  0.0811706781  1.3787689209  3.6810584068  3.7935774326
 [301]  4.0558838844  0.5348263979  2.2467145920  2.8342413902  2.6657555103
 [306]  2.0781259537  3.5917663574  2.8813018799  1.5410767794  1.7654626369
 [311]  1.7306041718  1.6941331625  2.4214487076  3.7189218998  3.7189121246
 [316]  3.3816304207  2.3528835773  1.8597058058  0.2390454113  1.9141585827
 [321]  0.0963011831  0.1043753251  0.0758432969  1.0032598972  0.2391163856
 [326]  1.0600595474  2.0963580608  1.7375489473  2.0489583015  2.4950792789
 [331]  1.5405198336  1.1197284460  1.1781380177  1.1002534628  1.0881018639
 [336]  2.9167385101  2.9237513542  2.9896149635  2.4838402271  3.9032206535
 [341]  4.0468077660  3.6228766441  3.3799390793  3.9063823223  3.6678977013
 [346]  3.8409905434  3.7616209984  4.4345030785  3.6280562878  4.8499436378
 [351]  3.9892601967  2.9336810112  0.2994098961  2.9793064594  1.3938285112
 [356]  0.4819150567  2.3351089954  0.7720621824  2.7646238804  3.7006080151
 [361]  2.7275705338  3.6461501122  1.6446586847  0.3779983521  0.4496799111
 [366]  2.5058615208  2.9459381104  3.5132601261  3.8156435490  3.0815725327
 [371]  3.7586321831  1.5033165216  2.9060416222  1.2998985052  2.1318233013
 [376]  3.8715310097  3.9057457447  3.6521289349  4.1636996269  1.9765993357
 [381]  3.9080402851  3.9011080265  4.0485086441  3.4192817211  2.6586418152
 [386]  2.2907817364  3.3208322525  3.6424889565  1.7105822563  2.0895178318
 [391]  0.9311988354  3.9305567741  3.5626831055  2.3653120995  1.9944138527
 [396]  3.5599513054  3.5138974190  3.3087646961  3.0183017254  2.9959540367
 [401]  2.4251406193  3.0889029503  3.9092342854  1.6914136410  3.0142433643
 [406]  0.2687499225  1.8911541700  2.5488398075  3.4427535534  2.9988157749
 [411]  2.4487290382  3.3132314682  0.6955704093  2.1624815464  0.1090258434
 [416]  2.7120447159  2.8907785416  2.6321787834  0.1415264159  1.8304445744
 [421]  1.8730462790  4.0059394836  1.3084719181  2.6621267796  3.5294783115
 [426]  3.5843610764  0.2517098188  1.8439096212 -0.0734903067  2.0114004612
 [431]  3.3839678764 -0.0069811805  1.0538690090  3.2426071167  0.1433277130
 [436]  1.6483258009  1.6305059195  2.4547784328  2.0495436192  3.1495385170
 [441]  3.9762520790  2.2944741249  1.2949727774  3.7500481606  3.5679187775
 [446]  2.2209413052  4.2237782478  3.0041341782  4.0286555290  1.8289910555
 [451]  1.0192111731  0.8192729950  2.5397748947  2.4814829826  3.7996392250
 [456]  3.9253387451  2.3001060486  3.5583996773  3.9516649246  3.5342650414
 [461]  1.2505578995  2.1824088097  2.0471549034  0.7727910876  3.9976341724
 [466]  1.3580948114  3.0776576996  2.5143258572  2.3818125725  3.7022655010
 [471]  2.4370865822  3.0032749176  2.7581996918  2.9809346199  1.9972832203
 [476]  2.7040896416  1.7859376669  3.5436239243  3.7944850922  3.7628648281
 [481]  3.8162734509  2.2319335938  0.9434784651  2.6929593086  3.5070824623
 [486]  2.1340868473  1.1095553637  3.7884628773  3.6496143341  4.2499523163
 [491]  1.6043778658  2.9451353550  2.2857878208  3.8248324394  2.7182545662
 [496]  3.3982656002  3.9462633133  2.9827022552  0.7314687371  3.4521980286
 [501]  1.2433965206  1.1050972939  1.7221662998  0.1815452427  0.7976022363
 [506]  3.8100726604  1.8329946995  1.1333003044  1.4036549330  3.2679393291
 [511]  3.1106123924  1.2791961432  0.2555083930  0.2081540823  0.6835598350
 [516]  0.2532295883  3.6983542442  0.2119016349  0.4975233376  0.3839474618
 [521]  0.0356640182  2.6128439903  3.2933528423  0.1390186995  2.7396986485
 [526]  2.2616536617  2.1563177109  3.6929459572 -0.0936696157  2.9909901619
 [531]  3.6195747852  0.5695230365  0.0024914443  0.2649347186  3.7970545292
 [536]  3.5900962353  2.8283123970  3.0041198730  0.5043609142  3.3465871811
 [541]  3.8133018017  2.9348533154  2.2894074917  1.2463600636  0.4173358679
 [546]  1.8586695194  1.1714203358  1.1876326799  1.6433839798  0.5036016107
 [551]  1.4448809624  2.5332927704  1.0483595133  1.9910624027  2.7449576855
 [556]  1.5185317993  1.3298066854  0.5548558831  3.7765314579  0.2187010944
 [561]  2.9892573357  3.7233626842  0.6536880732  2.7322838306  2.8536288738
 [566]  3.3236064911  2.1734201908  3.7906515598  2.8718981743  2.3858985901
 [571]  0.6612510681  2.1865537167  1.1848201752  3.3586173058  1.3814588785
 [576]  3.0554282665  2.7081515789  2.7585177422  3.9437644482  2.1716289520
 [581]  0.5817713737  0.3644906878  3.5287647247  1.9816726446  3.9221494198
 [586]  2.8383238316  4.0704007149  0.3875005245  0.2160972655 -0.8457582593
 [591]  3.8133075237  3.9816122055  3.9234271049  4.4327025414  3.0296807289
 [596] -0.8704627156  2.9318685532  3.5214660168  3.8377501965  3.8798038960
 [601]  4.1251759529  3.9047956467  3.8484482765  1.0009669065  4.0532832146
 [606]  3.9797263145  3.7597444057  3.9484310150  4.0183339119  3.7242670059
 [611]  4.1242480278  0.0215572808  3.6274523735 -0.8680636883 -0.0750789046
 [616]  0.0499127209  0.1560827196  0.0648349747 -0.0641639978 -0.1837419868
 [621] -0.7889648676 -0.2820420861 -0.0073592467 -0.0073592467  0.0729082152
 [626]  3.9800579548 -0.1931684911 -0.4922719300  1.2619909048  2.6559534073
 [631]  3.7778198719  3.8832077980  3.7345097065  1.6658245325  2.9199376106
 [636]  3.0448257923  2.5710928440  3.3456103802  2.3577630520  3.6944251060
 [641]  2.1727609634  2.4900891781  2.5255837440  3.5033016205  2.8367378712
 [646]  2.4744775295  3.4472384453  2.3871307373  1.2556849718 -0.1263288110
 [651]  2.2760069370  3.0683839321  2.8191075325  1.4181261063  0.5386313796
 [656]  3.0136632919  1.9803342819  1.5827125311  3.1468124390  3.5342714787
 [661]  3.6972241402  2.2687630653  0.7345765829 -0.0054019652  3.4851796627
 [666]  3.0643010139  2.9592185020  1.6293004751  3.5052731037  0.2898353338
 [671]  2.2555565834  1.0132130384  3.9500417709  2.0618352890  3.4949672222
 [676]  1.4326045513  4.0437011719  1.2907906771  3.8630049229  3.0020918846
 [681]  0.8844481707  4.0693516731  0.0484765470  0.3513165414  3.9789876938
 [686]  2.1574509144  0.3393954635  1.9382706881  4.1241207123  2.4368574619
 [691]  0.4992885292  0.8238880038  4.0131359100  3.9630064964  4.0523657799
 [696]  0.5085495710  0.8740566969  2.5917217731  3.9722704887  0.9212352037
 [701]  1.3023787737  3.9734930992  0.5972358584  3.9604191780  1.0651910305
 [706]  4.0062174797  4.1205081940  0.8883472085  1.0166916847  4.0173945427
 [711]  4.0994019508  0.7086693645  0.3605328500  3.9287264347  2.7700262070
 [716]  1.4033184052  0.3694818616  3.9176137447  4.1316251755  4.0120701790
 [721]  3.8746736050  3.8568868637  2.3019742966  3.9868717194  1.6288007498
 [726]  3.9550864697  1.3910193443  1.1938086748  4.0463099480  3.9218823910
 [731]  3.3134179115  3.9200196266  2.1894795895  2.8336336613  3.6480281353
 [736]  3.9516842365  3.9653775692  0.2585515976  2.1744604111  0.4624096155
 [741]  0.4136188924  0.5623389482  2.7848403454  0.2689853609  1.6528395414
 [746]  0.1006818786  1.2198845148  3.6598162651  3.4668090343  0.2534538209
 [751]  0.0489292443  1.8625000715  0.2460940778  0.1760386676  0.0839682594
 [756]  2.0040161610  0.0540378205  0.8773087859  2.2386283875  0.3263838589
 [761]  1.7493007183  2.0028283596  1.2844231129  1.9118887186  3.8745644093
 [766]  0.0768978596  0.9449077249  1.0557500124  2.9180603027  3.6599073410
 [771] -0.2467637956  1.8440383673  0.7698636055  0.5097256303  3.2044696808
 [776]  2.3551375866  2.2017431259  1.0422163010  3.2716736794  0.9564324021
 [781]  3.5944950581  2.0486538410 -0.1599977314  2.6358528137  0.3526131213
 [786]  0.1212228909  3.1305916309  1.3824017048  0.3313206136  3.4783501625
 [791]  0.2363571823  3.9607071877  0.9232991338  3.7482240200  0.8382273912
 [796]  3.3906633854  3.9269649982  0.2386291325  3.5448472500  1.5167562962
 [801]  3.8237948418  4.0061774254  3.7393684387  3.9832844734  2.4793999195
 [806]  4.1000175476  3.9712493420  1.2856038809  2.9087209702  2.3608996868
 [811]  2.4057924747  0.4676413834  3.7554526329  1.1415206194  4.0071873665
 [816]  4.0321798325  1.2883422375  1.2388118505  1.2883422375  3.9621798992
 [821]  1.6590909958  3.4077925682  3.5415239334  0.6841968298  3.0410699844
 [826]  1.0536607504  3.6594638824  1.2953578234  1.2505683899  2.0276362896
 [831]  3.5598680973  2.3772621155  3.7925798893  0.4355019033  3.7803349495
 [836]  2.6735508442  3.9338958263  0.0526578948  3.5871455669  3.9017188549
 [841]  3.2535870075  3.9808154106 -0.3266888857  3.7271726131  2.1045453548
 [846]  1.3636219501  1.0271917582  2.9484391212  2.0583631992  1.9069067240
 [851]  2.7768661976  0.5828909278  1.1248471737  2.6111977100  2.8370604515
 [856]  2.7176449299  3.8731417656  3.6786890030  0.3377197981  3.5579152107
 [861]  2.4985003471  3.8657519817  3.2824769020  2.4639508724  3.1211645603
 [866]  1.6760650873  0.7558543086  0.3705604672  1.1840666533 -0.0714927390
 [871]  0.3867553473  2.4010972977  2.8565778732  2.1033005714  0.2819735408
 [876] -0.0732906535  0.2782883942  0.0944842771  1.1106581688 -0.3266888857
 [881]  1.6012558937 -0.0504701063  0.2671549618  0.2618252933  0.9797248244
 [886]  0.7981355190  0.9938872457 -0.0504701063  0.2765434384  3.0685441494
 [891]  0.0101039857  0.1324576139  4.0401749611  0.1404820234  0.1826501191
 [896]  4.0441255569  1.0059963465  1.9636884928  0.8275871873  3.2248466015
 [901]  1.2927258015  3.8662428856  3.5657577515  3.9785015583  1.5088310242
 [906]  0.1289082915  1.0755320787  3.3308160305  1.6348507404  1.1607730389
 [911]  1.1124722958  1.1615742445  3.8181686401  3.8181686401  2.3510694504
 [916]  3.1256339550  3.4608261585  3.2058837414  2.7196173668  1.9473162889
 [921]  1.1175477505  3.5672221184  3.1256339550  1.3147158623  3.7179427147
 [926]  3.4516565800  3.9584879875  2.6462104321  3.5672221184  1.6880563498
 [931]  3.1263318062  2.2964572906  3.8790402412  3.8845927715  1.3280605078
 [936]  2.4896945953  3.7422647476  2.0191464424  3.8832426071  3.8036606312
 [941]  1.1306449175  1.0960127115  3.8303899765  1.2251799107  2.1571121216
 [946]  0.9744787216  3.2243094444  0.7983689904  2.8161919117  0.9535017610
 [951]  0.9643403292  1.6965088844  2.8274893761  1.5320142508  0.4850459099
 [956] -0.0120788664  2.0605974197  1.1464005709  0.3423894644  0.9472337961
 [961]  0.3423894644 -0.0953129977  1.4795701504  1.1550236940  0.3785848320
 [966]  0.3994980752  1.1744681597  0.4523925185  1.1938310862  1.0555893183
 [971]  1.0783578157  0.2727789879  3.5414752960  1.0626384020  0.9323360324
 [976]  2.1569280624  1.1390510798  1.1341155767  1.1210424900  3.9356858730
 [981]  0.7635868788  0.1290315837  0.9964349866  1.9444509745  1.0320687294
 [986]  2.3159778118  2.7121710777  3.1211974621  1.6242408752  3.0254690647
 [991]  0.3318686187  1.8216705322  1.2088198662  3.9269342422  1.4503512383
 [996]  2.1921522617  0.2258181274  0.5836071372  1.5201992989  0.8781962395
[1001]  0.1268261671  3.7315304279  0.9339951277  2.3542943001  0.0111311600
[1006]  0.2828021348  3.4237911701  3.8389682770  3.5393152237  1.5199778080
[1011]  3.3231196404  3.6218535900  0.1504523903  3.8381977081  1.8745220900
[1016]  2.0607116222  1.3557778597  3.1415138245  3.6247603893  2.8002686501
[1021]  0.8495833278  3.3355934620  3.8249588013  3.9304876328  1.9196850061
[1026]  3.8319826126  0.0593273193 -0.1100592539  1.5252090693  1.9617538452
[1031]  2.1583945751  0.7421587706  3.4505066872  0.2345154583  2.6863186359
[1036]  0.1316934377  2.7084729671  0.0165510587  0.6813250184  0.9444360137
[1041]  1.1117949486  0.1966798156  2.0003938675  1.3072867393  3.2037246227
[1046]  3.0260565281  0.7214275002  0.8875322938  3.2904894352  3.6819994450
[1051]  3.0995311737  3.0175116062  3.9657807350  1.1292690039  3.0097570419
[1056]  2.0388517380  2.1459968090  3.0737261772  2.8300011158  2.6967093945
[1061]  0.8122280240  4.0709753036  3.3160924911  3.4509086609  3.9413046837
[1066]  3.0780694485  3.3969070911  2.2930359840  1.2789934874  3.9639217854
[1071]  3.9287230968  0.1998147368  1.0784668922  0.5459121466  1.7215588093
[1076]  3.0016050339  0.3964754045 -0.1643215716  2.4021873474  0.4000349343
[1081]  0.2171687782  0.4101455510  1.0163420439  0.9561768174  3.4419543743
[1086]  0.3365513682  0.4529777467 -0.9771207571  1.1086908579  0.0651207566
[1091]  0.8683967590  0.3602101505 -1.0889847279  1.0859268904  3.9783389568
[1096]  2.2977752686  0.4331173301  3.9307699203  3.3945493698  3.7492015362
[1101]  2.8818731308  2.3583309650  2.3176677227  1.9806758165  3.7556934357
[1106]  3.8749196529  2.0940549374  1.5135961771  3.7533597946  4.0579586029
[1111]  3.6680843830  0.9244040847  0.0059900382  1.7109258175  1.5333710909
[1116]  2.6407577991  0.8367750049  1.7608095407  3.4114863873  3.9464714527
[1121]  3.4506914616  2.0394201279  1.3555573225  2.6551437378  3.9207625389
[1126]  3.8163309097  3.5190851688  1.0702472925  0.2650046647  0.6375897527
[1131]  0.8557124734  0.9645181894  2.1630108356  0.6268613338  3.4449448586
[1136]  2.0973613262  1.2070335150  1.4292402267  0.9082891941  1.1481738091
[1141]  1.1009955406  3.0307018757  2.5137887001  1.6659349203  0.1800003648
[1146]  1.1114100218  2.4154775143  3.4544460773  3.3056740761  1.7455698252
[1151]  0.5238978267  2.0253694057  0.7376883626  1.0636749268 -0.1231178343
[1156]  0.1174162999 -0.1991092265  0.0019523799  0.8003979921  0.0784987137
[1161]  0.1198941842  1.9598442316  0.3245315552  1.0428061485  0.0641283914
[1166]  1.1734037399  1.3856272697 -0.1080962941  0.2115522027  0.0244886708
[1171]  0.6287459135  0.0590756610  1.2773624659  0.0388571024  2.1125421524
[1176] -0.4185890257  1.8432036638  1.8200993538  1.6171430349  0.4137125313
[1181]  1.0274055004  1.8147884607  1.8238457441  0.2082988769  1.3015662432
[1186]  1.1297525167  3.8361923695  3.1460943222  0.2850028872  3.5506958961
[1191]  3.5736625195  3.2921297550  3.3512473106  0.9092300534  0.0916172266
[1196]  3.7021205425  3.8851008415  2.1589806080  2.4905476570  0.2030005008
[1201]  1.2957679033  1.0467243195  3.8970773220  3.9558153152  3.4620254040
[1206]  3.8880927563  2.3792989254  4.0410857201  0.9281889200  1.2368652821
[1211]  4.0417156219  3.9734201431  0.4459127188  3.8102285862  0.3697453737
[1216]  3.9549155235  4.0381569862  3.8417818546  4.1591219902  3.0998733044
[1221]  3.9824352264  3.9305419922  3.9007458687  0.8033939004  3.6647253036
[1226]  1.6138304472  3.7477567196  4.0924630165  4.0202546120  3.4673004150
[1231]  0.1345293373  1.8399615288  0.1713745743  3.7893025875  1.3911849260
[1236]  1.1416400671  0.2693577111  2.5319371223  1.3647997379  2.4705336094
[1241]  1.6703073978  0.9896717072  0.1515698433  0.1658188701  3.8338317871
[1246]  1.8388363123  0.6302657127  3.3984475136  2.9698538780  2.1698529720
[1251]  2.2544031143  1.4033418894 -1.3740590811  2.0618405342 -0.0764414966
[1256]  2.4037754536  1.0112786293  0.1902255714  0.0632141456  0.3484929502
[1261]  0.1037299708  1.0111857653 -0.2803048491  0.2824737728  1.1841549873
[1266]  1.1766661406  1.9169368744  0.4581196010 -0.2320729196 -0.2312047631
[1271]  1.7336171865 -0.2607564032  1.1661928892  4.0205659866  1.6587492228
[1276]  3.8079421520  0.9676966667  4.0737996101  4.1118860245  3.7722182274
[1281]  4.0942893028  3.8678431511  3.5952360630  4.1118860245  4.0297660828
[1286]  4.0125989914  1.2200851440  3.8063311577  3.9336106777  3.9981057644
[1291]  3.9772634506  1.4771096706  4.0784401894  0.7275596857  3.9553663731

In [46]:
xgbclsmin

   [1] 4 3 3 2 0 4 4 2 2 4 4 4 1 4 4 0 0 0 4 0 4 2 1 2 4 2 4 4 4 4 0 0 4 4 3 4 2
  [38] 4 4 0 4 4 4 4 0 3 3 3 3 4 4 4 0 4 0 3 0 3 4 3 1 1 4 1 3 4 4 2 0 4 3 0 4 4
  [75] 3 4 4 4 4 2 4 4 4 4 4 4 4 4 4 4 4 4 4 1 1 4 1 4 2 4 4 4 4 4 0 2 2 4 4 4 4
 [112] 4 4 3 4 3 4 0 0 4 4 4 3 1 0 0 4 4 4 1 3 4 2 3 3 4 3 4 0 2 3 2 1 4 4 1 2 2
 [149] 3 3 2 1 4 3 2 4 4 0 4 2 4 4 1 1 1 4 0 4 4 0 0 0 0 4 0 4 4 4 0 2 2 4 4 4 4
 [186] 4 3 4 2 2 4 3 1 4 4 4 0 0 0 4 4 4 4 4 1 2 4 4 4 4 4 4 4 0 4 4 2 4 4 1 0 1
 [223] 4 4 4 0 0 0 3 4 4 4 4 3 3 3 2 4 4 4 0 3 3 3 3 4 3 1 0 0 0 1 1 1 1 4 1 1 1
 [260] 2 4 4 2 4 4 4 4 4 4 4 0 4 0 4 3 4 2 4 1 4 4 4 4 0 3 4 4 4 4 4 4 4 4 2 0 0
 [297] 0 0 4 4 4 0 4 3 3 4 4 3 1 4 1 1 2 4 4 4 2 0 0 0 0 0 0 0 0 2 2 2 2 2 1 1 1
 [334] 1 1 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 3 0 3 1 0 4 0 4 4 3 4 4 0 0 3 3 4 4 4
 [371] 4 1 3 1 2 4 4 4 4 4 4 4 4 4 2 2 4 4 0 2 1 4 4 2 2 4 4 4 4 3 2 3 4 1 2 0 2
 [408] 4 2 3 2 4 0 1 0 4 3 4 0 4 4 4 4 4 4 4 0 3 0 2 4 0 1 3 0 4 4 0 2 2 4 2 1 4
 [445] 4 0 4 3 4 2 1 1 4 4 4 4 4 4 4 4 1 4 4 4 4 1 3 2 2 4 2 3 3 4 1 4 1 4 4 4 4
 [482] 2 1 3 4 2 1 4 4 4 2 4 2 4 3 4 4 4 2 4 1 2 1 0 0 4 0 1 1 3 4 1 0 0 0 0 4 0
 [519] 1 0 0 1 3 3 3 2 2 4 2 3 4 2 2 2 4 4 3 3 2 4 4 3 2 1 0 2 1 1 1 4 1 2 1 2 2
 [556] 4 0 0 4 0 4 4 0 4 4 4 4 4 4 4 0 2 2 4 1 3 4 3 4 2 2 0 4 2 4 4 4 4 0 0 4 4
 [593] 4 4 4 0 4 3 4 4 4 4 4 0 4 4 4 4 4 4 4 0 4 0 0 0 0 0 0 0 0 0 0 0 0 4 0 2 1
 [630] 3 4 4 4 2 3 3 3 4 4 4 2 2 0 4 3 2 4 4 1 0 2 3 3 2 2 3 2 2 3 4 4 2 2 2 4 3
 [667] 3 1 4 2 2 0 4 2 4 1 4 1 4 3 4 4 0 4 4 3 4 3 4 2 0 4 4 4 4 4 2 2 4 4 1 4 4
 [704] 4 1 4 4 1 4 4 4 4 1 4 3 1 4 4 4 4 4 4 4 4 1 4 2 4 4 4 4 4 3 3 4 4 4 4 4 1
 [741] 0 0 4 0 0 0 2 4 4 0 0 2 0 0 0 2 0 1 2 1 2 4 1 2 4 0 1 2 3 4 0 1 0 3 3 4 3
 [778] 1 4 1 4 2 0 3 1 0 3 1 0 4 2 4 1 4 1 3 4 0 4 4 4 4 4 4 4 4 4 4 3 4 4 0 4 4
 [815] 4 4 4 1 4 4 4 4 4 2 4 4 4 1 1 2 4 2 4 2 4 3 4 0 4 4 3 4 0 4 2 4 4 3 2 2 4
 [852] 0 1 3 3 4 4 4 0 4 4 4 4 4 4 2 1 1 1 0 0 4 3 2 1 1 2 0 1 0 2 1 0 0 2 0 1 1
 [889] 1 4 1 1 4 0 0 4 1 2 1 4 1 4 4 4 4 1 1 4 1 1 1 1 4 4 1 3 4 3 3 2 4 4 3 4 4
 [926] 4 4 4 4 4 3 4 4 4 4 4 4 4 4 4 4 0 4 1 1 4 4 1 3 1 2 0 3 2 2 0 2 1 0 3 0 0
 [963] 2 1 0 0 1 2 1 2 1 0 4 4 1 2 1 1 1 4 2 0 1 2 1 2 3 3 1 4 0 2 1 4 1 4 0 0 1
[1000] 4 0 4 1 2 0 0 4 4 3 4 3 4 1 4 4 2 1 3 4 4 0 4 4 4 0 4 0 0 4 2 0 0 4 0 3 0
[1037] 3 0 0 1 1 0 4 0 4 4 0 4 4 4 3 3 4 1 3 2 1 3 4 4 0 4 4 4 4 3 4 2 4 4 4 0 4
[1074] 0 1 4 4 0 0 0 4 0 1 1 4 0 0 0 1 0 1 0 1 1 4 4 2 4 4 4 3 4 4 4 4 4 2 4 4 4
[1111] 4 1 0 4 1 4 4 4 4 4 4 2 2 3 4 4 4 1 2 2 1 1 2 1 4 2 1 2 1 1 0 4 3 0 1 1 2
[1148] 4 4 1 2 2 0 1 1 0 0 0 0 0 0 2 0 1 0 1 2 0 0 0 1 0 1 0 2 1 4 0 2 0 1 2 2 0
[1185] 1 1 4 4 2 4 4 4 4 0 0 4 4 2 4 0 4 4 4 4 4 4 4 4 4 4 4 4 4 4 0 4 4 4 4 3 4
[1222] 4 4 0 4 1 4 4 4 4 2 2 0 4 1 1 2 2 1 2 4 1 0 0 4 2 2 4 3 2 2 1 4 2 0 4 1 1
[1259] 1 0 1 1 1 0 1 1 2 0 2 1 2 2 1 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
[1296] 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 0 0 4 2 0 0 2 0 2 4 2 4 0 2 0 0 4 1 4 2 2
[1333] 4 2 2 0 2 4 0 4 4 4 4 4 4 1 1 1 1 0 4 0 2 4 2 4 4 0 4 1 4 1 0 2 2 0 2 2 2
[1370] 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 2 1 2 1 0 1 1 1 1 0 0 0 0 0 0 0 1 1 2 1 0 0
[1407] 0 1 0 2 0 0 0 0 0 0 0 4 0 0 1 1 0 1 0 2 1 4 4 4 4 4 4 0 4 2 3 4 4 4 4 4 4
[1444] 0 1 4 4 3 4 2 1 4 3 4 2 4 4 3 3 4 4 2 2 3 0 2 0 4 4 4 4 4 4 4 4 4 3 4 4 4
[1481] 4 4 4 2 4 4 2 4 4 4 4 4 4 4 0 4 3 0 4 0 4 4 1 3 0 3 4 4 4 0 4 0 4 0 4 4 0
[1518] 1 4 4 4 4 4 0 0 0 4 4 2 1 1 2 2 2 1 1 1 1 1 2 2 2 2 1 2 0 1 1 2 2 2 1 1 2
[1555] 2 2 2 1 1 2 2 2 2 2 2 1 2 2 1 2 2 1 4 4 2 2 4 1 2 4 2 2 1 1 1 1 1 2 4 2 1
[1592] 2 1 2 1 4 2 1 4 2 2 4 4 4 4 0 4 4 4 3 3 4 4 1 4 0 1 4 1 3 3 4 4 1 4 4 4 4
[1629] 4 2 1 4 4 0 4 4 4 4 4 4 3 3 4 4 4 2 2 2 4 4 3 4 4 4 0 0 2 4 4 4 0 0 4 4 4
[1666] 0 4 4 0 4 4 4 4 1 4 4 4 4 4 2 4 2 4 3 4 4 4 3 4 4 4 4 4 4 4 4 4 0 3 2 4 4
[1703] 4 4 2 1 4 3 4 4 4 4 4 2 4 4 4 4 3 1 4 4 4 0 4 2 0 4 1 4 4 4 4 4 4 4 4 4 4
[1740] 3 4 4 4 4 4 3 4 3 3 2 4 3 0 4 1 4 2 4 4 4 3 4 3 1 4 0 4 3 4 4 4 4 2 0 4 4
[1777] 0 4 4 4 4 4 4 1 3 4 0 3 4 4 4 0 2 0 2 2 4 3 3 0 3 4 4 4 0 4 4 4 4 4 4 3 4
[1814] 2 4 4 4 4 0 4 4 4 4 4 4 0 2 4 4 4 3 3 4 4 1 0 2 0 3 0 0 2 4 1 4 4 4 4 4 3
[1851] 3 3 0 1 4 1 2 0 0 4 4 4 0 4 4 4 4 1 4 2 4 4 0 0 4 0 4 2 2 1 4 2 4 4 2 4 4
[1888] 4 0 1 4 4 2 3 0 2 1 0 3 4 1 4 1 1 0 2 1 1 0 0 0 0 4 3 0 4 4 4 4 4 4 2 3 4
[1925] 4 4 4 0 4 3 4 3 4 3 4 4 4 4 4 3 0 4 1 0 2 4 4 4 0 2 4 4 3 3 3 4 4 0 4 4 4
[1962] 4 4 3 1 4 4 4 4 0 4 4 4 2 4 1 4 4 4 4 3 4 3 4 4 4 3 0 2 4 1 2 4 3 4 3 2 2
[1999] 4 1 4 4 4 3 0 0 4 3 4 4 0 1 4 3 1 4 4 1 1 1 4 2 3 3 3 4 4 1 4 4 3 4 0 0 4
[2036] 4 3 4 4 4 3 3 4 0 0 4 4 4 4 4 3 2 4 2 1 0 4 4 3 2 4 1 0 2 0 4 3 1 1 4 3 4
[2073] 4 4 4 4 4 4 0 4 2 4 4 4 4 4 4 4 4 4 3 4 2 4 4 4 0 4 4 4 4 4 3 4 0 3 4 0 4
[2110] 0 4 3 4 3 4 4 4 4 3 4 4 4 3 1 1 4 0 4 2 3 4 4 4 0 3 4 4 4 4 4 4 2 2 1 0 0
[2147] 4 3 3 4 2 0 4 3 4 3 4 3 4 3 4 0 1 2 1 0 0 4 1 4 3 4 4 4 4 4 4 4 4 4 4 4 4
[2184] 3 0 4 2 4 0 4 4 4 0 4 0 1 2 2 4 1 3 4 4 2 4 4 4 4 0 3 0 1 4 4 4 4 1 4 4 3
[2221] 3 2 0 0 2 2 0 0 2 2 4 4 4 2 1 4 0 4 4 2 1 4 2 4 0 2 4 2 4 4 4 2 4 4 0 4 3
[2258] 4 1 4 1 3 2 2 0 0 3 4 4 3 4 3 4 0 0 4 1 4 4 4 1 1 1 4 2 1 3 3 2 3 4 4 2 4
[2295] 4 0 3 2 1 0 0 1 4 4 2 1 3 3 3 3 0 1 4 4 2 4 2 0 4 1 2 2 1 4 2 3 4 0 3 4 2
[2332] 2 3 2 4 1 4 4 4 3 2 4 4 1 1 1 2 4 4 3 3 4 4 4 4 4 4 4 1 4 4 4 4 2 3 4 2 4
[2369] 4 4 4 4 4 4 4 4 4 4 1 1 4 4 2 4 4 4 3 4 1 1 2 4 1 4 4 4 2 4 0 4 4 4 4 0 4
[2406] 4 2 4 1 1 0 4 2 4 3 4 4 4 4 4 0 4 4 0 4 0 4 0 2 4 3 3 4 4 4 4 3 2 1 4 4 4
[2443] 4 2 4 1 4 4 4 1 4 4 4 3 4 0 2 4 4 4 4 4 4 4 2 4 2 4 4 4 4 0 4 4 4 0 1 2 1
[2480] 1 3 2 1 4 4 4 4 4 2 2 0 1 0 0 1 4 4 3 4 4 4 2 0 0 1 2 0 4 4 4 2 4 4 4 1 4
[2517] 1 4 4 0 4 1 4 0 4 4 4 1 3 4 4 0 0 0 0 3 4 4 1 4 4 4 0 3 4 1 4 2 0 3 4 0 4
[2554] 2 3 4 4 3 4 2 4 4 1 2 1 1 0 1 1 1 1 0 1 4 0 0 4 1 1 0 0 3 1 3 4 2 2 4 1 4
[2591] 4 2 2 0 3 4 4 4 4 4 4 2 0 4 4 2 4 3 0 1 4 4 1 4 1 4 1 3 4 3 4 3 4 0 2 4 1
[2628] 4 4 4 4 4 4 4 4 3 4 2 4 4 4 0 0 4 0 0 0 2 4 4 3 2 4 4 4 4 1 4 2 4 4 4 1 1
[2665] 4 2 4 4 4 4 4 4 4 4 0 4 3 4 4 4 4 3 4 4 1 4 2 4 3 4 4 0 4 4 4 4 1 4 4 4 4
[2702] 4 1 4 3 4 4 4 4 4 4 4 4 2 3 4 1 1 0 4 4 4 4 3 4 0 4 4 4 2 4 3 4 4 4 0 0 4
[2739] 4 4 4 4 0 2 4 4 4 4 4 3 4 1 4 4 2 4 0 3 3 2 4 4 4 2 4 4 4 0 2 1 1 0 4 2 1
[2776] 2 1 4 4 4 2 4 2 2 4 0 4 1 0 4 2 4 2 2 3 2 4 0 1 1 4 0 2 3 0 2 0 1 4 1 0 4
[2813] 1 3 4 4 0 4 4 4 3 4 4 4 4 2 0 1 0 0 0 0 0 4 4 4 0 4 1 2 3 4 4 4 0 4 4 3 1
[2850] 1 1 4 4 0 4 4 0 1 4 0 1 4 1 3 4 4 1 4 3 4 4 4 1 1 4 3 4 2 2 0 0 2 1 4 0 4
[2887] 4 4 4 4 1 4 3 0 2 1 2 4 1 1 4 4 2 4 0 1 4 1 4 1 2 1 4 4 0 4 4 4 4 4 4 4 4
[2924] 4 2 0 1 3 4 4 4 4 1 4 4 3 4 4 2 2 4 4 4 1 4 4 4 4 1 1 1 1 4 4 4 4 4 4 4 1
[2961] 4 2 1 4 0 2 4 4 0 4 1 1 2 1 2 2 4 4 4 4 0 0 0 4 0 0 0 1 4 4 1 1 1 1 0 0 4
[2998] 2 1 4 2 4 1 4 4 4 4 4 4 4 4 0 4 4 4 4 2 1 0 4 4 4 4 4 4 0 4 3 2 4 4 3 2 3
[3035] 3 4 4 4 4 4 4 2 3 1 2 2 0 4 0 4 4 2 3 4 4 3 2 0 3 4 4 4 2 0 0 1 3 0 4 1 1
[3072] 4 0 1 1 0 0 4 4 3 1 1 3 2 2 4 4 1 4 4 4 4 4 1 4 4 2 0 4 3 2 4 4 0 4 4 2 3
[3109] 4 2 4 4 4 3 4 4 2 0 4 3 2 2 4 4 4 0 0 4 4 4 2 2 2 4 4 3 4 4 2 4 4 2 4 4 4
[3146] 4 3 4 4 4 3 4 3 4 4 4 3 1 0 0 4 4 4 4 2 0 0 3 0 0 4 4 1 4 0 4 2 4 2 3 4 4
[3183] 4 4 4 4 4 2 1 2 0 1 4 4 4 2 4 4 4 4 4 4 4 0 4 4 4 0 4 4 4 4 4 4 4 4 4 2 4
[3220] 1 2 3 4 0 2 4 4 0 4 4 4 0 4 2 2 2 4 2 1 4 3 4 4 3 4 2 4 2 0 4 4 1 1 2 4 4
[3257] 4 1 2 2 3 0 4 4 2 2 4 4 0 4 2 4 4 4 1 4 4 4 4 1 2 0 4 4 4 4 1 1 4 1 4 3 3
[3294] 1 4 0 3 4 4 0 4 1 4 4 0 4 4 4 4 4 3 1 4 1 0 4 2 4 4 4 1 4 4 1 1 4 4 4 2 2
[3331] 4 2 4 1 4 4 4 4 2 2 2 4 1 1 1 2 1 2 2 2 2 4 2 0 4 1 4 1 3 4 4 2 4 2 4 4 2
[3368] 4 4 4 4 4 1 4 2 2 4 4 2 4 3 2 4 2 0 1 2 4 4 4 4 4 4 4 4 4 4 4 1 2 2 4 4 4
[3405] 4 3 4 3 4 1 1 0 0 0 2 2 4 1 3 0 4 1 2 4 4 4 4 4 4 2 4 4 2 1 2 4 4 2 2 1 1
[3442] 4 1 4 1 4 4 4 4 4 2 2 3 1 1 1 0 0 0 4 4 2 0 0 1 3 1 1 3 2 3 3 4 0 1 0 0 3
[3479] 4 4 4 2 4 4 4 4 4 4 4 1 4 1 4 1 1 1 2 4 4 4 4 3 3 4 2 4 4 4 2 3 4 4 0 0 3
[3516] 3 4 2 2 4 3 4 4 1 2 2 2 4 1 2 4 1 4 3 3 4 3 0 3 4 4 4 4 4 4 4 2 4 4 4 4 4
[3553] 4 4 0 4 0 3 3 4 4 4 4 4 4 4 2 2 4 4 3 3 4 4 4 4 4 4 4 1 4 4 4 4 4 1 4 4 4
[3590] 0 4 4 4 4 4 4 0 4 1 3 3 1 1 0 4 4 3 2 4 2 4 4 3 4 4 4 4 0 4 2 4 0 3 4 4 3
[3627] 0 4 3 0 4 4 3 0 4 4 2 3 4 3 4 3 4 3 2 4 4 4 0 0 4 4 4 0 4 4 3 1 3 2 0 3 3
[3664] 0 2 4 2 4 2 3 4 4 4 2 2 0 4 4 3 4 4 4 2 2 2 2 4 3 2 0 0 4 4 4 4 0 2 2 0 4
[3701] 0 0 4 4 4 4 3 3 4 4 2 0 4 1 3 0 4 4 4 4 4 4 4 0 1 2 2 0 0 4 4 0 2 4 4 4 0
[3738] 2 1 4 3 2 4 4 0 4 3 4 4 2 2 4 1 4 4 4 4 4 0 2 4 4 4 4 4 0 4 2 3 4 4 4 3 4
[3775] 1 1 0 4 4 4 4 4 2 4 4 4 0 4 3 4 2 4 4 4 4 4 4 4 2 2 4 4 4 4 4 3 4 3 2 3 4
[3812] 4 3 3 4 3 4 4 4 0 0 3 3 2 2 4 4 4 2 4 0 0 4 1 0 0 4 4 4 1 4 0 3 4 3 4 4 4
[3849] 4 0 4 4 4 4 4 4 4 4 0 1 4 3 0 4 3 3 4 3 3 4 3 4 4 2 4 3 4 4 4 2 2 4 4 4 2
[3886] 3 3 4 4 4 4 0 3 4 4 1 4 0 4 4 3 3 3 4 4 4 4 4 3 4 3 4 4 3 4 4 4 0 2 4 4 3
[3923] 2 3 4 4 4 4 2 4 4 3 4 4 4 2 4 4 4 0 4 4 3 4 1 3 4 4 4 4 4 1 4 1 2 4 4 0 3
[3960] 4 0 2 2 2 4 0 4 4 4 4 2 4 4 2 4 0 4 4 3 2 4 0 1 4 4 2 4 3 2 4 3 4 3 2 3 4
[3997] 4 4 4 2 4 3 1 4 1 4 3 4 2 4 4 4 3 4 4 3 4 1 1 3 4 2 3 3 3 4 0 4 0 1 4 2 4
[4034] 3 4 1 0 4 2 3 3 4 4 4 4 4 3 3 2 4 4 4 4 4 2 4 4 3 4 4 3 4 4 2 3 3 4 4 4 1
[4071] 4 3 0 4 4 4 4 1 4 4 4 4 1 4 4 4 4 4 4 4 4 0 3 4 4 4 3 4 4 4 3 4 4 0 4 4 0
[4108] 4 3 3 4 4 0 4 4 2 2 4 2 4 4 1 4 3 4 4 4 4 4 3 2 4 0 4 4 4 0 4 3 3 4 4 4 4
[4145] 4 4 3 4 3 4 2 3 4 3 4 4 4 3 4 4 4 2 3 4 4 4 3 1 4 4 4 4 4 4 3 3 2 4 4 4 4
[4182] 4 2 3 4 4 4 4 3 4 0 4 4 4 2 4 0 0 4 4 4 4 0 4 2 4 2 4 3 2 0 0 0 0 0 0 3 0
[4219] 0 0 4 0 0 0 0 1 1

In [47]:
lgbregmin

   [1]  3.908699752  2.811167017  2.122408565  2.024357700  1.601400500
   [6]  3.700863896  2.905236313  2.880446707  2.770436432  3.545700375
  [11]  3.006386714  3.115538703  2.120199549  3.945020149  3.987741193
  [16]  0.677609329  1.794359417  2.188628918  3.523816210  1.289312585
  [21]  3.797052867  3.035090822  2.564922203  3.048062839  2.976481621
  [26]  2.676860682  3.207340059  2.647774593  3.893491612  2.938992299
  [31]  1.148423603  1.583604586  4.018017169  3.589322998  2.918089809
  [36]  2.945494383  1.634551519  3.431066983  2.708417531  1.350464309
  [41]  3.309502179  1.602327799  2.686735332  2.846390969  1.352154360
  [46]  3.047518281  2.472934620  3.713092200  3.145919221  3.716552131
  [51]  3.573815875  3.058185199  1.334817290  3.024913816  1.798231724
  [56]  3.666221879  1.464074036  2.484322794  3.602349075  3.221910281
  [61]  1.921225531  1.762840882  3.772681996  1.885936048  2.371884666
  [66]  3.087071678  3.448749451  2.373900922  0.741275697  3.790724279
  [71]  2.779586781  1.627476343  3.318730704  1.568944599  2.582542413
  [76]  3.439832080  3.399038597  3.067117970  3.255479116  2.950952895
  [81]  3.178713151  3.150797633  2.922463721  2.135030206  3.089517643
  [86]  3.883222007  3.810458217  3.895811566  3.826201497  3.665676416
  [91]  3.833637949  3.224354214  3.845404337  1.610088485  1.897890001
  [96]  3.741599322  1.694133967  3.584517698  1.913694771  3.205596708
 [101]  3.739456183  3.602893419  3.028812661  3.158417716  2.172125546
 [106]  1.486200039  2.176917828  4.312655090  3.500292123  3.515872913
 [111]  4.102433684  4.185548750  3.404939818  2.738614440  3.303459944
 [116]  2.775230995  3.187038161  1.260991909  0.794706256  3.904929981
 [121]  3.165967298  3.532333994  2.563071648  1.256758788  0.744773721
 [126]  1.240936259  3.641941552  3.124911997  2.748197315  1.548033859
 [131]  2.631196577  3.499895269  3.492991155  3.107529308  2.874502726
 [136]  3.104192016  2.764897802  3.495443348  1.162425816  2.232581667
 [141]  2.216449479  2.236783695  1.899950412  3.623774243  3.130322395
 [146]  1.556386177  1.670294730  2.747546784  2.197631809  2.913331369
 [151]  2.715220865  2.417209281  2.918970396  3.321293449  2.411888182
 [156]  3.074383789  3.738062932  0.796373912  2.985115097  1.843908665
 [161]  3.355211510  2.817734501  2.052827023  1.226368132  1.264761145
 [166]  3.631658793  1.795700698  2.169494250  3.586715928  2.487418904
 [171]  0.982602458  0.978229365  0.926040436  2.254886994  1.905051402
 [176]  3.717711074  4.330422004  3.712350451  1.167940836  2.460979407
 [181]  2.071956200  2.914434740  4.224000244  3.775969258  3.928606789
 [186]  3.595175202  3.247422209  3.706676942  3.324844780  3.288355917
 [191]  3.784710433  3.158827072  2.187517683  4.509148689  3.917677473
 [196]  3.812916831  1.531497915  1.571781798  1.469920891  2.922921338
 [201]  3.359568169  2.404219401  3.113322204  2.668823882  2.155066073
 [206]  2.942960746  2.962904073  3.762171584  3.752957606  3.950189310
 [211]  4.233667641  2.660925281  2.713904607  1.609961490  2.531657423
 [216]  3.424795897  2.176845487  2.544295756  2.839426588  2.221467243
 [221]  0.561460938  1.986195533  3.605240690  3.817552937  3.813728215
 [226]  0.771894738  0.945139694  1.096560250  2.101046327  4.138724537
 [231]  3.828503119  3.868362658  1.953307548  2.587935394  3.128767024
 [236]  3.163136846  2.487850317  3.673900387  3.432873829  3.140610878
 [241]  1.891905470  3.416823981  3.172500155  3.386449890  2.952812251
 [246]  3.166508662  3.228634928  2.207750768  0.723477236  0.265608427
 [251]  0.743588394  1.738197060  1.922173853  1.846837530  2.288076064
 [256]  3.441960108  1.894892986  1.690314945  1.802952357  2.807503209
 [261]  3.102593817  2.755939404  2.388413931  2.830338809  2.707835432
 [266]  2.602378835  3.113358950  2.913668207  2.581651376  1.853041567
 [271]  1.045778724  2.343324314  1.218981408  3.040751558  2.545984811
 [276]  2.986169282  2.600928362  3.365885046  2.927289207  3.601423340
 [281]  3.453050474  3.307028304  3.370153326  0.789592118  2.228425102
 [286]  3.547366037  3.550101092  3.865292119  3.583755564  3.472509002
 [291]  3.675601855  3.692744185  3.590698087  2.315290604  1.094345929
 [296]  0.446241368  0.417116187  0.966490844  3.316543797  3.467258875
 [301]  3.636012914  1.151883138  3.450654345  2.980050156  2.750383553
 [306]  3.165357853  2.815023762  2.666295315  2.359167284  3.314441759
 [311]  2.753206248  2.977589087  2.373235235  3.207806720  3.409928481
 [316]  3.227712757  2.527972464  1.441917290  0.251114798  0.865543458
 [321]  0.562973002  0.676292416  0.479822472  1.469728900  0.814639966
 [326]  2.747064615  2.620334103  1.984055341  2.371421703  3.013563030
 [331]  2.056768133  1.240684937  1.306140393  1.296462096  1.024770628
 [336]  2.759536471  3.069412992  2.668434147  3.172049709  3.341004079
 [341]  3.057077794  3.052193064  3.189410461  3.358418105  3.435676818
 [346]  3.485373529  3.568893705  3.238230910  3.306712818  3.638125762
 [351]  3.661652229  2.743697612  1.595226194  2.805781729  1.667120767
 [356]  1.088052969  2.234064855  1.381067892  2.242610205  2.789281923
 [361]  2.765180385  3.301851890  1.699554678  1.207424857  1.072385865
 [366]  2.629563369  2.742181199  3.003558220  3.365392570  3.882018649
 [371]  3.153465034  2.395651117  2.679429015  2.367049946  2.467442221
 [376]  3.542428944  3.497832122  2.811937126  3.825613770  1.900913167
 [381]  3.012131017  3.270786457  3.463169115  2.977338660  2.694255108
 [386]  2.310578203  2.454640678  3.180007034  1.506716125  2.365894558
 [391]  2.367164148  3.093387402  3.519247794  2.782748683  2.793151802
 [396]  2.853161744  3.063050369  2.799072025  3.088280933  2.954798325
 [401]  2.732714561  3.008734840  3.316833636  1.709136466  3.280024214
 [406]  0.772894889  1.734242143  4.054643778  2.899767484  2.552263710
 [411]  2.562274989  2.531183118  1.267071139  2.601355409  0.503215037
 [416]  3.047579674  2.836653475  2.860725408  0.523933683  2.092223646
 [421]  4.061124690  4.038883891  1.696534025  4.091800882  3.016671037
 [426]  3.351773402  1.227649210  2.536790676  0.145321521  2.352120320
 [431]  4.019650266  0.059836966  1.567569330  3.703770837  0.957521157
 [436]  2.095282257  2.217591589  2.430510251  2.064948511  2.352104962
 [441]  3.485620145  2.777607866  2.266704075  2.729993001  2.536831848
 [446]  1.618632599  3.531773323  2.107777672  4.112572033  1.257090147
 [451]  1.178366971  0.758809492  2.613895931  3.651668778  3.612316430
 [456]  3.723489594  2.812103424  2.739607670  3.761999185  2.499514890
 [461]  2.211885168  3.179236034  3.317511600  2.786880478  3.926214934
 [466]  2.156416103  2.896022959  2.979598418  2.611296857  3.406327880
 [471]  2.620002086  2.763149318  2.626920403  2.693836662  2.225611796
 [476]  3.446618185  2.514614423  3.045256993  3.815573372  3.768369230
 [481]  3.429257521  2.279365500  2.299468148  1.837016737  2.902003158
 [486]  2.302493881  1.283456166  3.497455686  3.059312016  3.821872182
 [491]  2.330480765  2.708692718  2.476427856  3.172410042  2.853208157
 [496]  2.836250951  3.043417397  2.673845642  2.271175260  3.360095687
 [501]  1.571421249  1.885326733  2.528733595  0.785325271  1.346893489
 [506]  3.067891206  2.377927629  1.958027261  2.081378704  3.251629359
 [511]  2.886292338  1.380561133  0.840464371  0.179281945  1.640312494
 [516]  0.453782123  2.808345024  0.884984583  0.846425420  1.012278560
 [521]  0.077213371  2.787676443  2.955273002  3.148131538  2.957173743
 [526]  2.370263821  2.214730995  3.372891013  3.092094795  2.896290778
 [531]  3.092020746  3.422786732  2.881846563  3.371534931  3.169817476
 [536]  3.281900712  2.926271844  2.980031492  3.371534931  3.298843719
 [541]  3.918828011  2.860884207  2.464828646  1.338483274  1.233030979
 [546]  2.648976569  0.894439568  1.589853667  2.209859100  2.411221631
 [551]  1.802108845  3.030249842  1.144143193  2.624377277  2.842631801
 [556]  3.338790101  2.068196582  1.851413838  3.588773655  1.134503059
 [561]  3.723627191  3.726465775  1.940291124  3.335513341  3.639353337
 [566]  2.922878922  3.483100010  3.678701091  3.680854169  3.480988043
 [571]  1.394536766  2.976631392  2.994011284  3.192520604  1.836038507
 [576]  3.123684658  2.574395432  2.672815922  3.104526337  2.368286732
 [581]  2.426671047  1.591733012  2.438262240  2.068895224  3.779331128
 [586]  3.565985356  3.964902489  3.885034187  0.212278200  0.325179205
 [591]  2.911849937  3.920825047  3.212114504  3.238752409  2.967319886
 [596]  0.325179205  2.855725690  3.653499737  3.224667120  3.798890494
 [601]  3.737650365  3.271618107  3.942565685  1.841318964  3.800099516
 [606]  3.861778643  3.825560817  3.635053343  3.467681343  3.523556381
 [611]  3.893397522 -0.195442955  3.123033041  0.468460040 -0.025954904
 [616]  0.080595084  0.129735886  0.076535383 -0.009679007  0.230700033
 [621]  0.703431817  1.006056652  0.504071053  0.448450740  0.061250971
 [626]  2.782604374  0.109913863  2.557080724  2.472195895  2.202672765
 [631]  3.636858290  3.242240622  3.247810246  1.936709023  3.062128411
 [636]  3.014935007  2.945143794  3.306173790  2.206784457  3.261331734
 [641]  2.024990047  2.295476137  1.497839899  3.102067397  2.735312060
 [646]  2.481377542  3.118211758  3.593723103  2.249342736  0.262246227
 [651]  3.423019509  2.837529522  2.906326314  3.039889016  2.748371226
 [656]  3.142163749  3.230391736  2.902753915  2.813936809  3.414528394
 [661]  3.397666715  2.425438360  2.659150272  2.678223256  3.102429155
 [666]  2.872369433  2.586739868  2.428554441  3.170752176  2.760888707
 [671]  2.493489227  1.908593629  3.843785337  1.759920681  2.670191292
 [676]  1.742059370  3.910307543  2.030350542  3.755767183  2.810631836
 [681]  3.919659630  4.032831146  1.013753405  3.653247382  4.093369190
 [686]  2.819116049  3.904302274  3.077496181  3.944096086  2.801922062
 [691]  1.764810452  4.206427024  4.261093636  4.057554906  3.660714666
 [696]  3.559822873  2.260336160  2.880423594  4.057554906  3.919644682
 [701]  1.695293629  4.085027005  3.750854297  3.892225695  0.893775684
 [706]  3.998456576  4.014987727  1.313973085  3.755605045  4.034799875
 [711]  4.180996822  4.138512230  2.677108998  3.969119240  2.093720710
 [716]  1.498605956  3.712143625  3.875040852  3.955988941  3.896035671
 [721]  3.905936933  3.821144784  3.908082906  3.821061717  2.521666390
 [726]  3.735979587  2.562978090  3.449947051  3.851711234  3.755767183
 [731]  2.996443993  3.925799515  2.252186697  2.657373398  3.838843378
 [736]  3.896760956  3.911615713  3.666462767  3.930387083  1.129242122
 [741]  0.525320479  1.207940203  2.722376103  1.112465739  1.922344707
 [746]  0.226183219  2.339438011  2.580466215  2.684134483  1.897943233
 [751]  0.990308953  1.566629127  0.681193443  0.631731101  0.694959017
 [756]  1.824184502  1.210967874  0.845769002  2.245146424  1.915476276
 [761]  1.710989622  2.930468902  1.183786454  1.470882245  3.082698520
 [766]  0.811717374  1.339058558  2.019091353  2.962039698  3.143004343
 [771]  2.197575105  2.252394983  2.096076137  2.758590624  3.211595738
 [776]  3.178325478  2.451947044  1.291160765  3.252693149  1.988737721
 [781]  3.542885439  2.136140274  0.519991490  2.361923612  1.674065297
 [786]  0.813731118  3.448006524  2.109336647  0.881274161  4.068339885
 [791]  2.424395357  3.192399113  0.941732183  2.960768588  0.850053966
 [796]  3.467414510  3.482147274  1.051365783  2.634935967  2.974043920
 [801]  3.500563763  3.797757022  2.870254080  3.388525266  2.404183866
 [806]  3.912517018  3.527557377  3.605265076  2.960297158  2.906487509
 [811]  3.237207374  1.017906691  3.466754028  3.593176262  3.978834007
 [816]  4.054290606  3.705716563  1.865812674  3.657035331  4.061091909
 [821]  3.379181473  3.273965415  2.767759308  1.458613301  2.774421693
 [826]  2.636461464  3.174234476  1.723525485  1.993157659  2.550801636
 [831]  3.017716837  2.775002450  3.101950632  2.573429891  3.486655806
 [836]  2.867664151  3.694515236  0.831015748  3.251997221  3.538078209
 [841]  3.540578467  3.821578789  1.615468316  2.028565415  1.815775105
 [846]  1.533052360  1.740117946  2.654929750  2.589758826  1.510880317
 [851]  2.247252478  1.245179428  1.075183315  2.555846708  2.623111929
 [856]  3.574983430  3.841112466  3.551072526  0.909477044  3.477188444
 [861]  3.535736100  3.616525319  2.997699282  2.893637891  3.717324332
 [866]  1.165280884  0.804211324  1.585155269  1.080068779  0.348536347
 [871]  1.395822818  3.457010480  2.972613117  1.615986723  1.377028861
 [876]  1.358354499  2.017093569  0.411770923  1.104005051  1.615468316
 [881]  1.362976472  1.318604326  0.561634118  0.971005024  1.419940115
 [886]  1.741415478  1.016915815  1.318604326  1.400830541  3.598505195
 [891]  1.256796379  1.482481994  3.779594970  0.442841583  0.953936135
 [896]  3.429796214  1.214152090  1.811460949  1.091167193  2.427988873
 [901]  1.633060198  2.395324128  3.059508874  3.353890901  2.062178562
 [906]  1.209263603  1.060119208  2.616643058  1.419133727  1.341265600
 [911]  1.191741294  1.433186042  3.784984278  3.784984278  2.440999213
 [916]  3.124855899  2.925985762  3.319771207  2.562244212  1.647424759
 [921]  2.661531306  3.343789681  3.170506321  3.794809894  3.798659717
 [926]  3.272621058  3.864775401  3.323317736  3.293373120  3.889469442
 [931]  3.280781315  2.734848601  3.671285164  3.923386813  3.860401456
 [936]  3.184302126  3.243648262  2.504443149  3.942845622  3.696093720
 [941]  3.707056736  2.023338927  2.632211140  1.772364805  2.847575567
 [946]  2.819522977  2.650098467  2.178757840  2.192559070  1.219254541
 [951]  2.315982967  2.136070042  2.347753643  2.999516420  2.434736775
 [956]  0.701447277  2.329024307  1.262903622  0.351559206  2.114210381
 [961]  0.537588400  0.188470120  2.020482810  1.479917151  0.398620276
 [966]  1.140105830  1.119712282  2.543281112  0.903720031  2.308552281
 [971]  1.675431568  1.201573212  2.457139223  2.065823883  1.042918962
 [976]  2.395532416  1.270462687  1.620257889  1.376271686  3.565293760
 [981]  2.176015527  1.309362403  1.934848813  1.818744771  2.012960920
 [986]  3.069038016  2.750299240  2.997720636  1.652412201  2.667285207
 [991]  1.019715129  1.369636021  0.791040751  4.271447956  1.690781045
 [996]  3.515880123  0.650023295  1.051335215  1.547409210  2.421606593
[1001]  0.806938029  3.287240734  1.012383743  2.886903983  0.468676177
[1006]  0.892796947  3.175573207  2.751691187  3.085457976  3.292232001
[1011]  3.634177670  3.293553505  2.126358810  3.525809375  3.419121529
[1016]  2.392252390  2.634678895  3.345951322  2.701621682  3.684622143
[1021]  1.193149727  3.319282600  3.510322832  3.643987365  1.845312360
[1026]  2.969016587  0.353033765  0.228125502  2.087641636  1.556388740
[1031]  1.758375185  1.436790159  2.272959300  2.123980888  2.393422309
[1036]  0.621182909  2.328013905  1.329799287  1.475648821  0.832290384
[1041]  0.857459325  1.078327468  2.398887508  1.589975256  2.226723749
[1046]  2.468721692  2.104405945  1.578723814  2.965890136  3.009228594
[1051]  2.482017755  2.936979645  3.882915624  1.802465611  3.022485426
[1056]  2.459115989  2.578120791  2.980117457  3.095860329  3.059238653
[1061]  1.975945551  3.404472803  3.437480734  3.034471363  3.963165124
[1066]  2.939497175  2.723576711  2.954867876  3.962005344  3.943877055
[1071]  3.751585735  1.260809738  3.807047637  1.423328599  2.789809779
[1076]  3.845349877  3.375832428  0.847943728  1.788641492  0.866165422
[1081]  1.864331679  0.950313186  1.061785676  0.672513659  1.780306781
[1086]  1.028793406  1.014193884  1.405930206  0.950064794  0.667432721
[1091]  0.894330920  1.778375751  0.489330256  1.122022258  4.057731142
[1096]  3.326664398  1.444476128  3.800852546  3.359176918  4.289132366
[1101]  2.519109348  3.370161580  3.374198982  3.383078265  3.605321312
[1106]  3.857628950  2.286933210  3.404342350  2.862793666  4.071970836
[1111]  3.133870090  1.141354158  1.493259735  3.458624853  2.189322310
[1116]  3.313021421  3.853850294  3.344331739  3.780602498  4.012397236
[1121]  4.289119583  3.419922301  2.393708119  3.345839301  3.947952127
[1126]  2.877292514  2.947775683  1.305743567  2.113524231  1.752199071
[1131]  0.925339094  1.231031707  2.643246093  1.059718638  2.923258266
[1136]  1.782367540  1.629222896  1.719360537  1.014296972  1.040092091
[1141]  2.092435262  2.404999739  1.845875583  0.958574337  1.199148308
[1146]  0.960134447  2.463842894  2.545872939  2.019230447  1.761277134
[1151]  2.084923831  1.726404124  1.422992032  1.927302202  1.781784196
[1156]  0.602854354  0.893275606  1.243813015  1.764834206  0.421114403
[1161]  0.509044729  1.174052104  0.730510102  1.535580537 -0.036372133
[1166]  1.406951321  2.395790369  0.414589335  0.416095138  0.125820428
[1171]  0.801669568  0.948930951  1.490721866  0.673957069  1.652665270
[1176]  1.396685760  3.287207961  2.181486042  1.769146381  0.981888376
[1181]  1.507839823  1.180582177  1.601341916  1.580398242  2.392038198
[1186]  0.880635810  3.121645543  2.938763981  2.660490458  2.611266418
[1191]  2.698217377  2.784166958  3.029718157  1.864172435  0.150087751
[1196]  2.697181964  3.917125870  1.988428999  3.399584656  1.121175112
[1201]  3.359982047  3.775021034  3.730688450  3.744844926  2.768418971
[1206]  3.892768100  3.914882339  4.081965685  3.554320294  2.474042739
[1211]  4.028175031  4.030865030  3.361275770  2.846572470  0.735039348
[1216]  3.769477674  3.892768100  2.975942509  4.054649734  3.061813487
[1221]  3.892768100  3.677598750  3.941228786  0.984607396  2.811661596
[1226]  3.000006893  2.375434896  4.010256060  3.991343700  2.897468968
[1231]  1.533811898  1.327466137  0.560500576  3.472868716  1.910687125
[1236]  0.892377420  2.693226110  2.702840949  2.766096793  2.627887797
[1241]  2.497462092  1.130810430  0.371645203  0.726310270  2.064495464
[1246]  1.900296074  3.022284360  2.511670577  2.964749221  2.466640207
[1251]  2.598437484  2.364461194  2.428689721  2.690662350  0.421824848
[1256]  3.506502611  0.862318627  2.342233426  1.562790828  0.800474735
[1261]  1.385888175  0.651016004  1.146059936  0.870436687  1.313186533
[1266]  1.054578987  1.982152991  0.589395909  1.300033420  1.226061223
[1271]  1.153209012  1.544355625  0.981021002  3.844156698  3.685997214
[1276]  3.727437871  3.821010047  3.910038048  3.978138730  3.722917547
[1281]  3.789246104  3.633179247  3.714688257  3.946493718  4.076483874
[1286]  3.688354354  3.444501662  3.970749742  3.958763105  3.843180167
[1291]  4.076612914  3.484539143  3.946479374  3.530670540  3.941836667
[1296]  4.016079564  3.941836667  3.576899594  3.942039234  3.897645560
[1301]  3.730690768  3.913061157  4.153070673  4.004459217  3.705598999
[1306]  3.485886918  4.113421506  4.025568759  4.042921739  2.909445587
[1311]  3.027276649  1.249287548  1.085171345  2.661097247  1.742097542
[1316]  0.422281115  1.404220384  2.527289530  2.082714909  2.744324301
[1321]  3.536727829  2.701236525  2.672536365  0.697274365  1.937634794
[1326]  1.341982390  0.949663895  3.137217334  1.596981290  2.458020081
[1331]  1.392649180  1.748372127  3.867352194  1.988743037  1.981998103
[1336]  1.446014058  1.569222021  2.870731521  2.823687772  2.805481410
[1341]  3.114598074  3.605070272  3.698050182  3.039689786  3.048147850
[1346]  0.540505625  1.576767731  0.474808759  0.356250528  1.068771923
[1351]  1.204614634  0.566765970  2.666361580  1.538395472  1.285525941
[1356]  1.669153510  1.687748166  0.623932412  1.251715804  0.623932412
[1361]  1.331499756  1.465682134  0.804347315  2.627659876  2.022706593
[1366]  1.896132310  2.225359425  2.182425145  2.077751648  2.529257412
[1371]  2.427961869  2.250362411  2.690082781  2.427961869  2.459652437
[1376]  1.012580175  1.786098965  1.461200598  1.698592672  0.734836190
[1381]  1.090026230  0.705367223  1.181828435  1.613393154  1.225109662

In [48]:
lgbclsmin

      [,1]        [,2]         [,3]        [,4]        [,5]
 [1,] 0.006627230 0.0033924692 0.004297776 0.044227054 0.94145547
 [2,] 0.007316336 0.0205559440 0.022692825 0.882527209 0.06690769
 [3,] 0.121833622 0.0057535702 0.019190618 0.815186676 0.03803551
 [4,] 0.114244711 0.0205339520 0.763919122 0.021704876 0.07959734
 [5,] 0.794027808 0.0134338569 0.008624192 0.042255555 0.14165859
 [6,] 0.012722062 0.0018953211 0.023398506 0.007026098 0.95495801
 [7,] 0.150350846 0.0109875566 0.305192680 0.042764013 0.49070490
 [8,] 0.005771339 0.0178151475 0.687976428 0.061743222 0.22669386
 [9,] 0.015437138 0.0171101984 0.660491985 0.070562355 0.23639832
[10,] 0.009692029 0.0175414250 0.040173020 0.070825601 0.86176792
[11,] 0.027447858 0.0493557055 0.046206395 0.138625001 0.73836504
[12,] 0.022729634 0.2859991478 0.072948680 0.106658921 0.51166362
[13,] 0.008273238 0.6634182017 0.048773310 0.050018292 0.22951696
[14,] 0.004343098 0.0005893467 0.003909674 0.003183595 0.98797429
[15,] 0.019566899 0.0108238594 0.037245637 0.059600091 0.87276351
[16,] 0.892794828 0.0215751626 0.005168371 0.018315975 0.06214566
[17,] 0.743479987 0.0681955448 0.059007027 0.063563333 0.06575411
[18,] 0.701137407 0.0258796886 0.011363988 0.059784197 0.20183472
[19,] 0.002892637 0.0033117921 0.002594189 0.009748722 0.98145266
[20,] 0.804859638 0.0247200180 0.040930198 0.007324338 0.12216581
[21,] 0.003634065 0.0074027698 0.002481186 0.012185024 0.97429696
[22,] 0.015127645 0.1601725177 0.289673896 0.033033751 0.50199219
[23,] 0.006606621 0.6303916164 0.061421014 0.061443104 0.24013764
[24,] 0.014332499 0.1887696471 0.356966828 0.032399032 0.40753199
[25,] 0.005662758 0.0594683833 0.071166575 0.065718705 0.79798358
[26,] 0.014547120 0.0489103201 0.673056045 0.025460857 0.23802566
[27,] 0.002962529 0.3326304232 0.059035859 0.054298467 0.55107272
[28,] 0.102591569 0.2453682797 0.327168691 0.033021710 0.29184975
[29,] 0.011010286 0.0051718165 0.009389080 0.010693676 0.96373514
[30,] 0.145783886 0.0574139198 0.075137422 0.136696443 0.58496833
[31,] ⋮           ⋮            ⋮           ⋮           ⋮
[32,] 0.544672921 0.028243435  0.023864155 0.056415326 0.346804163
[33,] 0.088173447 0.014370109  0.028538732 0.010448543 0.858469169
[34,] 0.009349638 0.030367716  0.039188998 0.062286810 0.858806838
[35,] 0.005693182 0.034018730  0.042029037 0.066926448 0.851332602
[36,] 0.008164281 0.028950226  0.097031275 0.109510296 0.756343922
[37,] 0.495502705 0.097123546  0.038314189 0.061092962 0.307966598
[38,] 0.055253024 0.029540820  0.078826528 0.065053728 0.771325901
[39,] 0.082838089 0.081333003  0.476415286 0.026274689 0.333138933
[40,] 0.066432236 0.031169210  0.026227006 0.104818351 0.771353197
[41,] 0.078401216 0.037002937  0.427321534 0.063840266 0.393434048
[42,] 0.043149299 0.108478536  0.196926790 0.042924919 0.608520456
[43,] 0.032222682 0.019144047  0.063234076 0.723268602 0.162130593
[44,] 0.071592493 0.012594662  0.756389044 0.049745142 0.109678660
[45,] 0.948371622 0.001997959  0.003128128 0.035788734 0.010713556
[46,] 0.928038374 0.007582450  0.004179963 0.026816468 0.033382745
[47,] 0.947520311 0.005786114  0.003254640 0.020463455 0.022975480
[48,] 0.970508640 0.001203465  0.002130852 0.019517547 0.006639496
[49,] 0.971481405 0.001204671  0.001645064 0.019537110 0.006131749
[50,] 0.977209269 0.001411109  0.002381640 0.014462586 0.004535397
[51,] 0.343570103 0.002503840  0.006285103 0.635253682 0.012387272
[52,] 0.929980262 0.008065597  0.007498142 0.023591424 0.030864575
[53,] 0.961586906 0.001469660  0.004373477 0.026383422 0.006186536
[54,] 0.824880713 0.003009111  0.003466703 0.161246919 0.007396554
[55,] 0.009823083 0.017460999  0.035795011 0.074523045 0.862397862
[56,] 0.975337978 0.003340788  0.001474707 0.011421821 0.008424706
[57,] 0.937735172 0.008582184  0.004550719 0.018920895 0.030211030
[58,] 0.967864389 0.002858306  0.002072088 0.014304375 0.012900841
[59,] 0.962822744 0.004872785  0.002742504 0.010489801 0.019072166
[60,] 0.117576545 0.821872629  0.032313825 0.005693593 0.022543409
[61,] 0.002237445 0.575232304  0.075014252 0.097421154 0.250094845

In [49]:
datalength=dim(data)[1]
lgbclsm=matrix(lgbclsmin,m,datalength)
lgbclsminr=matrix(0,datalength,1)
for(i in 1:datalength)
    {
    lgbclsminr[i,]=which.max(lgbclsm[,i])
}
lgbclsminr=lgbclsminr-1

In [50]:
lgbclsminr

      [,1]
 [1,] 4
 [2,] 1
 [3,] 0
 [4,] 0
 [5,] 1
 [6,] 4
 [7,] 0
 [8,] 4
 [9,] 4
[10,] 1
[11,] 2
[12,] 1
[13,] 3
[14,] 3
[15,] 1
[16,] 2
[17,] 3
[18,] 1
[19,] 1
[20,] 4
[21,] 4
[22,] 0
[23,] 4
[24,] 3
[25,] 4
[26,] 0
[27,] 0
[28,] 3
[29,] 0
[30,] 1
[31,] ⋮
[32,] 3
[33,] 2
[34,] 2
[35,] 1
[36,] 2
[37,] 2
[38,] 4
[39,] 1
[40,] 0
[41,] 4
[42,] 0
[43,] 3
[44,] 0
[45,] 1
[46,] 0
[47,] 2
[48,] 1
[49,] 3
[50,] 4
[51,] 0
[52,] 0
[53,] 2
[54,] 2
[55,] 0
[56,] 2
[57,] 3
[58,] 0
[59,] 0
[60,] 3
[61,] 4

In [51]:
xgbregmean=predict(xgb_mean_reg,alldataxgb)
xgbclsmean=predict(xgb_mean_cl,alldataxgb)
lgbregmean=predict(lgb_mean_reg,as.matrix(data))
lgbclsmean=predict(lgb_mean_cl,as.matrix(data))

In [52]:
lgbclsm=matrix(lgbclsmean,m,datalength)
lgbclsmeanr=matrix(0,datalength,1)
for(i in 1:datalength)
    {
    lgbclsmeanr[i,]=which.max(lgbclsm[,i])
}
lgbclsmeanr=lgbclsmeanr-1

In [53]:
preallmin=cbind(xgbclsmin,xgbregmin)
preallmin=cbind(preallmin,lgbclsminr)
preallmin=cbind(preallmin,lgbregmin)

In [54]:
colnames(preallmin)=c('xgbclsmin','xgbregmin','lgbclsmin','lgbregmin')
head(preallmin)

     xgbclsmin xgbregmin lgbclsmin lgbregmin
[1,] 4         3.805095  4         3.908700
[2,] 3         2.953971  1         2.811167
[3,] 3         2.900985  0         2.122409
[4,] 2         2.112844  0         2.024358
[5,] 0         0.209325  1         1.601400
[6,] 4         3.955451  4         3.700864

In [55]:
preallmean=cbind(xgbclsmean,xgbregmean)
preallmean=cbind(preallmean,lgbclsmeanr)
preallmean=cbind(preallmean,lgbregmean)

In [56]:
head(preallmean)

     xgbclsmean xgbregmean   lgbregmean
[1,] 4          3.6884120  4 3.7138140
[2,] 2          2.3273439  1 2.5378621
[3,] 1          1.0572011  4 0.8504283
[4,] 3          2.7177610  1 2.2087852
[5,] 0          0.1347971  1 1.2520085
[6,] 4          4.1197233  2 3.5999014

In [57]:
colnames(preallmean)=c('xgbclsmean','xgbregmean','lgbclsmean','lgbregmean')
head(preallmean)

     xgbclsmean xgbregmean lgbclsmean lgbregmean
[1,] 4          3.6884120  4          3.7138140
[2,] 2          2.3273439  1          2.5378621
[3,] 1          1.0572011  4          0.8504283
[4,] 3          2.7177610  1          2.2087852
[5,] 0          0.1347971  1          1.2520085
[6,] 4          4.1197233  2          3.5999014

In [58]:
end_time = Sys.time()
time_matrix[4,]=end_time-start_time

In [59]:
result_list=list(preallmin,preallmean,time_matrix)

In [63]:
save(result_list, file = "Daily_nnetar_opt_pre_result.RData")

In [62]:
time_matrix

     user_time system_time elapsed_time
[1,] 3.256759  3.256759    3.256759
[2,] 7.354278  7.354278    7.354278
[3,] 5.932424  5.932424    5.932424
[4,] 2.570808  2.570808    2.570808

In [31]:
importance_matrix1 <- xgb.importance(model = xgb_mean_cl)
importance_matrix2 <- xgb.importance(model = xgb_mean_reg)
importance_matrix3 <- lgb.importance(lgb_mean_cl)
importance_matrix4 <- lgb.importance(lgb_mean_reg)

importance_matrix1=importance_matrix1[order(importance_matrix1$Feature),]
importance_matrix2=importance_matrix2[order(importance_matrix2$Feature),]
importance_matrix3=importance_matrix3[order(importance_matrix3$Feature),]
importance_matrix4=importance_matrix4[order(importance_matrix4$Feature),]

importance_matrix_mean=(importance_matrix1[,2:4]+importance_matrix2[,2:4]+importance_matrix3[,2:4]+importance_matrix4[,2:4])/4

importance=cbind(importance_matrix1[,1],importance_matrix_mean)

write.csv(importance,'d_ets_imp_mean.csv')