In [1]:
library("xgboost")
library("Matrix")
library('Ckmeans.1d.dp')
library('lightgbm')

载入程辑包：‘lightgbm’


The following object is masked from ‘package:xgboost’:

    slice

## Read data and process data labels

In [2]:
time_matrix <- matrix(0,ncol = 3, nrow =4)
colnames(time_matrix) <- c("user_time", "system_time", "elapsed_time")
start_time = Sys.time()

In [3]:
data=read.csv('Monthly_features_matrix.csv')
data=data[,2:dim(data)[2]]

In [4]:
dim(data)

[1] 48000    27

In [5]:
head(data)

  frequency nperiods seasonal_period trend     spike        linearity
1 12        1        12              0.9472661 1.912037e-08  0.872829
2 12        1        12              0.8085632 2.203382e-07  0.943755
3 12        1        12              0.9992200 8.446236e-12 21.172689
4 12        1        12              0.8687883 3.833819e-06 -7.295270
5 12        1        12              0.7457338 1.006626e-05  4.869531
6 12        1        12              0.9976576 3.100646e-10 13.985335
  curvature   e_acf1     e_acf10   seasonal_strength ⋯ diff2_acf1 diff2_acf10
1  10.9548535 0.18758224 0.1214246 0.8404932         ⋯ -0.3962824 0.4604731
2   4.7359892 0.09830677 0.1405957 0.4180888         ⋯ -0.5668803 0.3576969
3   4.0198303 0.36279469 0.4204365 0.5104123         ⋯ -0.4913136 0.3353221
4   0.3739581 0.50800514 0.5935817 0.2357374         ⋯ -0.5149001 0.3611336
5   0.5621160 0.19177799 0.2581481 0.3207559         ⋯ -0.6516841 0.5925659
6 -12.7683661 0.50582153 0.2947603 0.4390163         ⋯ -0.4473514 0.2338179
  seas_acf1 length user_time  system_time elapsed_time user_time.1
1 0.8293577 469    0.05674529 0.05674529  0.05674529   0
2 0.5860238 469    0.05383134 0.05383134  0.05383134   0
3 0.9154861 469    0.06982851 0.06982851  0.06982851   0
4 0.3110420  82    0.06202483 0.06202483  0.06202483   0
5 0.1199568 112    0.04698277 0.04698277  0.04698277   0
6 0.9367465 666    0.07257485 0.07257485  0.07257485   0
  system_time.1 elapsed_time.1
1 0             0
2 0             0
3 0             0
4 0             0
5 0             0
6 0             0

In [6]:
dlist= load('Monthly_nnetar_datalist.RData')
datalist=eval(parse(text = dlist ))
res=datalist[[1]]
MASE=res[,,,6]
m=5

In [7]:
dim(MASE)

[1] 48000     5     4

In [8]:
whichmin<-function(x){
    minx=min(x[x>0])
    loc=which(x==minx)[1]-1
    loc
}

meanunique=function(x)
    {
    mean(unique(x))
}

In [9]:
nanum=c()
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    a=apply(count,1,min)
    if(sum(is.na(a))>0)
        {
        nanum=append(nanum,i)
    }
    }

In [10]:
nanum

    [1]     4     5     7     8    41    42    43    56    58    59    61    62
   [13]    63    64    65    66    67    68    69    72    73    74    75    78
   [25]    79    81    82    83    84    85    86    87    88    91   103   104
   [37]   106   107   108   109   110   111   112   113   131   132   133   134
   [49]   135   136   137   141   143   147   153   154   155   160   161   162
   [61]   165   167   170   173   191   192   194   195   203   204   205   207
   [73]   215   216   217   218   219   220   221   222   223   226   227   228
   [85]   229   230   231   232   236   238   239   240   241   242   246   247
   [97]   248   252   253   254   255   256   257   258   259   261   262   263
  [109]   264   265   266   271   278   280   282   283   284   286   287   289
  [121]   290   292   293   295   296   297   298   300   303   313   314   315
  [133]   317   318   323   325   326   327   341   344   345   346   347   348
  [145]   349   354   365   366   373   384   388   389   391   396   398   399
  [157]   400   401   402   405   410   411   412   414   420   423   424   426
  [169]   427   434   435   436   439   440   441   447   460   461   462   463
  [181]   469   470   471   472   475   476   477   480   484   503   516   517
  [193]   544   564   566   574   575   576   577   586   591   594   610   612
  [205]   613   634   642   643   645   692   722   737   738   743   745   760
  [217]   765   773   774   777   782   790   800   801   808   843   845   875
  [229]   910   926   953   954   955   958  1064  1087  1112  1224  1232  1271
  [241]  1272  1273  1305  1352  1374  1379  1424  1425  1485  1512  1642  1665
  [253]  1684  1685  1723  1724  1729  1746  1768  1777  1781  1846  1849  1851
  [265]  1860  1861  1862  1913  1914  1949  1950  2040  2077  2130  2136  2139
  [277]  2140  2144  2147  2148  2149  2150  2151  2191  2192  2193  2196  2232
  [289]  2233  2267  2361  2373  2380  2383  2393  2404  2406  2416  2417  2418
  [301]  2419  2421  2462  2508  2509  2511  2582  2586  2587  2588  2589  2590
  [313]  2591  2592  2593  2594  2627  2628  2629  2643  2645  2648  2649  2650
  [325]  2674  2675  2678  2679  2680  2682  2685  2712  2721  2740  2741  2742
  [337]  2743  2744  2745  2746  2747  2748  2749  2750  2751  2752  2753  2754
  [349]  2755  2756  2757  2758  2759  2760  2761  2762  2763  2764  2765  2766
  [361]  2767  2768  2769  2770  2771  2772  2773  2774  2775  2776  2777  2778
  [373]  2779  2780  2781  2782  2783  2784  2785  2786  2787  2788  2789  2790
  [385]  2791  2792  2793  2794  2795  2796  2797  2798  2799  2800  2801  2802
  [397]  2803  2804  2805  2806  2836  2837  2838  2839  2840  2841  2842  2843
  [409]  2844  2845  2846  2847  2848  2849  2850  2851  2866  2867  2900  2901
  [421]  2911  2912  2913  2914  2915  2928  2952  2954  2955  2956  2964  2966
  [433]  2967  2968  2969  2986  2992  3006  3007  3011  3013  3014  3035  3036
  [445]  3037  3047  3050  3052  3053  3054  3069  3071  3072  3073  3074  3075
  [457]  3076  3078  3080  3081  3084  3116  3119  3139  3140  3141  3142  3148
  [469]  3161  3162  3163  3164  3165  3166  3198  3212  3213  3237  3267  3268
  [481]  3269  3270  3284  3329  3380  3385  3387  3390  3392  3466  3467  3468
  [493]  3469  3470  3542  3543  3544  3545  3546  3547  3548  3549  3550  3551
  [505]  3552  3553  3554  3555  3556  3557  3603  3614  3616  3619  3802  3891
  [517]  3903  3910  3911  3912  3913  3914  3915  3925  3936  3940  3948  4080
  [529]  4081  4082  4083  4084  4085  4086  4087  4088  4089  4090  4091  4092
  [541]  4093  4098  4100  4102  4103  4105  4108  4109  4110  4111  4112  4113
  [553]  4114  4115  4116  4117  4118  4120  4121  4122  4123  4124  4125  4126
  [565]  4127  4128  4129  4130  4131  4132  4133  4134  4136  4137  4138  4139
  [577]  4140  4141  4142  4143  4144  4145  4146  4147  4148  4149  4223  4224
  [589]  4225  4226  4230  4371  4427  4428  4429  4430  4431  4432  4433  4434
  [601]  4435  4436  4437  4460  4502  4503  4504  4505  4506  4507  4508  4509
  [613]  4510  4511  4512  4513  4514  4515  4516  4517  4518  4519  4520  4521
  [625]  4522  4523  4524  4525  4526  4527  4528  4529  4530  4531  4532  4533
  [637]  4584  4585  4586  4587  4588  4589  4590  4591  4592  4593  4594  4595
  [649]  4596  4597  4598  4599  4600  4601  4602  4603  4605  4606  4607  4608
  [661]  4609  4610  4611  4612  4613  4614  4615  4616  4617  4618  4619  4620
  [673]  4621  4622  4623  4624  4625  4626  4627  4628  4629  4630  4631  4632
  [685]  4633  4634  4635  4636  4637  4638  4639  4640  4641  4642  4643  4644
  [697]  4645  4646  4647  4648  4649  4650  4651  4652  4653  4654  4655  4656
  [709]  4657  4658  4659  4660  4661  4662  4663  4664  4665  4666  4667  4668
  [721]  4669  4670  4671  4672  4673  4674  4675  4681  4682  4683  4684  4685
  [733]  4686  4750  4752  4753  4754  4773  4774  4775  4776  4785  4813  4814
  [745]  4816  4817  4840  4851  4852  4854  4858  4865  4866  4867  4868  4870
  [757]  4875  4881  4883  4886  4887  4896  4900  4903  5220  5221  5222  5223
  [769]  5862  5863  5864  5865  5866  5867  5868  5869  5870  5871  5872  5873
  [781]  5874  5875  5876  5926  5927  5928  5929  5930  5931  5932  5933  5934
  [793]  5935  5936  5937  5938  5939  5940  5946  5947  5948  5949  5950  5951
  [805]  5952  5953  5954  5994  6003  6073  6074  6089  6090  6091  6098  6114
  [817]  6172  6191  6192  6193  6194  6195  6196  6197  6198  6199  6200  6201
  [829]  6202  6203  6204  6205  6206  6207  6208  6209  6210  6211  6212  6213
  [841]  6214  6215  6238  6240  6241  6248  6251  6252  6254  6255  6256  6261
  [853]  6274  6277  6287  6288  6289  6292  6294  6298  6300  6301  6302  6303
  [865]  6304  6305  6306  6307  6308  6309  6310  6311  6317  6318  6319  6320
  [877]  6322  6323  6325  6326  6330  6331  6332  6333  6334  6335  6336  6337
  [889]  6338  6339  6340  6341  6343  6344  6345  6346  6347  6348  6349  6350
  [901]  6351  6352  6353  6354  6355  6356  6357  6359  6360  6361  6362  6363
  [913]  6364  6365  6376  6378  6379  6380  6381  6382  6383  6384  6385  6386
  [925]  6387  6388  6393  6394  6395  6397  6398  6399  6400  6401  6402  6403
  [937]  6404  6405  6407  6408  6409  6410  6420  6425  6426  6427  6428  6429
  [949]  6463  6514  6539  6543  6559  6560  6561  6562  6563  6769  6781  6856
  [961]  6857  6858  6859  6860  6861  6892  6893  6974  6975  6976  6980  6981
  [973]  6982  6983  6984  6985  6986  6987  6988  6989  6990  6991  6992  6993
  [985]  6994  6995  6996  6997  6998  6999  7000  7001  7002  7003  7004  7007
  [997]  7008  7009  7010  7011  7012  7013  7014  7015  7016  7017  7018  7019
 [1009]  7020  7021  7022  7023  7024  7025  7026  7027  7028  7029  7030  7031
 [1021]  7032  7033  7034  7035  7036  7037  7038  7039  7040  7041  7042  7043
 [1033]  7044  7045  7046  7047  7048  7049  7050  7051  7052  7053  7054  7055
 [1045]  7056  7057  7058  7059  7060  7061  7062  7063  7064  7065  7066  7067
 [1057]  7068  7069  7070  7071  7072  7073  7074  7075  7076  7077  7078  7079
 [1069]  7080  7081  7082  7083  7084  7085  7086  7087  7088  7089  7090  7091
 [1081]  7092  7093  7094  7095  7096  7097  7098  7099  7100  7101  7102  7103
 [1093]  7104  7105  7106  7107  7108  7109  7110  7111  7112  7113  7114  7115
 [1105]  7116  7117  7118  7119  7120  7121  7122  7123  7124  7125  7126  7127
 [1117]  7128  7129  7130  7131  7132  7133  7134  7135  7136  7137  7138  7139
 [1129]  7140  7141  7142  7143  7144  7145  7146  7147  7148  7149  7150  7151
 [1141]  7152  7153  7154  7155  7156  7157  7158  7159  7160  7161  7162  7163
 [1153]  7164  7165  7166  7167  7168  7169  7170  7171  7172  7173  7174  7175
 [1165]  7176  7177  7178  7179  7180  7181  7182  7183  7184  7185  7186  7187
 [1177]  7188  7189  7190  7191  7192  7193  7194  7195  7196  7197  7198  7199
 [1189]  7200  7201  7202  7203  7204  7205  7206  7207  7208  7209  7210  7211
 [1201]  7212  7213  7214  7215  7216  7217  7218  7219  7220  7221  7222  7223
 [1213]  7224  7225  7226  7227  7228  7229  7230  7231  7232  7233  7234  7235
 [1225]  7236  7237  7238  7239  7240  7241  7242  7243  7244  7245  7246  7247
 [1237]  7248  7249  7250  7251  7252  7253  7254  7255  7256  7257  7258  7259
 [1249]  7260  7261  7262  7263  7264  7265  7266  7267  7268  7269  7270  7271
 [1261]  7272  7273  7274  7275  7276  7277  7278  7279  7280  7281  7282  7283
 [1273]  7284  7285  7286  7287  7288  7289  7290  7291  7292  7293  7294  7295
 [1285]  7296  7297  7298  7299  7300  7301  7302  7303  7304  7305  7306  7307
 [1297]  7308  7309  7310  7311  7312  7313  7314  7315  7316  7317  7318  7319
 [1309]  7320  7321  7322  7323  7324  7325  7326  7327  7328  7329  7330  7331
 [1321]  7332  7333  7334  7335  7336  7337  7338  7339  7340  7341  7342  7343
 [1333]  7344  7345  7346  7347  7348  7349  7350  7351  7352  7353  7354  7355
 [1345]  7356  7357  7358  7359  7360  7361  7362  7363  7364  7365  7366  7367
 [1357]  7368  7369  7370  7371  7372  7373  7374  7375  7376  7377  7378  7379
 [1369]  7380  7381  7382  7383  7384  7385  7386  7387  7388  7389  7390  7391
 [1381]  7392  7393  7394  7395  7396  7397  7398  7399  7400  7401  7402  7403
 [1393]  7404  7405  7406  7407  7408  7409  7410  7411  7412  7413  7414  7415
 [1405]  7416  7417  7418  7419  7420  7421  7422  7423  7424  7425  7426  7427
 [1417]  7428  7429  7430  7431  7432  7433  7434  7435  7436  7437  7438  7439
 [1429]  7440  7441  7442  7443  7444  7445  7446  7447  7448  7449  7450  7451
 [1441]  7452  7453  7454  7455  7456  7457  7458  7459  7460  7461  7462  7463
 [1453]  7464  7465  7466  7467  7468  7469  7470  7471  7472  7473  7474  7475
 [1465]  7476  7477  7478  7479  7480  7481  7482  7483  7484  7485  7486  7487
 [1477]  7488  7489  7490  7491  7492  7493  7500  7502  7503  7505  7506  7507
 [1489]  7508  7509  7510  7511  7512  7513  7517  7518  7519  7520  7521  7522
 [1501]  7523  7524  7525  7526  7527  7528  7529  7530  7531  7532  7533  7534
 [1513]  7535  7536  7537  7538  7539  7540  7541  7542  7543  7544  7545  7546
 [1525]  7547  7548  7549  7550  7551  7552  7553  7554  7555  7556  7557  7558
 [1537]  7559  7560  7561  7562  7563  7564  7565  7566  7567  7568  7569  7570
 [1549]  7571  7572  7573  7574  7575  7576  7577  7578  7579  7580  7581  7582
 [1561]  7583  7584  7585  7586  7587  7588  7589  7590  7591  7592  7593  7594
 [1573]  7595  7596  7597  7598  7599  7600  7601  7602  7603  7604  7605  7606
 [1585]  7607  7608  7609  7610  7611  7612  7613  7614  7615  7616  7617  7618
 [1597]  7619  7620  7621  7622  7623  7624  7625  7626  7627  7628  7629  7630
 [1609]  7631  7632  7633  7634  7635  7636  7637  7638  7639  7640  7641  7642
 [1621]  7643  7644  7645  7646  7647  7648  7649  7650  7651  7652  7653  7654
 [1633]  7655  7656  7657  7658  7659  7660  7661  7662  7663  7664  7665  7666
 [1645]  7667  7668  7669  7670  7671  7672  7673  7674  7675  7676  7677  7678
 [1657]  7679  7680  7681  7682  7683  7684  7685  7686  7687  7688  7689  7690
 [1669]  7691  7692  7693  7694  7695  7696  7697  7698  7699  7700  7701  7702
 [1681]  7703  7704  7705  7706  7707  7708  7709  7710  7711  7712  7713  7714
 [1693]  7715  7716  7717  7718  7719  7720  7721  7722  7723  7724  7725  7726
 [1705]  7727  7728  7729  7730  7731  7732  7733  7734  7735  7736  7737  7738
 [1717]  7739  7740  7741  7742  7743  7744  7745  7746  7747  7748  7749  7750
 [1729]  7751  7752  7753  7754  7755  7756  7757  7758  7759  7760  7761  7762
 [1741]  7763  7764  7765  7766  7767  7768  7769  7770  7771  7772  7773  7774
 [1753]  7775  7776  7777  7778  7779  7780  7781  7782  7783  7784  7785  7786
 [1765]  7787  7788  7789  7790  7791  7792  7793  7794  7795  7796  7797  7798
 [1777]  7799  7800  7801  7802  7803  7804  7805  7806  7807  7808  7809  7810
 [1789]  7811  7812  7813  7814  7815  7816  7817  7818  7819  7820  7821  7822
 [1801]  7823  7824  7825  7826  7827  7828  7829  7830  7831  7832  7833  7834
 [1813]  7835  7836  7837  7838  7839  7840  7841  7842  7843  7844  7845  7846
 [1825]  7847  7848  7849  7850  7851  7852  7853  7854  7855  7856  7857  7858
 [1837]  7859  7860  7861  7862  7863  7864  7865  7866  7867  7868  7869  7870
 [1849]  7871  7872  7873  7874  7875  7876  7877  7878  7879  7880  7881  7882
 [1861]  7883  7884  7885  7886  7887  7888  7889  7890  7891  7892  7893  7894
 [1873]  7895  7896  7897  7898  7899  7900  7901  7902  7903  7904  7905  7906
 [1885]  7907  7908  7909  7910  7911  7912  7913  7914  7915  7916  7917  7918
 [1897]  7919  7920  7921  7922  7923  7924  7925  7926  7927  7928  7929  7930
 [1909]  7931  7932  7933  7934  7935  7936  7937  7938  7939  7940  7941  7942
 [1921]  7943  7944  7945  7946  7947  7948  7949  7950  7951  7952  7953  7954
 [1933]  7955  7956  7957  7958  7959  7960  7961  7962  7963  7964  7965  7966
 [1945]  7967  7968  7969  7970  7971  7972  7973  7974  7975  7976  7977  7978
 [1957]  7979  7980  7981  7982  7983  7984  7985  7986  7987  7988  7989  7990
 [1969]  7991  7992  7993  7994  7995  7996  7997  7998  7999  8000  8001  8002
 [1981]  8003  8004  8005  8006  8007  8008  8009  8010  8011  8012  8013  8014
 [1993]  8015  8016  8017  8018  8019  8020  8021  8022  8023  8024  8025  8026
 [2005]  8027  8028  8029  8030  8031  8032  8033  8034  8035  8036  8037  8038
 [2017]  8039  8040  8041  8042  8043  8044  8045  8046  8047  8048  8049  8050
 [2029]  8051  8052  8053  8054  8055  8056  8057  8058  8059  8060  8061  8062
 [2041]  8063  8064  8065  8066  8067  8068  8069  8070  8071  8072  8073  8074
 [2053]  8075  8076  8077  8078  8079  8080  8081  8082  8083  8084  8085  8086
 [2065]  8087  8088  8089  8090  8091  8092  8093  8094  8095  8096  8097  8098
 [2077]  8099  8100  8101  8102  8103  8104  8105  8106  8107  8108  8109  8110
 [2089]  8111  8112  8113  8114  8115  8116  8117  8118  8119  8120  8121  8122
 [2101]  8123  8124  8125  8126  8127  8128  8129  8130  8131  8132  8133  8134
 [2113]  8135  8136  8137  8138  8139  8140  8141  8142  8143  8144  8145  8146
 [2125]  8147  8148  8149  8150  8151  8152  8153  8154  8155  8156  8157  8158
 [2137]  8159  8160  8161  8162  8163  8164  8165  8166  8167  8168  8169  8170
 [2149]  8171  8172  8173  8174  8175  8176  8177  8178  8179  8180  8181  8182
 [2161]  8183  8184  8185  8186  8187  8188  8189  8190  8191  8192  8193  8194
 [2173]  8195  8196  8197  8198  8199  8200  8201  8202  8203  8204  8205  8206
 [2185]  8207  8208  8209  8210  8211  8212  8213  8214  8215  8216  8217  8218
 [2197]  8219  8220  8221  8222  8223  8224  8225  8226  8227  8228  8229  8230
 [2209]  8231  8232  8233  8234  8235  8236  8237  8238  8239  8240  8241  8242
 [2221]  8243  8244  8245  8246  8247  8248  8249  8250  8251  8252  8253  8254
 [2233]  8255  8256  8257  8258  8259  8260  8261  8262  8263  8264  8265  8266
 [2245]  8267  8268  8269  8270  8271  8272  8273  8274  8275  8276  8277  8278
 [2257]  8279  8280  8281  8282  8283  8284  8285  8286  8287  8288  8289  8290
 [2269]  8291  8292  8293  8294  8295  8296  8297  8298  8299  8300  8301  8302
 [2281]  8303  8304  8305  8306  8307  8308  8309  8310  8311  8312  8313  8314
 [2293]  8315  8316  8317  8318  8319  8320  8321  8322  8323  8324  8325  8326
 [2305]  8327  8328  8329  8330  8331  8332  8333  8334  8335  8336  8337  8338
 [2317]  8339  8340  8341  8342  8343  8344  8345  8346  8348  8349  8350  8351
 [2329]  8352  8353  8354  8355  8356  8357  8358  8359  8360  8361  8362  8363
 [2341]  8364  8365  8366  8367  8368  8369  8371  8372  8373  8374  8375  8376
 [2353]  8377  8378  8379  8380  8381  8382  8383  8384  8385  8386  8387  8388
 [2365]  8389  8390  8391  8392  8393  8394  8395  8396  8397  8398  8399  8400
 [2377]  8401  8402  8403  8404  8405  8406  8407  8408  8409  8410  8411  8412
 [2389]  8413  8414  8415  8416  8417  8418  8419  8420  8421  8422  8423  8424
 [2401]  8425  8426  8427  8428  8429  8430  8431  8432  8433  8434  8435  8436
 [2413]  8437  8438  8439  8440  8441  8442  8443  8444  8445  8446  8447  8448
 [2425]  8449  8450  8451  8452  8453  8454  8455  8456  8457  8458  8459  8460
 [2437]  8461  8462  8463  8464  8465  8466  8467  8468  8469  8470  8471  8472
 [2449]  8473  8474  8475  8476  8477  8478  8479  8480  8481  8482  8483  8484
 [2461]  8485  8486  8487  8488  8489  8490  8491  8492  8493  8494  8495  8496
 [2473]  8497  8498  8499  8500  8501  8502  8503  8504  8505  8506  8507  8508
 [2485]  8509  8510  8511  8512  8513  8514  8515  8516  8517  8518  8519  8520
 [2497]  8521  8522  8523  8524  8525  8526  8527  8528  8529  8530  8531  8532
 [2509]  8533  8534  8535  8536  8537  8538  8539  8540  8541  8542  8543  8544
 [2521]  8545  8546  8547  8548  8549  8550  8551  8552  8553  8554  8555  8556
 [2533]  8557  8558  8559  8560  8561  8562  8563  8564  8565  8566  8567  8568
 [2545]  8569  8570  8571  8572  8573  8574  8575  8576  8577  8578  8579  8580
 [2557]  8581  8582  8583  8584  8585  8586  8587  8588  8589  8590  8591  8592
 [2569]  8593  8594  8595  8596  8597  8598  8599  8600  8601  8602  8603  8604
 [2581]  8605  8606  8607  8608  8609  8610  8611  8612  8613  8614  8615  8616
 [2593]  8617  8618  8619  8620  8621  8622  8623  8624  8625  8626  8627  8628
 [2605]  8631  8633  8634  8635  8638  8640  8645  8646  8647  8648  8649  8650
 [2617]  8651  8652  8653  8654  8655  8656  8657  8658  8659  8660  8661  8662
 [2629]  8663  8664  8665  8666  8667  8668  8669  8670  8671  8672  8673  8674
 [2641]  8675  8676  8677  8678  8679  8680  8681  8682  8683  8684  8685  8686
 [2653]  8687  8688  8689  8690  8691  8692  8693  8694  8695  8696  8697  8698
 [2665]  8699  8700  8701  8702  8703  8704  8705  8706  8707  8708  8709  8710
 [2677]  8711  8712  8713  8714  8715  8716  8717  8718  8719  8720  8721  8722
 [2689]  8723  8724  8725  8726  8727  8728  8729  8730  8731  8732  8733  8734
 [2701]  8735  8736  8737  8738  8739  8740  8741  8742  8743  8744  8745  8746
 [2713]  8747  8748  8749  8750  8751  8752  8753  8754  8755  8756  8757  8758
 [2725]  8759  8760  8761  8762  8763  8764  8765  8766  8767  8768  8769  8770
 [2737]  8771  8772  8773  8774  8775  8776  8777  8778  8779  8780  8781  8782
 [2749]  8783  8784  8785  8786  8787  8788  8789  8790  8791  8792  8793  8794
 [2761]  8795  8796  8797  8798  8799  8800  8801  8802  8803  8804  8805  8806
 [2773]  8807  8808  8809  8810  8811  8812  8813  8814  8815  8816  8817  8818
 [2785]  8819  8820  8821  8822  8823  8824  8825  8826  8827  8828  8829  8830
 [2797]  8831  8832  8833  8834  8835  8836  8837  8838  8839  8840  8841  8842
 [2809]  8843  8844  8845  8846  8847  8848  8849  8850  8851  8852  8853  8854
 [2821]  8855  8856  8857  8858  8859  8860  8861  8862  8863  8864  8865  8866
 [2833]  8867  8868  8869  8870  8871  8872  8873  8874  8875  8876  8877  8878
 [2845]  8879  8880  8881  8882  8883  8884  8885  8886  8887  8888  8889  8890
 [2857]  8891  8892  8893  8894  8895  8896  8897  8898  8899  8900  8901  8902
 [2869]  8903  8904  8905  8906  8907  8908  8909  8910  8911  8912  8913  8914
 [2881]  8915  8916  8917  8918  8919  8920  8921  8922  8923  8924  8925  8926
 [2893]  8927  8928  8929  8930  8931  8932  8933  8934  8935  8936  8937  8938
 [2905]  8939  8940  8941  8942  8943  8944  8945  8946  8947  8948  8949  8950
 [2917]  8951  8952  8953  8954  8955  8956  8957  8958  8959  8960  8961  8962
 [2929]  8963  8964  8965  8966  8967  8968  8969  8970  8971  8972  8973  8974
 [2941]  8975  8976  8977  8978  8979  8980  8981  8982  8983  8984  8985  8986
 [2953]  8987  8988  8989  8990  8991  8992  8993  8994  8995  8996  8997  8998
 [2965]  8999  9000  9001  9002  9003  9004  9005  9006  9007  9008  9009  9010
 [2977]  9011  9012  9013  9014  9015  9016  9017  9018  9019  9020  9021  9022
 [2989]  9023  9024  9025  9026  9027  9028  9029  9030  9031  9032  9033  9034

In [11]:
realbestmin=matrix(0,dim(MASE)[1],1)
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    min_value=apply(count,1,min)
    if (max(min_value,na.rm = TRUE)==0){
        realbestmin[i,]=0
        }
    else
        {
        min_value[is.na(min_value)]=100 
        realbestmin[i,]= whichmin(min_value)
    }
    }

In [12]:
table(realbestmin)

realbestmin
    0     1     2     3     4
10824  8212  7894 11816  9254

In [13]:
realbestmean=matrix(0,dim(MASE)[1],1)
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    mean_value=apply(count,1,meanunique)
    if (max(mean_value,na.rm = TRUE)==0){
        realbestmean[i,]=0
        }
    else
        {
        mean_value[is.na(mean_value)]=100 
        realbestmean[i,]= whichmin(mean_value)
    }
    }

In [14]:
realbestmean

      [,1]
 [1,] 4
 [2,] 3
 [3,] 3
 [4,] 1
 [5,] 3
 [6,] 1
 [7,] 1
 [8,] 2
 [9,] 0
[10,] 4
[11,] 0
[12,] 2
[13,] 0
[14,] 0
[15,] 4
[16,] 0
[17,] 3
[18,] 0
[19,] 1
[20,] 1
[21,] 0
[22,] 1
[23,] 2
[24,] 3
[25,] 3
[26,] 4
[27,] 3
[28,] 3
[29,] 3
[30,] 3
[31,] ⋮
[32,] 1
[33,] 0
[34,] 0
[35,] 0
[36,] 4
[37,] 4
[38,] 0
[39,] 4
[40,] 3
[41,] 2
[42,] 3
[43,] 0
[44,] 2
[45,] 3
[46,] 3
[47,] 1
[48,] 3
[49,] 0
[50,] 0
[51,] 0
[52,] 1
[53,] 3
[54,] 0
[55,] 3
[56,] 3
[57,] 0
[58,] 3
[59,] 0
[60,] 1
[61,] 1

In [15]:
head(data)

  frequency nperiods seasonal_period trend     spike        linearity
1 12        1        12              0.9472661 1.912037e-08  0.872829
2 12        1        12              0.8085632 2.203382e-07  0.943755
3 12        1        12              0.9992200 8.446236e-12 21.172689
4 12        1        12              0.8687883 3.833819e-06 -7.295270
5 12        1        12              0.7457338 1.006626e-05  4.869531
6 12        1        12              0.9976576 3.100646e-10 13.985335
  curvature   e_acf1     e_acf10   seasonal_strength ⋯ diff2_acf1 diff2_acf10
1  10.9548535 0.18758224 0.1214246 0.8404932         ⋯ -0.3962824 0.4604731
2   4.7359892 0.09830677 0.1405957 0.4180888         ⋯ -0.5668803 0.3576969
3   4.0198303 0.36279469 0.4204365 0.5104123         ⋯ -0.4913136 0.3353221
4   0.3739581 0.50800514 0.5935817 0.2357374         ⋯ -0.5149001 0.3611336
5   0.5621160 0.19177799 0.2581481 0.3207559         ⋯ -0.6516841 0.5925659
6 -12.7683661 0.50582153 0.2947603 0.4390163         ⋯ -0.4473514 0.2338179
  seas_acf1 length user_time  system_time elapsed_time user_time.1
1 0.8293577 469    0.05674529 0.05674529  0.05674529   0
2 0.5860238 469    0.05383134 0.05383134  0.05383134   0
3 0.9154861 469    0.06982851 0.06982851  0.06982851   0
4 0.3110420  82    0.06202483 0.06202483  0.06202483   0
5 0.1199568 112    0.04698277 0.04698277  0.04698277   0
6 0.9367465 666    0.07257485 0.07257485  0.07257485   0
  system_time.1 elapsed_time.1
1 0             0
2 0             0
3 0             0
4 0             0
5 0             0
6 0             0

In [16]:
set.seed(100)
index = sample(2,nrow(data),replace = TRUE,prob=c(0.7,0.3))

In [17]:
train_data=data[index==1,]
test_data=data[index==2,]
train_label_min=realbestmin[index==1,]
test_label_min=realbestmin[index==2,]
train_label_mean=realbestmean[index==1,]
test_label_mean=realbestmean[index==2,]

In [18]:
head(train_data)

  frequency nperiods seasonal_period trend     spike        linearity
1 12        1        12              0.9472661 1.912037e-08  0.872829
2 12        1        12              0.8085632 2.203382e-07  0.943755
3 12        1        12              0.9992200 8.446236e-12 21.172689
4 12        1        12              0.8687883 3.833819e-06 -7.295270
5 12        1        12              0.7457338 1.006626e-05  4.869531
6 12        1        12              0.9976576 3.100646e-10 13.985335
  curvature   e_acf1     e_acf10   seasonal_strength ⋯ diff2_acf1 diff2_acf10
1  10.9548535 0.18758224 0.1214246 0.8404932         ⋯ -0.3962824 0.4604731
2   4.7359892 0.09830677 0.1405957 0.4180888         ⋯ -0.5668803 0.3576969
3   4.0198303 0.36279469 0.4204365 0.5104123         ⋯ -0.4913136 0.3353221
4   0.3739581 0.50800514 0.5935817 0.2357374         ⋯ -0.5149001 0.3611336
5   0.5621160 0.19177799 0.2581481 0.3207559         ⋯ -0.6516841 0.5925659
6 -12.7683661 0.50582153 0.2947603 0.4390163         ⋯ -0.4473514 0.2338179
  seas_acf1 length user_time  system_time elapsed_time user_time.1
1 0.8293577 469    0.05674529 0.05674529  0.05674529   0
2 0.5860238 469    0.05383134 0.05383134  0.05383134   0
3 0.9154861 469    0.06982851 0.06982851  0.06982851   0
4 0.3110420  82    0.06202483 0.06202483  0.06202483   0
5 0.1199568 112    0.04698277 0.04698277  0.04698277   0
6 0.9367465 666    0.07257485 0.07257485  0.07257485   0
  system_time.1 elapsed_time.1
1 0             0
2 0             0
3 0             0
4 0             0
5 0             0
6 0             0

In [19]:
end_time = Sys.time()

In [20]:
time_matrix[1,]=end_time-start_time

In [21]:
end_time-start_time

Time difference of 19.28747 secs

## Target the interval where the actual error is minimum

In [22]:
start_time = Sys.time()

In [23]:
dtrain_xg_min_reg <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(train_label_min)) 
dtrain_xg_min_cl <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_min)) )

In [24]:
dtrain_lg_min_reg <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(train_label_min))
dtrain_lg_min_cl <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_min)))

In [25]:
xgb_min_reg <- xgboost(data = dtrain_xg_min_reg, nround=100)

[1]	train-rmse:1.717546
[2]	train-rmse:1.494097
[3]	train-rmse:1.367672
[4]	train-rmse:1.297307
[5]	train-rmse:1.258110
[6]	train-rmse:1.234723
[7]	train-rmse:1.219706
[8]	train-rmse:1.208295
[9]	train-rmse:1.200432
[10]	train-rmse:1.193467
[11]	train-rmse:1.189482
[12]	train-rmse:1.186445
[13]	train-rmse:1.185284
[14]	train-rmse:1.183805
[15]	train-rmse:1.180842
[16]	train-rmse:1.177202
[17]	train-rmse:1.175663
[18]	train-rmse:1.172185
[19]	train-rmse:1.170842
[20]	train-rmse:1.165507
[21]	train-rmse:1.163062
[22]	train-rmse:1.160947
[23]	train-rmse:1.158142
[24]	train-rmse:1.153431
[25]	train-rmse:1.152216
[26]	train-rmse:1.148526
[27]	train-rmse:1.145918
[28]	train-rmse:1.142743
[29]	train-rmse:1.139650
[30]	train-rmse:1.139272
[31]	train-rmse:1.136147
[32]	train-rmse:1.132675
[33]	train-rmse:1.132215
[34]	train-rmse:1.128989
[35]	train-rmse:1.126119
[36]	train-rmse:1.124130
[37]	train-rmse:1.121234
[38]	train-rmse:1.117761
[39]	train-rmse:1.115875
[40]	train-rmse:1.112881
[41]	train-rmse:1.111296
[42]	train-rmse:1.109174
[43]	train-rmse:1.107952
[44]	train-rmse:1.105709
[45]	train-rmse:1.103647
[46]	train-rmse:1.102384
[47]	train-rmse:1.101777
[48]	train-rmse:1.099546
[49]	train-rmse:1.098052
[50]	train-rmse:1.096144
[51]	train-rmse:1.093142
[52]	train-rmse:1.091339
[53]	train-rmse:1.089256
[54]	train-rmse:1.085582
[55]	train-rmse:1.082539
[56]	train-rmse:1.080532
[57]	train-rmse:1.077328
[58]	train-rmse:1.072940
[59]	train-rmse:1.070907
[60]	train-rmse:1.069380
[61]	train-rmse:1.067448
[62]	train-rmse:1.064636
[63]	train-rmse:1.062655
[64]	train-rmse:1.060477
[65]	train-rmse:1.057552
[66]	train-rmse:1.054860
[67]	train-rmse:1.053569
[68]	train-rmse:1.053018
[69]	train-rmse:1.051335
[70]	train-rmse:1.050645
[71]	train-rmse:1.047518
[72]	train-rmse:1.044578
[73]	train-rmse:1.042929
[74]	train-rmse:1.041878
[75]	train-rmse:1.041078
[76]	train-rmse:1.038433
[77]	train-rmse:1.037210
[78]	train-rmse:1.036654
[79]	train-rmse:1.034754
[80]	train-rmse:1.031657
[81]	train-rmse:1.030517
[82]	train-rmse:1.029735
[83]	train-rmse:1.026377
[84]	train-rmse:1.023969
[85]	train-rmse:1.021684
[86]	train-rmse:1.018939
[87]	train-rmse:1.015948
[88]	train-rmse:1.014157
[89]	train-rmse:1.013779
[90]	train-rmse:1.011763
[91]	train-rmse:1.009748
[92]	train-rmse:1.009390
[93]	train-rmse:1.008818
[94]	train-rmse:1.006647
[95]	train-rmse:1.004725
[96]	train-rmse:1.002506
[97]	train-rmse:1.000102
[98]	train-rmse:0.998647
[99]	train-rmse:0.997257
[100]	train-rmse:0.996464

In [26]:
xgb_min_cl <- xgboost(data = dtrain_xg_min_cl, nround=100, objective='multi:softmax',num_class=5)

[1]	train-mlogloss:1.522099
[2]	train-mlogloss:1.464419
[3]	train-mlogloss:1.421188
[4]	train-mlogloss:1.388207
[5]	train-mlogloss:1.361329
[6]	train-mlogloss:1.339267
[7]	train-mlogloss:1.320911
[8]	train-mlogloss:1.305706
[9]	train-mlogloss:1.291235
[10]	train-mlogloss:1.279405
[11]	train-mlogloss:1.267428
[12]	train-mlogloss:1.257418
[13]	train-mlogloss:1.248994
[14]	train-mlogloss:1.241427
[15]	train-mlogloss:1.234098
[16]	train-mlogloss:1.227503
[17]	train-mlogloss:1.219976
[18]	train-mlogloss:1.214410
[19]	train-mlogloss:1.210445
[20]	train-mlogloss:1.205435
[21]	train-mlogloss:1.200466
[22]	train-mlogloss:1.194654
[23]	train-mlogloss:1.189775
[24]	train-mlogloss:1.187514
[25]	train-mlogloss:1.185359
[26]	train-mlogloss:1.180508
[27]	train-mlogloss:1.177089
[28]	train-mlogloss:1.172830
[29]	train-mlogloss:1.169591
[30]	train-mlogloss:1.165501
[31]	train-mlogloss:1.161478
[32]	train-mlogloss:1.158127
[33]	train-mlogloss:1.154914
[34]	train-mlogloss:1.153237
[35]	train-mlogloss:1.148601
[36]	train-mlogloss:1.144834
[37]	train-mlogloss:1.142124
[38]	train-mlogloss:1.138568
[39]	train-mlogloss:1.135092
[40]	train-mlogloss:1.131415
[41]	train-mlogloss:1.126777
[42]	train-mlogloss:1.122352
[43]	train-mlogloss:1.119665
[44]	train-mlogloss:1.116492
[45]	train-mlogloss:1.113705
[46]	train-mlogloss:1.110066
[47]	train-mlogloss:1.106282
[48]	train-mlogloss:1.102330
[49]	train-mlogloss:1.099770
[50]	train-mlogloss:1.096992
[51]	train-mlogloss:1.093451
[52]	train-mlogloss:1.090110
[53]	train-mlogloss:1.086375
[54]	train-mlogloss:1.081808
[55]	train-mlogloss:1.078114
[56]	train-mlogloss:1.075153
[57]	train-mlogloss:1.072969
[58]	train-mlogloss:1.069121
[59]	train-mlogloss:1.066320
[60]	train-mlogloss:1.062867
[61]	train-mlogloss:1.059029
[62]	train-mlogloss:1.056962
[63]	train-mlogloss:1.053679
[64]	train-mlogloss:1.050869
[65]	train-mlogloss:1.048396
[66]	train-mlogloss:1.045964
[67]	train-mlogloss:1.043386
[68]	train-mlogloss:1.040086
[69]	train-mlogloss:1.037380
[70]	train-mlogloss:1.033904
[71]	train-mlogloss:1.030458
[72]	train-mlogloss:1.027359
[73]	train-mlogloss:1.024233
[74]	train-mlogloss:1.022061
[75]	train-mlogloss:1.019500
[76]	train-mlogloss:1.017339
[77]	train-mlogloss:1.013587
[78]	train-mlogloss:1.011230
[79]	train-mlogloss:1.008046
[80]	train-mlogloss:1.005260
[81]	train-mlogloss:1.000992
[82]	train-mlogloss:0.997987
[83]	train-mlogloss:0.995044
[84]	train-mlogloss:0.990315
[85]	train-mlogloss:0.987602
[86]	train-mlogloss:0.985212
[87]	train-mlogloss:0.981958
[88]	train-mlogloss:0.979842
[89]	train-mlogloss:0.976734
[90]	train-mlogloss:0.973638
[91]	train-mlogloss:0.970623
[92]	train-mlogloss:0.967348
[93]	train-mlogloss:0.964061
[94]	train-mlogloss:0.960851
[95]	train-mlogloss:0.958588
[96]	train-mlogloss:0.956492
[97]	train-mlogloss:0.954142
[98]	train-mlogloss:0.951963
[99]	train-mlogloss:0.949631
[100]	train-mlogloss:0.946201

In [27]:
lgb_min_reg <- lgb.train(data = dtrain_lg_min_reg, nrounds = 100)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011917 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4868
[LightGBM] [Info] Number of data points in the train set: 33791, number of used features: 21
[LightGBM] [Info] Start training from score 2.013820

In [28]:
params <- list(objective = "multiclass",
               num_class = 5, 
               metric = "multi_logloss")
lgb_min_cl <- lgb.train(data = dtrain_lg_min_cl,nrounds = 100,params=params)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006550 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4868
[LightGBM] [Info] Number of data points in the train set: 33791, number of used features: 21
[LightGBM] [Info] Start training from score -1.485881
[LightGBM] [Info] Start training from score -1.780430
[LightGBM] [Info] Start training from score -1.801723
[LightGBM] [Info] Start training from score -1.405506
[LightGBM] [Info] Start training from score -1.635400

In [29]:
end_time = Sys.time()
time_matrix[2,]=end_time-start_time

## Target the interval where the average error is minimum

In [30]:
start_time = Sys.time()

In [31]:
dtrain_xg_mean_reg <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(train_label_mean)) 
dtrain_xg_mean_cl <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_mean)) )

In [32]:
dtrain_lg_mean_reg <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(train_label_mean))
dtrain_lg_mean_cl <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_mean)))

In [33]:
xgb_mean_reg <- xgboost(data = dtrain_xg_mean_reg, nround=100)

[1]	train-rmse:1.496878
[2]	train-rmse:1.346614
[3]	train-rmse:1.261811
[4]	train-rmse:1.214192
[5]	train-rmse:1.187002
[6]	train-rmse:1.170034
[7]	train-rmse:1.157559
[8]	train-rmse:1.148882
[9]	train-rmse:1.144276
[10]	train-rmse:1.138588
[11]	train-rmse:1.133601
[12]	train-rmse:1.131450
[13]	train-rmse:1.128560
[14]	train-rmse:1.126860
[15]	train-rmse:1.121205
[16]	train-rmse:1.118770
[17]	train-rmse:1.116138
[18]	train-rmse:1.115413
[19]	train-rmse:1.114553
[20]	train-rmse:1.112527
[21]	train-rmse:1.110023
[22]	train-rmse:1.106163
[23]	train-rmse:1.104051
[24]	train-rmse:1.103132
[25]	train-rmse:1.100170
[26]	train-rmse:1.096876
[27]	train-rmse:1.094057
[28]	train-rmse:1.092860
[29]	train-rmse:1.089424
[30]	train-rmse:1.086710
[31]	train-rmse:1.085540
[32]	train-rmse:1.084260
[33]	train-rmse:1.080781
[34]	train-rmse:1.078690
[35]	train-rmse:1.074243
[36]	train-rmse:1.071490
[37]	train-rmse:1.070209
[38]	train-rmse:1.067184
[39]	train-rmse:1.064583
[40]	train-rmse:1.062882
[41]	train-rmse:1.061376
[42]	train-rmse:1.059045
[43]	train-rmse:1.057333
[44]	train-rmse:1.055159
[45]	train-rmse:1.051118
[46]	train-rmse:1.048272
[47]	train-rmse:1.047602
[48]	train-rmse:1.046701
[49]	train-rmse:1.044348
[50]	train-rmse:1.043499
[51]	train-rmse:1.041293
[52]	train-rmse:1.038795
[53]	train-rmse:1.037693
[54]	train-rmse:1.035236
[55]	train-rmse:1.034643
[56]	train-rmse:1.032538
[57]	train-rmse:1.029510
[58]	train-rmse:1.027655
[59]	train-rmse:1.024240
[60]	train-rmse:1.023385
[61]	train-rmse:1.022504
[62]	train-rmse:1.019979
[63]	train-rmse:1.017465
[64]	train-rmse:1.016031
[65]	train-rmse:1.013077
[66]	train-rmse:1.011545
[67]	train-rmse:1.009901
[68]	train-rmse:1.008345
[69]	train-rmse:1.006437
[70]	train-rmse:1.005581
[71]	train-rmse:1.005230
[72]	train-rmse:1.004651
[73]	train-rmse:1.002419
[74]	train-rmse:1.001271
[75]	train-rmse:0.999022
[76]	train-rmse:0.998103
[77]	train-rmse:0.997960
[78]	train-rmse:0.994957
[79]	train-rmse:0.993791
[80]	train-rmse:0.991316
[81]	train-rmse:0.990147
[82]	train-rmse:0.988311
[83]	train-rmse:0.987534
[84]	train-rmse:0.987313
[85]	train-rmse:0.984894
[86]	train-rmse:0.984144
[87]	train-rmse:0.982996
[88]	train-rmse:0.980052
[89]	train-rmse:0.977772
[90]	train-rmse:0.975983
[91]	train-rmse:0.973740
[92]	train-rmse:0.971927
[93]	train-rmse:0.971597
[94]	train-rmse:0.968640
[95]	train-rmse:0.967479
[96]	train-rmse:0.966224
[97]	train-rmse:0.964641
[98]	train-rmse:0.963612
[99]	train-rmse:0.960884
[100]	train-rmse:0.958854

In [34]:
xgb_mean_cl <- xgboost(data = dtrain_xg_mean_cl, nround=100, objective='multi:softmax',num_class=5)

[1]	train-mlogloss:1.518933
[2]	train-mlogloss:1.460102
[3]	train-mlogloss:1.417816
[4]	train-mlogloss:1.384642
[5]	train-mlogloss:1.358453
[6]	train-mlogloss:1.336262
[7]	train-mlogloss:1.317345
[8]	train-mlogloss:1.300439
[9]	train-mlogloss:1.286771
[10]	train-mlogloss:1.273942
[11]	train-mlogloss:1.262375
[12]	train-mlogloss:1.252611
[13]	train-mlogloss:1.243783
[14]	train-mlogloss:1.235543
[15]	train-mlogloss:1.228125
[16]	train-mlogloss:1.220255
[17]	train-mlogloss:1.215724
[18]	train-mlogloss:1.210127
[19]	train-mlogloss:1.205996
[20]	train-mlogloss:1.201892
[21]	train-mlogloss:1.195737
[22]	train-mlogloss:1.191366
[23]	train-mlogloss:1.188600
[24]	train-mlogloss:1.184831
[25]	train-mlogloss:1.181518
[26]	train-mlogloss:1.178424
[27]	train-mlogloss:1.174236
[28]	train-mlogloss:1.170777
[29]	train-mlogloss:1.166499
[30]	train-mlogloss:1.163586
[31]	train-mlogloss:1.159831
[32]	train-mlogloss:1.156769
[33]	train-mlogloss:1.153036
[34]	train-mlogloss:1.148482
[35]	train-mlogloss:1.145132
[36]	train-mlogloss:1.142018
[37]	train-mlogloss:1.136627
[38]	train-mlogloss:1.133566
[39]	train-mlogloss:1.130052
[40]	train-mlogloss:1.127670
[41]	train-mlogloss:1.124678
[42]	train-mlogloss:1.120160
[43]	train-mlogloss:1.118130
[44]	train-mlogloss:1.116295
[45]	train-mlogloss:1.112014
[46]	train-mlogloss:1.107031
[47]	train-mlogloss:1.103790
[48]	train-mlogloss:1.098423
[49]	train-mlogloss:1.093663
[50]	train-mlogloss:1.090000
[51]	train-mlogloss:1.085163
[52]	train-mlogloss:1.080168
[53]	train-mlogloss:1.076465
[54]	train-mlogloss:1.073059
[55]	train-mlogloss:1.069078
[56]	train-mlogloss:1.066518
[57]	train-mlogloss:1.063607
[58]	train-mlogloss:1.061240
[59]	train-mlogloss:1.056437
[60]	train-mlogloss:1.054777
[61]	train-mlogloss:1.051827
[62]	train-mlogloss:1.048156
[63]	train-mlogloss:1.046510
[64]	train-mlogloss:1.044651
[65]	train-mlogloss:1.041997
[66]	train-mlogloss:1.038984
[67]	train-mlogloss:1.036067
[68]	train-mlogloss:1.032325
[69]	train-mlogloss:1.026800
[70]	train-mlogloss:1.023864
[71]	train-mlogloss:1.021686
[72]	train-mlogloss:1.018350
[73]	train-mlogloss:1.015709
[74]	train-mlogloss:1.012569
[75]	train-mlogloss:1.010227
[76]	train-mlogloss:1.006390
[77]	train-mlogloss:1.004886
[78]	train-mlogloss:1.003018
[79]	train-mlogloss:1.000905
[80]	train-mlogloss:0.998358
[81]	train-mlogloss:0.995903
[82]	train-mlogloss:0.993013
[83]	train-mlogloss:0.990328
[84]	train-mlogloss:0.987806
[85]	train-mlogloss:0.983287
[86]	train-mlogloss:0.980632
[87]	train-mlogloss:0.976811
[88]	train-mlogloss:0.973447
[89]	train-mlogloss:0.970158
[90]	train-mlogloss:0.966678
[91]	train-mlogloss:0.964290
[92]	train-mlogloss:0.960992
[93]	train-mlogloss:0.959156
[94]	train-mlogloss:0.955833
[95]	train-mlogloss:0.953092
[96]	train-mlogloss:0.949722
[97]	train-mlogloss:0.946400
[98]	train-mlogloss:0.943414
[99]	train-mlogloss:0.941031
[100]	train-mlogloss:0.939158

In [35]:
lgb_mean_reg <- lgb.train(data = dtrain_lg_mean_reg,nrounds = 100)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012255 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4868
[LightGBM] [Info] Number of data points in the train set: 33791, number of used features: 21
[LightGBM] [Info] Start training from score 1.613921

In [36]:
params <- list(objective = "multiclass",
               num_class = 5, 
               metric = "multi_logloss")
lgb_mean_cl <- lgb.train(data = dtrain_lg_mean_cl,params=params,nrounds = 100)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.014135 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4868
[LightGBM] [Info] Number of data points in the train set: 33791, number of used features: 21
[LightGBM] [Info] Start training from score -1.196925
[LightGBM] [Info] Start training from score -1.644554
[LightGBM] [Info] Start training from score -1.677425
[LightGBM] [Info] Start training from score -1.493495
[LightGBM] [Info] Start training from score -2.371523

In [37]:
end_time = Sys.time()
time_matrix[3,]=end_time-start_time

In [38]:
end_time-start_time

Time difference of 6.743447 mins

## predict

In [39]:
start_time = Sys.time()

In [40]:
alldatalgb <- lgb.Dataset(data = as.matrix(data))
alldataxgb <- xgb.DMatrix(data = as.matrix(data))

In [41]:
xgbregmin=predict(xgb_min_reg,alldataxgb)
xgbclsmin=predict(xgb_min_cl,alldataxgb)
lgbregmin=predict(lgb_min_reg,as.matrix(data))
lgbclsmin=predict(lgb_min_cl,as.matrix(data))

In [42]:
xgbregmin

    [1]  2.152967215  2.726136208  3.490833998  0.963540494  1.782772422
    [6]  1.351021767  2.004328489  1.766270757  0.063182786  2.612715960
   [11]  0.940591156  2.551850319  1.824522257  0.314219803  3.474584103
   [16]  1.401627660  2.627771378  1.080519080  1.152341008  1.170283675
   [21]  0.370090187  2.242703199  2.417632580  2.956578255  3.444133997
   [26]  4.245733738  2.937590599  3.557305574  3.121192932  3.017340183
   [31]  2.201222181  3.627236605  2.760938406  3.429369688  3.204774141
   [36]  3.306174040  2.245378256  3.331686497  3.619935036  2.490279675
   [41]  0.604798913  1.714360476  1.608341336  1.581571937  2.643884182
   [46]  0.980133653  1.603292227  1.796469331  3.446124077  1.042351604
   [51]  0.899235666  2.552964926  1.152990341  1.821436882  4.437406540
   [56]  0.811987579  3.739730120  0.875431478  1.632732511  3.270207644
   [61]  2.214380264  1.063173175  2.198515892  1.143623471  0.708917439
   [66]  1.343036532  0.741026700  0.808353841  1.202339053  1.500287652
   [71]  2.345278978  0.895453274  0.396864951  1.192916751  0.559424818
   [76]  1.352250099  2.647163153  1.332638383  2.366533518 -0.063412219
   [81]  1.114540935  1.146957636  1.651744485  1.702612400  1.646305084
   [86]  0.669811845  1.912268877  0.214891940  3.634505987  2.430215120
   [91]  1.969828129  3.558357239  3.873558521  3.108409643  2.699500322
   [96]  1.636866331  2.190882206  1.659093976  2.206583261  2.244879246
  [101]  2.795243263  2.390689850  1.783189535  1.486630917  2.565108299
  [106]  1.397357106  2.767122030  2.576589584  1.549165010  2.412219763
  [111]  1.716117501  2.325438023  2.488443136  4.259027958  2.612607718
  [116]  3.467970133  2.807435513  2.827523708  3.894091129  3.013121367
  [121]  3.848409176  3.580446720  3.222263813  2.951273441  3.042505980
  [126]  3.110945225  1.902128696  3.425821304  2.728754282  3.236620665
  [131]  2.069349766  1.465744972  2.289245844  2.483783007  1.707449079
  [136]  1.517614841  1.200183272  3.610449553  3.604918003  3.152868271
  [141]  1.497338653  3.150889635  1.937798738  3.800989389  3.847596169
  [146]  2.967991114  2.080148458  3.953291416  3.603089333  3.991143942
  [151]  3.995767832  4.504533291  1.533993244  1.023447037  1.725066304
  [156]  3.499234915  3.203178406  2.723104477  3.356287479  1.405358315
  [161]  1.655444264  1.491019845  2.583268642  3.061182976  0.972278595
  [166]  3.605332136  1.042006135  3.336572647  4.503390312  1.054183960
  [171]  3.017807961  3.790796995  1.632302880  3.530216217  2.499430418
  [176]  3.320864201  3.385291576  3.267187357  2.793814182  4.159082413
  [181]  3.388543606  2.623871088  3.855698824  3.078676462  2.728038311
  [186]  3.812362194  3.344994068  3.717531681  2.811560869  3.413211107
  [191]  1.712705374  1.266361713  3.261271954  2.268346786  1.205682635
  [196]  2.863394499  3.217510223  3.482663393  2.704217196  4.507576466
  [201]  1.641276717  4.010640621  2.346408844  2.263463259  0.878168583
  [206]  4.109899998  1.671491861  3.226465702  2.978772879  3.965246916
  [211]  3.763414621  3.576545477  2.747369289  3.127432108  1.158445239
  [216]  1.295568228  1.838637829  1.348262429  1.540421605  1.458715200
  [221]  1.246519089  0.911495030  1.298215389  3.175863981  2.796379328
  [226]  1.363682270  1.298215389  0.967327416  1.429591894  1.553978086
  [231]  0.967327416  2.566266775  2.881872177  3.457875490  2.522015333
  [236]  1.349783182  3.390132427  1.555053473  1.836503267  2.070483685
  [241]  1.037945509  2.288156271  2.816546202  2.181993961  2.992666483
  [246]  2.356641054  0.787754834  1.900164843  2.143348932  3.204990864
  [251]  3.271353960  1.904351830  2.196312904  2.057452440  1.112125278
  [256]  1.722271681  1.751315832  1.270165920  1.129794598  2.771250486
  [261]  1.410220146  1.908277154  1.703421235  1.647153974  2.376046181
  [266]  2.651263237  2.386403799  2.091088295  3.064906359  3.490305662
  [271]  0.966048002  3.620027781  2.929390669  2.692790508  1.706436872
  [276]  2.377774477  1.902508736  1.637647033  0.746499479  1.340600729
  [281]  2.433630705  1.962256074  0.863238215  1.951407075  3.033882618
  [286]  1.902529120  1.963607073  3.491180658  1.558278322  1.871122122
  [291]  1.995481133  1.968998551  2.016691446  1.458635688  0.996265233
  [296]  1.620441556  1.054186702  1.302968740  1.984485865  3.002155542
  [301]  3.094152451  1.207766652  1.670717239  3.380506039  2.853200912
  [306]  3.211734772  2.983131170  2.593425751  2.518111467  2.731680155
  [311]  2.052973509  2.795257092  1.521313190  0.936072528  1.243538857
  [316]  3.571036339  1.559028149  1.919751406  2.139054775  2.240592003
  [321]  2.708769083  1.705638409  1.151595235  3.421552420  1.996013641
  [326]  2.077850580  2.061745405  3.632484198  2.897579908  2.179068327
  [331]  1.362319827  2.690906763  2.788141489  3.722039223  3.092353106
  [336]  2.818617105  1.660951257  2.664731741  2.283649206  2.746040106
  [341]  1.922637939  3.852827549  2.790632725  2.381739378  0.777248621
  [346]  1.300164938  2.886180878  1.840831757  1.251057744  2.642062426
  [351]  3.523674250  3.760539532  3.591962814  1.173724890  2.813106060
  [356]  2.773775578  2.698132038  3.519132614  3.460752249  2.606877565
  [361]  3.303936958  2.645687819  1.784723997  1.500300288  1.277862668
  [366]  1.436194301  3.272611856  2.388768673  3.029088974  2.779211998
  [371]  2.131141186  3.094579220  1.468305349  3.590115070  2.889008760
  [376]  1.249450922  2.217592955  2.590457201  1.687288165  2.172326565
  [381]  2.036691189  1.603874564  1.930844545  0.833243310  1.119148850
  [386]  1.264704108  2.700203896  1.459731102  2.060699463  2.745151281
  [391]  2.278349161  1.957220793  2.776736498  2.081510782  3.128027916
  [396]  0.821483076  3.505469799  1.017610312  0.802675903  2.660877943
  [401]  2.128821850  2.141296625  3.253950596  2.437103987  2.331025839
  [406]  2.074945927  1.619826913  2.528214455  3.031198978  1.404564738
  [411]  0.687947512  1.695563436  2.013138771  1.749243259  2.183427334
  [416]  3.897092342  1.599460244  3.572799206  3.540357590  1.868340492
  [421]  2.313859940  3.853324890  2.870288610  1.023631573  3.273148060
  [426]  2.580070496  2.618432045  2.872499228  3.172775745  3.064783573
  [431]  2.186954260  4.164774418  2.323843002  0.872727334  1.276866794
  [436]  2.856796265  3.351200581  4.517944336  1.465785265  2.089804649
  [441]  1.146986604  2.143641233  3.343175411  2.572788954  3.547924042
  [446]  3.067639589  1.799257040  1.406453013  2.096099377  2.733331203
  [451]  2.803786039  2.798536062  2.810329437  3.372435808  2.596375704
  [456]  3.828186274  3.076080084  2.457525969  0.797271669  2.858309031
  [461]  1.658935428  2.589589119  2.984598637  1.950509667  3.232916355
  [466]  3.100579739  3.116985798  2.398665905  2.276176691  2.416256428
  [471]  2.880712509  2.042804003  2.059095144  2.991055489  2.829206228
  [476]  1.816044092  1.873880386  1.832481384  0.974578321  1.945562959
  [481]  2.502974033  1.506482720  2.863865852  2.447023392  1.512004137
  [486]  2.878036022  2.960480213  1.827505589  2.388279438  2.512757540
  [491]  3.503000975  1.715493679  2.271990061  3.012614489  3.033827066
  [496]  3.109700441  2.673411608  2.074781656  3.062367439  1.738078833
  [501]  2.354725838  2.333842278  1.731528044  2.324320316  2.463222504
  [506]  2.980354786  3.271810532  2.926802635  2.287268877  2.830319643
  [511]  3.348770142  2.577029705  2.294701099  2.178087234  3.030405045
  [516]  1.245190620  2.190837383  3.151508808  3.401298046  2.689442396
  [521]  3.462033510  4.361051083  2.902586699  3.372390032  2.284120321
  [526]  3.578557253  2.245532990  2.643014431  2.822047710  2.685459375
  [531]  2.905811310  1.448287845  2.886583805  2.160296202  2.210455656
  [536]  2.767257929  1.994643092  1.864121318  2.757917881  2.757061481
  [541]  2.884588003  2.120349646  1.816073895  1.743699789  3.244625568
  [546]  3.429693460  3.064332485  2.103651762  2.604373217  2.138059855
  [551]  1.889661789  3.088424921  2.375728846  3.683281183  0.427535683
  [556]  2.309815407  2.900090218  2.029726982  1.107196689  2.107530832
  [561]  2.877331495  3.144040585  2.668247700  2.241976738  1.954007506
  [566]  2.065659046  2.776352167  3.506933451  2.151482105  3.106423855
  [571]  0.816213608  1.755174041  3.141099215  0.660472572  1.015804887
  [576]  0.894676030  2.044130087  1.663106203  0.547112882  2.086235046
  [581]  1.929298759  1.981410265  1.618450642  3.107862473  2.643195391
  [586]  2.785645485  0.553583384  2.421353817  2.079161644  3.670001030
  [591]  1.185299635  3.913476229  3.820339918  2.659802198  3.966640234
  [596]  2.811191797  3.207468987  1.228916764  3.602770805  3.959039450
  [601]  3.720965147  3.633219004  2.709756374  2.505920649  2.190966606
  [606]  2.365076542  4.114686489  2.474611521  3.350784779  2.138306618
  [611]  0.967367589  2.574843407  2.541607857  4.145394802  2.646063089
  [616]  2.093886852  2.687074900  3.940163374  0.561641932  3.752416849
  [621]  2.778485060  2.715484619  1.637495756  3.313235521  3.236747742
  [626]  3.924185276  3.806773663  2.736082792  2.955433369  2.427591801
  [631]  3.422952175  3.419331074  3.389945030  2.090085506  3.869503021
  [636]  3.664888382  2.807571173  3.705179453  3.041115284  3.175538778
  [641]  3.741586208  2.995920658  2.092404842  1.285797238  2.239037275
  [646]  1.586923361  3.252742529  3.279951334  2.269305944  4.304203510
  [651]  3.578737259  3.888406992  3.061298609  3.439944983  3.434453964
  [656]  3.199187756  2.654575825  3.327219725  3.268891573  1.528696060
  [661]  2.444052458  2.723203182  3.039937258  4.105568409  2.712268114
  [666]  2.556994200  3.190909386  3.238814592  2.043780327  2.409759283
  [671]  2.332818270  2.578520775  2.293505430  1.197904110  1.115999460
  [676]  1.822866797  2.482698202  2.249978065  2.514260054  2.144878864
  [681]  3.197048426  2.549973249  1.994039893  3.148911238  1.833753109
  [686]  0.175739303  2.803641796  3.474666595  4.277289391  0.637774646
  [691]  2.589319468  1.885781646  2.182886124  2.577875614  1.525162339
  [696]  2.786812305  1.758412480  1.572846055  2.357816696  3.459034204
  [701]  2.815382719  3.837498188  4.716680050  2.554382563  2.914484262
  [706]  2.051994801  2.476364851  1.415784478  2.230111837  2.762377262
  [711]  1.837990403  1.212200165  2.494498730  2.281248808  1.735732079
  [716]  1.722947359  3.017617464  2.747775316  3.121630430  3.855904341
  [721]  1.763968468  1.894921184  3.274378538  2.528314590  3.558600426
  [726]  2.019014120  3.120030642  1.721691370  2.209690571  3.705934286
  [731]  2.107677460  1.604331613  1.875467658  2.711202860  3.028120041
  [736]  2.304187775  0.812357187  1.474351406  3.033622026  2.124030828
  [741]  2.768979073  3.878401995  1.739639759  2.468973637  1.695049167
  [746]  2.039693594  3.281911135  2.289246082  2.181284189  3.157497406
  [751]  1.431864858  2.996377230  2.192829370  2.985725403  1.450725317
  [756]  2.336609364  1.635484219  2.708040237  2.285405874  2.251043558
  [761]  1.647779703  3.305542469  2.891375303  2.331891298  1.027572155
  [766]  2.009479523  2.087689400  3.450199127  2.611128330  2.112365484
  [771]  3.594771624  2.089254141  1.865971804  1.773195982  3.095412970
  [776]  3.717245102  2.358785152  2.625171661  1.987697005  2.373215437
  [781]  1.963050127  1.350365758  2.625374317  2.186973810  3.054036617
  [786]  2.360680103  2.909393072  3.389297962  2.326828003  1.249756575
  [791]  3.467511415  3.905398130  1.612961769  1.353957057  2.770201206
  [796]  2.195031881  2.547108173  2.302202225  2.942259789  1.923382282
  [801]  1.874072671  2.431045771  2.460763693  2.322076082  3.609228611
  [806]  3.119501352  1.448708177  1.929293633  0.589293480  3.817569971
  [811]  2.255328417  3.855213881  3.750343084  2.739533663  1.301377296
  [816]  1.724979281  2.580728769  3.639292479  3.237126827  2.725031853
  [821]  2.546012402  2.877511024  2.462956667  1.778490305  3.878877640
  [826]  3.293523550  2.236086130  3.435012579  2.365832090  2.161627054
  [831]  1.478220344  1.736713648  1.683974504  2.408138514  2.352627993
  [836]  3.594377279  3.501539946  2.888727903  3.250891924  3.201445818
  [841]  3.570384741  3.161903620  2.040849924  3.454818010  2.009382248
  [846]  3.339246750  3.707013845  4.258301258  2.806367636  3.845145464
  [851]  3.830362797  3.935754776  1.026457906  3.712132692  1.966774821
  [856]  2.674336195  2.921394825  3.156393290  2.762305260  1.731461644
  [861]  2.661179066  3.673358917  2.371062756  2.365133286  3.676582575
  [866]  2.322307348  0.519172788  3.184795618  2.561714888  2.328584194
  [871]  2.690528870  2.667293072  2.018910885  2.455183983  1.996570110
  [876]  3.717476606  3.341979980  3.128833055  3.018954992  2.780108929
  [881]  2.781538963  3.778885841  3.706053495  1.587138295  3.368641615
  [886]  2.880887032  1.668893456  3.109235048  3.261480570  2.171007395
  [891]  3.046033859  2.672029972  2.489045620  2.974362612  2.737824917
  [896]  2.401708126  1.307321429  3.492875814  3.334146738  1.763573408
  [901]  2.824685812  1.833498836  3.026947737  1.182040572  3.151204586
  [906]  3.530735254  2.178237915  3.594929695  2.744899750  0.318980873
  [911]  2.168849468  3.272246122  3.080088615  1.540465593  2.744742870
  [916]  2.515985966  2.659190178  1.578462839  2.286954880  2.187386513
  [921]  3.946355104  3.118729353  2.920290232  2.392180681  2.994903088
  [926]  2.422308207  1.537137866  3.849503756  3.262622356  2.474317789
  [931]  1.547780991  2.360164165  2.311225176  2.862782240  2.797335863
  [936]  2.212803125  1.756404638  4.045176983  3.707007408  2.339458466
  [941]  2.526260376  3.039998293  1.734828472  1.580107212  3.134266615
  [946]  1.776604176  3.066159010  3.299013138  1.023745775  2.632219791
  [951]  2.369182825  2.933729887  1.754736900  2.980525494  2.340219259
  [956]  3.132225990  2.539474249  2.121152163  1.036012650  3.072831392
  [961]  3.467847586  3.074856281  2.683197737  2.284468412  2.354096413
  [966]  2.444235325  2.750932693  2.759607077  2.638154030  2.459700108
  [971]  1.553091764  1.303515673  1.394466400  2.764559269  2.023452997
  [976]  3.217014551  1.840120196  2.622128010  2.200902939  3.278745413
  [981]  3.554364443  3.934563637  3.078013897  3.014007807  3.861692905
  [986]  3.695392370  2.970740318  3.436321497  3.366529942  2.502596378
  [991]  2.770775557  3.280598164  2.697079897  2.639196873  2.091439009
  [996]  2.110526800  1.352022052  2.862039328  2.557957649  2.033413649
 [1001]  1.345055580  3.354653597  2.342569113  3.484704018  2.663204670
 [1006]  3.393551588  2.084581375  2.218399763  1.729173303  2.902463198
 [1011]  1.127878785  0.952914417  2.103357315  2.147616386  2.472398043
 [1016]  3.114744902  2.236012936  3.051944733  2.489018679  2.496750593
 [1021]  2.664752722  2.941642284  1.784280658  0.551991999  1.479243636
 [1026]  1.430046439  0.829264045  3.439011097  3.088369131  2.756445885
 [1031]  2.722075224  1.066145539  3.227714539  2.201740742  2.003425837
 [1036]  1.690345287  2.234258652  1.653902173  1.551260948  1.506913662
 [1041]  1.754878283  2.067639351  3.375032425  2.893484592  1.158931494
 [1046]  2.987670898  3.037611485  2.872340679  2.634970903  2.640376568
 [1051]  1.488334894  2.959873438  2.532171965  2.082882166  2.705569267
 [1056]  1.538074255  1.935987234  1.580408812  2.244686604  3.350424528
 [1061]  2.491976976  3.129056454  2.384236813  1.398883224  2.511482239
 [1066]  3.271650553  2.860476255  2.714474678  2.472099543  1.471168995
 [1071]  1.200869083  1.749123335  3.675554752  1.738320112  3.046410561
 [1076]  2.911296844  2.230737686  1.562094331  2.824997187  3.819586039
 [1081]  2.244155169  3.624705315  2.900577545  2.287267923  3.196032524
 [1086]  1.904942274  1.603618503  3.820542336  2.411989689  2.036401510
 [1091]  1.892845035  4.503609657  3.426400185  1.587564230  1.521975040
 [1096]  2.936970949  2.917070150  0.931516051  1.829254270  2.920280933
 [1101]  1.490231395  3.284725428  3.158816814  3.123208046  3.573448896
 [1106]  2.681710482  2.235486031  3.695121527  2.647988319  1.521404028
 [1111]  1.938124776  2.484345198  2.702806950  1.979023695  2.038467169
 [1116]  3.164139986  2.049716711  3.120870113  2.234365702  1.951210141
 [1121]  2.387203455  3.278126717  2.814264536  2.119053125  1.240965724
 [1126]  2.562811375  2.512046814  2.475538969  2.427833080  2.369129896
 [1131]  2.706051826  1.892885208  1.217651248  4.288663387  2.429548264
 [1136]  3.038931847  3.212910175  2.567894936  3.011441946  3.563744307
 [1141]  3.450291872  1.528756261  1.453162909  3.291338921  2.990127563
 [1146]  2.020280838  1.605360270  1.879348993  1.928830147  2.466620684
 [1151]  3.124627829  1.805978775  3.017576694  2.942980051  3.010858297
 [1156]  2.252470255  2.784221411  3.149671316  2.948010206  1.652836800
 [1161]  1.805084229  1.799198389  2.071373701  3.538062572  3.023909330
 [1166]  1.624973416  2.712830782  1.063038111  1.389171839  1.014924288
 [1171]  2.955600262  2.857750416  1.452057362  2.304951191  2.400886536
 [1176]  3.286642551  2.354024887  3.540108442  1.987930536  2.502998114
 [1181]  1.719895124  1.410863519  1.613073707  1.615944028  2.900844812
 [1186]  2.484701157  2.695066452  2.657767773  3.039329052  1.615898728
 [1191]  3.007771730  2.338480473  2.713645935  2.501068115  1.793364525
 [1196]  1.681884289  1.686594367  2.694037437  3.040098906  1.478116393
 [1201]  2.772532225  3.422619820  3.668092251  2.197857857  2.290713549
 [1206]  1.747994661  3.189917803  1.999652743  2.325362444  2.758954763
 [1211]  2.049343109  3.129723072  2.263282061  2.491637707  2.501522303
 [1216]  2.375086546  2.887096643  1.622157335  1.854271889  3.309302092
 [1221]  3.183169365  3.259274960  2.320096731  2.783719063  2.574420214
 [1226]  3.377560377  3.182246208  1.833875418  1.645067215  2.302385092
 [1231]  2.708898544  1.318376422  2.751347542  3.868883133  2.467768431
 [1236]  1.626425982  3.328453302  2.363749504  2.653945684  0.995471060
 [1241]  2.504106522  1.212004304  1.654441237  2.270394325  1.877408862
 [1246]  3.521951914  3.539572239  2.881679058  3.607637167  2.919000864
 [1251]  1.308331251  1.033609509  1.764315367  1.696370363  3.925704718
 [1256]  5.044324875  2.122076511  1.175666809  0.582883418  2.625699997
 [1261]  3.628309727  3.717578888  2.558494806  1.703780293  1.993157864
 [1266]  2.790905714  3.085690737  3.399655819  3.159894943  2.648288727
 [1271]  0.968832433  2.392520666  1.979407549  2.449738503  2.920780897
 [1276]  1.881980777  2.484470129  2.818658590  3.570196629  4.255936623
 [1281]  3.179509878  1.320464969  2.071748972  2.463344097  1.691167951
 [1286]  3.665333271  4.161539078  1.937995434  4.223299503  2.159607887
 [1291]  1.493090391  2.383338690  3.146269560  4.280077934  2.669542313
 [1296]  2.531301737  2.993906021  2.686326027  1.672710061  2.144922972
 [1301]  3.137877226  2.545749187  2.604462624  1.728338242  1.171988964
 [1306]  2.752439499  2.222031116  3.069410086  3.003972292  0.756626189
 [1311]  0.689949036  3.494816065  2.594940424  3.298724890  2.822845697
 [1316]  2.992568970  3.057081223  3.902433157  3.426263332  3.677815914
 [1321]  2.820287228  3.798185587  1.785685539  3.266893387  3.338361740
 [1326]  2.252079487  3.088166237  2.189309597  1.704339743  2.793194056
 [1331]  2.859629154  2.146001101  2.884590864  2.737960577  2.013996601
 [1336]  3.167208433  4.076001644  1.767653108  2.765379906  1.574193239
 [1341]  3.876943827  1.853688002  1.045464873  2.849274635  3.181458235
 [1346]  1.671057582  2.197484493  2.645260572  3.200288057  1.876001716
 [1351]  3.156705856  1.110036850  2.552021742  3.106847286  1.914734364
 [1356]  3.559983492  2.547400713  3.827642202  3.549113512  2.435912609
 [1361]  2.541989803  1.750047922  2.674958944  3.867194176  2.240544319

In [43]:
xgbclsmin

    [1] 4 4 4 0 2 1 3 3 0 3 0 2 4 0 1 0 3 1 1 1 0 3 2 4 3 4 3 4 4 4 3 3 4 3 4 3
   [37] 3 4 3 4 0 1 1 3 4 0 3 0 4 0 0 4 1 0 4 1 4 0 2 4 2 3 3 0 1 0 0 0 2 0 3 0
   [73] 0 2 0 1 3 0 3 0 0 2 0 3 2 0 2 0 4 1 1 4 4 4 2 1 4 1 4 1 4 4 3 0 4 1 3 3
  [109] 3 3 3 3 3 4 4 4 4 3 4 3 4 4 4 4 3 4 3 4 4 4 3 3 3 3 0 1 0 4 4 3 1 4 2 3
  [145] 4 3 3 4 4 4 4 3 0 0 3 3 3 4 4 3 3 3 3 3 0 4 0 3 3 3 3 4 3 3 3 4 3 3 2 4
  [181] 3 4 3 3 4 4 4 4 4 3 2 0 4 3 1 2 4 4 4 3 4 3 3 3 0 3 3 4 4 4 4 3 4 4 0 0
  [217] 3 0 0 0 0 1 0 1 4 0 0 0 2 2 0 3 3 4 4 1 3 3 3 3 1 3 2 1 4 3 1 3 2 3 4 3
  [253] 2 3 0 0 3 0 0 3 1 3 3 3 3 3 2 4 3 3 3 4 4 4 4 3 4 3 0 1 4 3 1 2 4 2 2 2
  [289] 0 3 0 2 3 1 1 2 0 3 0 3 3 0 3 4 4 3 4 2 2 2 0 4 2 0 0 4 3 3 0 3 2 4 0 3
  [325] 1 3 1 4 2 0 0 4 4 4 2 4 0 2 3 4 2 4 4 4 0 0 3 1 0 3 4 4 4 0 3 4 3 4 3 4
  [361] 4 4 0 0 1 1 4 2 3 3 3 3 3 4 4 0 4 3 0 3 4 1 4 0 3 0 4 0 3 4 3 0 3 0 4 3
  [397] 4 3 0 3 2 3 4 4 2 4 0 3 3 0 0 3 3 3 3 4 1 4 4 3 4 4 3 3 4 3 3 3 4 4 3 4
  [433] 4 0 3 3 1 3 0 3 0 4 4 2 4 3 3 0 3 3 4 4 3 3 3 4 3 4 0 3 2 3 3 3 3 3 3 4
  [469] 3 3 3 2 0 3 3 1 1 0 1 0 4 0 2 3 4 2 3 0 4 3 4 3 3 2 4 3 4 4 0 0 3 2 3 2
  [505] 2 4 2 4 3 2 4 3 4 2 3 1 2 4 4 3 3 4 3 3 3 4 2 0 3 3 3 2 2 0 2 4 4 2 2 2
  [541] 3 2 2 2 3 3 4 3 2 3 4 0 4 4 0 0 3 2 0 2 2 3 4 3 1 2 1 3 3 1 1 0 3 3 0 0
  [577] 1 0 0 3 0 4 3 3 4 3 0 3 2 3 0 4 4 2 3 3 1 4 4 4 4 4 3 2 2 3 4 4 3 3 0 3
  [613] 3 4 3 0 4 4 0 4 1 1 1 4 3 3 4 3 4 3 4 3 4 4 4 3 4 3 3 4 4 1 1 0 3 0 3 1
  [649] 2 4 3 4 4 2 4 4 1 4 4 1 2 3 2 4 3 4 4 4 4 3 4 3 3 0 0 4 3 4 3 4 1 4 1 4
  [685] 0 0 1 4 4 0 0 2 4 3 1 3 3 0 3 4 4 4 4 4 4 4 4 3 3 0 3 0 3 4 0 0 2 4 4 4
  [721] 0 2 1 3 2 0 3 1 2 4 1 0 0 4 4 2 0 1 2 1 4 1 1 4 1 4 1 3 3 4 0 4 0 4 1 3
  [757] 0 4 4 2 3 4 4 4 0 0 4 4 4 4 4 1 0 2 4 4 3 4 1 1 1 0 1 0 1 1 4 4 4 1 2 4
  [793] 0 0 4 3 3 3 3 1 1 4 4 4 1 4 1 0 0 0 0 4 4 1 0 1 4 4 4 4 3 4 0 0 3 4 4 4
  [829] 0 4 0 4 2 3 4 3 4 3 4 4 4 4 3 4 3 3 4 4 4 4 3 4 1 4 3 2 4 4 4 4 1 4 4 2
  [865] 4 4 0 1 3 4 1 4 4 4 3 2 1 4 4 1 4 4 4 0 2 4 3 3 1 3 4 2 4 4 4 4 1 3 4 0
  [901] 4 1 4 0 1 4 1 4 4 0 3 4 4 1 0 4 4 0 4 4 4 4 4 3 4 3 0 1 4 1 1 0 4 4 1 0
  [937] 0 4 4 3 4 1 1 0 4 1 4 1 0 4 1 2 2 3 3 1 1 2 0 1 4 4 1 2 4 3 4 2 4 3 0 1
  [973] 0 1 2 1 4 1 4 4 4 4 4 3 4 4 3 4 4 3 2 3 4 4 1 3 3 4 4 3 0 4 4 4 4 4 2 4
 [1009] 1 3 0 1 3 4 1 4 2 4 4 3 4 4 1 0 3 4 0 3 4 3 0 0 4 3 4 1 3 2 3 1 1 2 4 1
 [1045] 2 4 3 1 3 3 3 4 4 0 4 0 2 0 3 1 4 1 2 1 4 4 4 4 4 0 1 0 3 0 4 2 1 3 4 4
 [1081] 1 3 4 4 4 1 2 3 4 0 2 4 4 1 1 3 3 1 4 1 1 2 1 3 4 4 3 3 3 4 3 3 3 3 3 3
 [1117] 3 3 3 1 1 0 3 4 4 3 4 4 3 3 4 0 0 4 4 4 4 1 4 3 4 1 0 3 2 3 4 0 3 4 4 3
 [1153] 4 4 1 3 4 3 2 0 2 2 2 4 3 0 3 1 0 0 4 4 0 0 2 3 3 4 0 4 0 0 0 1 1 4 3 4
 [1189] 3 0 3 3 4 1 0 4 1 3 3 0 1 0 4 4 4 4 4 0 4 4 4 4 2 4 4 3 4 1 0 4 4 4 4 3
 [1225] 4 4 4 4 0 4 1 0 4 4 3 0 4 4 3 1 1 1 0 0 3 4 1 3 4 4 0 0 1 1 4 4 4 3 0 4
 [1261] 4 4 3 0 3 4 4 4 4 3 0 3 3 2 4 3 3 4 4 4 4 3 3 1 1 4 4 4 4 3 3 2 3 4 4 3
 [1297] 4 4 1 2 4 4 4 3 1 4 4 3 4 0 0 4 1 4 1 4 4 4 4 3 4 4 1 4 4 3 2 4 0 4 4 4
 [1333] 4 4 2 4 4 3 3 0 4 3 0 4 4 3 4 0 4 4 4 0 4 4 3 4 3 4 4 0 3 3 4 2 4 4 0 2
 [1369] 1 4 4 3 4 3 0 4 0 4 0 4 4 4 4 4 4 4 0 0 3 4 4 3 4 3 4 4 3 0 1 4 4 4 4 3
 [1405] 0 3 4 4 4 4 3 1 0 3 3 4 3 4 0 4 2 0 2 0 3 4 0 1 3 0 3 1 4 0 3 2 4 1 4 4
 [1441] 4 3 2 0 4 3 1 4 3 3 4 4 3 4 4 2 4 4 3 0 4 4 3 4 0 2 1 4 4 4 1 1 4 4 4 4
 [1477] 4 0 1 3 4 1 4 0 2 4 4 0 0 3 3 0 0 1 3 0 0 0 4 4 4 4 0 4 4 4 0 4 4 2 4 0
 [1513] 3 0 2 4 0 4 4 3 0 4 2 2 0 4 3 1 0 2 4 4 3 0 3 3 3 3 4 1 3 4 0 1 4 4 4 1
 [1549] 0 0 0 4 3 4 4 0 0 3 3 3 4 4 4 4 1 3 0 4 4 3 4 4 2 0 3 3 3 4 4 4 3 4 4 4
 [1585] 0 1 1 3 0 1 3 4 4 0 4 1 3 4 4 4 3 4 3 4 0 4 4 4 4 4 4 0 0 4 4 4 3 0 1 0
 [1621] 4 0 1 4 4 1 0 3 4 0 4 3 3 1 4 1 0 3 4 0 4 2 3 0 1 4 4 3 4 3 4 4 3 1 0 4
 [1657] 4 1 1 4 4 4 4 4 2 3 3 4 4 4 4 0 3 0 1 4 4 4 4 4 0 0 2 0 0 4 4 3 3 2 1 0
 [1693] 1 4 0 0 1 2 4 4 4 4 0 4 1 4 4 4 3 4 3 0 3 4 4 4 1 4 1 4 4 4 1 1 4 4 4 4
 [1729] 2 4 3 3 2 4 4 0 0 3 0 0 4 0 4 2 4 3 4 4 4 4 4 4 2 1 0 4 4 4 4 4 0 3 4 0
 [1765] 4 4 4 3 4 4 4 4 0 0 3 4 0 2 4 3 1 4 4 3 3 4 1 4 1 4 1 4 0 1 4 3 4 1 1 0
 [1801] 3 4 4 4 0 4 4 4 1 0 1 0 2 3 1 2 1 2 1 2 4 1 1 4 4 4 4 4 3 4 1 4 4 4 4 4
 [1837] 2 3 4 2 3 4 0 4 4 3 3 3 3 4 0 3 0 3 1 4 4 4 4 2 0 1 4 0 4 4 4 0 0 4 4 0
 [1873] 4 4 4 4 4 4 4 4 4 4 4 0 2 4 2 4 4 3 4 4 3 4 3 1 1 1 0 1 1 3 4 4 0 1 4 4
 [1909] 2 3 3 1 1 3 4 4 3 4 3 4 3 4 1 0 4 4 3 1 3 3 4 3 0 3 4 4 0 0 4 4 4 4 4 2
 [1945] 4 1 3 4 3 0 4 1 4 3 1 2 0 4 4 0 3 4 3 4 4 0 4 3 3 4 1 4 4 0 0 4 0 3 4 4
 [1981] 3 3 4 4 2 3 2 4 4 4 4 4 4 4 4 4 0 0 1 3 4 3 3 3 4 0 1 1 1 4 2 4 1 3 4 4
 [2017] 3 3 4 0 0 2 3 0 3 3 0 2 3 0 0 3 0 1 3 3 4 0 4 3 4 4 3 3 4 4 3 4 0 3 2 2
 [2053] 4 3 4 2 3 4 1 4 4 4 4 3 0 4 4 3 4 4 0 1 4 4 4 4 0 4 3 4 3 2 4 4 4 3 4 0
 [2089] 4 2 3 4 4 0 4 1 4 4 4 0 1 3 4 1 4 4 0 1 4 1 4 4 4 3 4 4 3 3 1 4 2 3 3 3
 [2125] 0 4 4 3 3 2 0 4 3 3 1 2 4 0 2 1 1 4 0 1 0 0 3 3 2 2 1 4 4 4 0 4 3 4 3 3
 [2161] 4 4 0 4 4 4 0 3 1 0 0 4 4 4 4 1 0 4 4 4 4 4 0 3 0 4 4 3 4 1 3 3 3 4 3 3
 [2197] 4 4 0 3 3 2 0 0 3 4 4 3 3 4 3 3 4 3 3 4 4 4 1 4 4 1 4 4 4 4 4 4 4 4 1 3
 [2233] 3 4 2 4 4 4 4 4 4 3 4 3 4 1 4 4 3 2 1 3 4 0 4 4 4 4 4 1 4 4 4 3 3 4 3 3
 [2269] 4 4 3 4 4 4 4 4 4 4 4 4 4 0 3 3 4 0 0 4 2 3 3 4 0 1 3 4 4 4 3 3 4 4 4 4
 [2305] 0 3 4 4 3 0 1 4 4 4 1 3 3 4 4 0 4 4 4 4 4 4 4 2 4 3 3 4 4 4 4 4 4 4 4 2
 [2341] 4 1 4 1 0 3 4 4 4 1 3 0 4 4 0 1 4 1 4 1 3 0 1 1 1 1 3 4 3 4 1 4 1 4 4 4
 [2377] 4 1 4 0 4 3 0 4 4 4 3 0 4 4 4 4 0 0 3 0 1 4 4 4 0 1 0 3 1 0 4 3 4 3 3 1
 [2413] 4 3 4 0 3 3 3 0 2 3 4 0 0 4 3 4 0 0 4 4 4 3 4 4 4 3 4 4 4 4 4 4 4 4 4 4
 [2449] 4 0 3 4 4 4 4 4 4 4 4 4 4 3 4 0 4 4 3 1 4 3 4 3 1 4 3 4 4 1 4 1 4 4 4 1
 [2485] 3 1 3 4 4 4 4 4 3 3 4 4 4 4 3 0 3 1 3 4 2 1 4 3 3 4 1 3 4 4 3 3 3 3 0 1
 [2521] 4 0 2 3 0 2 2 2 1 3 3 3 3 2 0 3 3 3 3 4 3 4 1 4 4 4 4 4 4 4 3 4 2 1 4 0
 [2557] 3 4 0 4 3 3 4 3 4 4 4 3 4 3 4 3 3 3 3 4 3 4 4 4 4 1 1 4 3 3 3 3 3 2 3 1
 [2593] 3 3 4 4 4 4 3 4 3 1 4 4 3 4 3 4 4 0 2 4 3 3 4 3 3 0 3 4 3 3 3 3 3 3 0 0
 [2629] 3 4 0 1 4 4 0 2 0 4 4 4 3 4 0 1 1 4 4 3 3 3 4 3 3 3 4 3 3 3 3 3 3 0 3 4
 [2665] 4 4 4 4 4 4 4 4 2 0 3 2 1 0 0 0 0 3 1 4 3 2 4 2 2 4 2 4 3 1 2 4 4 4 4 3
 [2701] 2 2 3 3 2 3 0 1 0 4 4 3 4 1 4 3 3 4 3 4 3 3 1 4 3 0 1 4 3 3 1 4 4 4 3 4
 [2737] 4 0 2 3 3 3 2 1 3 1 3 3 3 3 1 0 0 3 0 3 0 1 3 0 3 3 2 2 2 3 0 0 0 0 2 0
 [2773] 3 1 1 3 3 3 3 3 0 3 0 0 3 0 3 0 3 0 3 3 1 3 3 3 1 0 3 3 3 3 3 0 0 0 3 4
 [2809] 1 4 4 4 2 4 3 2 3 1 4 0 4 3 3 4 4 4 1 4 4 1 0 0 4 3 3 3 0 0 0 1 0 1 3 0
 [2845] 3 3 3 3 0 1 1 3 4 0 4 4 4 4 1 4 4 4 4 4 3 1 3 3 4 4 2 4 4 2 2 4 3 0 0 4
 [2881] 0 1 4 4 3 3 3 4 4 3 3 0 1 3 4 3 3 4 0 2 1 4 4 3 3 3 4 4 2 4 3 3 3 3 1 4
 [2917] 3 4 4 0 4 4 4 1 0 4 4 3 3 4 4 3 4 3 1 3 3 4 4 4 3 3 4 4 4 3 4 4 4 3 0 1
 [2953] 3 0 3 3 3 3 4 4 3 4 3 3 2 3 3 3 3 3 4 3 4 3 4 4 3 3 3 3 4 4 4 3 4 3 4 2
 [2989] 3 2 3 0 3 3 4 4 4 4 4 3 0 0 4 4 3 0 2 1 0 1 3 4 0 0 4 3 4 4 4 4 4 3 4 3
 [3025] 4 3 3 3 0 2 4 4 3 3 0 0 0 3 3 4 4 3 4 4 3 2 2 4 4 3 3 3 3 3 4 3 3 3 4 3
 [3061] 3 4 3 4 3 3 4 4 0 4 3 3 3 3 3 1 4 0 4 0 0 0 4 3 0 3 1 0 3 4 0 4 3 4 3 0
 [3097] 0 0 4 0 3 4 4 4 4 3 3 3 4 4 3 3 4 4 4 3 3 2 3 4 1 0 1 1 4 4 4 4 4 1 4 1
 [3133] 3 3 0 0 0 3 3 0 0 3 4 3 4 4 4 2 1 4 4 3 4 4 4 3 4 4 4 4 0 3 3 0 2 0 3 3
 [3169] 4 3 3 1 1 4 4 3 4 4 4 3 4 4 0 4 4 3 4 4 4 4 4 4 0 4 4 2 4 0 3 3 4 0 4 4
 [3205] 4 4 0 4 0 4 2 3 3 4 3 0 3 4 3 4 3 4 4 4 0 4 0 4 4 4 3 3 4 4 4 4 0 4 4 3
 [3241] 3 4 0 4 4 4 4 3 4 4 4 4 0 3 3 4 3 4 3 4 3 4 3 4 3 0 3 3 3 3 3 4 3 4 4 4
 [3277] 0 4 4 1 4 0 4 3 3 4 1 4 0 1 4 4 4 0 4 1 1 4 4 3 3 4 4 4 1 3 3 3 4 4 0 4
 [3313] 4 4 3 4 3 3 3 4 4 3 0 4 4 0 4 3 3 4 4 3 4 3 4 3 1 4 4 0 4 4 4 0 4 3 4 4
 [3349] 4 1 1 4 3 3 3 4 0 4 4 1 3 3 3 1 4 4 1 4 4 3 3 3 4 4 3 4 0 4 1 3 4 4 4 0
 [3385] 3 4 3 4 4 1 4 3 4 4 4 4 0 4 4 4 3 0 3 3 4 0 3 4 3 0 4 4 4 3 0 0 2 4 0 3
 [3421] 4 2 4 2 3 4 4 4 4 0 4 2 0 4 1 3 0 4 0 0 0 4 4 0 4 0 4 4 0 3 0 0 1 0 3 4
 [3457] 4 4 4 4 4 3 2 4 2 2 3 0 2 3 4 4 4 4 4 4 4 3 0 4 4 4 3 0 4 4 3 4 3 0 3 4
 [3493] 3 4 4 4 4 4 3 3 0 4 3 0 3 0 4 4 3 4 3 3 3 3 3 4 4 0 0 4 4 4 3 4 4 4 2 4
 [3529] 4 3 4 4 4 0 3 2 4 3 4 4 0 0 3 0 2 2 0 2 3 3 2 3 2 1 3 3 3 3 4 1 4 3 1 3
 [3565] 0 3 1 0 1 0 4 0 4 4 4 0 4 4 0 3 0 0 3 3 3 4 3 3 3 3 3 4 4 4 3 4 3 3 4 4
 [3601] 4 4 1 4 3 0 4 4 4 4 4 3 4 1 0 3 3 4 3 4 4 0 0 4 4 4 4 4 4 4 4 4 0 4 3 0
 [3637] 4 4 4 3 4 0 4 4 3 4 3 4 2 4 4 4 3 4 3 0 3 3 1 0 3 4 0 4 3 3 3 3 4 3 4 3
 [3673] 4 0 4 4 4 4 4 4 4 3 3 3 4 4 3 4 4 4 4 4 1 4 3 3 3 3 0 3 3 0 3 3 4 3 4 3
 [3709] 0 1 4 1 0 4 1 1 4 4 1 3 1 3 1 0 3 3 4 0 3 3 3 3 4 4 3 4 4 4 4 4 4 3 1 4
 [3745] 4 4 3 4 4 4 4 4 2 4 0 0 3 0 1 4 0 0 3 4 4 3 4 4 3 4 3 3 3 4 4 4 1 4 4 4
 [3781] 4 4 3 4 0 0 3 4 4 3 3 1 4 3 3 3 4 4 0 4 2 1 4 4 4 3 4 4 4 4 1 3 4 1 4 1
 [3817] 4 0 4 3 1 3 4 4 4 4 4 1 3 4 4 3 3 4 4 4 0 4 3 3 4 0 4 3 3 3 1 3 4 4 4 3
 [3853] 3 4 4 4 3 0 4 4 2 3 2 3 4 4 3 3 0 0 0 3 3 0 0 1 4 0 4 4 4 4 3 0 1 4 0 4
 [3889] 0 3 2 4 3 3 4 4 3 3 3 0 3 3 3 0 0 3 4 4 3 2 1 2 3 1 3 0 4 1 3 4 3 3 4 3
 [3925] 1 4 4 0 4 3 4 3 3 0 3 2 4 4 3 1 0 4 4 1 4 4 3 2 4 3 4 4 4 3 4 0 4 3 3 3
 [3961] 0 4 4 3 4 3 4 3 3 3 1 4 3 3 3 4 3 3 3 4 3 4 3 4 3 4 4 4 4 4 3 3 4 3 0 3
 [3997] 4 4 4 4 3 3 3 3 4 4 4 3 3 4 2 3 4 2 0 3 4 4 4 4 4 2 4 4 3 1 4 0 4 2 0 0
 [4033] 4 2 3 4 3 3 4 4 3 1 0 4 4 3 4 4 4 3 1 3 2 4 2 4 1 1 0 4 4 3 0 3 4 4 4 3
 [4069] 3 2 3 4 4 4 4 3 4 3 3 0 2 3 3 3 2 0 1 3 2 2 2 1 2 3 4 2 3 0 3 1 2 3 3 4
 [4105] 3 3 3 0 1 1 1 1 3 2 3 2 2 0 4 2 3 3 3 2 3 2 2 2 2 1 1 3 1 3 3 3 3 3 3 1
 [4141] 3 3 1 2 3 3 2 1 2 4 4 4 4 4 4 3 3 4 3 3 3 3 4 4 3 0 3 3 3 3 4 3 3 4 3 3
 [4177] 3 3 3 4 3 3 3 3 4 4 3 3 4 4 3 4 3 3 3 3 4 4 3 4 4 4 3 3 3 4 3 3 3 4 1 3
 [4213] 3 2 3 1 4 3 3 4 3 4 3 3 3 3 4 3 3 3 4 4 3 3 3 4 3 3 4 3 3 3 3 3 4 3 3 3
 [4249] 4 1 3 3 2 3 4 3 3 4 3 4 3 4 4 4 3 3 3 3 3 3 3 4 3 0 4 4 4 3 2 3 4 4 4 4
 [4285] 3 3 0 3 3 4 3 1 4 3 1 3 3 3 3 4 4 4 0 2 4 3 2 3 3 1 4 4 4 4 4 1 3 4 3 3
 [4321] 1 0 2 2 0 3 3 4 3 3 3 3 3 4 4 4 4 4 4 4 4 3 4 3 4 3 3 3 3 4 4 3 3 4 4 3
 [4357] 4 3 4 4 4 3 3 4 4 4 4 4 1 1 0 4 4 3 3 4 3 0 3 4 3 3 0 4 4 4 4 4 3 0 0 1
 [4393] 4 4 4 4 3 3 0 4 4 3 3 4 4 4 4 4 4 0 4 3 0 3 4 4 1 0 0 0 4 0 3 0 0 4 2 3
 [4429] 3 3 3 1 2 2 3 3 2 0 4 3 3 4 4 4 4 4 3 4 4 0 4 4 4 4 4 3 4 4 4 2 4 4 4 4
 [4465] 4 4 3 4 4 2 2 2 4 4 4 1 3 4 3 3 4 2 1 3 4 3 0 3 3 2 2 4 2 1 3 4 4 3 4 4
 [4501] 3 0 3 0 0 2 3 3 2 2 3 0 3 3 2 3 2 3 1 3 3 2 0 3 1 2 1 0 3 1 0 3 3 2 3 4
 [4537] 3 4 4 4 2 2 3 3 3 1 4 4 4 3 4 4 4 4 3 4 4 4 4 4 4 3 3 3 3 4 4 4 4 3 3 3
 [4573] 3 4 3 4 4 4 4 4 4 2 4 1 1 1 0 0 0 1 2 2 3 2 0 1 3 3 3 3 2 3 3 0 2 0 2 3
 [4609] 3 3 1 1 3 3 3 0 3 1 0 3 3 1 1 3 3 3 0 2 3 2 2 1 2 3 3 3 3 3 1 2 3 1 1 2
 [4645] 3 2 3 3 3 0 2 2 3 3 0 0 3 3 2 0 3 1 1 3 3 2 2 3 3 2 3 2 2 2 3 3 3 3 4 3
 [4681] 0 2 3 0 1 0 4 3 4 3 3 3 3 3 3 4 3 3 3 4 4 3 3 3 3 3 3 3 3 3 3 3 3 4 0 3
 [4717] 4 3 3 4 3 3 3 3 4 1 3 3 4 4 2 4 3 4 3 3 3 3 3 4 3 3 3 3 3 3 2 3 3 2 3 3
 [4753] 3 3 4 3 4 4 1 4 4 3 4 3 3 4 3 3 3 3 3 4 3 3 3 1 3 4 4 3 3 3 3 3 2 4 4 4
 [4789] 4 3 4 1 3 3 4 0 3 3 0 4 3 4 4 3 4 4 3 4 4 4 4 1 3 3 4 3 3 4 4 0 0 1 1 4
 [4825] 3 0 4 3 4 4 3 3 0 3 1 3 4 4 4 3 4 0 3 3 3 0 3 4 4 4 3 3 4 3 3 4 4 3 4 4
 [4861] 4 4 4 4 3 3 3 3 4 3 4 4 4 4 3 2 2 2 4 3 3 0 3 0 4 3 3 3 4 4 4 4 4 4 3 2
 [4897] 4 4 4 3 4 4 0 3 4 4 4 4 3 3 4 4 0 4 3 4 4 4 0 4 4 4 2 4 4 4 4 3 4 4 4 4
 [4933] 0 4 4 4 3 4 4 3 4 2 1 4 4 4 4 4 4 4 3 3 4 3 3 3 3 4 4 4 2 3 3 3 4 4 0 3
 [4969] 3 3 4 4 3 3 4 3 3 4 4 4 3 3 3 3 2 3 3 4 3 3 4 4 4 3 3 3 3 3 4 3 3 3 3 4
 [5005] 3 3 3 3 4 3 4 3 3 3 3 4 3 2 4 3 3 3 4 3 4 4 0 3 4 1 1 4 0 0 4 3 4 1 4 1
 [5041] 4 0 4 4 4 4 0 0 1 0 0 0 1 0 0 3 3 4 0 0 0 4 3 1 0 0 3 4 4 4 3 0 3 3 4 4
 [5077] 3 3 4 0 4 4 4 0 4 4 4 3 3 0 0 4 4 1 1 0 4 3 3 4 3 3 0 3 3 4 3 4 3 4 4 3
 [5113] 4 1 1 4 4 4 4 4 4 4 3 3 1 0 4 4 0 0 4 4 2 4 3 4 4 4 4 3 3 0 4 4 4 3 4 4
 [5149] 4 4 3 0 4 4 3 4 4 4 4 3 1 3 3 0 0 0 1 4 4 0 0 0 0 0 0 0 3 3 3 3 3 0 0 0
 [5185] 0 4 0 0 0 0 0 4 3 4 4 4 3 4 4 3 0 4 3 0 1 0 1 0 4 0 3 3 3 4 0 0 1 4 4 1
 [5221] 3 3 3 2 3 3 4 2 4 2 0 0 0 4 4 3 4 4 4 0 4 4 2 4 2 4 0 0 0 0 0 3 4 4 2 4
 [5257] 4 4 4 4 4 2 2 4 0 0 0 4 2 0 4 4 4 0 4 4 4 4 2 4 3 0 0 0 0 0 0 2 0 4 4 4
 [5293] 4 4 2 4 0 0 0 0 4 4 4 4 4 4 4 4 3 4 2 4 3 0 4 0 0 4 4 3 4 3 4 2 3 4 4 4
 [5329] 3 3 3 0 4 4 4 4 4 2 2 2 2 2 4 4 4 0 4 1 1 1 2 2 0 3 4 4 2 2 2 2 4 4 2 3
 [5365] 0 2 2 3 4 4 2 2 4 4 4 0 4 0 0 4 2 2 4 4 4 4 4 2 2 2 3 3 4 3 4 1 4 0 2 2
 [5401] 0 2 4 2 2 2 4 3 4 4 2 0 1 0 3 3 2 4 4 3 4 4 4 4 3 4 4 4 3 3 3 3 0 4 3 4
 [5437] 2 2 2 2 4 2 0 0 0 4 2 4 4 4 4 4 4 2 4 0 0 4 4 4 3 4 4 4 3 4 4 4 3 4 4 3
 [5473] 4 3 4 3 4 2 3 3 3 4 4 4 2 4 0 4 3 3 2 4 3 4 3 4 3 3 4 3 3 3 3 3 3 3 2 4
 [5509] 4 4 3 4 4 2 4 3 3 3 3 3 4 4 3 4 4 4 2 2 4 3 4 4 2 4 4 4 4 4 4 2 1 4 4 4
 [5545] 3 3 3 4 4 2 0 2 2 0 0 4 4 0 0 3 4 2 3 0 4 2 0 3 3 4 0 2 3 2 3 3 4 4 3 4
 [5581] 4 4 0 1 4 4 0 4 4 4 0 1 0 0 1 0 4 0 0 3 0 0 3 0 3 3 4 3 4 4 3 4 4 0 4 4
 [5617] 0 0 1 4 4 4 0 1 1 1 4 4 4 4 4 4 1 3 4 3 0 0 0 4 4 3 3 2 4 4 4 4 1 2 0 4
 [5653] 3 3 4 0 0 4 4 3 4 4 3 4 4 4 4 4 4 3 4 0 0 4 3 1 4 0 3 4 4 0 3 2 4 3 4 3
 [5689] 3 4 4 4 4 4 4 4 3 4 3 3 4 3 2 3 4 4 4 3 4 4 4 4 4 4 4 3 4 3 0 2 0 0 4 1
 [5725] 3 4 4 4 0 4 4 4 4 3 3 4 3 4 4 3 4 4 0 4 4 2 2 4 4 3 4 3 3 3 3 3 4 4 4 3
 [5761] 4 3 4 3 4 0 4 3 3 4 4 4 4 1 3 4 4 4 3 3 4 3 4 3 4 4 3 3 3 4 2 2 3 2 3 3
 [5797] 4 3 3 3 3 4 0 2 4 3 4 4 3 4 3 4 4 4 4 3 4 4 2 4 4 4 4 4 4 4 4 3 3 4 0 2
 [5833] 4 4 4 4 3 4 2 4 3 3 4 3 2 3 3 4 2 2 2 3 4 4 4 4 0 0 4 4 3 3 2 0 3 3 3 3
 [5869] 3 3 3 2 3 3 3 3 0 0 4 0 0 3 3 4 4 4 0 3 4 4 0 4 4 4 4 0 4 0 4 3 0 3 4 0
 [5905] 0 4 4 3 4 4 3 4 3 4 3 4 4 2 4 4 4 3 4 4 4 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2
 [5941] 3 4 3 3 4 3 3 1 3 3 3 2 1 0 0 4 4 4 1 3 4 4 3 1 3 3 4 4 4 0 4 3 4 4 3 3
 [5977] 3 4 3 3 4 3 4 3 3 3 4 4 4 4 4 3 4 0 1 3 4 4 3 3 3 2 3 3 4 3 4 4 3 3 4 3
 [6013] 3 3 3 4 3 4 3 3 4 3 4 3 3 3 4 2 3 3 3 3 3 3 3 3 3 3 3 4 4 3 3 4 3 3 4 4
 [6049] 3 4 3 3 4 3 3 3 4 3 3 3 3 3 3 3 3 3 4 3 2 3 4 3 1 3 3 3 3 3 3 3 4 1 3 3
 [6085] 3 3 4 4 3 3 3 0 0 3 3 0 3 3 4 3 3 3 3 4 3 4 0 4 3 3 3 4 4 1 4 4 3 0 1 3
 [6121] 4 4 3 4 3 4 3 3 3 3 4 3 3 3 4 3 0 4 4 3 3 4 4 4 3 4 3 3 3 3 3 3 3 3 3 4
 [6157] 4 4 3 3 3 3 3 3 4 4 2 4 3 4 4 2 3 3 4 4 3 3 3 3 4 3 4 3 4 3 3 4 4 3 3 0
 [6193] 3 3 1 3 3 1 3 3 1 3 1 0 1 1 3 3 0 3 1 1 3 1 3 3 4 4 3 3 2 0 3 4 3 2 3 3
 [6229] 3 3 4 4 3 4 4 4 2 3 4 2 2 3 3 2 3 4 3 2 3 4 2 2 4 3 3 2 0 0 4 4 3 4 4 3
 [6265] 4 4 0 2 4 4 3 3 2 3 3 4 0 3 4 3 3 4 1 0 4 4 0 3 0 4 0 0 0 0 4 0 4 0 3 3
 [6301] 3 3 3 3 1 0 3 3 3 3 0 0 4 4 3 4 0 3 3 0 4 3 3 4 1 3 3 3 4 0 2 0 0 1 3 3
 [6337] 0 3 2 1 2 3 3 0 0 3 1 0 0 0 3 3 2 3 0 2 0 4 3 0 2 0 3 3 0 4 3 0 2 0 3 2
 [6373] 4 4 3 3 4 0 0 0 0 0 1 3 3 1 2 0 0 0 0 0 3 1 1 4 0 1 1 3 1 1 3 0 1 1 0 0
 [6409] 1 0 4 3 1 4 3 4 1 4 4 1 3 4 0 3 3 3 0 3 3 0 2 3 4 3 1 3 3 4 2 0 3 0 3 3
 [6445] 0 0 0 2 3 4 3 4 3 1 0 0 4 3 3 4 3 3 3 3 4 4 3 0 0 3 0 4 3 1 4 0 1 2 3 4
 [6481] 3 0 3 4 3 3 4 4 4 4 3 0 3 4 4 3 4 3 3 4 3 4 3 3 2 0 4 4 4 3 1 2 4 0 4 4
 [6517] 3 3 3 4 2 2 3 2 3 2 3 3 3 3 2 1 3 0 0 0 3 4 0 4 3 3 0 3 4 4 2 3 1 3 3 2
 [6553] 0 3 1 4 4 3 0 3 1 1 0 1 3 4 3 4 3 0 3 2 4 4 2 3 3 2 3 4 4 4 1 2 3 3 4 3
 [6589] 3 3 2 2 3 4 0 2 3 2 1 4 4 3 2 4 4 0 4 2 3 4 4 3 3 1 2 4 4 3 3 4 4 2 2 4
 [6625] 2 3 2 3 4 4 0 3 4 0 1 4 4 2 2 4 4 0 0 0 0 4 3 3 4 3 2 3 4 0 0 3 3 3 3 3
 [6661] 3 4 4 3 3 3 4 3 3 4 3 3 4 2 4 2 4 4 2 4 3 4 4 0 4 3 4 3 4 3 3 3 3 3 0 3
 [6697] 4 3 3 3 4 0 3 3 2 2 4 4 4 1 4 4 4 4 4 3 4 3 4 4 4 3 4 4 4 3 2 3 4 4 4 2
 [6733] 3 3 4 3 3 2 4 4 4 0 3 4 3 0 4 4 0 3 3 3 4 1 3 1 3 1 0 3 3 1 3 1 4 4 1 3
 [6769] 1 4 3 3 0 1 2 0 0 1 1 1 0 3 0 3 2 4 3 1 3 2 2 3 4 3 4 1 3 2 3 3 3 4 4 3
 [6805] 3 3 3 3 3 3 3 3 3 3 3 3 4 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 1 4 4 3
 [6841] 3 3 4 3 4 4 0 0 3 4 4 0 3 3 4 3 0 3 3 1 1 2 2 4 2 1 1 3 3 2 1 4 4 3 3 4
 [6877] 3 4 1 3 4 4 0 3 3 2 4 4 4 4 3 3 2 1 1 3 1 4 3 2 4 3 4 3 3 1 3 0 3 3 4 4
 [6913] 3 4 4 2 4 2 4 3 2 3 3 3 3 3 3 3 3 4 4 4 3 4 4 3 4 4 3 3 3 4 4 4 4 3 4 3
 [6949] 4 3 1 3 4 0 0 4 4 0 4 4 2 1 1 0 3 1 1 4 4 1 3 1 2 3 3 3 3 4 3 3 3 3 3 1
 [6985] 3 3 3 2 3 3 3 3 3 3 3 3 3 1 1 1 3 2 2 3 3 4 0 1 1 3 2 2 2 0 0 3 0 0 0 0
 [7021] 3 0 3 0 3 1 1 0 3 3 2 1 3 3 1 3 3 3 1 0 3 1 1 1 1 3 1 1 1 1 0 2 1 1 0 0
 [7057] 0 0 0 1 0 0 0 1 1 3 3 0 0 0 0 3 0 0 3 0 0 0 0 3 2 0 3 1 1 3 1 1 3 3 1 1
 [7093] 3 3 3 3 2 3 3 3 1 3 3 0 0 1 0 1 0 1 0 0 0 3 1 1 1 1 1 0 2 3 3 3 1 3 3 3
 [7129] 3 0 3 3 3 0 0 0 0 0 0 1 1 1 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 1 1 1 1 0 1 0
 [7165] 3 0 1 0 3 0 1 1 1 0 1 0 0 0 0 1 3 0 0 1 0 0 0 1 1 0 0 0 1 1 3 0 3 0 0 1
 [7201] 0 1 1 0 0 3 0 1 0 0 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 0 1 1 0 0 1 0 1 1 0
 [7237] 0 0 0 0 0 1 0 0 3 1 1 3 3 0 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 3 0 1 0 3 0
 [7273] 0 3 0 0 1 0 0 0 3 3 3 0 3 0 1 1 0 0 0 0 1 3 3 0 1 1 1 0 1 0 0 0 0 0 1 0
 [7309] 2 0 0 1 0 0 1 1 1 0 0 0 0 0 0 0 1 0 2 3 1 0 0 1 0 0 0 0 0 0 1 0 0 1 0 3
 [7345] 2 0 0 0 0 0 3 1 0 0 1 0 0 0 0 0 1 1 0 0 0 1 3 0 1 0 1 0 0 3 1 1 1 3 0 0
 [7381] 0 1 3 1 0 0 1 1 3 3 3 0 0 0 0 3 3 0 1 0 3 0 0 0 0 0 0 1 0 0 1 1 0 0 3 3
 [7417] 0 1 3 0 0 0 3 1 1 0 0 3 3 1 0 0 0 0 0 3 1 0 0 3 0 0 0 3 0 1 1 0 1 0 1 1
 [7453] 0 0 1 3 3 3 3 1 1 0 0 3 3 3 3 3 2 1 3 3 3 0 2 3 3 3 1 1 0 3 1 1 3 3 1 3
 [7489] 3 2 2 3 0 3 0 1 3 1 1 3 2 3 3 2 1 0 0 0 3 1 0 0 3 4 0 4 0 0 3 3 0 3 2 3
 [7525] 1 1 3 1 1 0 1 1 3 0 3 1 3 1 3 0 3 3 1 3 1 2 3 3 0 0 2 2 3 1 1 1 1 3 2 3
 [7561] 2 3 3 0 0 3 2 2 1 0 3 0 3 3 2 0 2 0 1 1 3 3 3 2 3 3 3 3 0 1 1 3 1 2 1 1
 [7597] 3 3 3 1 1 3 0 3 2 0 3 3 1 3 0 3 3 2 3 2 3 3 0 3 0 2 2 3 3 3 3 2 2 1 3 2
 [7633] 3 0 1 3 1 2 2 3 1 2 2 3 3 3 1 0 1 3 2 3 3 2 1 0 1 1 1 3 1 2 1 3 3 2 3 3
 [7669] 3 2 2 3 3 1 3 3 2 3 3 3 1 3 3 2 2 3 0 3 3 3 1 3 0 3 1 3 0 3 3 3 2 0 3 0
 [7705] 0 0 2 3 3 3 1 3 2 3 3 0 3 1 2 2 1 3 2 3 3 0 3 0 3 1 1 3 3 0 1 2 2 1 3 2
 [7741] 1 3 3 3 0 3 3 1 0 0 1 0 0 0 0 0 1 3 1 1 1 0 0 0 0 1 3 0 0 3 0 1 0 0 0 1
 [7777] 0 0 1 0 0 0 0 3 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 1 0 1 3 0 1 3 0
 [7813] 0 0 1 1 0 0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 0 1 0 0 0 0 1 3 3 3 0 0 0 1 0 1
 [7849] 0 0 0 0 1 1 1 3 1 0 0 0 1 0 0 0 0 0 0 1 3 0 0 0 1 1 1 3 1 1 0 0 0 0 0 1
 [7885] 0 0 0 0 1 1 1 1 3 0 1 3 0 3 1 1 1 0 1 1 1 3 0 1 0 0 1 1 0 3 0 1 1 1 1 1
 [7921] 0 0 0 3 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 1 3 0 0 0 1 1
 [7957] 0 3 3 1 1 0 0 1 3 1 0 0 1 0 3 3 0 3 0 0 3 1 0 0 0 0 0 3 1 3 0 0 1 3 3 0
 [7993] 0 1 0 0 1 0 0 0 0 1 2 1 3 0 0 0 3 3 0 1 0 3 0 0 3 0 1 1 0 1 0 0 1 1 0 3
 [8029] 1 0 0 0 1 3 1 0 1 0 0 1 0 1 1 3 1 0 0 0 1 0 1 0 3 1 0 0 1 0 0 0 3 0 0 1
 [8065] 1 0 1 0 3 0 0 1 1 0 0 0 1 3 1 0 1 0 3 1 0 1 0 0 1 0 1 0 1 0 1 0 0 0 0 0
 [8101] 1 0 3 3 3 0 1 0 3 1 1 0 0 1 3 0 1 0 2 0 3 0 0 3 0 1 0 3 1 0 0 0 1 1 0 1
 [8137] 1 1 0 0 1 1 0 0 0 0 0 0 1 2 0 3 1 1 0 1 0 0 3 1 3 3 1 1 1 0 0 0 3 0 3 0
 [8173] 3 0 1 1 3 3 0 0 3 0 0 0 0 0 3 0 0 0 1 0 0 3 0 0 1 2 0 0 0 0 0 1 0 0 1 3
 [8209] 0 0 0 0 1 1 0 0 3 0 0 1 0 1 3 0 0 1 0 0 1 1 0 1 1 0 0 3 1 0 1 0 0 3 3 3
 [8245] 1 3 1 0 1 1 3 3 0 1 3 0 0 3 1 0 3 0 0 0 0 3 0 1 0 0 0 3 0 1 0 3 3 1 0 2
 [8281] 0 0 3 0 0 3 2 3 3 1 1 1 3 1 3 0 1 3 0 0 1 0 0 0 2 1 1 0 0 0 3 0 3 3 0 3
 [8317] 3 3 0 3 0 0 0 1 0 0 0 3 3 0 1 2 0 3 3 2 0 3 3 3 0 3 2 3 3 3 3 0 3 3 1 3
 [8353] 3 1 0 3 3 1 1 0 1 3 0 0 1 0 3 0 0 3 1 3 3 1 2 0 3 3 3 0 0 1 1 0 3 3 2 3
 [8389] 1 3 3 0 2 3 0 3 3 1 3 3 3 3 3 3 3 3 0 0 1 3 0 2 3 3 1 2 0 3 0 3 1 0 1 0
 [8425] 1 0 1 3 1 3 3 0 3 3 3 2 1 3 1 3 0 1 1 3 3 3 1 1 1 2 1 2 1 3 0 1 2 0 1 3
 [8461] 1 3 1 3 3 3 3 2 2 3 3 3 3 2 1 3 3 0 0 3 3 1 3 2 1 3 1 3 0 1 1 3 3 1 3 3
 [8497] 1 3 1 2 0 1 3 2 3 1 3 3 0 0 2 3 2 1 0 1 1 2 3 1 3 3 3 0 1 3 0 3 3 1 3 3
 [8533] 3 2 0 3 1 3 2 0 2 2 2 3 3 2 0 3 2 2 1 3 3 0 3 1 3 2 2 3 1 3 1 2 2 3 3 2
 [8569] 1 1 2 3 0 2 3 3 2 3 2 2 3 3 3 3 2 0 1 3 1 2 3 3 2 0 3 3 1 2 3 3 3 3 3 3
 [8605] 3 1 3 2 2 3 0 3 3 3 0 1 1 3 2 3 0 3 0 3 2 3 3 3 3 3 2 1 1 3 1 4 3 0 3 0
 [8641] 4 4 3 3 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 1 1 0 2 0 0 0 0 0 1 1 1 3 0
 [8677] 0 1 0 1 1 1 1 0 0 0 0 2 1 0 0 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 1 0 1 0 0 1
 [8713] 1 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 0 0 0 3 1 1 1 0 0 1 0 3 1 1 1 0 0 1 1 0
 [8749] 1 1 0 0 0 0 0 1 1 1 3 1 0 1 0 0 2 1 0 1 0 1 3 1 0 3 1 1 1 0 0 1 0 0 0 1
 [8785] 0 0 1 0 3 1 1 0 3 3 1 1 1 1 0 0 1 1 1 0 1 1 0 0 1 0 1 1 1 0 0 1 0 1 3 0
 [8821] 0 0 0 0 0 0 1 0 1 3 0 1 0 0 1 1 0 3 1 2 1 1 2 1 1 1 1 0 0 3 3 3 1 1 0 0
 [8857] 1 3 1 1 0 1 0 1 0 0 1 3 1 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 3 3 1 0 1 3 0 0
 [8893] 0 3 0 0 0 0 0 0 1 1 0 3 3 0 3 0 1 3 0 1 1 0 0 0 1 0 3 0 0 0 3 1 0 1 1 0
 [8929] 0 0 1 0 1 3 0 3 0 1 0 1 0 0 0 1 0 3 1 0 0 0 0 0 1 3 2 0 0 1 0 1 0 1 0 0
 [8965] 0 1 1 1 0 2 3 0 1 3 0 1 0 0 0 0 3 1 0 0 1 3 1 1 0 0 3 1 3 0 3 0 0 0 1 2

In [44]:
lgbregmin

    [1] 2.4162667 2.4605042 3.2152334 1.3042642 1.7996480 1.5336135 1.8292733
    [8] 1.8955540 1.8232382 2.1242919 1.8541989 1.3535123 2.0869732 1.9481133
   [15] 2.7368334 1.9542744 2.5212819 2.2616556 1.5393794 1.8791604 1.6278143
   [22] 1.9633285 1.7394255 3.4481567 3.4276742 3.8710147 3.3992814 2.7402018
   [29] 3.2327751 3.0967395 2.1389004 3.1067284 3.2502589 2.8050457 2.7978936
   [36] 3.0729307 2.2622333 3.3016784 2.8224461 2.6140818 1.3373944 1.3172042
   [43] 1.4198436 2.3304740 2.0126956 1.9908029 1.9430552 1.7536393 2.2965934
   [50] 1.4498059 0.9341517 3.1245654 1.5630590 1.5473349 3.5718051 1.5080536
   [57] 2.5823813 0.7685219 1.3321480 2.3461712 1.8308320 1.7653867 1.8659418
   [64] 1.3075095 0.8799400 1.3480145 0.7968576 1.4883606 1.5411848 1.5610258
   [71] 2.1496536 0.7038356 1.3992019 1.3789446 1.3018129 1.8023290 1.9999078
   [78] 0.9426251 1.5371225 1.5563162 0.8125816 1.3744360 1.0073777 1.4855452
   [85] 1.4833113 1.7683391 1.3871345 1.1875033 2.0828489 1.7824946 1.9631064
   [92] 3.2154588 3.7828526 2.6039288 2.4563091 1.7386971 2.1870739 1.8910747
   [99] 2.0673534 1.8264036 2.7254626 2.4237855 1.7500231 1.5446098 3.0523361
  [106] 1.4143668 2.0556834 1.6886095 1.7128345 2.2825687 1.4686441 2.2208121
  [113] 2.2214702 3.9076745 2.4869317 3.1091846 3.1295576 3.4175094 3.7869050
  [120] 3.6542312 3.6858009 3.5829072 3.3346618 2.6157281 2.4316785 3.0260550
  [127] 3.2679366 2.8888663 2.9684904 3.3862374 1.7217022 1.3069685 1.7576847
  [134] 1.8703263 1.3194096 1.5414046 1.4325492 3.2233642 3.2641308 3.2500663
  [141] 1.6075003 3.2345651 1.7657195 3.0299092 3.7409628 2.0936779 1.4708057
  [148] 3.6567164 3.4613281 3.8676832 3.6189715 3.2596960 1.1753437 1.1753437
  [155] 1.5134600 3.1395220 3.3641504 3.5179459 3.5401392 1.6030586 1.6462588
  [162] 1.6124222 2.6965384 2.7946263 1.5933348 3.5575716 0.7744563 3.1800017
  [169] 3.4288681 1.4641698 2.7105783 3.3919694 1.6721795 2.9674907 3.0649326
  [176] 3.2941832 3.1192448 3.2946079 2.8680745 3.4840896 3.1965272 1.9640176
  [183] 3.2369120 3.1099365 2.5487376 3.7708644 3.4200090 3.6913049 2.9649117
  [190] 2.8999182 1.4178494 1.4197558 3.5779439 1.5563269 1.4860405 3.4326821
  [197] 3.4235239 3.3419103 2.7117940 3.0928953 2.0028298 3.1319957 2.1588623
  [204] 1.7640986 1.3684838 3.3563842 1.2676024 3.1888126 3.0912898 3.6364112
  [211] 3.7511535 3.0861529 2.6326416 3.0540809 1.1889128 1.2385994 1.3514146
  [218] 0.9003609 1.4182468 1.1713724 1.0331287 1.2316232 1.6513673 2.5936608
  [225] 2.5819551 1.5749118 1.6513673 1.5175458 1.2093749 1.7791229 1.5175458
  [232] 2.3117770 2.9029277 3.4019048 2.3661023 1.7756538 3.3432192 1.4710009
  [239] 1.5438527 1.5608694 1.6057404 1.8577413 2.8122171 1.7753454 3.2387922
  [246] 1.7372624 1.3778286 1.6517732 1.9094608 3.2375720 3.1716002 1.4621917
  [253] 1.9471466 1.9561425 1.3252670 1.2675116 1.6677875 1.4005225 1.3022752
  [260] 3.1023666 1.6634994 1.7787046 1.6878160 1.2118409 2.1765393 2.0665254
  [267] 2.7718173 2.7742166 2.4761675 2.5185175 1.5872831 2.7090416 3.0200213
  [274] 2.5631836 2.3018550 2.7464819 2.2711385 1.2565058 1.8420684 1.7317441
  [281] 2.2196710 1.7720683 0.9957958 1.6526117 2.5406377 1.6577020 1.5061925
  [288] 2.9499447 1.4339449 1.9973946 2.0301112 1.9814312 1.9232372 1.8783249
  [295] 1.0112795 1.6616308 1.0632933 1.4462226 2.0070447 2.3684228 2.1437762
  [302] 1.5845739 1.6205557 3.2578955 2.7448271 2.4704523 3.4102753 3.4964332
  [309] 3.3029620 2.2243318 1.9568455 2.0572579 1.5365967 1.1949015 1.4362051
  [316] 3.4296034 1.5049041 1.4771182 2.4970227 1.8772296 3.0064348 2.4268628
  [323] 1.4209849 1.9370829 1.9612369 1.9164010 1.4882414 3.1413203 3.4002007
  [330] 1.7342495 1.6585279 2.8017221 3.0211325 2.8370836 3.1979117 2.9711017
  [337] 1.6134444 2.2594198 2.8840058 2.4275019 1.3723743 3.2993221 3.1152401
  [344] 2.7587260 1.2203978 1.4875976 2.8274441 1.5179481 1.6811473 2.1533442
  [351] 3.2883788 3.0701452 3.5552745 1.5763014 2.6505733 2.9039240 2.3025766
  [358] 2.6165484 2.5393388 2.2105392 2.9916881 2.3859289 1.5334670 2.0049400
  [365] 1.4219651 1.2020922 3.1326433 2.4706651 3.3395161 2.1720404 2.1895233
  [372] 2.9905640 1.4770423 3.4900057 2.7877654 1.7289595 1.8421577 2.7425738
  [379] 1.8542089 2.0525332 1.8470660 1.7189297 2.2176013 0.9318191 2.0904161
  [386] 1.4887321 1.8582038 1.4675738 1.7427465 2.2701810 2.0794773 1.6241697
  [393] 2.3088565 1.7871573 2.5311251 1.9346766 3.3696135 2.0803665 1.0018593
  [400] 2.5208363 2.1180550 1.6743044 2.8116781 2.4833681 1.6492021 1.9256114
  [407] 1.6071000 1.9075087 2.3837700 1.3836274 1.4907607 1.6673297 1.8213120
  [414] 1.3916086 2.5395262 3.3366081 1.9008829 2.8924570 3.3319940 1.6498058
  [421] 3.1487279 3.3607710 2.1948496 1.3031815 3.1887289 2.4168850 2.4061113
  [428] 3.2127603 3.3611556 3.2189413 2.2594680 3.6030804 2.6420864 0.8450455
  [435] 1.4657672 2.0424144 1.7420094 3.4427921 1.6545448 1.7440832 1.1358010
  [442] 2.1769375 3.5043855 2.5941725 2.8231773 3.5824898 1.6728773 2.3223711
  [449] 2.2151918 3.0694953 2.8876580 2.9178018 2.7485255 2.8566227 3.2306095
  [456] 3.5529845 2.6287849 2.4855277 1.3055585 2.8230529 2.7257882 2.1180549
  [463] 2.5150268 1.9601759 3.1064853 3.2033861 3.1900894 2.2599034 2.0020707
  [470] 1.8501326 2.3273612 2.1144095 2.1179131 3.2856260 2.1169098 1.3808026
  [477] 1.4600426 1.7362637 1.3226665 1.7717342 2.3253999 2.3110128 2.3701883
  [484] 2.3854602 2.3182323 2.4961084 2.1271275 1.7921453 2.5168927 2.1272456
  [491] 2.8241111 2.2673227 2.1921997 2.9165653 2.9158127 2.1399295 2.2857191
  [498] 1.9375815 2.0740676 1.7247267 2.1968584 1.7981436 2.0496249 2.6409733
  [505] 2.5148739 2.6010463 2.5968622 2.8924252 2.2982753 2.4453894 2.9820515
  [512] 2.5958095 2.5910633 2.4232425 2.7654157 1.3884611 1.8012735 3.5030463
  [519] 3.3853374 3.1762479 3.3811727 3.2019567 3.0124555 3.0538753 2.0451469
  [526] 3.1677461 2.0849003 1.4924577 2.3896386 2.6505187 2.8450271 1.6287853
  [533] 2.3607163 1.9267867 2.6281246 2.7292240 2.1945282 1.8137880 1.7865776
  [540] 1.9046189 2.7862410 2.4112331 2.3545446 1.4362774 2.3200341 2.6122596
  [547] 2.9608301 2.6901245 2.1049131 1.8164122 2.4117307 1.5418778 2.9763778
  [554] 2.5081232 1.2798252 1.7292034 2.3622396 2.2260092 1.8367563 2.3257388
  [561] 2.5504127 2.0264607 2.6546788 1.8389092 2.0608942 1.9707577 2.1156492
  [568] 3.1320150 1.8717887 2.0291773 0.9738406 1.8293181 2.3494112 1.6328957
  [575] 1.7391805 1.0633754 1.8556103 1.9439710 1.6219405 2.4334775 1.7564508
  [582] 2.7712509 2.2384915 2.8914248 2.5272626 1.7246160 1.4854852 2.8747825
  [589] 2.3547700 2.3098527 1.4942009 3.3685374 3.3286818 1.9686750 3.0750381
  [596] 2.7701066 2.3455783 2.8772402 3.4392570 3.4302347 3.7307793 3.0967070
  [603] 2.7408331 2.4262831 2.6689903 1.8517012 3.5117470 2.2915296 3.2820446
  [610] 2.3024304 1.7072455 2.4237703 2.2694037 3.2006688 1.8646038 2.0656004
  [617] 3.0026384 3.6843596 0.9834435 3.1903228 1.9499393 1.8760163 1.8768191
  [624] 3.3428733 3.2674804 3.0912463 2.9612088 3.0389393 3.4726339 2.5878883
  [631] 3.0690093 3.1524399 3.3584485 1.9469196 3.6063539 3.5474620 2.8677852
  [638] 3.0398765 2.7484688 3.2551425 3.6549980 2.2115447 1.4380531 1.4436929
  [645] 2.2784003 1.9918835 3.4066683 2.5624344 2.1774174 3.4868320 2.9216483
  [652] 3.0902272 2.9938373 2.8758873 2.7108378 3.0710219 2.0814706 2.7203964
  [659] 3.0340810 1.6540847 2.0559433 2.6089797 3.3655646 3.3164206 3.0725554
  [666] 2.7069043 2.5500112 2.9727586 2.5627858 1.9595774 1.9249723 2.7674576
  [673] 2.4309432 1.4868099 2.0126050 2.5810692 2.3937964 2.3589445 2.1464934
  [680] 2.3430473 2.6644345 2.5547813 2.0772461 2.2483909 1.8393092 1.0572397
  [687] 1.4688750 3.0187097 3.8194902 1.0795930 1.5628417 1.4057280 2.4391810
  [694] 2.4783153 1.5648772 1.9049829 2.0085957 1.5861093 1.8038593 2.4758119
  [701] 2.4613663 3.4501315 3.2670314 2.6739245 2.9754410 2.2816128 2.5119595
  [708] 1.5967631 1.8283640 2.6368855 1.8839640 1.8293308 2.0217798 2.4231491
  [715] 1.4504837 1.7774344 1.9778580 2.0082615 3.3174654 3.4042621 2.1468566
  [722] 2.0115397 2.3791111 2.4472001 2.4711162 2.0211544 2.3347844 1.5780816
  [729] 2.1876481 3.2608754 1.9172493 1.9973360 2.0538194 2.6083505 3.0252484
  [736] 1.8867507 1.1248829 1.2222969 1.9960172 1.6529675 3.0009463 2.2488824
  [743] 1.3803011 2.3921148 1.5476359 2.3266150 2.9554332 2.5966020 2.5800944
  [750] 2.3478810 1.5849904 2.9580141 1.9144377 2.8469627 1.4620587 2.0346596
  [757] 1.8813479 2.7776012 2.2556749 2.1495872 2.1075879 2.6116135 2.7762730
  [764] 2.6552307 1.4380827 1.9738533 1.9683540 2.6159443 2.7289565 1.9521173
  [771] 2.7219229 2.0927243 1.6613365 1.5204083 2.0504461 3.1335962 1.8917792
  [778] 2.5706653 1.9191925 2.2185915 1.7827814 1.1817114 2.2715126 2.4485899
  [785] 2.6357086 2.0110808 2.6485703 2.8689790 2.0523146 1.3269665 2.4898526
  [792] 3.3522739 1.8918351 1.9863126 2.5988763 2.2006448 2.1630751 2.1682097
  [799] 2.1550007 1.7320437 1.6004130 2.4935797 2.4283172 2.2606087 2.2455481
  [806] 2.7265170 1.6398876 1.3742416 1.2233056 2.5590505 1.5970971 3.5241112
  [813] 3.5909573 2.4176319 1.8171393 1.6836948 2.1227535 3.2819761 2.5704604
  [820] 2.4425731 1.9144025 3.0233502 2.7169832 1.5520361 2.9413644 2.7212149
  [827] 2.0169872 3.4157280 1.5524676 3.2943806 1.7179232 1.7741632 1.8964715
  [834] 2.1962513 2.9132765 3.3665842 3.3340828 2.5375667 3.2154368 3.1235436
  [841] 2.8834348 2.4224673 1.3095846 3.1334445 1.6669169 3.0101601 3.0141662
  [848] 3.9129716 2.8706742 3.6294557 2.9967829 3.5221765 1.5459001 3.4809367
  [855] 1.9659702 2.2324774 1.9970906 3.2139704 2.2962331 2.4165514 1.7906219
  [862] 3.3623236 2.0393562 1.4186222 2.6138243 3.0151291 1.6420284 2.3336484
  [869] 2.5932239 1.8807372 1.5250955 2.4690387 2.2041420 2.5035150 1.3974661
  [876] 2.5433348 2.3813846 2.8999050 3.0863367 1.7247368 2.5337113 2.6027348
  [883] 3.6255923 1.8739171 2.3923438 2.7061548 1.6926294 2.3221863 2.5171372
  [890] 2.0005429 2.5029720 1.7149230 2.9048273 2.5080856 2.7817814 2.4732445
  [897] 1.5165375 2.6049603 2.6225406 2.0100830 2.5764913 2.1656987 3.0005371
  [904] 1.8399521 2.5794818 2.6197955 2.1832494 3.6344248 2.9011835 0.7069507
  [911] 2.2766755 3.1541402 2.6525033 1.8126862 1.6089363 2.7297531 2.7983979
  [918] 1.8098702 2.4610535 1.9958782 3.1766277 3.0236227 2.7923204 2.1136911
  [925] 2.2846156 1.9085358 1.7821875 2.0570824 3.1572664 1.8403666 1.7415727
  [932] 1.5552803 2.6331503 2.3804990 2.0899149 1.6682805 1.8583431 3.1607256
  [939] 3.2677652 2.5933196 2.6640808 1.9628624 1.5806163 1.5996282 2.9040844
  [946] 1.6536815 3.0650555 2.0457670 1.3624481 2.3886104 1.9967038 2.4653834
  [953] 1.7015268 1.6825234 1.8312546 1.9968871 2.0429978 2.0631272 1.5351498
  [960] 2.0873236 2.1290051 2.3992560 1.6949878 2.2451032 2.7540494 1.8461421
  [967] 3.0369809 2.0077458 2.6176694 1.8962203 1.9690495 1.3550654 1.6458111
  [974] 2.0111918 2.1310702 2.1478938 2.5844776 2.0404232 2.7068437 2.6245382
  [981] 2.8649748 3.0238350 3.1957511 3.1510702 3.1560256 3.0015858 3.0323427
  [988] 3.3134324 3.0245315 2.3581844 3.0269561 3.0116181 2.8015447 1.9220221
  [995] 1.9472511 1.8620849 1.7564189 2.7892182 2.9369823 1.3804253 1.8778422
 [1002] 3.1937540 2.6597191 2.7483172 2.6132661 2.8127325 1.9975273 2.9848267
 [1009] 1.8518589 2.5195536 1.7320668 1.7973680 2.3309968 2.4741357 2.2795132
 [1016] 3.1868893 2.1822166 2.9718636 2.5266576 1.8036135 2.4218444 2.1466591
 [1023] 1.9839376 1.4633362 1.9038979 1.7335546 1.5992122 3.4695076 2.4872829
 [1030] 2.6853158 1.7004053 1.6803055 3.0605941 1.9750476 2.3117371 1.7807268
 [1037] 2.4283997 1.7261613 1.4446784 1.8350261 1.9772240 1.8967483 2.8565378
 [1044] 2.7759520 1.5494233 2.6156567 2.7005783 2.0424466 1.5308150 1.8084705
 [1051] 1.7760694 2.9902077 2.4348882 1.9471686 2.9115728 1.6043715 1.8953316
 [1058] 1.8322035 1.8936138 2.5997698 2.3618215 2.2708810 1.5149494 1.1122311
 [1065] 2.3510970 3.0718011 3.3244077 2.9430555 2.3576007 1.4138611 1.7601848
 [1072] 2.3252957 2.2977909 1.9458529 2.5025288 2.1610802 1.9359404 1.8935751
 [1079] 2.5213604 3.6043852 1.6680433 3.1841616 2.8633921 2.0705035 2.9711934
 [1086] 2.0746694 1.8372076 3.1093259 2.4907480 2.3208485 2.1166360 3.1864640
 [1093] 2.5204349 1.6273134 1.8109217 2.0966288 2.2646110 1.1661845 2.1542572
 [1100] 2.2701629 1.7080924 2.3388094 2.4616306 2.1595490 3.3013104 2.7214920
 [1107] 2.2266083 2.8429335 2.8635645 2.1002792 2.4299547 2.0095013 2.6461763
 [1114] 2.1891979 2.3399644 2.1275525 1.6760027 2.3409561 1.7171497 2.0220894
 [1121] 2.4158222 2.1269570 2.1809881 2.3485748 2.0763931 2.0458519 2.3082102
 [1128] 2.1351704 1.4660560 1.6742741 3.0824575 2.2865795 1.8090284 3.2335784
 [1135] 2.6029520 3.0514604 3.2600759 1.7521493 3.2270281 3.1018270 3.1651676
 [1142] 1.8917105 1.6777600 2.0872476 2.5905750 1.9150529 2.2546489 1.9419911
 [1149] 2.1022431 2.6297932 2.4185175 1.8554854 2.7640693 2.8726699 2.5483780
 [1156] 2.2919542 2.3502504 2.4245960 2.4200192 1.9964225 1.9910782 1.9534559
 [1163] 1.6003334 3.0495593 2.3724804 1.8846449 2.1624650 1.8903371 1.4801734
 [1170] 1.5281807 2.9305358 2.7573593 2.3631556 2.0852519 2.1082738 2.8302321
 [1177] 2.4895366 2.3352006 2.1788033 2.5199948 2.0045052 1.9089187 1.8661387
 [1184] 2.0816136 2.5777550 2.6525606 2.1990990 2.9431548 2.7639750 2.1955563
 [1191] 2.9630890 2.9620102 2.6310287 1.7512588 1.8009328 1.9773006 1.9730342
 [1198] 2.3255782 1.7569644 1.9115846 1.7216419 2.5581652 3.3725703 2.3942677
 [1205] 2.2181669 2.6265248 2.5964899 1.8400868 2.5644379 2.8554824 2.2453606
 [1212] 3.2655806 1.7142514 2.1441211 2.6945451 1.8541597 3.0641844 1.5963090
 [1219] 1.8572165 3.0449475 3.0486080 2.6609087 2.5268013 2.2183818 2.4637941
 [1226] 2.9585648 2.9477076 2.1434881 1.8373600 2.1282819 1.9845842 1.3335328
 [1233] 3.0411065 3.4696890 2.2600515 2.1101823 2.6572871 2.2233341 2.3778133
 [1240] 1.5352120 1.6144913 1.5325335 1.8229470 2.3040316 1.6614692 3.8673919
 [1247] 2.1809537 2.1500210 3.5766462 3.0389634 1.3435577 1.3383678 1.5381372
 [1254] 1.5626543 3.5257414 3.3978325 2.5976239 0.7297548 1.1494395 2.2869455
 [1261] 2.9192969 3.5210035 2.5382662 1.7275028 1.8354782 2.6288697 3.0388735
 [1268] 2.4984389 2.5626423 1.8583791 1.4083446 2.0819746 1.9480342 2.3980948
 [1275] 3.3071488 1.6782835 1.9747483 2.5222702 3.3377707 3.8872737 2.9696593
 [1282] 1.5575697 1.7388004 2.4369074 1.7757100 3.0893211 3.0957078 2.0316823
 [1289] 3.9681449 1.7718305 1.7415644 1.5219282 2.9407986 3.1080143 3.1130621
 [1296] 2.4581197 2.3103441 2.5293878 1.4914360 1.7203478 2.8401503 2.9723856
 [1303] 2.3742372 2.1496008 1.4036774 3.4114720 2.6521548 2.3328434 2.0619834
 [1310] 1.8733199 1.7105008 3.7531518 1.8264645 3.1092982 1.7384355 2.3946112
 [1317] 2.5910229 2.8368755 3.2513760 2.9802497 2.8801887 2.8980227 2.0826022
 [1324] 2.9291725 3.1176252 2.3999844 2.4102996 2.5378401 1.7035698 2.9508555
 [1331] 3.0060569 2.2995471 2.4402093 2.3894914 2.1213895 2.7232431 3.6022767
 [1338] 1.7558840 1.9387252 2.0784514 3.5798383 1.9642641 1.3314570 2.8821768
 [1345] 2.2199590 1.9101851 2.9429776 1.8313198 2.9957656 2.0170342 2.9272641
 [1352] 1.1433854 2.4294557 2.6538316 2.1243683 2.9644614 2.3857498 3.6112870
 [1359] 2.9140042 2.1389053 2.1250710 1.7099247 2.7897642 2.7193800 2.4187723
 [1366] 2.9719206 2.3872602 1.7593185 2.3777730 2.9619879 2.4742386 2.1634822
 [1373] 2.6823513 1.4118448 1.9592786 2.8002099 1.5116791 2.6845015 1.6590841
 [1380] 3.0562820 3.0737280 3.0830538 3.7048288 3.1062560 2.9516924 3.4754365
 [1387] 1.4668322 1.7174445 1.6882335 3.2117767 3.4027750 2.1311657 2.5059880
 [1394] 1.6445012 2.7145277 2.6292533 2.7852958 2.0016879 1.8504524 2.6723545
 [1401] 2.7457003 1.5673990 1.8819067 1.6777593 2.0298676 2.4017245 3.0030606
 [1408] 3.0348549 3.4821931 2.5452222 1.9551758 1.7214703 1.8391932 1.8675706
 [1415] 2.1340768 3.0707520 2.0215148 2.6178053 1.7703344 2.3957025 2.0593823
 [1422] 1.8813198 2.1273959 1.4618719 1.5785414 2.5270156 1.9393417 2.0182617
 [1429] 2.0117074 2.1048470 2.2292023 2.0358385 3.3212339 1.4914653 1.4722186
 [1436] 1.9933468 2.7434189 1.6370653 2.4748237 2.8274121 2.9535322 1.9760572
 [1443] 2.5529205 1.6179949 3.3451639 3.1562814 1.5226908 2.7040913 1.9430252
 [1450] 2.7162695 2.0531172 2.3903170 2.6246279 2.9707656 3.1389676 2.5434622
 [1457] 3.1526379 2.7704782 2.4588883 2.0407188 1.9733246 2.2372847 2.8310958
 [1464] 2.6514081 1.9770950 1.7665833 1.7806897 3.0505569 3.4929491 2.8883649
 [1471] 1.8865477 1.7807671 3.0038505 3.1426587 2.8309265 2.7732442 2.3420960
 [1478] 1.8772564 1.4925233 1.9632242 2.6421928 1.6068349 3.0230423 2.0539753
 [1485] 1.5121006 2.0664952 2.7325370 1.5061671 1.7359241 2.3208823 3.0516245
 [1492] 1.5874373 1.4739739 1.6883371 1.8732555 1.9881758 1.7739257 1.9203240
 [1499] 2.8498547 3.4439271 2.9147513 2.1053088 1.9262124 2.0053765 2.4769652
 [1506] 2.5193814 2.1413765 3.1760105 1.8667877 2.1564362 2.1733068 1.0444596
 [1513] 2.7699616 1.9669623 2.0296514 2.6119806 1.7477414 3.1001648 2.9209900
 [1520] 2.9622313 1.8533097 1.7632981 1.4422408 1.5004168 1.9493753 1.9467212
 [1527] 2.8150789 1.8608728 2.1692790 2.0671799 2.2884448 2.7207312 1.9649233
 [1534] 2.3826663 2.4216343 2.1302848 2.1008372 1.8919183 2.4963060 2.0539718
 [1541] 2.6195153 2.9971016 1.8106441 1.7302034 2.8866810 3.1598119 3.0829394
 [1548] 1.8846458 2.6530849 1.4460768 1.7022580 2.5243477 2.0737657 2.7555088
 [1555] 2.8372811 1.9858263 1.5284829 2.3735182 2.2893860 2.7180253 2.6508168
 [1562] 2.2319746 2.3434951 2.3291812 1.9228817 2.2895743 2.0616716 2.1463125
 [1569] 2.8707286 2.0969737 3.3405075 2.8188348 1.6211678 2.4907051 2.2516979
 [1576] 1.8198426 2.1471621 3.1424223 2.3330739 3.6261817 1.7914639 2.9652220
 [1583] 2.8914236 3.4539753 1.8360417 1.6588077 1.8894173 3.1413431 1.3354891
 [1590] 1.5584999 2.1144169 2.6285848 3.1525491 1.7858942 3.8070652 2.0241535
 [1597] 2.3320407 2.5217036 3.2658211 3.7022010 3.1506076 3.8661127 1.9093105
 [1604] 2.2203828 1.8195287 3.4335148 3.8252699 2.1129271 2.8858160 2.8960009
 [1611] 3.8140611 1.7669977 1.8414072 2.3036342 2.7293335 2.5276716 1.9855104
 [1618] 1.6282311 1.9670231 2.6440430 2.6871380 1.3694883 2.7434394 2.5826572
 [1625] 2.1692076 1.6538370 1.4856043 2.0106367 2.2805548 1.9191676 3.2698803
 [1632] 2.2815564 1.9918115 2.0147437 3.1314523 2.4459609 2.0011032 1.6810683
 [1639] 2.7399100 1.4907225 3.0277769 1.3119467 1.7203825 1.6437308 2.4033771
 [1646] 2.1319659 2.0212809 2.1435053 2.3791119 1.5723040 2.2417856 3.3735742
 [1653] 1.8725325 1.7107205 1.9596513 2.3884234 3.3332575 2.6752127 2.5861600
 [1660] 2.5350511 2.9417736 2.7707330 3.0045127 3.0508610 0.9349066 2.1729499
 [1667] 2.3669168 3.0356668 3.0905136 3.0687322 2.9833912 1.7482233 2.1149604
 [1674] 1.6582385 2.2768054 2.9044880 2.8217200 2.9230152 2.8902815 3.3689606
 [1681] 1.7459556 1.9113394 1.7533847 0.6830689 0.8570057 2.6737472 2.4527515
 [1688] 2.8600888 2.5785344 2.5685994 1.6229499 1.7964631 2.0550618 2.8383087
 [1695] 1.3445775 1.9043903 1.8988249 1.6093944 2.3256657 2.0996608 1.8023967
 [1702] 2.1121045 1.8918323 2.5732788 2.2339745 2.1430974 2.6423140 2.3592453
 [1709] 2.0678805 1.6889606 2.4244722 1.5028736 2.4420064 3.3359724 3.2823855
 [1716] 2.5572332 2.1458618 1.9667340 1.8064768 2.2714182 2.8241453 3.3380254
 [1723] 1.4540129 1.5813438 2.6808287 3.2479515 3.2876960 3.4274657 1.0444918
 [1730] 2.5040242 1.8791148 3.0528578 2.4990103 2.9916049 3.1885389 1.5383482
 [1737] 1.7047283 1.7921763 2.0049505 2.1210871 1.9930965 1.6422949 2.9365043
 [1744] 2.7331388 2.9883268 2.1995745 2.7420455 3.3388200 3.4245713 3.2491171
 [1751] 3.1399467 3.3228937 2.0560864 1.7928147 2.2542958 2.4164789 3.1381613
 [1758] 3.0160165 3.0143899 2.9037038 1.8288298 1.8574477 2.0120461 2.1182582
 [1765] 2.3872271 2.8023860 3.0985735 1.7395209 3.2767898 3.1305837 2.3467018
 [1772] 2.1635133 1.9939157 2.0819599 2.4854051 2.7034642 1.2462025 1.8599056
 [1779] 2.5766714 1.6592052 0.9079969 3.1158269 2.7948973 1.9109823 2.2440946
 [1786] 2.3206430 1.9357954 3.2928167 1.7524395 2.8617590 1.7072022 3.7033717

In [45]:
lgbclsmin

      [,1]       [,2]        [,3]       [,4]       [,5]
 [1,] 0.28316338 0.06331474  0.03993616 0.1051749  5.084109e-01
 [2,] 0.18668758 0.14071223  0.06239763 0.1209547  4.892479e-01
 [3,] 0.02679570 0.01657602  0.05014666 0.3201268  5.863548e-01
 [4,] 0.39908533 0.13171819  0.18882350 0.2802838  8.921875e-05
 [5,] 0.20173083 0.21064295  0.25384562 0.3336585  1.221310e-04
 [6,] 0.16762197 0.31510448  0.10361885 0.1220277  2.916270e-01
 [7,] 0.13581869 0.16422076  0.19545143 0.5043539  1.552365e-04
 [8,] 0.15994945 0.17252774  0.31031025 0.3570498  1.628031e-04
 [9,] 0.46834242 0.05785328  0.08316034 0.1009863  2.896577e-01
[10,] 0.26118103 0.16869120  0.06111416 0.3103215  1.986921e-01
[11,] 0.32851642 0.15265178  0.09213153 0.1970541  2.296461e-01
[12,] 0.20700049 0.10633665  0.17336472 0.1688337  3.444644e-01
[13,] 0.31386128 0.07423384  0.13880021 0.1265249  3.465797e-01
[14,] 0.29296307 0.15274543  0.09541044 0.2338107  2.250704e-01
[15,] 0.07399697 0.23617277  0.23302003 0.1847269  2.720833e-01
[16,] 0.34310441 0.15546330  0.09997361 0.2007477  2.007110e-01
[17,] 0.25396956 0.17609810  0.06456404 0.2728545  2.325138e-01
[18,] 0.08249427 0.45500768  0.03936030 0.1977288  2.254090e-01
[19,] 0.20249368 0.38115974  0.13738540 0.1382959  1.406652e-01
[20,] 0.20666254 0.20153256  0.12836973 0.2409890  2.224462e-01
[21,] 0.31139936 0.17737735  0.14030267 0.1910908  1.798298e-01
[22,] 0.18977154 0.22561461  0.22636093 0.2559001  1.023528e-01
[23,] 0.16759510 0.21628950  0.20815974 0.2006132  2.073424e-01
[24,] 0.01035507 0.03318734  0.07638083 0.5068081  3.732686e-01
[25,] 0.01532043 0.01886226  0.04344906 0.3578291  5.645391e-01
[26,] 0.02185330 0.00738528  0.11272435 0.1945952  6.634419e-01
[27,] 0.01857572 0.04489171  0.21548997 0.3405235  3.805191e-01
[28,] 0.03724447 0.08361248  0.18094832 0.3140075  3.841873e-01
[29,] 0.04052229 0.03169519  0.06493803 0.2837146  5.791299e-01
[30,] 0.05680395 0.04208393  0.07578055 0.2844695  5.408620e-01
[31,] ⋮          ⋮           ⋮          ⋮          ⋮
[32,] 0.16584700 0.515442534 0.06807279 0.10804487 1.425928e-01
[33,] 0.14380434 0.546529751 0.06552309 0.11508587 1.290569e-01
[34,] 0.29156386 0.210672368 0.18142074 0.21255754 1.037855e-01
[35,] 0.13421950 0.220631170 0.22655191 0.29957670 1.190207e-01
[36,] 0.14779500 0.175118213 0.11735238 0.10059943 4.591350e-01
[37,] 0.14536869 0.076566296 0.10895203 0.11971407 5.493989e-01
[38,] 0.13232669 0.118585620 0.11344985 0.09016853 5.454693e-01
[39,] 0.03614278 0.009989645 0.04253628 0.06307343 8.482579e-01
[40,] 0.03874197 0.046482503 0.12310790 0.79159090 7.671930e-05
[41,] 0.21694254 0.133786519 0.16174098 0.48733990 1.900543e-04
[42,] 0.11084375 0.121533093 0.23182839 0.29449631 2.412985e-01
[43,] 0.37551325 0.263805245 0.12484419 0.23570460 1.327171e-04
[44,] 0.04166463 0.104830404 0.19102641 0.55221039 1.102682e-01
[45,] 0.07241585 0.078408821 0.24801189 0.37440978 2.267537e-01
[46,] 0.03463428 0.055685460 0.18993499 0.59343423 1.263110e-01
[47,] 0.06485247 0.170825633 0.19509808 0.32814373 2.410801e-01
[48,] 0.04555204 0.088987937 0.27965808 0.28868313 2.971188e-01
[49,] 0.09177592 0.142329888 0.20715263 0.38004427 1.786973e-01
[50,] 0.23550176 0.160342703 0.25299391 0.35105411 1.075209e-04
[51,] 0.30342820 0.295468205 0.19181964 0.20917980 1.041540e-04
[52,] 0.32256939 0.367155104 0.15262664 0.15211789 5.530979e-03
[53,] 0.16215872 0.195371897 0.31473341 0.32762343 1.125413e-04
[54,] 0.21863898 0.266057318 0.24855983 0.26663597 1.079044e-04
[55,] 0.07319009 0.274451899 0.27453065 0.37769219 1.351659e-04
[56,] 0.17122706 0.186893894 0.29748888 0.34423675 1.534222e-04
[57,] 0.50199144 0.186848322 0.17233023 0.13873858 9.143171e-05
[58,] 0.25331912 0.264378585 0.22582002 0.25636410 1.181872e-04
[59,] 0.31481070 0.291889465 0.15930376 0.23388595 1.101153e-04
[60,] 0.29333204 0.228502184 0.22111990 0.25692918 1.166981e-04
[61,] 0.38316896 0.225129868 0.15570522 0.23589387 1.020819e-04

In [46]:
datalength=dim(data)[1]
lgbclsm=matrix(lgbclsmin,m,datalength)
lgbclsminr=matrix(0,datalength,1)
for(i in 1:datalength)
    {
    lgbclsminr[i,]=which.max(lgbclsm[,i])
}
lgbclsminr=lgbclsminr-1

In [47]:
lgbclsminr

      [,1]
 [1,] 3
 [2,] 3
 [3,] 0
 [4,] 0
 [5,] 0
 [6,] 4
 [7,] 0
 [8,] 1
 [9,] 0
[10,] 0
[11,] 0
[12,] 2
[13,] 4
[14,] 1
[15,] 1
[16,] 4
[17,] 0
[18,] 2
[19,] 4
[20,] 3
[21,] 3
[22,] 3
[23,] 0
[24,] 0
[25,] 3
[26,] 0
[27,] 4
[28,] 1
[29,] 0
[30,] 1
[31,] ⋮
[32,] 3
[33,] 2
[34,] 3
[35,] 4
[36,] 3
[37,] 1
[38,] 2
[39,] 3
[40,] 1
[41,] 3
[42,] 2
[43,] 4
[44,] 2
[45,] 1
[46,] 0
[47,] 3
[48,] 1
[49,] 2
[50,] 2
[51,] 0
[52,] 4
[53,] 3
[54,] 3
[55,] 4
[56,] 4
[57,] 2
[58,] 0
[59,] 1
[60,] 0
[61,] 1

In [48]:
xgbregmean=predict(xgb_mean_reg,alldataxgb)
xgbclsmean=predict(xgb_mean_cl,alldataxgb)
lgbregmean=predict(lgb_mean_reg,as.matrix(data))
lgbclsmean=predict(lgb_mean_cl,as.matrix(data))

In [49]:
lgbclsm=matrix(lgbclsmean,m,datalength)
lgbclsmeanr=matrix(0,datalength,1)
for(i in 1:datalength)
    {
    lgbclsmeanr[i,]=which.max(lgbclsm[,i])
}
lgbclsmeanr=lgbclsmeanr-1

In [50]:
preallmin=cbind(xgbclsmin,xgbregmin)
preallmin=cbind(preallmin,lgbclsminr)
preallmin=cbind(preallmin,lgbregmin)

In [51]:
colnames(preallmin)=c('xgbclsmin','xgbregmin','lgbclsmin','lgbregmin')
head(preallmin)

     xgbclsmin xgbregmin lgbclsmin lgbregmin
[1,] 4         2.1529672 3         2.416267
[2,] 4         2.7261362 3         2.460504
[3,] 4         3.4908340 0         3.215233
[4,] 0         0.9635405 0         1.304264
[5,] 2         1.7827724 0         1.799648
[6,] 1         1.3510218 4         1.533613

In [52]:
preallmean=cbind(xgbclsmean,xgbregmean)
preallmean=cbind(preallmean,lgbclsmeanr)
preallmean=cbind(preallmean,lgbregmean)

In [53]:
head(preallmean)

     xgbclsmean xgbregmean   lgbregmean
[1,] 3          2.7869437  3 1.9393675
[2,] 3          2.2656732  3 2.2951503
[3,] 3          3.0697255  0 2.7336085
[4,] 1          0.9555054  2 0.8140261
[5,] 3          1.4852703  0 1.6747099
[6,] 1          1.2191916  2 1.7768961

In [54]:
colnames(preallmean)=c('xgbclsmean','xgbregmean','lgbclsmean','lgbregmean')
head(preallmean)

     xgbclsmean xgbregmean lgbclsmean lgbregmean
[1,] 3          2.7869437  3          1.9393675
[2,] 3          2.2656732  3          2.2951503
[3,] 3          3.0697255  0          2.7336085
[4,] 1          0.9555054  2          0.8140261
[5,] 3          1.4852703  0          1.6747099
[6,] 1          1.2191916  2          1.7768961

In [55]:
end_time = Sys.time()
time_matrix[4,]=end_time-start_time

In [56]:
result_list=list(preallmin,preallmean,time_matrix)

In [57]:
save(result_list, file = "Monthly_nnetar_opt_pre_result.RData")

In [58]:
time_matrix

     user_time system_time elapsed_time
[1,] 19.287469 19.287469   19.287469
[2,]  6.736094  6.736094    6.736094
[3,]  6.743447  6.743447    6.743447
[4,]  2.278507  2.278507    2.278507