In [1]:
library("xgboost")
library("Matrix")
library('Ckmeans.1d.dp')
library('lightgbm')

载入程辑包：‘lightgbm’


The following object is masked from ‘package:xgboost’:

    slice

## Read data and process data labels

In [2]:
time_matrix <- matrix(0,ncol = 3, nrow =4)
colnames(time_matrix) <- c("user_time", "system_time", "elapsed_time")
start_time = Sys.time()

In [3]:
data=read.csv('Quarterly_features_matrix.csv')
data=data[,2:dim(data)[2]]

In [4]:
dim(data)

[1] 24000    27

In [5]:
head(data)

  frequency nperiods seasonal_period trend     spike        linearity
1 4         1        4               0.9492015 1.440272e-05 -3.801739
2 4         1        4               0.9332456 2.024615e-05 -3.528016
3 4         1        4               0.9753689 3.173153e-06 -4.202105
4 4         1        4               0.9597504 7.178017e-06 -4.163362
5 4         1        4               0.9770473 1.682990e-07 -5.666607
6 4         1        4               0.9884024 1.093815e-07  4.960507
  curvature  e_acf1     e_acf10   seasonal_strength ⋯ diff2_acf1 diff2_acf10
1 -1.3040882 -0.4829440 0.4354882 0.3478599         ⋯ -0.7896943 1.7947057
2 -1.5740960 -0.3277471 0.3143940 0.1373249         ⋯ -0.6669261 0.7095412
3 -1.3102058 -0.3300377 0.2486809 0.1689488         ⋯ -0.7152289 0.8909252
4 -0.7087874 -0.2787477 0.4831910 0.1164472         ⋯ -0.6048727 0.6906562
5  0.6009075 -0.5379779 0.5748836 0.9582223         ⋯ -0.2911521 1.9555069
6 -1.0952883 -0.1131941 0.3831215 0.6847558         ⋯ -0.5923500 2.3289573
  seas_acf1 length user_time  system_time elapsed_time user_time.1
1 0.5618988 25     0.01836705 0.01836705  0.01836705   0
2 0.5378848 25     0.02149177 0.02149177  0.02149177   0
3 0.6050959 25     0.01739883 0.01739883  0.01739883   0
4 0.6227230 25     0.01743579 0.01743579  0.01743579   0
5 0.7981635 59     0.01771545 0.01771545  0.01771545   0
6 0.6350911 59     0.01755309 0.01755309  0.01755309   0
  system_time.1 elapsed_time.1
1 0             0
2 0             0
3 0             0
4 0             0
5 0             0
6 0             0

In [6]:
dlist= load('Quarterly_nnetar_datalist.RData')
datalist=eval(parse(text = dlist ))
res=datalist[[1]]
MASE=res[,,,6]
m=5

In [7]:
dim(MASE)

[1] 24000     5     4

In [8]:
whichmin<-function(x){
    minx=min(x[x>0])
    loc=which(x==minx)[1]-1
    loc
}

meanunique=function(x)
    {
    mean(unique(x))
}

In [9]:
nanum=c()
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    a=apply(count,1,min)
    if(sum(is.na(a))>0)
        {
        nanum=append(nanum,i)
    }
    }

In [10]:
nanum

   [1]   158   159   160   208   237   244   255   259   266   301   303   314
  [13]   322   327   330   340  1081  1201  1558  1564  1576  1579  1582  1585
  [25]  1586  1615  1626  1627  1629  1630  1639  1641  1644  1655  1656  1659
  [37]  1704  1709  1737  1744  1745  1751  1754  1756  1759  1763  1767  1769
  [49]  1773  1776  1778  1779  1784  1787  1788  1789  1792  1793  1794  1802
  [61]  1828  1855  1867  1881  1890  1898  1899  1902  1921  1933  1934  1935
  [73]  1937  1973  1974  2001  2023  2035  2053  2065  2071  2077  2091  2196
  [85]  2210  2217  2230  2233  2239  2283  2284  2300  2306  2323  2344  2399
  [97]  2436  2671  2676  2678  2703  2743  2781  3073  3149  3234  3235  3326
 [109]  3327  3328  3329  3330  3331  3332  3333  3334  3335  3336  3337  3448
 [121]  3449  3450  3451  3452  3453  3454  3455  3456  3514  3631  3634  3659
 [133]  3670  3672  3678  3700  3709  3747  3748  3749  3750  3751  3752  3753
 [145]  3754  3755  3756  3757  3758  3759  3760  3761  4121  4122  4123  4124
 [157]  4125  4126  4127  4128  4129  4130  4131  4132  4133  4134  4135  4136
 [169]  4158  4159  4160  4161  4162  4163  4164  4165  4166  4167  4168  4169
 [181]  4170  4171  4172  4173  4174  4175  4176  4177  4178  4179  4180  4181
 [193]  4182  4183  4184  4185  4186  4187  4188  4189  4190  4191  4192  4193
 [205]  4194  4195  4196  4197  4198  4199  4200  4201  4202  4203  4204  4411
 [217]  4412  4413  4415  4416  4417  4423  4442  4443  4444  4445  4446  4447
 [229]  4448  4449  4450  4451  4452  4453  4454  4455  4456  4457  4458  4459
 [241]  4460  4461  4462  4463  4464  4465  4466  4467  4468  4469  4470  4471
 [253]  4472  4473  4474  4475  4476  4477  4478  4519  4520  4523  4524  4525
 [265]  4526  4527  4528  4529  4530  4531  4532  4533  4534  4535  4536  4537
 [277]  4538  4539  4540  4541  4542  4543  4544  4545  4546  4547  4548  4549
 [289]  4550  4551  4552  4553  4554  4555  4556  4799  4813  4817  4823  4826
 [301]  4829  4831  4832  4836  4839  4840  4900  4924  4926  4946  4947  4952
 [313]  4953  4967  5032  5103  5104  5105  5117  5119  5120  5169  5178  5179
 [325]  5180  5181  5182  5183  5184  5185  5186  5187  5188  5189  5190  5307
 [337]  5308  5309  5514  5515  5516  5525  5528  5529  5530  5531  5532  5533
 [349]  5555  5559  5560  5576  5583  5584  5585  5589  5593  5594  5595  5596
 [361]  5600  5601  5602  5608  5617  5619  5631  5632  5634  5653  5656  5657
 [373]  5664  5665  5679  5680  5684  5685  5686  5687  5688  5689  5691  5703
 [385]  5704  5713  5764  5770  5774  5781  5793  5795  5806  5807  5809  5824
 [397]  5825  5828  5842  5844  5854  5856  5871  5872  5886  5887  5901  5911
 [409]  5916  5917  5922  5924  5934  5935  5936  5937  5938  5939  6968  6969
 [421]  6970  6971  6972  6973  6974  6975  6976  6977  6978  6979  6980  6981
 [433]  6982  6983  6984  6985  6986  6987  6988  6989  6990  6991  6992  6993
 [445]  6994  6995  6996  6997  6998  6999  7000  7001  7002  7003  7004  7005
 [457]  7006  7007  7008  7021  7024  7026  7038  7039  7040  7041  7042  7043
 [469]  7044  7045  7046  7047  7048  7049  7050  7051  7052  7053  7054  7055
 [481]  7056  7057  7058  7059  7060  7061  7062  7063  7064  7065  7066  7067
 [493]  7068  7069  7070  7083  7101  7104  7110  7121  7122  7173  7175  7197
 [505]  7465  7466  7467  7468  7469  7470  7471  7472  7473  7474  7475  7476
 [517]  7477  7478  7479  7480  7481  7482  7483  7484  7485  7486  7487  7488
 [529]  7489  7490  7491  7492  7493  7494  7495  7496  7497  7498  7499  7500
 [541]  7501  7502  7503  7504  7505  7506  7507  7508  7509  7510  7511  7512
 [553]  7513  7514  7515  7516  7517  7518  7519  7520  7521  7522  7532  7534
 [565]  7536  7537  7538  7539  7540  7543  7544  7547  7550  7551  7552  7555
 [577]  7556  7557  7559  7564  7565  7567  7568  7569  7575  7578  7583  7584
 [589]  7585  7590  7591  7592  7593  7594  7595  7597  7600  7601  7602  7605
 [601]  7606  7607  7609  7631  7638  7639  7640  7641  7713  7714  7715  7716
 [613]  7717  7728  7729  7730  7731  7732  7733  7742  7765  7772  7777  7781
 [625]  7783  7784  7785  7786  7787  7788  7789  7792  7797  7824  7828  7835
 [637]  7840  7843  7848  7849  7852  7910  7917  7918  7919  7920  7921  7922
 [649]  7925  7926  7927  7928  7929  7930  7931  7932  7933  7934  7935  7936
 [661]  7937  7938  7939  7940  7941  7942  7943  7944  7945  7946  7947  7948
 [673]  7949  7950  7951  7952  7953  7954  7955  7956  7958  7961  7962  7963
 [685]  7964  7965  7966  7967  7968  7969  7970  7971  7972  7973  7974  7975
 [697]  7976  7977  7978  7979  7980  7981  7982  7983  7984  7985  7986  7987
 [709]  7988  7989  7990  7991  7992  7993  7994  7995  7996  7997  7998  7999
 [721]  8000  8004  8005  8006  8007  8008  8009  8045  8054  8324  8383  8388
 [733]  8405  8408  8411  8416  8417  8418  8419  8421  8422  8423  8424  8425
 [745]  8426  8427  8428  8429  8432  8433  8434  8439  8440  8441  8442  8443
 [757]  8444  8446  8447  8450  8452  8453  8454  8455  8456  8458  8459  8460
 [769]  8461  8462  8463  8465  8466  8467  8468  8469  8470  8471  8472  8499
 [781]  8514  8529  8545  8563  8564  8583  8584  8586  8598  8599  8636  8638
 [793]  8641  8642  8643  8672  8981  8982  8983  8984  8985  8986  8987  8988
 [805]  8989  8990  8991  8992  8993  8994  8995  8996  8997  9009  9010  9011
 [817]  9014  9015  9017  9024  9025  9031  9036  9362  9371  9375  9376  9381
 [829]  9382  9386  9389  9391  9392  9393  9395  9396  9398  9399  9401  9402
 [841]  9403  9404  9419  9420  9813  9912  9913  9918  9919  9920  9922  9927
 [853]  9929  9930  9931  9932  9933  9934  9935  9936  9937  9938  9939  9940
 [865]  9941  9942  9943  9944  9945  9946  9947  9948  9949  9950  9951  9952
 [877]  9953  9954  9955  9956  9957  9958  9959  9960  9961  9962  9963  9964
 [889]  9965  9966  9967  9968  9969  9970  9971  9972  9973  9974  9975  9976
 [901]  9977  9978  9979  9980  9981  9982  9983  9984  9985  9986  9987  9988
 [913]  9989  9990  9991  9992  9993  9994  9995  9996  9997  9998  9999 10000
 [925] 10001 10002 10003 10004 10005 10006 10007 10008 10009 10010 10011 10012
 [937] 10013 10014 10015 10016 10017 10018 10019 10020 10021 10022 10023 10024
 [949] 10025 10026 10027 10028 10029 10030 10031 10032 10033 10034 10035 10036
 [961] 10037 10038 10039 10040 10041 10042 10043 10044 10045 10046 10047 10048
 [973] 10049 10050 10051 10052 10053 10054 10055 10056 10057 10058 10059 10060
 [985] 10061 10062 10063 10064 10065 10066 10067 10068 10069 10070 10071 10072
 [997] 10073 10074 10075 10076 10077 10078 10079 10080 10081 10082 10083 10084
[1009] 10085 10086 10087 10088 10089 10090 10091 10092 10093 10094 10143 10157
[1021] 10158 10204 10205 10206 10207 10208 10209 10210 10211 10212 10213 10214
[1033] 10215 10216 10231 10232 10233 10234 10235 10236 10237 10238 10239 10240
[1045] 10241 10242 10416 10417 10418 10419 10420 10421 10423 10424 10425 10428
[1057] 10429 10431 10433 10435 10436 10437 10438 10439 10440 10487 10592 10594
[1069] 10635 10636 10674 10763 10764 10788 10789 10790 10791 10792 10793 10794
[1081] 10795 10796 10797 10798 10799 10800 10801 10833 10853 10856 10857 10858
[1093] 10859 10860 10861 10862 10863 10864 10866 10867 10868 10869 10870 10871
[1105] 10872 10904 10905 10906 10916 10917 10918 10919 10920 10921 10922 10923
[1117] 10924 10925 11107 11184 11246 11252 11253 11254 11255 11256 11258 11259
[1129] 11260 11272 11276 11277 11374 11376 11377 11378 11379 11380 11381 11382
[1141] 11383 11384 11385 11386 11389 11390 11391 11411 11412 11413 11414 11415
[1153] 11416 11417 11418 11423 11479 11480 11481 11482 11483 11484 11485 11486
[1165] 11487 11488 11489 11490 11491 11492 11493 11494 11495 11496 11497 11498
[1177] 11499 11500 11546 11549 11550 11551 11552 11553 11559 11560 11561 11562
[1189] 11563 11564 11565 11566 11567 11569 11570 11571 11572 11573 11574 11575
[1201] 11576 11577 11578 11579 11581 11582 11583 11584 11585 11586 11587 11588
[1213] 11589 11590 11591 11592 11593 11594 11595 11596 11597 11598 11619 11620
[1225] 11621 11623 11626 11627 11629 11630 11631 11632 11635 11636 11640 11641
[1237] 11642 11643 11645 11646 11651 11652 11653 11654 11657 11659 11664 11665
[1249] 11674 11677 11683 11686 11687 11688 11689 11691 11692 11693 11694 11695
[1261] 11801 11802 11892 11912 11913 11916 11928 11939 11944 11957 11965 11970
[1273] 11983 11985 12012 12041 12171 12173 12174 12175 12176 12177 12178 12179
[1285] 12180 12181 12182 12183 12184 12185 12186 12187 12188 12189 12190 12191
[1297] 12192 12193 12194 12195 12196 12197 12198 12199 12200 12201 12202 12203
[1309] 12204 12205 12206 12207 12208 12209 12210 12211 12212 12213 12214 12215
[1321] 12216 12217 12218 12219 12220 12221 12222 12223 12224 12225 12226 12227
[1333] 12228 12229 12230 12231 12232 12233 12234 12235 12236 12237 12238 12239
[1345] 12240 12241 12242 12243 12244 12245 12246 12247 12248 12249 12250 12251
[1357] 12252 12253 12254 12255 12256 12257 12258 12259 12260 12261 12262 12263
[1369] 12264 12265 12266 12267 12268 12269 12270 12271 12272 12273 12274 12275
[1381] 12276 12277 12278 12279 12280 12281 12282 12283 12284 12297 12298 12437
[1393] 12443 12459 12460 12461 12462 12475 12476 12477 12478 12479 12547 12551
[1405] 12552 12553 12554 12582 12652 12653 12654 12724 12725 12769 12770 12771
[1417] 12772 12777 12779 12783 12784 12785 12786 12965 12966 12967 12968 12969
[1429] 12970 12971 12972 12973 13010 13115 13125 13126 13127 13136 13140 13189
[1441] 13190 13191 13192 13417 13447 13449 13453 13467 13481 13490 13491 13492
[1453] 13500 13501 13928 13950 13991 13992 13993 13994 13995 13996 13997 13999
[1465] 14000 14003 14009 14010 14024 14025 14080 14083 14107 14113 14137 14140
[1477] 14141 14188 14195 14199 14201 14227 14241 14244 14257 14270 14280 14281
[1489] 14288 14289 14299 14300 14303 14578 14610 14623 14665 14666 14669 14679
[1501] 14727 14729 14834 14835 14836 14839 14840 14852 14858 14859 14863 14865
[1513] 14921 14935 14936 14937 14939 15057 15063 15064 15065 15066 15074 15075
[1525] 15077 15079 15325 15326 15366 15477 15478 15479 15480 15486 15581 15582
[1537] 15630 15657 15702 15703 15704 15705 15706 15707 15708 15709 15710 15711
[1549] 15712 15713 15714 15715 15716 15717 15718 15719 15720 15721 15722 15723
[1561] 15724 15725 15726 15727 15728 15729 15730 15731 15732 15734 15735 15737
[1573] 15738 15739 15740 15741 15742 15743 15744 15745 15746 15747 15748 15749
[1585] 15750 15751 15752 15753 15754 15755 15756 15757 15759 15760 15761 15762
[1597] 15763 15771 15772 15773 15775 15776 15781 15782 15783 15785 15787 15788
[1609] 15790 15792 15793 15795 15799 15800 15805 15807 15808 15809 15810 15811
[1621] 15812 15813 15815 15817 15818 15820 15821 15822 15823 15824 15825 15826
[1633] 15827 15828 15829 15830 15831 15832 15833 15834 15836 15837 15839 15840
[1645] 15841 15842 15844 15846 15847 15848 15849 15850 15851 15852 15853 15854
[1657] 15856 15857 15860 15861 15863 15864 15865 15866 15867 15868 15869 15870
[1669] 15871 15872 15873 15874 15875 15876 15877 15878 15909 15912 15913 15914
[1681] 15915 15917 15918 15919 15920 15921 15922 15923 15924 15927 15928 15932
[1693] 15934 15937 15938 15939 15940 15941 16196 16197 16198 16319 16330 16332
[1705] 16333 16336 16337 16342 16343 16350 16352 16353 16356 16358 16360 16361
[1717] 16363 16369 16371 16376 16388 16404 16407 16408 16410 16411 16426 16443
[1729] 16460 16461 16462 16463 16464 16465 16560 16561 16562 16563 16564 16565
[1741] 16566 16567 16568 16570 16571 16572 16573 16574 16575 16577 16578 16580
[1753] 16581 16582 16583 16584 16585 16586 16587 16589 16590 16591 16592 16593
[1765] 16594 16595 16596 16597 16598 16599 17490 17681 17705 17778 17779 17780
[1777] 17781 17782 17831 17867 17921 17922 17923 17924 17925 17926 17927 17928
[1789] 17929 17930 17931 17932 17933 17934 17935 17936 17937 17938 17939 17940
[1801] 17941 17942 17943 17944 17945 17946 17947 17948 17949 17950 17951 17952
[1813] 17953 17954 17955 17956 17957 17958 17959 17960 17961 17962 17963 17964
[1825] 17965 17966 17967 17968 17969 17970 17971 17972 17973 17974 17975 17976
[1837] 17977 17978 17979 17980 17981 17982 17983 17984 17985 17986 17987 17988
[1849] 17989 17990 17991 17992 17993 17994 17995 17996 17997 17998 17999 18000
[1861] 18001 18002 18003 18004 18005 18006 18007 18008 18009 18010 18011 18012
[1873] 18013 18014 18015 18016 18017 18018 18019 18020 18021 18022 18023 18024
[1885] 18025 18026 18027 18028 18029 18030 18031 18032 18033 18034 18035 18036
[1897] 18037 18038 18039 18040 18041 18042 18043 18044 18045 18046 18047 18048
[1909] 18049 18050 18051 18052 18053 18054 18055 18056 18057 18058 18059 18060
[1921] 18061 18062 18063 18064 18065 18066 18067 18068 18069 18070 18071 18072
[1933] 18073 18074 18075 18076 18077 18078 18079 18080 18081 18082 18083 18084
[1945] 18085 18086 18087 18088 18089 18090 18091 18092 18093 18094 18095 18096
[1957] 18097 18098 18099 18100 18101 18102 18103 18104 18105 18106 18107 18108
[1969] 18109 18110 18111 18112 18113 18114 18115 18116 18117 18118 18119 18120
[1981] 18121 18122 18123 18124 18125 18126 18127 18128 18129 18130 18131 18132
[1993] 18133 18134 18135 18136 18137 18138 18139 18140 18141 18142 18143 18144
[2005] 18145 18146 18147 18148 18149 18150 18151 18152 18153 18154 18155 18156
[2017] 18157 18158 18159 18160 18161 18162 18163 18164 18165 18166 18167 18168
[2029] 18169 18170 18171 18172 18173 18174 18175 18176 18177 18178 18179 18180
[2041] 18181 18182 18183 18184 18185 18186 18187 18188 18189 18190 18191 18192
[2053] 18193 18194 18195 18196 18197 18198 18199 18200 18201 18202 18203 18204
[2065] 18205 18206 18207 18208 18209 18210 18211 18212 18213 18214 18215 18216
[2077] 18217 18218 18219 18220 18221 18222 18223 18224 18225 18226 18227 18228
[2089] 18229 18230 18231 18232 18233 18234 18235 18236 18237 18238 18239 18240
[2101] 18241 18242 18243 18244 18245 18246 18247 18248 18249 18250 18251 18252
[2113] 18253 18254 18255 18256 18257 18258 18259 18260 18261 18263 18264 18266
[2125] 18267 18268 18269 18270 18271 18272 18274 18275 18277 18278 18279 18280
[2137] 18281 18282 18283 18284 18285 18286 18287 18288 18289 18290 18291 18292
[2149] 18293 18294 18295 18296 18297 18298 18299 18300 18301 18302 18303 18304
[2161] 18305 18306 18307 18308 18309 18310 18311 18312 18313 18314 18315 18316
[2173] 18317 18318 18319 18320 18321 18368 18597 18625 18626 18642 18643 18664
[2185] 18665 18666 18667 18668 18669 18670 18680 18766 18767 18768 18769 18770
[2197] 18811 18825 18826 18856 18857 18858 18860 18861 18862 18863 18864 18865
[2209] 18866 18867 18868 18869 18870 18871 18878 18879 18880 18881 18905 18906
[2221] 18909 18910 18911 18956 18957 18958 18959 18960 18961 18964 18965 18966
[2233] 18967 18968 18969 18970 19014 19015 19016 19048 19049 19050 19051 19112
[2245] 19113 19114 19115 19116 19117 19118 19119 19127 19137 19145 19159 19202
[2257] 19245 19255 19264 19297 19299 19307 19310 19329 19353 19367 19405 19443
[2269] 19450 19469 19493 19521 19529 19550 19573 19608 19626 19645 19659 19662
[2281] 19680 19691 19813 19814 19836 19837 19838 19839 19840 19841 19842 19851
[2293] 19852 19853 19854 19855 19856 19857 19858 19859 19860 19861 19863 19873
[2305] 19876 19877 19878 19879 19880 19907 20026 20027 20086 20087 20088 20093
[2317] 20098 20106 20108 20113 20120 20122 20123 20125 20126 20128 20129 20130
[2329] 20131 20132 20133 20134 20140 20142 20143 20145 20146 20148 20150 20157
[2341] 20159 20160 20163 20164 20165 20173 20176 20178 20196 20197 20198 20199
[2353] 20200 20201 20202 20207 20246 20391 20436 20437 20438 20439 20440 20441
[2365] 20442 20443 20444 20445 20446 20447 20448 20449 20450 20451 20452 20453
[2377] 20454 20455 20456 20457 20458 20459 20460 20461 20462 20463 20464 20465
[2389] 20466 20467 20468 20471 20569 20637 20638 20654 20674 20693 20790 20791
[2401] 20792 20793 20794 20993 20995 20996 21321 21382 21383 21384 21385 21386
[2413] 21387 21388 21390 21391 21392 21395 21397 21398 21399 21400 21401 21402
[2425] 21403 21404 21405 21406 22107 22108 22109 22110 22111 22112 22126 22129
[2437] 22132 22135 22162 22164 22178 22179 22180 22181 22182 22183 22184 22185
[2449] 22186 22187 22188 22189 22190 22191 22197 22198 22199 22200 22235 22252
[2461] 22253 22254 22255 22256 22257 22258 22259 22260 22261 22262 22263 22264
[2473] 22265 22267 22268 22269 22270 22271 22272 22273 22274 22275 22276 22279
[2485] 22282 22285 22291 22293 22295 22298 22301 22304 22306 22307 22309 22310
[2497] 22311 22314 22315 22316 22317 22318 22319 22320 22323 22324 22326 22328
[2509] 22329 22330 22331 22332 22333 22334 22335 22336 22337 22338 22339 22340
[2521] 22341 22342 22343 22344 22346 22448 22481 22482 22483 22484 22562 22653
[2533] 22669 22676 22677 22678 22689 22690 22691 22708 22709 22827 22828 22829
[2545] 22832 22833 22834 22835 22836 22844 22845 22846 22853 22872 22876 22877
[2557] 22878 22879 22880 22881 22882 22883 22884 22885 22886 22887 22888 22889
[2569] 22890 22891 22892 22893 22894 22903 22915 23117 23131 23132 23156 23157
[2581] 23158 23159 23160 23161 23162 23163 23164 23165 23166 23167 23168 23169
[2593] 23170 23171 23172 23173 23174 23175 23176 23177 23178 23179 23180 23181
[2605] 23182 23183 23184 23185 23186 23187 23188 23189 23190 23191 23192 23193
[2617] 23194 23195 23196 23197 23198 23199 23200 23201 23202 23203 23204 23205
[2629] 23206 23207 23208 23209 23210 23211 23212 23213 23214 23215 23216 23217
[2641] 23218 23219 23220 23221 23222 23223 23224 23225 23226 23227 23228 23229
[2653] 23230 23231 23232 23233 23234 23235 23236 23237 23238 23239 23240 23241
[2665] 23242 23243 23244 23245 23246 23247 23248 23249 23250 23251 23252 23253
[2677] 23254 23255 23256 23257 23258 23259 23260 23261 23262 23263 23264 23265
[2689] 23266 23267 23268 23269 23270 23271 23272 23273 23274 23275 23276 23277
[2701] 23278 23279 23280 23281 23282 23283 23284 23285 23286 23287 23288 23289
[2713] 23290 23291 23292 23293 23294 23295 23296 23297 23298 23299 23300 23301
[2725] 23302 23303 23304 23305 23306 23307 23308 23309 23310 23311 23312 23313
[2737] 23314 23315 23316 23317 23318 23319 23320 23321 23322 23323 23324 23325
[2749] 23326 23327 23328 23329 23330 23331 23332 23333 23334 23335 23336 23337
[2761] 23338 23339 23340 23341 23342 23343 23344 23345 23346 23347 23348 23349
[2773] 23350 23351 23352 23353 23354 23355 23356 23357 23358 23359 23360 23361
[2785] 23362 23363 23364 23365 23366 23367 23368 23369 23370 23371 23372 23373
[2797] 23374 23375 23376 23377 23378 23379 23380 23381 23382 23383 23384 23385
[2809] 23386 23387 23388 23389 23390 23391 23392 23393 23394 23395 23396 23397
[2821] 23398 23399 23400 23401 23402 23403 23425 23426 23603 23612 23613 23615
[2833] 23616 23626 23639 23677 23678 23681 23682 23683 23684 23685 23686 23687
[2845] 23688 23689 23690 23691 23692 23693 23694 23696 23698 23699 23965 23966
[2857] 23967 23968

In [11]:
realbestmin=matrix(0,dim(MASE)[1],1)
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    min_value=apply(count,1,min)
    if (max(min_value,na.rm = TRUE)==0){
        realbestmin[i,]=0
        }
    else
        {
        min_value[is.na(min_value)]=100 
        realbestmin[i,]= whichmin(min_value)
    }
    }

In [12]:
table(realbestmin)

realbestmin
   0    1    2    3    4
3503 3076 3947 6060 7414

In [13]:
realbestmean=matrix(0,dim(MASE)[1],1)
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    mean_value=apply(count,1,meanunique)
    if (max(mean_value,na.rm = TRUE)==0){
        realbestmean[i,]=0
        }
    else
        {
        mean_value[is.na(mean_value)]=100 
        realbestmean[i,]= whichmin(mean_value)
    }
    }

In [14]:
realbestmean

      [,1]
 [1,] 2
 [2,] 2
 [3,] 2
 [4,] 1
 [5,] 0
 [6,] 3
 [7,] 2
 [8,] 2
 [9,] 2
[10,] 0
[11,] 0
[12,] 3
[13,] 0
[14,] 3
[15,] 2
[16,] 4
[17,] 1
[18,] 2
[19,] 2
[20,] 3
[21,] 1
[22,] 2
[23,] 4
[24,] 2
[25,] 2
[26,] 3
[27,] 3
[28,] 4
[29,] 3
[30,] 0
[31,] ⋮
[32,] 4
[33,] 2
[34,] 3
[35,] 0
[36,] 0
[37,] 1
[38,] 3
[39,] 4
[40,] 0
[41,] 0
[42,] 1
[43,] 3
[44,] 2
[45,] 0
[46,] 2
[47,] 2
[48,] 4
[49,] 4
[50,] 3
[51,] 1
[52,] 0
[53,] 1
[54,] 4
[55,] 3
[56,] 2
[57,] 2
[58,] 0
[59,] 0
[60,] 2
[61,] 2

In [15]:
head(data)

  frequency nperiods seasonal_period trend     spike        linearity
1 4         1        4               0.9492015 1.440272e-05 -3.801739
2 4         1        4               0.9332456 2.024615e-05 -3.528016
3 4         1        4               0.9753689 3.173153e-06 -4.202105
4 4         1        4               0.9597504 7.178017e-06 -4.163362
5 4         1        4               0.9770473 1.682990e-07 -5.666607
6 4         1        4               0.9884024 1.093815e-07  4.960507
  curvature  e_acf1     e_acf10   seasonal_strength ⋯ diff2_acf1 diff2_acf10
1 -1.3040882 -0.4829440 0.4354882 0.3478599         ⋯ -0.7896943 1.7947057
2 -1.5740960 -0.3277471 0.3143940 0.1373249         ⋯ -0.6669261 0.7095412
3 -1.3102058 -0.3300377 0.2486809 0.1689488         ⋯ -0.7152289 0.8909252
4 -0.7087874 -0.2787477 0.4831910 0.1164472         ⋯ -0.6048727 0.6906562
5  0.6009075 -0.5379779 0.5748836 0.9582223         ⋯ -0.2911521 1.9555069
6 -1.0952883 -0.1131941 0.3831215 0.6847558         ⋯ -0.5923500 2.3289573
  seas_acf1 length user_time  system_time elapsed_time user_time.1
1 0.5618988 25     0.01836705 0.01836705  0.01836705   0
2 0.5378848 25     0.02149177 0.02149177  0.02149177   0
3 0.6050959 25     0.01739883 0.01739883  0.01739883   0
4 0.6227230 25     0.01743579 0.01743579  0.01743579   0
5 0.7981635 59     0.01771545 0.01771545  0.01771545   0
6 0.6350911 59     0.01755309 0.01755309  0.01755309   0
  system_time.1 elapsed_time.1
1 0             0
2 0             0
3 0             0
4 0             0
5 0             0
6 0             0

In [16]:
set.seed(100)
index = sample(2,nrow(data),replace = TRUE,prob=c(0.7,0.3))

In [17]:
train_data=data[index==1,]
test_data=data[index==2,]
train_label_min=realbestmin[index==1,]
test_label_min=realbestmin[index==2,]
train_label_mean=realbestmean[index==1,]
test_label_mean=realbestmean[index==2,]

In [18]:
head(train_data)

  frequency nperiods seasonal_period trend     spike        linearity
1 4         1        4               0.9492015 1.440272e-05 -3.801739
2 4         1        4               0.9332456 2.024615e-05 -3.528016
3 4         1        4               0.9753689 3.173153e-06 -4.202105
4 4         1        4               0.9597504 7.178017e-06 -4.163362
5 4         1        4               0.9770473 1.682990e-07 -5.666607
6 4         1        4               0.9884024 1.093815e-07  4.960507
  curvature  e_acf1     e_acf10   seasonal_strength ⋯ diff2_acf1 diff2_acf10
1 -1.3040882 -0.4829440 0.4354882 0.3478599         ⋯ -0.7896943 1.7947057
2 -1.5740960 -0.3277471 0.3143940 0.1373249         ⋯ -0.6669261 0.7095412
3 -1.3102058 -0.3300377 0.2486809 0.1689488         ⋯ -0.7152289 0.8909252
4 -0.7087874 -0.2787477 0.4831910 0.1164472         ⋯ -0.6048727 0.6906562
5  0.6009075 -0.5379779 0.5748836 0.9582223         ⋯ -0.2911521 1.9555069
6 -1.0952883 -0.1131941 0.3831215 0.6847558         ⋯ -0.5923500 2.3289573
  seas_acf1 length user_time  system_time elapsed_time user_time.1
1 0.5618988 25     0.01836705 0.01836705  0.01836705   0
2 0.5378848 25     0.02149177 0.02149177  0.02149177   0
3 0.6050959 25     0.01739883 0.01739883  0.01739883   0
4 0.6227230 25     0.01743579 0.01743579  0.01743579   0
5 0.7981635 59     0.01771545 0.01771545  0.01771545   0
6 0.6350911 59     0.01755309 0.01755309  0.01755309   0
  system_time.1 elapsed_time.1
1 0             0
2 0             0
3 0             0
4 0             0
5 0             0
6 0             0

In [19]:
end_time = Sys.time()

In [20]:
time_matrix[1,]=end_time-start_time

In [21]:
end_time-start_time

Time difference of 8.286007 secs

## Target the interval where the actual error is minimum

In [22]:
start_time = Sys.time()

In [23]:
dtrain_xg_min_reg <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(train_label_min)) 
dtrain_xg_min_cl <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_min)) )

In [24]:
dtrain_lg_min_reg <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(train_label_min))
dtrain_lg_min_cl <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_min)))

In [25]:
xgb_min_reg <- xgboost(data = dtrain_xg_min_reg, nround=100)

[1]	train-rmse:1.921655
[2]	train-rmse:1.623835
[3]	train-rmse:1.449043
[4]	train-rmse:1.352082
[5]	train-rmse:1.294304
[6]	train-rmse:1.260646
[7]	train-rmse:1.240497
[8]	train-rmse:1.228017
[9]	train-rmse:1.218087
[10]	train-rmse:1.211537
[11]	train-rmse:1.205602
[12]	train-rmse:1.199236
[13]	train-rmse:1.196396
[14]	train-rmse:1.191373
[15]	train-rmse:1.188459
[16]	train-rmse:1.182525
[17]	train-rmse:1.181139
[18]	train-rmse:1.177912
[19]	train-rmse:1.173245
[20]	train-rmse:1.171881
[21]	train-rmse:1.169006
[22]	train-rmse:1.164384
[23]	train-rmse:1.161411
[24]	train-rmse:1.158681
[25]	train-rmse:1.154426
[26]	train-rmse:1.149255
[27]	train-rmse:1.143185
[28]	train-rmse:1.138924
[29]	train-rmse:1.134757
[30]	train-rmse:1.131593
[31]	train-rmse:1.128289
[32]	train-rmse:1.125054
[33]	train-rmse:1.122628
[34]	train-rmse:1.118683
[35]	train-rmse:1.111193
[36]	train-rmse:1.106551
[37]	train-rmse:1.103415
[38]	train-rmse:1.099871
[39]	train-rmse:1.094565
[40]	train-rmse:1.089662
[41]	train-rmse:1.084560
[42]	train-rmse:1.080607
[43]	train-rmse:1.078150
[44]	train-rmse:1.077497
[45]	train-rmse:1.071677
[46]	train-rmse:1.070244
[47]	train-rmse:1.069042
[48]	train-rmse:1.063061
[49]	train-rmse:1.061289
[50]	train-rmse:1.057234
[51]	train-rmse:1.052344
[52]	train-rmse:1.047602
[53]	train-rmse:1.044278
[54]	train-rmse:1.040847
[55]	train-rmse:1.038134
[56]	train-rmse:1.032991
[57]	train-rmse:1.028411
[58]	train-rmse:1.024225
[59]	train-rmse:1.019324
[60]	train-rmse:1.017060
[61]	train-rmse:1.013805
[62]	train-rmse:1.012221
[63]	train-rmse:1.010634
[64]	train-rmse:1.006152
[65]	train-rmse:1.002580
[66]	train-rmse:1.000698
[67]	train-rmse:0.996768
[68]	train-rmse:0.994723
[69]	train-rmse:0.993673
[70]	train-rmse:0.989845
[71]	train-rmse:0.986333
[72]	train-rmse:0.982952
[73]	train-rmse:0.980480
[74]	train-rmse:0.974826
[75]	train-rmse:0.974569
[76]	train-rmse:0.971623
[77]	train-rmse:0.969431
[78]	train-rmse:0.968480
[79]	train-rmse:0.966644
[80]	train-rmse:0.964208
[81]	train-rmse:0.961083
[82]	train-rmse:0.956344
[83]	train-rmse:0.955590
[84]	train-rmse:0.953605
[85]	train-rmse:0.949766
[86]	train-rmse:0.947772
[87]	train-rmse:0.943290
[88]	train-rmse:0.939825
[89]	train-rmse:0.939065
[90]	train-rmse:0.934172
[91]	train-rmse:0.931567
[92]	train-rmse:0.927660
[93]	train-rmse:0.925472
[94]	train-rmse:0.921332
[95]	train-rmse:0.917224
[96]	train-rmse:0.913555
[97]	train-rmse:0.909443
[98]	train-rmse:0.908488
[99]	train-rmse:0.907102
[100]	train-rmse:0.904900

In [26]:
xgb_min_cl <- xgboost(data = dtrain_xg_min_cl, nround=100, objective='multi:softmax',num_class=5)

[1]	train-mlogloss:1.534000
[2]	train-mlogloss:1.480562
[3]	train-mlogloss:1.440894
[4]	train-mlogloss:1.408224
[5]	train-mlogloss:1.380780
[6]	train-mlogloss:1.359510
[7]	train-mlogloss:1.339360
[8]	train-mlogloss:1.322181
[9]	train-mlogloss:1.305054
[10]	train-mlogloss:1.290748
[11]	train-mlogloss:1.277521
[12]	train-mlogloss:1.265152
[13]	train-mlogloss:1.256132
[14]	train-mlogloss:1.247558
[15]	train-mlogloss:1.239966
[16]	train-mlogloss:1.229089
[17]	train-mlogloss:1.221593
[18]	train-mlogloss:1.211621
[19]	train-mlogloss:1.202557
[20]	train-mlogloss:1.194965
[21]	train-mlogloss:1.187396
[22]	train-mlogloss:1.179862
[23]	train-mlogloss:1.172479
[24]	train-mlogloss:1.165012
[25]	train-mlogloss:1.161617
[26]	train-mlogloss:1.153289
[27]	train-mlogloss:1.149708
[28]	train-mlogloss:1.141740
[29]	train-mlogloss:1.135824
[30]	train-mlogloss:1.127760
[31]	train-mlogloss:1.120399
[32]	train-mlogloss:1.115214
[33]	train-mlogloss:1.109838
[34]	train-mlogloss:1.104349
[35]	train-mlogloss:1.096538
[36]	train-mlogloss:1.089637
[37]	train-mlogloss:1.086519
[38]	train-mlogloss:1.081115
[39]	train-mlogloss:1.075334
[40]	train-mlogloss:1.070232
[41]	train-mlogloss:1.065532
[42]	train-mlogloss:1.059668
[43]	train-mlogloss:1.053426
[44]	train-mlogloss:1.046511
[45]	train-mlogloss:1.039858
[46]	train-mlogloss:1.035215
[47]	train-mlogloss:1.028498
[48]	train-mlogloss:1.021082
[49]	train-mlogloss:1.015412
[50]	train-mlogloss:1.010735
[51]	train-mlogloss:1.006942
[52]	train-mlogloss:1.003579
[53]	train-mlogloss:0.998933
[54]	train-mlogloss:0.993406
[55]	train-mlogloss:0.988825
[56]	train-mlogloss:0.983346
[57]	train-mlogloss:0.976751
[58]	train-mlogloss:0.971023
[59]	train-mlogloss:0.966242
[60]	train-mlogloss:0.961552
[61]	train-mlogloss:0.954950
[62]	train-mlogloss:0.948529
[63]	train-mlogloss:0.942373
[64]	train-mlogloss:0.937746
[65]	train-mlogloss:0.934106
[66]	train-mlogloss:0.931033
[67]	train-mlogloss:0.924286
[68]	train-mlogloss:0.919603
[69]	train-mlogloss:0.914694
[70]	train-mlogloss:0.909392
[71]	train-mlogloss:0.906945
[72]	train-mlogloss:0.903108
[73]	train-mlogloss:0.900813
[74]	train-mlogloss:0.897047
[75]	train-mlogloss:0.892453
[76]	train-mlogloss:0.888688
[77]	train-mlogloss:0.884512
[78]	train-mlogloss:0.882218
[79]	train-mlogloss:0.877991
[80]	train-mlogloss:0.872963
[81]	train-mlogloss:0.868061
[82]	train-mlogloss:0.863316
[83]	train-mlogloss:0.859943
[84]	train-mlogloss:0.854098
[85]	train-mlogloss:0.849386
[86]	train-mlogloss:0.844006
[87]	train-mlogloss:0.839603
[88]	train-mlogloss:0.835630
[89]	train-mlogloss:0.831530
[90]	train-mlogloss:0.827277
[91]	train-mlogloss:0.823506
[92]	train-mlogloss:0.819708
[93]	train-mlogloss:0.814836
[94]	train-mlogloss:0.811334
[95]	train-mlogloss:0.808502
[96]	train-mlogloss:0.804948
[97]	train-mlogloss:0.802662
[98]	train-mlogloss:0.798242
[99]	train-mlogloss:0.794474
[100]	train-mlogloss:0.790117

In [27]:
lgb_min_reg <- lgb.train(data = dtrain_lg_min_reg, nrounds = 100)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.017309 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4811
[LightGBM] [Info] Number of data points in the train set: 16927, number of used features: 21
[LightGBM] [Info] Start training from score 2.457435

In [28]:
params <- list(objective = "multiclass",
               num_class = 5, 
               metric = "multi_logloss")
lgb_min_cl <- lgb.train(data = dtrain_lg_min_cl,nrounds = 100,params=params)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.017352 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4811
[LightGBM] [Info] Number of data points in the train set: 16927, number of used features: 21
[LightGBM] [Info] Start training from score -1.936502
[LightGBM] [Info] Start training from score -2.058802
[LightGBM] [Info] Start training from score -1.803585
[LightGBM] [Info] Start training from score -1.372390
[LightGBM] [Info] Start training from score -1.171253

In [29]:
end_time = Sys.time()
time_matrix[2,]=end_time-start_time

## Target the interval where the average error is minimum

In [30]:
start_time = Sys.time()

In [31]:
dtrain_xg_mean_reg <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(train_label_mean)) 
dtrain_xg_mean_cl <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_mean)) )

In [32]:
dtrain_lg_mean_reg <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(train_label_mean))
dtrain_lg_mean_cl <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_mean)))

In [33]:
xgb_mean_reg <- xgboost(data = dtrain_xg_mean_reg, nround=100)

[1]	train-rmse:1.678534
[2]	train-rmse:1.467918
[3]	train-rmse:1.348601
[4]	train-rmse:1.278984
[5]	train-rmse:1.238840
[6]	train-rmse:1.214818
[7]	train-rmse:1.199831
[8]	train-rmse:1.185376
[9]	train-rmse:1.177762
[10]	train-rmse:1.171192
[11]	train-rmse:1.161893
[12]	train-rmse:1.157028
[13]	train-rmse:1.147895
[14]	train-rmse:1.145244
[15]	train-rmse:1.142812
[16]	train-rmse:1.141130
[17]	train-rmse:1.136624
[18]	train-rmse:1.133881
[19]	train-rmse:1.132015
[20]	train-rmse:1.126269
[21]	train-rmse:1.121698
[22]	train-rmse:1.115438
[23]	train-rmse:1.110164
[24]	train-rmse:1.107718
[25]	train-rmse:1.105993
[26]	train-rmse:1.101001
[27]	train-rmse:1.094798
[28]	train-rmse:1.093149
[29]	train-rmse:1.087175
[30]	train-rmse:1.082206
[31]	train-rmse:1.076830
[32]	train-rmse:1.073872
[33]	train-rmse:1.071635
[34]	train-rmse:1.067139
[35]	train-rmse:1.060829
[36]	train-rmse:1.057066
[37]	train-rmse:1.054920
[38]	train-rmse:1.052407
[39]	train-rmse:1.050331
[40]	train-rmse:1.048286
[41]	train-rmse:1.044965
[42]	train-rmse:1.040380
[43]	train-rmse:1.035593
[44]	train-rmse:1.032920
[45]	train-rmse:1.030189
[46]	train-rmse:1.027138
[47]	train-rmse:1.022497
[48]	train-rmse:1.016775
[49]	train-rmse:1.012362
[50]	train-rmse:1.007121
[51]	train-rmse:1.004053
[52]	train-rmse:1.000781
[53]	train-rmse:0.996616
[54]	train-rmse:0.993212
[55]	train-rmse:0.989478
[56]	train-rmse:0.986296
[57]	train-rmse:0.983675
[58]	train-rmse:0.981861
[59]	train-rmse:0.981415
[60]	train-rmse:0.978891
[61]	train-rmse:0.973923
[62]	train-rmse:0.971271
[63]	train-rmse:0.970709
[64]	train-rmse:0.966618
[65]	train-rmse:0.962304
[66]	train-rmse:0.960865
[67]	train-rmse:0.957718
[68]	train-rmse:0.957286
[69]	train-rmse:0.954453
[70]	train-rmse:0.951970
[71]	train-rmse:0.947977
[72]	train-rmse:0.945096
[73]	train-rmse:0.941814
[74]	train-rmse:0.939567
[75]	train-rmse:0.938689
[76]	train-rmse:0.934641
[77]	train-rmse:0.930808
[78]	train-rmse:0.926782
[79]	train-rmse:0.924120
[80]	train-rmse:0.920567
[81]	train-rmse:0.917137
[82]	train-rmse:0.912163
[83]	train-rmse:0.910620
[84]	train-rmse:0.909404
[85]	train-rmse:0.908429
[86]	train-rmse:0.906907
[87]	train-rmse:0.902886
[88]	train-rmse:0.899041
[89]	train-rmse:0.895753
[90]	train-rmse:0.892267
[91]	train-rmse:0.890269
[92]	train-rmse:0.887928
[93]	train-rmse:0.885571
[94]	train-rmse:0.881408
[95]	train-rmse:0.878234
[96]	train-rmse:0.876513
[97]	train-rmse:0.873326
[98]	train-rmse:0.869318
[99]	train-rmse:0.868525
[100]	train-rmse:0.867006

In [34]:
xgb_mean_cl <- xgboost(data = dtrain_xg_mean_cl, nround=100, objective='multi:softmax',num_class=5)

[1]	train-mlogloss:1.547209
[2]	train-mlogloss:1.500310
[3]	train-mlogloss:1.464830
[4]	train-mlogloss:1.433249
[5]	train-mlogloss:1.406502
[6]	train-mlogloss:1.383358
[7]	train-mlogloss:1.364090
[8]	train-mlogloss:1.347497
[9]	train-mlogloss:1.330028
[10]	train-mlogloss:1.316457
[11]	train-mlogloss:1.303076
[12]	train-mlogloss:1.290711
[13]	train-mlogloss:1.279098
[14]	train-mlogloss:1.270127
[15]	train-mlogloss:1.259051
[16]	train-mlogloss:1.250475
[17]	train-mlogloss:1.239814
[18]	train-mlogloss:1.232032
[19]	train-mlogloss:1.223921
[20]	train-mlogloss:1.218477
[21]	train-mlogloss:1.209782
[22]	train-mlogloss:1.204139
[23]	train-mlogloss:1.199058
[24]	train-mlogloss:1.192379
[25]	train-mlogloss:1.184425
[26]	train-mlogloss:1.176348
[27]	train-mlogloss:1.170544
[28]	train-mlogloss:1.164477
[29]	train-mlogloss:1.157021
[30]	train-mlogloss:1.151899
[31]	train-mlogloss:1.147092
[32]	train-mlogloss:1.143071
[33]	train-mlogloss:1.135474
[34]	train-mlogloss:1.127507
[35]	train-mlogloss:1.124380
[36]	train-mlogloss:1.119530
[37]	train-mlogloss:1.115243
[38]	train-mlogloss:1.107314
[39]	train-mlogloss:1.101296
[40]	train-mlogloss:1.095306
[41]	train-mlogloss:1.090705
[42]	train-mlogloss:1.085715
[43]	train-mlogloss:1.079395
[44]	train-mlogloss:1.076236
[45]	train-mlogloss:1.069471
[46]	train-mlogloss:1.064988
[47]	train-mlogloss:1.060156
[48]	train-mlogloss:1.054388
[49]	train-mlogloss:1.051480
[50]	train-mlogloss:1.043704
[51]	train-mlogloss:1.035644
[52]	train-mlogloss:1.030390
[53]	train-mlogloss:1.024345
[54]	train-mlogloss:1.022136
[55]	train-mlogloss:1.014691
[56]	train-mlogloss:1.009394
[57]	train-mlogloss:1.005731
[58]	train-mlogloss:0.998854
[59]	train-mlogloss:0.996768
[60]	train-mlogloss:0.991767
[61]	train-mlogloss:0.984250
[62]	train-mlogloss:0.978563
[63]	train-mlogloss:0.975773
[64]	train-mlogloss:0.973258
[65]	train-mlogloss:0.967296
[66]	train-mlogloss:0.960976
[67]	train-mlogloss:0.956134
[68]	train-mlogloss:0.949272
[69]	train-mlogloss:0.943856
[70]	train-mlogloss:0.939141
[71]	train-mlogloss:0.936658
[72]	train-mlogloss:0.930522
[73]	train-mlogloss:0.926843
[74]	train-mlogloss:0.922151
[75]	train-mlogloss:0.916502
[76]	train-mlogloss:0.913270
[77]	train-mlogloss:0.909783
[78]	train-mlogloss:0.903643
[79]	train-mlogloss:0.900694
[80]	train-mlogloss:0.896006
[81]	train-mlogloss:0.890395
[82]	train-mlogloss:0.888865
[83]	train-mlogloss:0.884932
[84]	train-mlogloss:0.879701
[85]	train-mlogloss:0.876883
[86]	train-mlogloss:0.873542
[87]	train-mlogloss:0.868198
[88]	train-mlogloss:0.863884
[89]	train-mlogloss:0.860302
[90]	train-mlogloss:0.855986
[91]	train-mlogloss:0.848705
[92]	train-mlogloss:0.843241
[93]	train-mlogloss:0.837533
[94]	train-mlogloss:0.831543
[95]	train-mlogloss:0.827343
[96]	train-mlogloss:0.822641
[97]	train-mlogloss:0.819612
[98]	train-mlogloss:0.816311
[99]	train-mlogloss:0.813047
[100]	train-mlogloss:0.809686

In [35]:
lgb_mean_reg <- lgb.train(data = dtrain_lg_mean_reg,nrounds = 100)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011275 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4811
[LightGBM] [Info] Number of data points in the train set: 16927, number of used features: 21
[LightGBM] [Info] Start training from score 1.997164

In [36]:
params <- list(objective = "multiclass",
               num_class = 5, 
               metric = "multi_logloss")
lgb_mean_cl <- lgb.train(data = dtrain_lg_mean_cl,params=params,nrounds = 100)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011250 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4811
[LightGBM] [Info] Number of data points in the train set: 16927, number of used features: 21
[LightGBM] [Info] Start training from score -1.585044
[LightGBM] [Info] Start training from score -1.776691
[LightGBM] [Info] Start training from score -1.561962
[LightGBM] [Info] Start training from score -1.362419
[LightGBM] [Info] Start training from score -1.831961

In [37]:
end_time = Sys.time()
time_matrix[3,]=end_time-start_time

In [38]:
end_time-start_time

Time difference of 3.54173 mins

## predict

In [39]:
start_time = Sys.time()

In [40]:
alldatalgb <- lgb.Dataset(data = as.matrix(data))
alldataxgb <- xgb.DMatrix(data = as.matrix(data))

In [41]:
xgbregmin=predict(xgb_min_reg,alldataxgb)
xgbclsmin=predict(xgb_min_cl,alldataxgb)
lgbregmin=predict(lgb_min_reg,as.matrix(data))
lgbclsmin=predict(lgb_min_cl,as.matrix(data))

In [42]:
xgbregmin

    [1]  1.678847075  2.196492195  2.039880276  1.631919146  1.130262017
    [6]  2.234442234  2.126114845  2.578284502  2.777132988  2.360685349
   [11]  1.682183146  2.401282549  2.378574133  2.215666056  1.475599408
   [16]  2.815427780  2.399661064  1.811874747  2.199201822  2.204082966
   [21]  2.125024557  3.154262781  3.232300758  1.692758322  2.916904926
   [26]  2.019187927  1.509433985  3.067646265  1.957460403  1.148835063
   [31]  2.349027157  2.173642635  2.155700207  2.757719755  2.189349174
   [36]  3.188462257  2.609694958  2.777057171  2.036886215  1.686612368
   [41]  1.244007945  1.915075421  2.461247921  2.062518120  1.462778091
   [46]  2.877420187  3.306163311  2.317509651  2.351312876  2.440857410
   [51]  2.260694981  2.439066410  2.217546225  2.264739275  2.285696507
   [56]  1.940544724  1.814587951  2.391540289  2.575481892  3.114255190
   [61]  3.255158186  2.631958723  2.995078087  3.303005695  1.856225252
   [66]  3.689611435  2.753265381  1.856667519  3.024650335  2.929448605
   [71]  1.475754976  3.492564678  2.184723854  2.661376715  1.067652464
   [76]  2.780360222  2.592822790  2.225185871  1.992012978  0.935863733
   [81]  2.990128279  1.530846119  1.148543835  3.524352789  3.719002247
   [86]  1.165849209  2.228123665  1.355759978  1.815532088  4.116433620
   [91]  2.082741499  0.133624762  1.074004292  3.711094856  3.080430269
   [96]  2.979250431  3.889401197  1.866292596  1.740680337  1.941419601
  [101]  1.764821172  2.227084875  1.004523635  3.488415241  1.166857839
  [106]  2.434157133  1.590731621  1.095494270  2.822778702  1.682954192
  [111]  1.573654175  1.504765511  1.885696411  1.910945058  2.060121775
  [116]  2.581387758  2.091354609  1.935963154  1.273712039  3.083402157
  [121]  0.707977951  2.111901522  2.871163845  0.842371166  2.593249559
  [126]  2.438488483  1.497356415  2.723469496  2.237867832  2.501115084
  [131]  3.159856558  3.256636143  3.699127436  2.322740316  2.704833508
  [136]  1.464628816  2.184133530  2.883663893  2.198277473  3.122625589
  [141]  2.552573681  3.463275671  3.653491020  3.877525568  2.178106070
  [146]  3.110078096  3.057132244  2.708776236  2.819230318  2.197490931
  [151]  2.346106291  1.593912601  1.875863671  2.630438566  2.289174318
  [156]  2.104814053  3.286248922  2.718425512  0.310539752  0.783407509
  [161]  0.935169220  1.372096062  1.499936461  0.254771858  1.006731987
  [166]  2.300774336  1.561592698  2.215716124  1.951647758  1.116350174
  [171]  3.182897329  0.233355865  0.606018007  1.752729893  1.259726524
  [176]  1.407585740  2.379384995  0.410636365  2.228292465  1.103285551
  [181]  0.540655136  1.086917520  1.930748701  0.641667366  0.742329836
  [186]  0.365209341  1.703612447  1.441409945  1.257508159  1.203784347
  [191]  1.586059690  1.087009430  1.219825864  1.225595236  2.120196581
  [196]  1.724875808  0.207838327  0.966975272  2.884591579  2.992269754
  [201]  1.532767892  2.828263521  1.598246813  0.626477420  1.518035650
  [206]  2.412412167  2.628880501  1.550460219  3.079468250  2.841194153
  [211]  2.949361801  2.975143194  3.294548512  2.673100948  1.710000277
  [216]  1.905509949  2.288256884  1.082389116  3.071243763  3.241003990
  [221]  3.351795435  3.628067493  3.679234743  2.730233669  3.136658192
  [226]  1.545715451  2.816159487  3.182578087  2.039482594  0.240420237
  [231]  3.433687449  1.025833607  3.773173809  2.710556507  3.320072889
  [236]  3.616073847  0.502567649  2.620654821  2.887051821  2.831637383
  [241]  3.071104050  2.700939894  1.253702164  2.094345093  3.585831642
  [246]  2.745975018  1.050502896  1.661511421  3.029112339  3.574868441
  [251]  2.380366087  2.641563416  3.610710382  2.700274467  2.939825773
  [256]  2.720953703  3.198694706  2.231788158  1.859796047  2.050660849
  [261]  2.886522055  2.987713814  3.288528204  3.438424110  1.811218143
  [266]  2.845331192  2.437747478  3.317812443  2.700883865  2.724989653
  [271]  2.531485319  1.770603538  3.796587944  2.443406582  2.010061979
  [276]  2.957721710  3.358810663  0.539245725  2.653500319  2.100079775
  [281]  2.537770271  3.206579685  3.353412628  2.501023293  3.434404135
  [286]  2.564768791  2.562795639  3.717912912  2.107423544  3.099480867
  [291]  3.557520866  1.602267861  2.594629526  3.358013868  2.414752960
  [296]  3.152308941  0.353583097  2.370705128  2.159629583  2.936874390
  [301]  2.252068520  3.213935614  2.668622255  3.113366365  2.587094069
  [306]  1.762618661  3.208905458  2.210103989  0.465490788  2.613291740
  [311]  2.728455067  2.460024357  0.788592577  0.239255860  3.679245472
  [316]  0.504655242  1.923571229  3.365223646  3.020487309  3.351934910
  [321]  2.194809437  1.396629810  3.091185570  1.967450976  1.681802154
  [326]  3.041853428  3.224653244  1.751540899  3.422482491  1.644327402
  [331]  1.900639534  3.955235720  3.675654411  3.948859930  3.198123455
  [336]  2.163107157  3.425047398  3.308102846  1.454522610  1.998254299
  [341]  3.040747166  3.197265387  3.232882738  1.332456708  2.792967319
  [346]  3.361474991  2.474797487  2.193151236  1.934105635  3.128582954
  [351]  2.921319962  1.088411212  2.704733372  2.704733372  1.282758713
  [356]  2.708151102  2.252237082  2.211669922  1.783697963  2.351230383
  [361]  2.295424461  1.317066312  2.906772852  3.152474165  1.606181741
  [366]  1.728531480  3.351125956  1.700125217  2.809955120  2.891366243
  [371]  2.069789648  2.950969458  1.292933106  3.411980629  2.419440508
  [376]  2.929609060  0.974991083  2.637813807  1.829931140  1.695240617
  [381]  2.420412302  1.131759048  2.815363169  1.733560681  1.783840418
  [386]  1.519326687  2.264237881  2.270503521  2.306775808  3.893589735
  [391]  1.091369510  2.181056023  2.181056023  2.528755188  3.402876616
  [396]  2.575983286  1.238808155  1.238808155  2.533397913  2.910756588
  [401]  2.925534725  3.049972296  2.680242062  2.833053112  2.285369158
  [406]  1.426787734  3.150991678  1.767371893  3.092999458  3.362313509
  [411]  2.973862648  0.778792322  2.417976618  2.086501598  3.380863190
  [416]  1.499563575  0.879643261  3.313572407  2.589228630  1.874491572
  [421]  2.027307034  3.317622662  3.168066502  2.835100412  2.007999659
  [426]  3.168928623  1.781851411  2.872753143  2.578773022  0.825698256
  [431]  1.349162698  2.077785730  2.658269405  3.095628262  3.280820608
  [436]  1.490345836  3.287460566  3.100113153  3.466409445  1.925179124
  [441]  3.425943136  2.951584578  2.373790264  1.988857746  2.571510553
  [446]  1.816948771  2.162623405  1.923957467  2.468930721  3.378570795
  [451]  0.827010393  3.449860334  2.669903517  3.049130678  2.811921597
  [456]  2.424145937  2.424145937  2.998254538  2.392514944  3.200090647
  [461]  2.852227449  3.548261642  3.109457731  2.655074120  2.459054470
  [466]  3.319755554  3.464233160  2.851727724  2.954507828  2.767223358
  [471]  3.345462322  1.467485547  1.498257637  2.049232483  2.762196779
  [476]  1.954578876  2.761590958  2.950694323  2.851616859  2.816678286
  [481]  3.692065477  1.264929771  2.266219378  1.498796821  1.630722284
  [486]  3.058509588  2.795826197  2.175891638  3.109951735  3.116161585
  [491]  3.187179327  2.633152723  3.911752224  0.922748744  0.535831332
  [496]  2.850048304  2.085428953  2.668265820  2.401667595  1.690492511
  [501]  2.450970411  2.532369137  1.565650702  1.945810080  2.798527002
  [506]  3.112551451  1.029706955  2.507689953  1.681169987  2.041772604
  [511]  0.925061226  3.416554451  3.315823317  0.654311538  2.640122175
  [516]  2.815040112  1.166165233  0.984052300  2.069071770  2.180105925
  [521]  1.423430800  3.480624676  3.133267879  2.420820236  1.045736790
  [526]  1.893908620  3.089977264  2.434405565  2.323335648  3.421145678
  [531]  3.308861732  1.297526836  3.458899736  2.877986670  3.858377218
  [536]  3.858377218  2.590849161  1.684156537  2.408609629  2.714551449
  [541]  3.750531673  2.772191286  1.733695388  3.177118778  2.585627556
  [546]  2.198932171  2.076862574  3.381196260  1.835132360  2.203871727
  [551]  2.419945002  3.675570488  1.726925254  2.175816536  1.178644419
  [556]  3.640173674  2.899143219  2.547386169  2.084115982  2.543905735
  [561]  2.578343153  2.173691750  2.255324602  2.344261885  3.050529957
  [566]  2.179341793  2.927173853  1.741835713  3.522750854  1.845504165
  [571]  1.435200095  3.645009279  2.525611639  2.877266407  2.726382971
  [576]  1.964272261  3.453336239  2.043334723  2.803897142  2.825522423
  [581]  2.944076777  2.031012058  2.199075699  2.582563400  2.725923538
  [586]  2.467744827  2.711486101  3.398774862  3.400194168  1.925121188
  [591]  1.971246243  2.792697430  2.267226696  3.041473150  2.947118759
  [596]  3.336040974  2.704295635  3.338751793  2.105109692  1.407338977
  [601]  3.253685713  2.614677668  2.165715456  2.612656832  1.563670874
  [606]  3.424890041  2.407740116  2.088735580  2.126902819  1.925770760
  [611]  2.091199398  1.428211451  2.251255512  2.403992176  1.791437149
  [616]  0.794919848  1.901774883  2.390647650  2.436455011  2.004762411
  [621]  2.270700932  2.575707674  2.401741982  2.984475851  0.438847125
  [626]  2.452627897  1.564960122  2.016460896  2.677411318  2.089024782
  [631]  1.615197897  2.631664515  2.316806555  3.443762779  2.985448122
  [636]  1.357565999  1.063386321  2.396008492  1.875004053  2.249699593
  [641]  1.906534076  2.326405525  2.326405525  1.793379784  1.862963319
  [646]  2.985581398  2.112816334  1.136340499  2.842655420  2.959805965
  [651]  1.416726947  2.127514601  1.068315268  2.730674505  3.043022871
  [656]  2.692427397  1.866351724  1.245318890  2.303533316  0.685077131
  [661]  2.698557854  2.489246607  2.633739710  1.167478561  1.548366427
  [666]  3.039990425  2.193591595  3.059571981  3.094170809  3.100789547
  [671]  1.466287732  2.303473234  2.216030836  1.926579595  1.726720691
  [676]  2.955720186  1.670425534  1.959735274  2.550841570  1.141299129
  [681]  2.450186014  1.530469656  2.204881907  2.505677223  2.103065491
  [686]  1.794468284  2.087959051  2.099544525  2.623759031  3.163309813
  [691]  2.191560030  2.230315685  3.317523003  2.992837191  2.992837191
  [696]  2.847700357  2.734492540  2.416657448  2.416657448  1.086028934
  [701]  1.319279313  1.440288782  1.959146857  1.436438084  2.227434874
  [706]  2.428884745  2.130987883  3.744985104  0.952189445  3.196945429
  [711]  0.671914577  3.155893803  2.740202427  1.185836673  2.137942076
  [716]  2.616623163  2.354929924  2.041917086  1.278793931  1.911915421
  [721]  2.856499910  3.553273201  1.920465350  1.859226942  2.229040384
  [726]  2.676839113  2.140294552  2.657234192  2.458568096  2.413944483
  [731]  1.724110484  2.851218462  1.769476295  3.262615204  1.556226015
  [736]  2.335871935  2.205661774  2.518517256  2.197673798  3.189017773
  [741]  2.357416630  2.560379744  3.264590979  1.623268604  2.788496733
  [746]  2.387382269  2.537700653  1.629910827  1.308196783  2.815057993
  [751]  2.030817509  2.320113420  3.065552235  1.404832840  2.793597698
  [756]  2.204606771  1.860468626  1.786656857  1.997554064  1.802592397
  [761]  1.817595363  1.360644341  3.782995462  1.492577314  2.029653549
  [766]  2.732477903  2.041017771  2.296066284  1.891998649  2.643465281
  [771]  2.854423046  2.425889015  3.185119390  2.194024801  2.316039085
  [776]  2.082211494  2.414015293  1.864628792  3.148417234  1.648174644
  [781]  2.403064966  2.014897108  1.785186052  1.651034713  2.242982388
  [786]  2.688873529  1.752417922  1.903253198  2.648509741  2.567404985
  [791]  0.601308942  1.999863386  3.206782341  1.814589739  3.046705723
  [796]  1.999217033  1.972123981  3.135524988  2.907166958  3.195186138
  [801]  1.853234529  2.256892681  1.234175682  3.435484171  2.647720814
  [806]  2.353340149  1.480987787  0.449561834  0.449913263 -0.578684568
  [811]  0.312750608  1.179486036  1.351862788  1.904000640  2.926572323
  [816]  1.525581241  2.046371698  1.767532229  2.423379898  2.082055330
  [821]  2.727019072  3.096993923  2.512652874  2.371250629  3.159647703
  [826]  3.396662712  3.027423859  2.324668646  1.962271810  2.253754616
  [831]  3.174205542  2.177421331  2.218183279  2.216229916  1.557943821
  [836]  0.762242436  1.750438333  3.594293118  3.188277006  2.676695347
  [841]  1.471642971  1.715547442  3.016321421  0.660966039  3.253381014
  [846]  2.624215364  2.753270626  3.289360046  2.133312702  3.010421753
  [851]  1.569258451  2.712769508  2.546122074  1.833722591  2.646674156
  [856]  1.786986589  0.659367502  2.508356333  2.508356333  2.947947502
  [861]  3.319239140  1.912090182  2.724962234  3.176068306  1.814201832
  [866]  2.114962339  1.896359324  1.769976974  3.307473660  1.459620476
  [871]  3.099565268  2.655929327  1.986418843  1.951441765  2.681960344
  [876]  1.925182700  3.329041481  1.357949734  2.466256380  3.199317217
  [881]  1.870404005  2.618380547  1.424297452  1.368732810  2.377668619
  [886]  2.306374788  0.794246078  2.722008467  2.010493279  2.165204763
  [891]  3.501285791  1.972235441  2.805655718  1.879527450  1.724274039
  [896]  2.101254463  0.682188511  1.788728476  3.292932510  2.217777729
  [901]  2.689832687  2.281563282  1.223805666  2.169768095  2.812508583
  [906]  1.964474916  2.232825756  1.519475222  3.552725792  3.097410440
  [911]  2.123835802  3.440990686  1.176335812  2.528280497  0.805176079
  [916]  1.628047109  2.712837219  2.328056335  2.543358326  1.176707506
  [921]  3.113856077  2.124648571  3.063825369  2.973006725  2.016867638
  [926]  3.744775772  1.507864952  2.295555115  2.903968573  2.509852648
  [931]  2.905027628  1.620442748  2.149687529  1.236784458  2.960821390
  [936]  3.803217888  3.610402822  3.977044344  2.096761465  1.658277392
  [941]  3.010386467  1.974941373  1.196652889  2.495008230  2.322736502
  [946]  3.307689667  3.041835546  2.190699816  2.195403576  2.253844976
  [951]  3.351677656  1.778567433  2.905235291  2.557164907  3.270958900
  [956]  2.126097441  1.512524486  2.296372652  3.430428743  2.564437628
  [961]  2.404006004  2.218337536  1.655083179  1.516533613  1.976997852
  [966]  2.518887281  1.702486157  2.267475605  2.180338860  1.286859632
  [971]  0.728556514  1.985549808  2.833563089  1.768946648  3.741004944
  [976]  3.187136412  0.822770357  2.889576197  1.716126442  2.076308489
  [981]  1.793953538  2.968513012  2.549299240  1.765258431  3.015428066
  [986]  2.277863503  1.419120908  2.150037050  1.686527967  2.153281927
  [991]  1.658594012  1.713958144  1.743675590  2.882307768  1.974587679
  [996]  3.083931923  2.899919271  1.832128406  2.186695337  1.899109960
 [1001]  3.545704365  2.385583878  2.515286446  3.172579765  2.579014540
 [1006]  1.439860940  2.118657589  2.503923178  2.197103262  2.669454575
 [1011]  1.051791787  2.564516068  3.282839775  1.951771617  2.608274937
 [1016]  1.940823078  3.510423660  3.009966850  3.140456676  2.311967850
 [1021]  2.158562422  2.659599304  2.725303411  1.453188419  2.314541340
 [1026]  0.718992949  0.718992949  1.595811129  2.403527737  1.882605791
 [1031]  1.870687246  2.905127048  1.513534188  2.674452543  1.079195619
 [1036]  1.368064761  3.045917511  2.740158319  2.009490490  3.041962147
 [1041]  3.389498234  1.020337224  3.709781408  2.511853456  2.752840996
 [1046]  1.781604171  2.469737768  1.583183765  1.776613593  1.012261152
 [1051]  3.822936773  2.636237144  3.374029160  2.822021723  2.020501614
 [1056]  2.142049313  2.478695154  2.752164841  2.972232103  2.744770050
 [1061]  2.516716003  2.659762859  1.897979975  3.043246269  3.043246269
 [1066]  1.690711975  2.642015696  2.138736486  2.469473362  2.065080881
 [1071]  0.846519709  1.636517882  1.882984638  2.404183626  2.643454313
 [1076]  1.962148905  1.962148905  2.277253628  1.609698534  2.715096951
 [1081]  2.335663557  2.276582718  1.061633825  2.693873405  2.642506838
 [1086]  2.415419817  3.158080101  2.046599388  2.858557224  1.719674110
 [1091]  0.956217647  2.568090200  1.312227964  0.910891116  0.414537042
 [1096]  2.776495218  2.713862896  1.941401005  1.644758582  2.209397793
 [1101]  2.294807434  1.112384200  2.158010483  3.016575575  1.800563812
 [1106]  2.223378897  2.478226662  2.251136541  1.775629044  2.357786655
 [1111]  1.594395757  2.815840483  2.542754173  3.104013205  2.439802647
 [1116]  2.767967939  2.532048941  2.450108767  2.454682350  1.835478663
 [1121]  2.859092712  2.344400883  1.645629525  1.168188691  1.222029090
 [1126]  1.691529393  2.348575115  2.502772093  3.770279408  3.255882502
 [1131]  2.220714092  1.590624928  2.851392269  3.487240076  3.362718105
 [1136]  2.547181368  2.473565102  3.359745741  1.990997791  3.404323816
 [1141]  2.216375589  2.472102642  0.725360811  2.507565498  2.507565498
 [1146]  2.109264374  2.470870018  0.050038569  3.139619350  3.002938032
 [1151]  2.819219589  1.320643425  2.485822678  2.799655199  2.032943487
 [1156]  1.324900031  2.208208561  2.322946548  1.557709098  1.087028265
 [1161]  1.787781239  2.101559401  1.373004556  3.055217266  2.541726589
 [1166]  2.072840214  3.112946272  1.597748756  1.874157310  3.431395054
 [1171]  3.360648155  3.049710035  3.352478981  3.634477854  2.914889812
 [1176]  2.966998100  2.234020233  3.070006609  3.553874016  3.780643225
 [1181]  3.372084379  3.220957994  2.741302490  2.801042318  3.215749979
 [1186]  3.280662775  3.104552746  2.130470753  2.006519556  2.728774548
 [1191]  3.570364952  1.183513641  3.507880688  3.335072279  1.295994163
 [1196]  0.987987459  2.758460999  1.539696813  2.826683283  2.436991215
 [1201]  3.172966719  3.639501572  2.028966904  3.585853815  2.381219864
 [1206]  3.375766039  3.562652826  2.200897217  3.180337667  2.750825405
 [1211]  2.552805185  2.675471067  1.573022604  1.050421953  1.754820347
 [1216]  3.625741959  2.985464334  3.099034786  2.855768681  2.964458942
 [1221]  3.267739534  1.862207055  1.842758417  2.566136122  1.637582421
 [1226]  3.071624041  2.228186131  2.715735435  2.313370705  1.630901337
 [1231]  2.708521128  3.002979517  1.653534532  1.653534532  0.347544789
 [1236]  0.347544789  0.162574872  2.463913441  2.463913441  1.162199497
 [1241]  3.237400055  2.694637537  2.872794628  1.796247959  1.641675472
 [1246]  1.728071690  2.936401844  1.712480068  3.516314983  2.008326292
 [1251]  2.068911076  2.846620798  2.401870012  1.158858061  3.091559649
 [1256]  2.179061413  1.841652870  2.629752636  2.886848450  1.769219398
 [1261]  2.910371065  2.730361462  3.567836285  2.413105726  1.696115494
 [1266]  3.112304449  2.145619392  2.043979168  3.185339689  2.477998734
 [1271]  2.256731033  3.167830706  3.068032503  1.940365791  3.492740154
 [1276]  2.626575947  4.142889023  2.715015411  3.474730253  2.755541801
 [1281]  3.279326200  2.418291569  2.732125044  2.191287756  2.463767290
 [1286]  2.662055254  3.267516136  2.860987425  1.812595248  2.374577761
 [1291]  2.743017673  2.373267651  3.328378201  2.627016544  3.645590067
 [1296]  2.776607990  3.194588661  2.657282352  2.585737467  1.355781913
 [1301]  1.874957681  0.929457426  2.920731783  3.025530338  1.665770888
 [1306]  1.763545394  2.473157883  1.901721954  2.492615700  2.154267788
 [1311]  2.206166029  1.425272226  3.233673096  1.991184711  1.973265648
 [1316]  2.540058613  1.696145177  3.151988029  2.939815044  2.453538179
 [1321]  2.933940887  1.771678090  1.904912114  2.783109188  3.581990004
 [1326]  3.625951052  2.819887161  2.147195101  1.430770993  1.430770993
 [1331]  2.753499985  2.028546095  3.335844755  2.743499279  2.146803141
 [1336]  2.644937992  2.094418526  1.795612216  3.557726622  2.434913158
 [1341]  2.533797026  2.266581059  2.431607485  2.168453932  2.663742065
 [1346]  2.507473230  2.553383350  1.405395746  2.341739178  3.001531839
 [1351]  3.122980595  1.917207241  3.785426140  3.177493095  3.238049746
 [1356]  3.186640263  3.277383089  1.786385417  2.532794476  2.217838287
 [1361]  2.566080332  2.366293907  2.506801128  2.287997246  3.519566059

In [43]:
xgbclsmin

    [1] 2 2 2 2 0 4 4 4 4 4 0 1 0 3 4 4 4 2 2 4 0 4 4 1 4 2 3 4 3 0 3 4 0 4 2 4
   [37] 4 3 4 0 0 4 0 4 1 4 4 4 3 3 1 3 1 0 0 4 0 3 4 4 3 2 0 3 1 4 2 2 4 4 2 4
   [73] 2 4 0 4 4 4 0 0 3 1 4 4 4 0 4 3 0 4 1 0 0 4 4 4 4 3 2 1 2 4 0 4 0 3 1 1
  [109] 3 0 4 4 2 0 0 3 0 2 0 4 0 4 4 0 4 0 0 3 3 4 3 4 4 2 4 0 2 3 4 3 2 4 4 4
  [145] 2 4 4 3 4 2 0 1 2 3 4 3 4 3 0 0 0 2 0 0 0 4 1 4 4 2 4 0 0 1 0 0 3 0 4 1
  [181] 0 0 0 0 0 0 1 0 2 0 0 1 0 0 2 2 0 1 3 4 1 4 4 4 0 3 4 1 4 4 4 2 4 4 1 3
  [217] 4 0 3 4 4 4 4 3 4 4 4 4 2 0 4 1 4 4 4 4 0 3 4 4 4 4 1 4 4 4 1 1 4 4 4 4
  [253] 4 4 3 4 4 4 3 4 4 4 4 4 4 4 3 4 4 4 3 4 4 3 3 4 4 0 4 3 3 4 4 4 4 3 4 4
  [289] 3 4 4 1 4 4 3 3 0 3 2 3 3 4 3 4 3 4 4 2 0 4 3 4 0 0 4 0 0 4 3 4 3 0 4 3
  [325] 0 4 3 1 4 0 3 4 4 4 3 4 4 4 4 2 4 4 3 1 4 4 3 0 0 4 4 1 3 3 1 2 4 4 1 2
  [361] 2 1 0 3 1 4 4 2 4 4 4 4 1 4 4 2 3 3 2 2 2 0 4 0 1 0 2 0 4 4 0 2 3 3 4 0
  [397] 0 0 4 2 4 2 2 4 4 0 4 4 4 4 4 0 4 4 4 0 0 4 3 0 4 4 3 4 3 4 1 4 3 1 1 4
  [433] 2 4 4 4 4 4 4 4 4 2 1 2 1 4 0 4 2 4 0 4 4 4 4 2 4 3 1 4 2 4 4 4 1 2 4 3
  [469] 4 2 4 1 4 4 4 4 4 4 4 4 4 3 4 1 1 4 4 4 4 4 4 4 4 0 0 3 0 4 4 1 4 4 1 1
  [505] 4 4 4 1 4 4 0 4 4 0 4 4 1 0 2 1 0 4 4 4 1 2 4 4 4 4 4 4 4 4 4 4 4 2 4 3
  [541] 4 3 2 4 4 2 4 4 3 4 2 4 1 4 0 4 4 4 1 2 4 2 1 4 4 3 4 2 4 4 2 4 4 3 4 3
  [577] 0 1 1 3 4 0 2 3 4 4 4 4 4 4 1 4 2 4 4 4 4 4 1 0 4 4 2 4 0 4 4 3 4 4 0 4
  [613] 0 3 0 0 4 3 2 2 0 4 1 4 0 4 0 4 4 4 1 3 4 4 4 1 1 4 4 4 2 4 4 1 1 4 0 0
  [649] 3 4 1 4 0 4 4 4 4 4 4 0 4 2 4 0 0 3 4 4 4 4 1 2 1 0 1 4 1 1 0 1 4 1 2 4
  [685] 4 4 4 1 3 3 4 1 4 4 4 4 4 3 1 4 1 0 0 0 4 4 2 4 4 4 0 4 4 0 4 4 4 1 0 2
  [721] 4 4 4 1 1 4 4 4 4 4 3 4 1 4 1 3 2 4 4 4 4 4 4 0 4 1 4 1 0 4 2 2 3 1 3 0
  [757] 2 4 3 0 1 4 4 0 4 3 4 4 3 4 4 2 4 4 4 4 4 1 4 1 2 4 4 4 4 2 0 0 3 4 1 1
  [793] 4 1 3 1 1 4 3 4 1 4 0 4 1 4 1 0 0 1 0 0 1 1 4 1 4 1 0 3 4 3 1 4 4 4 3 4
  [829] 1 4 4 2 2 4 0 0 1 4 4 4 0 0 4 0 4 4 2 4 2 4 2 4 4 4 4 4 1 2 2 4 4 4 2 4
  [865] 4 4 4 4 4 1 4 4 2 3 4 4 4 0 0 4 1 4 0 0 4 4 0 4 4 4 4 4 4 3 3 1 0 0 4 4
  [901] 4 4 0 3 4 4 3 1 4 4 2 4 0 1 4 1 3 3 4 3 4 3 4 4 1 4 1 4 3 4 1 1 3 0 4 4
  [937] 4 4 1 4 4 1 0 4 4 4 4 1 2 4 4 4 4 4 4 1 1 4 4 4 4 3 0 1 2 4 0 4 4 3 0 4
  [973] 4 4 4 4 0 4 1 2 4 4 4 1 4 4 1 0 4 4 2 0 4 4 2 4 3 4 4 4 4 4 4 4 2 0 1 4
 [1009] 4 4 0 2 4 0 4 4 4 4 4 4 4 4 1 0 4 0 0 1 4 0 4 4 2 4 1 0 3 4 4 4 4 0 4 4
 [1045] 3 3 4 4 4 0 4 2 4 3 2 2 2 3 4 2 3 4 2 4 4 0 4 0 4 2 0 1 1 3 3 2 2 4 1 4
 [1081] 4 4 0 4 3 4 4 4 4 0 0 3 0 0 0 4 4 2 0 3 2 4 4 4 0 0 4 4 1 4 0 4 3 4 2 4
 [1117] 4 4 4 0 4 4 1 0 1 0 4 2 4 4 4 4 2 4 4 1 1 4 1 4 3 3 0 0 0 3 3 0 4 4 4 1
 [1153] 2 4 1 1 4 4 1 2 1 1 1 2 4 1 4 1 3 4 4 4 4 4 3 4 3 4 4 4 4 4 3 3 4 4 4 4
 [1189] 1 4 4 1 4 4 1 0 4 1 4 4 3 4 1 4 3 3 4 1 4 4 3 3 0 1 0 4 3 3 4 4 4 4 1 4
 [1225] 1 4 1 4 4 1 0 4 0 0 0 0 0 4 4 0 4 4 4 3 3 1 4 4 4 1 2 4 4 1 4 4 0 4 4 3
 [1261] 4 4 4 4 2 3 1 2 4 1 1 4 4 2 4 4 4 3 4 4 4 2 4 4 3 3 4 4 2 4 3 4 4 4 4 4
 [1297] 4 1 4 2 4 0 4 4 1 4 2 2 4 1 0 0 4 0 4 3 1 1 4 0 4 2 4 4 4 4 4 0 0 0 4 1
 [1333] 4 4 4 4 2 1 4 4 3 4 4 4 4 4 3 4 3 4 4 2 4 4 3 4 4 1 3 1 1 2 3 4 4 3 2 4
 [1369] 2 2 3 4 4 0 4 4 4 4 4 4 4 4 4 4 4 4 1 4 4 4 0 4 1 4 3 4 2 0 2 1 2 4 4 1
 [1405] 4 4 2 3 4 1 4 3 4 1 4 4 4 4 4 4 4 4 1 1 3 2 2 4 2 4 4 4 4 0 4 3 3 4 4 4
 [1441] 4 4 4 2 2 4 4 4 4 4 4 4 1 4 3 4 4 4 4 0 2 1 4 4 2 4 4 1 4 1 4 4 4 1 2 4
 [1477] 4 4 4 4 3 0 0 0 0 1 3 0 2 3 0 3 3 4 1 3 4 0 4 4 4 4 1 4 1 2 4 0 4 4 4 0
 [1513] 0 4 4 0 0 2 0 4 4 4 4 0 4 4 1 4 0 4 0 0 4 0 1 1 4 2 4 0 2 3 1 0 1 3 1 4
 [1549] 3 0 1 2 4 0 2 0 0 1 4 2 1 1 4 0 4 4 1 3 2 3 2 4 1 1 4 2 4 1 1 0 1 1 2 4
 [1585] 4 1 4 4 0 2 0 4 4 1 2 3 1 0 4 3 3 3 1 2 0 3 1 4 4 0 0 4 0 4 3 2 2 1 3 3
 [1621] 2 0 3 3 2 3 2 4 3 0 4 4 2 2 4 4 4 2 1 4 3 3 4 2 4 3 0 1 3 3 0 0 4 3 3 1
 [1657] 0 1 3 4 4 3 3 3 4 3 4 4 3 0 4 2 4 1 0 1 3 1 4 1 4 0 4 3 4 4 3 4 0 0 4 4
 [1693] 4 1 1 1 0 4 3 0 1 3 4 3 4 4 0 4 3 1 0 3 4 1 0 0 4 0 1 1 4 1 4 3 1 2 2 1
 [1729] 1 1 4 4 4 0 4 4 2 0 4 3 2 2 4 0 2 4 4 4 4 4 3 3 4 3 4 3 3 4 1 4 3 4 1 4
 [1765] 4 4 0 3 3 4 2 4 3 4 4 3 3 3 3 4 4 4 4 0 3 4 3 1 3 3 3 2 3 3 3 4 4 3 4 4
 [1801] 4 1 4 4 1 0 0 0 4 0 0 1 3 4 4 4 4 4 0 4 4 3 4 4 4 4 4 3 4 1 4 0 4 0 0 3
 [1837] 3 0 0 4 4 4 4 0 2 3 4 4 0 1 3 0 0 4 2 0 4 4 4 0 4 4 4 4 1 4 0 3 4 3 4 3
 [1873] 3 0 0 1 0 4 3 1 0 4 4 4 4 4 0 4 3 0 4 4 4 3 4 0 1 1 3 4 1 2 4 3 4 4 4 4
 [1909] 0 4 4 0 4 4 2 4 4 1 4 3 3 4 0 4 4 4 2 4 3 3 4 3 1 3 3 3 2 2 3 4 3 3 4 2
 [1945] 2 4 4 4 4 4 4 4 3 3 1 4 4 0 1 4 4 4 4 4 4 4 3 4 4 3 4 4 2 0 4 4 4 4 4 4
 [1981] 3 2 1 4 4 4 4 4 0 0 4 4 4 4 4 4 4 1 0 0 1 4 4 2 4 4 4 2 4 4 4 0 4 0 4 1
 [2017] 4 4 4 0 3 4 3 1 0 4 0 3 1 4 4 4 3 4 0 4 3 3 1 3 3 3 0 0 0 1 4 0 1 4 0 4
 [2053] 0 4 3 3 4 2 3 2 4 4 3 4 3 4 4 2 4 4 3 4 4 4 4 4 3 3 4 4 4 4 4 3 4 4 4 4
 [2089] 4 4 2 4 3 4 4 4 4 4 4 2 4 4 4 4 0 4 4 4 4 3 4 4 4 4 4 3 0 4 2 4 4 4 3 3
 [2125] 4 4 4 4 4 0 3 4 1 0 1 4 4 0 4 0 0 0 1 4 1 0 4 4 0 2 1 4 4 4 4 4 4 4 4 4
 [2161] 4 3 3 4 4 3 0 4 4 3 4 4 3 4 4 4 4 4 4 1 2 3 1 3 3 4 4 4 0 4 4 4 4 2 4 0
 [2197] 3 1 4 0 2 1 3 3 4 4 4 0 4 1 3 1 0 4 4 3 3 4 3 1 4 4 1 4 4 4 4 4 3 3 4 4
 [2233] 0 0 4 4 1 4 0 0 4 4 4 4 4 4 4 4 4 4 4 4 2 1 3 4 3 4 3 4 3 3 4 0 4 3 4 0
 [2269] 0 0 2 1 0 1 1 4 1 1 3 4 4 2 2 3 4 4 4 0 0 2 4 4 0 0 4 0 3 4 4 1 4 4 4 4
 [2305] 4 1 3 4 4 3 4 4 4 4 4 1 4 4 1 4 4 4 3 0 4 1 0 1 4 4 4 4 4 4 4 2 3 0 4 4
 [2341] 4 4 3 2 4 4 4 4 0 4 3 4 3 4 4 4 4 4 4 4 0 3 4 2 4 3 4 4 3 3 4 4 4 4 4 3
 [2377] 4 4 4 4 4 4 3 4 0 3 4 3 4 0 0 4 3 4 4 4 4 4 3 4 0 4 3 4 4 4 4 0 4 4 4 4
 [2413] 4 1 0 4 4 4 4 4 0 4 2 3 4 3 4 0 0 4 4 4 4 4 3 1 3 4 3 4 4 4 2 4 3 4 4 4
 [2449] 4 4 4 4 3 4 4 0 0 1 4 1 4 3 4 4 1 0 4 4 4 3 4 4 4 4 4 4 4 4 4 0 4 4 4 3
 [2485] 4 4 4 4 4 3 1 3 4 4 3 2 4 4 4 4 4 4 4 4 4 4 4 3 4 4 4 3 4 4 4 4 3 4 1 3
 [2521] 3 1 4 4 4 4 4 0 4 4 4 4 4 2 4 4 4 3 4 2 4 4 2 4 3 4 3 4 4 4 4 4 0 4 3 3
 [2557] 4 4 4 3 4 4 4 4 4 4 3 4 4 4 3 4 4 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 2
 [2593] 4 4 4 3 4 1 4 4 1 4 3 3 2 1 4 2 2 4 2 4 4 4 3 4 2 4 4 4 4 3 3 3 3 1 4 4
 [2629] 4 4 4 1 1 4 3 2 2 2 4 3 3 4 4 4 1 2 3 4 4 4 4 4 4 4 4 4 3 4 2 4 4 4 4 4
 [2665] 1 4 4 4 3 4 0 1 2 1 4 3 4 3 2 4 1 4 3 4 4 4 3 4 3 4 3 4 4 4 0 4 4 4 4 4
 [2701] 2 3 0 3 4 4 3 4 3 4 4 4 0 4 0 4 4 4 4 3 4 4 4 1 4 4 4 4 4 4 4 4 3 4 4 2
 [2737] 4 4 2 4 4 4 4 4 4 4 1 4 4 4 3 4 2 2 3 4 4 4 4 4 4 4 4 4 4 1 4 4 4 0 0 4
 [2773] 4 0 4 4 3 4 4 4 3 4 4 4 4 0 0 4 4 4 4 3 0 4 4 4 4 3 4 4 1 4 0 4 0 4 4 3
 [2809] 4 4 4 4 4 4 2 4 4 3 3 4 4 4 4 3 2 3 4 4 3 4 2 4 1 4 4 4 0 4 4 4 4 4 0 2
 [2845] 4 4 4 4 4 4 4 4 4 4 3 3 2 3 4 3 4 2 2 4 4 4 4 4 4 2 4 0 3 2 4 4 3 4 4 4
 [2881] 3 4 4 4 4 3 4 4 1 4 4 2 2 4 2 4 4 4 3 4 3 4 4 4 4 4 4 4 4 1 4 4 4 4 3 4
 [2917] 4 3 0 4 4 4 3 4 4 0 2 2 4 4 4 4 4 4 4 1 4 4 3 3 4 4 4 1 0 4 4 4 3 4 4 4
 [2953] 4 4 4 4 4 4 3 4 4 0 3 4 4 3 1 0 4 3 4 4 4 1 3 3 3 4 0 3 3 0 1 4 4 3 3 0
 [2989] 4 3 4 4 4 4 4 4 3 4 4 4 0 3 2 4 4 3 4 4 1 4 3 0 3 4 1 4 4 4 4 4 4 4 0 4
 [3025] 4 4 4 4 4 2 4 4 1 4 4 4 4 4 4 3 0 4 4 4 3 4 3 4 4 4 4 3 2 3 4 4 4 4 4 4
 [3061] 4 4 4 3 4 4 4 4 4 3 4 4 3 4 4 4 4 4 3 4 3 4 3 4 4 3 4 3 4 3 4 4 4 4 4 4
 [3097] 4 4 1 0 3 2 4 2 4 4 0 0 0 1 4 3 3 0 3 3 4 0 0 0 4 0 4 0 2 3 4 4 3 0 4 4
 [3133] 4 4 3 2 4 4 4 4 3 2 4 4 4 0 1 4 0 4 4 4 0 4 0 4 0 2 2 2 2 2 3 4 4 4 2 3
 [3169] 3 4 0 4 3 4 4 4 3 4 4 0 3 0 2 4 2 4 2 3 4 4 0 2 3 4 4 0 3 4 4 4 4 4 3 1
 [3205] 3 3 0 4 4 3 3 4 4 4 4 4 3 4 2 3 3 4 4 3 0 4 4 4 2 4 1 0 0 2 0 4 2 2 1 4
 [3241] 3 4 4 1 3 4 4 4 4 4 4 4 4 4 3 1 4 2 4 3 3 4 4 4 4 4 4 4 0 4 4 4 4 3 4 4
 [3277] 4 4 4 4 4 3 3 4 4 4 4 4 1 4 4 3 4 4 4 4 4 4 4 3 1 4 4 1 4 3 3 1 1 3 3 1
 [3313] 3 4 4 1 1 2 1 4 1 4 0 4 0 0 2 1 1 1 4 3 0 4 1 0 2 4 3 0 1 4 3 4 0 4 4 1
 [3349] 4 4 4 4 4 4 4 2 0 4 4 4 4 4 4 3 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4
 [3385] 4 4 4 4 0 4 0 4 2 4 1 4 1 1 4 0 4 3 0 4 1 1 4 4 1 1 4 4 4 4 4 3 4 3 4 4
 [3421] 2 4 4 2 3 2 1 4 1 4 3 4 4 4 3 1 2 4 3 2 3 0 3 4 2 2 4 3 2 1 2 2 3 1 1 3
 [3457] 4 3 3 4 4 4 4 4 4 4 4 4 4 3 4 3 4 4 4 3 4 1 4 4 4 4 4 4 4 3 4 4 4 3 4 4
 [3493] 2 3 3 3 4 4 3 0 3 2 3 2 1 2 1 2 3 4 4 0 4 4 4 4 4 4 4 1 2 1 1 4 2 0 4 3
 [3529] 4 4 3 4 3 4 4 4 4 4 3 4 1 3 0 4 4 4 4 3 3 4 3 3 3 3 4 3 4 4 4 4 4 4 4 4
 [3565] 4 4 4 4 4 4 4 4 4 4 4 3 4 0 1 3 4 4 3 3 0 3 4 0 4 4 0 0 4 3 1 4 4 4 3 4
 [3601] 4 4 4 3 2 4 2 4 4 4 4 4 4 4 0 4 4 1 0 2 2 3 3 4 2 4 4 0 4 4 2 4 4 3 4 0
 [3637] 0 2 4 1 4 0 4 0 4 0 4 3 1 4 0 3 3 1 4 3 4 4 2 4 4 4 3 4 4 4 4 3 4 1 4 3
 [3673] 4 4 4 4 0 3 2 4 3 4 4 4 4 3 4 4 4 3 1 4 4 4 4 3 4 0 4 1 0 0 4 4 3 4 4 4
 [3709] 3 4 4 4 4 4 3 3 4 3 0 4 4 4 4 4 4 4 4 4 4 3 4 4 4 4 4 3 4 4 3 4 4 4 4 3
 [3745] 3 3 3 0 3 0 1 2 2 3 3 4 3 0 3 3 0 4 4 0 3 4 4 4 4 4 4 4 4 4 4 4 4 3 4 3
 [3781] 1 0 3 4 4 2 4 3 4 4 4 3 4 3 4 4 4 4 4 4 4 4 1 4 3 3 4 4 4 4 4 4 4 4 4 3
 [3817] 0 4 4 4 4 2 1 3 4 3 3 4 4 4 4 2 4 2 2 3 4 4 4 3 3 2 3 3 4 4 4 2 4 4 4 4
 [3853] 2 2 4 4 4 4 4 4 4 4 2 4 4 4 0 4 4 2 4 4 3 4 1 3 3 4 4 4 3 4 4 4 3 4 3 4
 [3889] 4 4 4 3 4 4 3 3 4 3 4 4 3 4 3 4 1 4 3 3 2 3 3 4 4 3 4 2 2 4 4 4 4 1 3 3
 [3925] 4 4 4 4 3 4 4 4 4 3 4 4 4 3 4 4 4 4 0 4 4 2 4 4 3 1 4 3 4 4 4 1 4 3 4 4
 [3961] 4 4 4 4 3 3 4 4 4 4 3 4 4 3 3 3 4 4 3 3 4 2 4 4 3 4 3 4 4 4 4 3 3 3 4 3
 [3997] 4 4 3 4 4 3 4 3 4 3 2 4 4 4 3 4 3 4 3 4 3 4 1 4 4 3 4 3 4 4 4 0 4 2 2 3
 [4033] 4 3 3 4 3 3 1 3 3 4 3 4 4 3 3 3 3 4 4 4 3 0 4 3 3 4 3 3 3 4 3 4 4 2 1 3
 [4069] 4 3 1 4 3 3 3 4 4 3 4 3 4 4 4 4 3 3 3 4 3 3 3 4 3 4 4 1 4 4 4 4 2 4 4 3
 [4105] 4 4 4 3 4 4 3 4 4 4 4 2 4 4 1 3 0 1 2 3 3 3 1 3 3 3 3 0 1 1 1 3 4 4 3 4
 [4141] 4 4 4 4 4 4 4 4 3 4 3 4 4 4 4 1 4 0 0 1 1 0 0 1 0 0 3 3 1 0 0 0 1 3 3 1
 [4177] 4 0 1 1 1 4 0 3 3 1 3 1 3 3 0 0 3 4 4 1 1 0 2 2 2 1 0 3 4 0 4 4 3 4 3 0
 [4213] 0 0 4 4 3 2 3 4 3 4 4 3 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 3 3 4 3 4 4 4 4
 [4249] 4 4 4 3 0 3 3 2 0 2 0 2 2 3 0 3 3 3 0 3 3 3 3 2 2 3 1 2 3 4 4 4 4 3 1 3
 [4285] 4 1 3 4 3 4 4 3 4 4 4 3 1 4 4 3 3 4 4 0 2 3 1 1 3 4 4 1 4 3 3 3 4 4 2 4
 [4321] 3 4 4 3 2 1 4 2 4 3 4 4 2 4 1 4 3 3 4 4 3 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4
 [4357] 4 4 3 3 4 4 4 3 4 4 3 4 2 4 2 3 3 4 3 4 4 3 3 4 2 4 4 4 3 4 4 3 4 4 4 4
 [4393] 3 4 4 4 4 4 3 4 4 4 4 4 4 3 3 4 4 4 3 3 3 4 2 3 1 4 2 1 0 4 3 3 4 4 4 4
 [4429] 4 4 4 4 2 0 2 1 3 4 4 4 3 3 0 0 0 3 3 0 0 3 0 0 0 0 3 4 0 2 0 0 0 3 0 1
 [4465] 0 0 1 2 1 1 3 0 0 2 3 1 0 1 2 4 2 0 2 2 2 0 4 4 4 1 4 3 4 0 4 4 4 4 4 4
 [4501] 4 4 3 4 4 4 4 4 4 3 4 4 4 4 0 0 0 2 0 3 4 4 1 0 0 2 1 0 0 0 0 3 1 2 3 3
 [4537] 3 4 3 3 0 3 0 2 3 3 3 0 1 0 1 0 3 2 1 0 1 1 3 4 4 0 0 4 3 1 4 1 3 4 3 4
 [4573] 4 4 4 2 1 2 4 3 4 4 2 4 4 4 3 3 4 4 4 1 1 2 3 4 0 4 4 2 4 4 0 4 4 4 3 4
 [4609] 3 1 4 3 4 2 4 1 4 4 4 4 4 3 3 4 4 3 4 4 4 3 0 4 4 4 0 4 4 4 0 4 1 3 4 1
 [4645] 4 4 4 1 4 0 1 4 4 4 3 4 4 4 4 4 4 4 4 4 3 1 0 4 2 2 4 2 4 0 4 0 1 0 1 0
 [4681] 4 4 0 4 4 0 1 4 4 4 4 1 4 1 0 4 0 4 4 3 3 3 4 4 4 0 4 4 2 4 4 3 4 2 2 2
 [4717] 4 3 4 4 3 4 3 3 4 2 4 4 4 3 2 1 1 1 1 1 2 2 0 3 1 4 3 4 4 4 2 0 4 2 2 2
 [4753] 1 0 1 4 4 4 4 0 1 3 4 1 0 4 4 4 4 3 4 1 4 1 0 1 1 0 4 1 1 3 4 4 4 4 2 4
 [4789] 3 3 3 4 0 4 3 4 4 3 0 4 1 4 1 4 0 3 3 4 0 0 4 0 3 3 4 4 3 4 0 4 4 3 1 0
 [4825] 0 0 4 4 0 2 3 3 0 3 1 1 0 2 4 0 3 1 0 2 4 3 4 4 4 1 4 4 4 4 0 2 4 4 4 3
 [4861] 4 4 4 0 4 3 0 4 4 2 4 0 0 1 4 4 2 4 4 4 3 3 4 4 4 4 2 4 1 4 4 0 4 4 4 4
 [4897] 4 4 0 1 3 4 3 4 4 4 3 4 4 4 0 4 4 4 0 4 4 4 0 4 3 4 4 2 3 0 0 0 2 0 0 4
 [4933] 2 0 3 3 4 4 3 4 0 4 3 4 3 3 3 4 0 3 3 0 2 2 1 4 4 4 4 2 4 4 0 0 2 3 2 4
 [4969] 3 2 4 3 3 2 4 0 4 2 4 4 4 4 2 3 3 3 3 0 0 0 4 3 4 4 4 4 4 0 0 0 3 3 3 4
 [5005] 0 4 4 3 2 2 2 4 3 4 4 2 4 4 3 0 4 3 0 3 2 1 4 3 0 3 4 2 2 1 4 4 3 4 4 4
 [5041] 4 4 4 4 3 1 2 2 2 4 3 4 3 4 1 4 4 3 4 2 4 2 4 3 4 4 3 3 1 4 3 3 4 3 3 2
 [5077] 2 4 3 3 4 4 4 4 4 4 4 4 4 4 3 2 3 0 3 4 1 4 2 3 4 0 3 2 3 1 1 3 3 4 4 4
 [5113] 3 2 4 3 0 4 1 3 0 4 4 3 4 4 3 4 4 4 3 1 4 3 4 4 3 1 2 4 4 4 1 4 3 4 4 2
 [5149] 1 4 4 4 4 4 4 4 1 2 2 2 3 4 4 3 4 4 4 3 0 4 4 4 4 4 4 3 4 0 0 3 0 1 0 2
 [5185] 3 0 0 0 2 0 4 2 4 4 4 3 4 4 4 4 4 3 4 1 4 3 4 4 4 3 3 3 4 4 1 2 1 3 0 1
 [5221] 4 4 4 4 2 4 1 4 0 2 4 2 1 0 4 4 4 3 4 4 4 0 4 0 0 4 4 4 4 3 3 3 3 4 4 4
 [5257] 4 3 3 4 4 2 2 0 3 4 1 2 4 3 2 3 2 4 2 1 1 1 4 4 0 3 3 3 3 3 4 1 4 4 3 4
 [5293] 4 3 2 4 4 3 1 0 4 4 3 4 3 3 3 4 1 3 3 4 4 3 2 4 1 2 4 3 2 4 4 4 4 2 4 4
 [5329] 4 4 4 4 4 4 4 1 4 1 2 4 4 4 1 4 4 4 3 4 4 4 3 3 4 1 4 3 3 4 4 3 4 4 3 1
 [5365] 0 2 4 4 2 0 0 0 4 3 0 4 0 2 2 1 4 4 2 4 0 4 4 4 0 4 4 4 2 4 4 4 1 4 4 4
 [5401] 4 4 2 0 4 0 2 4 0 1 3 4 4 1 4 2 0 4 1 4 0 4 2 0 4 4 2 4 4 4 4 4 4 4 4 4
 [5437] 3 3 1 2 4 3 0 4 4 0 4 1 1 4 0 4 3 4 4 4 3 1 3 4 4 1 3 0 4 4 4 4 4 4 4 4
 [5473] 4 2 1 4 1 4 4 3 3 3 4 3 4 4 4 4 4 4 4 3 4 4 2 2 0 1 2 1 2 4 2 0 1 2 4 0
 [5509] 0 4 4 1 4 0 0 2 4 3 4 4 4 3 3 2 1 1 4 3 3 0 1 3 3 2 0 2 0 1 0 2 0 4 0 4
 [5545] 0 0 0 1 0 4 1 4 4 2 0 4 4 0 1 0 4 4 4 3 4 4 4 3 3 3 4 3 2 4 4 3 0 4 4 4
 [5581] 4 4 3 0 3 3 2 4 2 4 2 4 3 3 0 3 4 3 1 0 0 1 0 2 0 2 4 1 0 4 0 4 3 3 3 3
 [5617] 2 3 3 0 1 4 4 4 4 4 3 4 3 3 2 3 4 2 4 3 2 0 4 4 4 4 4 4 0 3 2 2 4 4 4 1
 [5653] 0 2 4 2 3 1 2 4 4 3 0 2 3 4 0 3 0 3 3 4 3 4 4 4 3 4 3 3 4 3 4 1 2 3 2 4
 [5689] 1 2 3 4 4 3 2 3 4 2 3 4 4 4 3 3 4 4 4 4 4 4 4 4 0 3 0 3 4 0 4 3 3 4 4 4
 [5725] 4 3 3 3 3 3 3 4 4 3 4 3 1 4 3 4 4 4 3 2 2 4 3 4 3 3 4 4 4 4 4 3 4 4 4 4
 [5761] 4 4 4 3 4 4 4 3 4 0 3 4 4 2 4 1 2 1 4 4 3 3 4 3 4 2 4 0 0 4 2 0 3 4 3 0
 [5797] 4 4 4 4 3 4 4 4 4 3 3 4 3 4 3 4 4 3 0 4 4 1 4 4 2 4 4 3 3 4 4 3 4 3 4 2
 [5833] 2 2 0 3 4 4 3 3 4 3 4 3 4 3 4 0 3 4 0 4 2 3 4 2 4 4 3 4 3 0 3 4 4 0 3 4
 [5869] 1 4 3 3 4 1 4 3 4 3 3 3 4 4 2 0 2 3 3 4 4 4 4 3 3 4 0 1 4 4 4 0 3 4 4 4
 [5905] 4 4 0 4 0 3 4 0 4 4 4 2 3 4 4 3 4 0 4 3 4 4 4 4 4 0 0 4 4 3 1 3 3 0 0 3
 [5941] 4 0 4 4 4 3 1 2 1 4 4 4 3 4 4 3 4 0 1 3 4 4 4 2 4 3 3 0 0 1 3 4 4 4 4 4
 [5977] 3 2 1 4 1 4 4 4 1 4 0 4 3 0 4 4 3 1 3 4 3 4 1 4 0 0 1 1 0 4 3 4 0 4 0 4
 [6013] 4 4 4 3 1 2 1 4 3 4 4 3 1 4 0 0 3 4 3 3 4 1 2 4 4 4 4 2 4 4 4 4 4 4 4 4
 [6049] 2 3 4 4 4 4 4 0 2 4 3 4 1 1 1 1 4 4 2 4 4 1 4 1 0 2 4 2 4 0 0 0 4 4 4 3
 [6085] 4 4 4 2 1 4 1 4 4 4 4 1 3 4 1 3 4 4 4 4 4 4 1 3 3 0 4 4 2 4 0 4 3 4 4 4
 [6121] 4 4 0 1 4 4 4 1 0 4 3 2 1 4 0 4 1 0 3 4 2 4 3 4 4 4 1 4 4 0 2 3 4 0 4 0
 [6157] 2 4 4 4 4 1 4 3 4 4 3 1 1 0 4 1 4 0 0 3 4 4 4 4 4 4 4 4 4 4 4 0 4 4 4 4
 [6193] 4 4 3 4 4 4 4 1 3 1 1 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4 4 1 4 3 4 4 4 4 4 4
 [6229] 4 4 0 3 4 4 4 0 4 4 0 4 3 4 4 4 4 3 4 0 3 4 4 3 3 0 3 4 4 4 4 2 4 2 4 4
 [6265] 4 2 1 4 0 4 4 4 3 4 1 3 4 4 3 3 1 4 4 1 4 4 4 4 4 3 0 4 4 4 4 0 1 4 0 4
 [6301] 4 3 2 2 4 4 4 4 4 4 3 0 0 0 4 3 3 4 2 0 4 4 4 2 3 3 1 4 4 1 3 1 4 4 4 4
 [6337] 4 3 1 4 4 4 4 1 3 4 4 4 4 4 4 4 4 4 4 1 4 0 0 0 3 4 4 4 1 3 4 4 2 3 4 1
 [6373] 2 4 4 4 4 4 4 0 4 3 2 4 4 3 3 4 4 3 4 4 3 1 4 4 1 4 4 4 0 4 1 0 3 4 4 1
 [6409] 4 4 2 4 4 1 4 2 1 2 0 3 2 4 0 4 4 4 0 4 4 0 4 3 3 3 4 4 3 4 3 4 4 0 0 4
 [6445] 1 4 4 4 3 3 4 0 4 4 3 4 1 4 4 1 4 4 0 1 4 4 4 4 4 4 4 0 4 4 0 4 3 3 4 0
 [6481] 4 0 4 3 4 4 4 0 0 4 4 4 4 0 3 2 3 4 0 0 4 4 4 4 4 1 0 3 3 4 4 2 2 2 4 4
 [6517] 4 4 4 4 4 1 4 1 4 0 4 2 4 4 4 0 4 0 0 4 1 4 3 2 2 4 1 4 0 0 4 2 4 4 4 4
 [6553] 4 4 2 3 0 0 1 4 4 4 4 3 4 0 4 4 4 4 4 0 4 4 4 1 4 4 3 2 4 0 0 4 2 4 4 4
 [6589] 4 4 1 3 0 4 4 0 4 0 0 4 4 0 0 3 3 4 4 4 4 4 4 4 4 3 4 1 0 0 4 4 3 4 4 4
 [6625] 1 4 4 1 2 4 4 4 4 0 0 3 0 0 4 3 0 3 4 4 4 4 4 4 3 4 4 4 4 4 4 4 4 4 3 4
 [6661] 4 3 3 4 4 0 4 0 4 4 0 0 4 4 4 4 0 4 4 3 2 3 1 3 4 4 4 3 3 4 4 1 2 4 4 4
 [6697] 4 1 0 4 4 4 4 1 4 1 4 1 1 3 3 0 0 4 4 4 4 4 4 1 4 4 3 3 3 4 0 4 4 0 2 1
 [6733] 0 4 1 4 4 4 2 4 4 4 3 2 3 1 4 0 4 4 4 4 0 0 4 2 4 0 4 1 4 4 4 0 4 2 4 1
 [6769] 4 4 4 4 4 4 4 4 4 4 4 3 4 3 2 4 4 3 4 2 4 3 4 4 0 4 4 4 4 4 4 4 4 0 3 4
 [6805] 4 3 4 3 2 3 1 0 3 1 1 4 4 1 4 4 0 4 4 3 3 4 4 3 4 4 3 4 4 3 3 3 4 4 4 4
 [6841] 3 4 0 4 4 4 4 4 4 2 4 2 4 3 2 0 1 2 0 4 1 4 4 4 4 4 4 0 0 3 3 4 2 4 4 3
 [6877] 4 4 4 4 3 3 4 4 4 3 1 4 0 4 1 1 4 4 4 4 4 1 3 3 1 4 4 0 4 4 0 2 3 4 4 4
 [6913] 4 2 4 4 1 4 4 4 4 2 4 4 1 4 4 4 4 4 4 0 4 4 4 4 2 4 4 2 4 1 4 4 0 4 4 4
 [6949] 3 4 4 4 2 2 2 4 4 4 4 4 4 4 4 4 4 4 4 3 0 3 0 2 3 1 3 0 1 0 0 2 3 1 1 3
 [6985] 0 3 3 3 3 0 3 0 3 3 3 3 3 3 3 3 3 3 2 3 3 0 3 3 2 4 0 4 4 4 2 4 0 2 4 3
 [7021] 0 1 2 3 3 2 0 3 4 2 4 0 2 2 4 2 1 3 3 0 0 0 0 2 0 3 1 0 0 0 0 0 0 0 0 2
 [7057] 2 3 3 3 0 3 3 3 3 0 3 2 0 0 4 3 4 1 3 2 0 4 0 1 0 4 4 3 4 3 3 4 3 4 3 4
 [7093] 2 3 3 0 2 3 4 4 2 4 2 3 2 4 0 4 4 0 2 2 2 3 4 4 4 3 4 4 0 0 3 3 4 3 2 2
 [7129] 4 0 1 0 4 4 2 4 4 4 4 4 4 3 4 1 1 4 1 2 4 4 4 4 3 3 4 4 4 4 4 4 4 3 1 0
 [7165] 1 2 4 4 1 1 0 4 1 2 0 4 4 0 4 2 3 2 0 3 4 4 4 2 1 2 2 1 2 3 3 4 1 4 4 4
 [7201] 4 4 4 4 4 4 3 2 3 4 4 1 4 1 2 0 4 4 3 3 4 2 0 0 4 0 4 3 4 3 0 4 3 4 3 0
 [7237] 1 4 3 4 4 3 4 1 4 3 4 2 4 1 4 4 1 4 4 4 4 4 4 4 4 3 4 4 0 1 4 3 4 4 3 2
 [7273] 4 0 4 1 4 0 4 3 4 4 4 0 4 4 2 4 4 4 4 4 4 4 1 0 4 0 4 0 4 0 1 3 0 1 1 0
 [7309] 4 4 4 3 3 4 0 3 3 0 3 2 2 3 1 4 4 3 0 4 0 1 3 3 4 0 4 4 4 0 0 0 4 0 3 3
 [7345] 0 4 2 3 0 4 4 4 0 3 0 0 3 0 3 3 3 4 1 1 3 1 4 4 1 0 0 1 1 4 4 4 1 4 4 0
 [7381] 4 4 4 4 1 0 4 4 0 0 4 2 2 1 2 4 3 1 4 4 4 0 3 3 3 3 2 0 0 3 0 4 3 4 3 4
 [7417] 3 0 4 0 3 1 4 1 0 4 0 4 0 0 0 0 2 2 2 1 4 3 1 1 3 3 4 1 4 3 4 2 2 4 4 4
 [7453] 1 2 4 3 4 3 4 4 4 4 2 4 3 2 3 1 0 3 0 0 4 3 0 3 3 3 2 0 3 0 2 0 1 1 3 2
 [7489] 1 1 3 0 2 3 2 0 1 0 2 3 3 3 3 2 0 1 3 1 3 3 0 1 3 1 0 3 2 0 0 3 0 0 4 4
 [7525] 4 4 4 4 3 4 3 3 3 0 4 3 3 2 0 0 4 3 0 3 2 2 3 3 0 1 3 3 4 4 2 0 2 3 0 3
 [7561] 4 0 0 3 3 4 3 1 3 2 2 2 3 4 2 4 4 3 0 3 4 4 0 2 0 2 4 3 2 0 2 3 2 2 3 4
 [7597] 3 3 4 0 3 0 3 4 3 1 2 2 3 4 1 4 3 4 0 0 4 4 0 1 3 3 2 4 4 4 4 4 3 2 3 2
 [7633] 2 4 2 0 2 3 1 0 0 0 3 4 4 4 4 4 4 3 3 4 4 4 0 4 1 3 4 4 4 0 3 4 4 4 4 2
 [7669] 4 4 4 4 4 4 4 4 4 3 4 4 3 4 1 4 2 4 3 4 4 4 4 4 4 4 4 4 3 2 4 3 4 4 4 4
 [7705] 4 4 4 4 0 2 4 4 1 2 4 1 3 4 4 4 3 0 2 4 4 0 3 3 3 3 2 1 3 4 1 4 1 2 0 2
 [7741] 0 3 4 4 3 4 2 4 4 4 4 4 4 0 4 4 2 4 4 4 4 3 4 3 3 4 4 3 4 4 0 1 4 4 3 4
 [7777] 2 4 4 4 3 3 3 3 3 3 3 0 3 4 4 3 0 4 3 3 1 3 4 4 0 1 4 4 4 4 4 2 3 3 4 4
 [7813] 4 4 4 4 4 4 1 4 4 4 4 3 4 4 4 2 4 4 4 4 4 4 0 4 0 3 3 3 4 4 3 4 3 4 4 3
 [7849] 2 4 4 3 4 4 3 1 4 0 0 3 4 0 4 4 4 4 4 4 4 4 4 3 4 4 4 2 2 4 4 2 4 3 2 4
 [7885] 4 4 4 4 4 3 4 4 3 4 4 4 4 4 3 4 4 4 4 4 4 4 4 1 1 0 3 4 4 4 4 4 3 0 0 3
 [7921] 3 0 4 4 3 3 3 1 3 3 1 3 1 3 3 2 3 3 3 1 1 0 1 2 1 3 1 2 0 3 1 3 3 3 3 1
 [7957] 4 3 4 4 3 1 3 3 3 3 3 3 3 3 1 1 3 3 3 3 3 2 3 3 3 3 3 3 3 3 1 0 1 3 1 3
 [7993] 3 3 2 3 3 3 1 3 4 0 4 1 3 3 3 2 0 4 4 4 4 4 2 4 4 3 4 4 2 3 3 4 4 4 4 3
 [8029] 4 0 4 3 3 1 4 4 4 3 4 4 3 4 4 4 3 0 4 4 0 4 4 3 4 3 4 3 4 4 4 3 2 4 4 3
 [8065] 1 0 4 3 4 4 3 4 4 4 4 0 4 4 3 4 4 2 4 4 4 4 2 4 4 4 3 2 4 3 3 4 3 4 4 3
 [8101] 4 4 4 4 4 4 4 0 3 2 4 1 4 4 3 2 4 3 4 3 3 1 3 4 4 2 4 4 4 0 3 1 4 4 1 4
 [8137] 4 2 3 4 4 4 4 4 4 4 3 0 4 4 3 3 4 4 3 4 4 4 4 4 4 4 0 4 4 4 3 4 2 4 4 4
 [8173] 3 3 4 4 4 3 2 0 0 4 4 3 4 2 4 4 3 4 4 3 4 2 3 4 4 4 4 4 4 4 4 3 4 0 4 3
 [8209] 3 4 4 4 4 4 4 4 3 4 4 4 4 4 3 3 4 4 4 4 4 3 4 4 4 4 4 4 3 4 3 3 4 4 3 3
 [8245] 4 4 4 4 4 4 4 4 4 4 0 4 4 0 4 3 4 4 4 4 2 4 4 1 4 4 4 4 3 4 4 1 3 4 4 4
 [8281] 3 3 1 4 3 4 4 3 4 2 4 4 4 2 4 4 4 4 4 4 3 4 4 4 4 4 4 3 4 4 4 4 4 4 3 4
 [8317] 4 3 4 0 1 0 4 3 4 4 4 4 2 3 4 2 4 3 4 4 3 4 3 3 2 3 3 0 2 4 4 4 3 3 0 3
 [8353] 3 4 3 0 4 4 4 0 4 3 2 3 2 2 4 4 4 4 3 4 2 4 4 4 4 4 4 3 3 4 1 1 4 4 2 3
 [8389] 4 4 0 4 4 4 4 4 4 4 4 3 4 4 4 4 3 4 2 3 4 4 2 3 3 3 3 1 3 3 3 4 3 3 0 3
 [8425] 3 2 3 3 1 4 4 3 3 3 4 4 0 4 2 3 3 3 3 3 4 1 3 4 4 3 4 3 2 3 1 2 3 3 3 3
 [8461] 1 3 3 4 3 3 3 3 3 2 3 3 4 4 4 4 0 4 4 3 4 4 4 3 3 0 3 4 4 3 4 4 4 4 4 1
 [8497] 2 4 2 4 4 4 4 4 4 0 4 4 3 4 3 4 4 1 3 2 2 3 0 3 2 4 4 4 4 3 4 4 3 4 4 0
 [8533] 4 4 3 3 4 4 4 4 4 0 2 4 2 4 4 0 4 3 4 4 4 4 4 3 4 4 4 4 4 4 3 3 4 4 2 4
 [8569] 4 4 1 3 2 4 4 3 1 4 3 3 2 3 3 3 4 3 2 4 4 0 3 1 3 3 4 3 4 1 0 4 4 0 4 4
 [8605] 4 4 3 1 4 2 4 2 4 4 4 4 4 2 3 4 2 4 4 4 4 3 4 4 4 4 4 4 4 4 2 3 4 2 4 4
 [8641] 0 2 0 4 4 4 4 4 4 4 2 4 4 3 0 4 3 0 4 4 4 4 1 4 4 4 4 4 4 3 4 1 4 3 4 2
 [8677] 3 4 4 4 2 4 4 4 3 4 4 4 3 4 3 2 4 0 0 2 3 3 3 4 2 1 4 4 3 0 4 3 4 0 4 3
 [8713] 3 4 4 3 4 3 2 1 2 4 4 2 4 2 4 4 4 4 4 4 4 4 4 4 1 1 2 4 1 4 3 4 1 4 4 2
 [8749] 2 4 2 1 4 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4 4 4 3 4 4 4 4 1 4 4 4 1
 [8785] 4 2 4 2 3 1 4 0 2 4 4 4 4 3 3 4 4 1 4 2 4 2 4 4 4 3 2 4 1 4 4 4 4 3 4 4
 [8821] 4 4 4 1 4 4 3 4 4 4 4 3 4 4 4 4 4 4 4 4 3 2 1 4 2 4 4 3 4 4 3 4 4 4 4 3
 [8857] 4 4 4 4 0 2 3 4 3 3 4 4 3 4 4 4 4 3 4 4 4 3 3 4 4 4 2 0 4 3 4 4 3 4 4 3
 [8893] 3 4 4 2 3 4 4 4 4 4 2 4 3 3 4 3 3 3 3 4 4 3 3 4 4 4 4 4 3 3 4 2 2 3 3 3
 [8929] 2 0 1 4 4 4 4 3 4 4 3 4 4 4 4 4 3 4 4 3 4 4 4 3 3 0 0 1 4 4 3 4 4 3 3 4
 [8965] 3 4 4 4 4 4 3 4 4 4 4 4 4 3 3 0 2 2 0 3 3 2 3 1 3 2 3 1 0 2 0 2 3 3 4 3

In [44]:
lgbregmin

    [1] 1.5071196 1.5962776 1.3542608 1.3923528 1.3634821 1.9738661 1.7420033
    [8] 2.4350817 1.9443495 2.1961087 1.1683025 1.7698839 2.0855295 2.3924090
   [15] 1.2137819 2.4293169 2.2621307 1.8451393 2.3006538 2.4833108 1.9669308
   [22] 2.3735616 2.9280350 1.8707888 2.0037804 2.1419652 1.7564257 2.1254973
   [29] 1.8281363 1.6866725 2.1223759 2.0981537 2.0435297 2.2531961 2.0182287
   [36] 2.2257892 2.1627540 2.4297902 2.1037573 1.6467009 1.8878266 2.0390519
   [43] 1.8428070 1.6460643 1.8618469 2.3186601 2.5171046 2.5340655 2.5068256
   [50] 2.2283387 2.4367191 2.3737835 2.3641556 2.0883703 2.0498935 1.9122741
   [57] 2.0949738 2.3600807 2.3200089 2.3368757 3.3922239 2.4766603 2.1180485
   [64] 3.3742149 1.7935970 3.3124460 2.5777385 2.0827550 2.5733976 2.8671783
   [71] 2.0445978 2.5793460 2.1708728 2.2006147 1.7072125 2.8675903 2.9772696
   [78] 3.0510971 2.3859410 3.3839772 2.7460643 1.8999476 1.6916014 3.6324519
   [85] 3.4707061 1.3309432 1.5911932 1.6175165 1.3175728 4.0828058 2.1301931
   [92] 0.6135951 1.0901790 3.4246571 3.8182657 2.9785423 3.2259890 1.8317731
   [99] 2.1799545 2.0789224 2.1414146 2.3123372 1.6555366 3.4049340 1.9454315
  [106] 2.6207479 1.8315361 1.6210236 3.2739511 1.5780898 2.1449758 2.0380169
  [113] 1.9257041 1.4273104 2.4367118 2.3441498 1.3249293 2.1684201 1.4620084
  [120] 2.6728970 1.6533070 1.7513165 2.2700918 1.6533070 2.7083208 1.8906282
  [127] 1.2458141 1.8555714 1.7546268 2.5210363 2.8651663 3.2865564 3.0494279
  [134] 2.5949247 2.1580815 1.8144578 2.4805486 3.1143396 2.3788057 3.1907236
  [141] 2.9761667 3.2736306 3.5920338 4.0645991 2.8168554 3.6231506 3.8606118
  [148] 2.7334386 2.8757196 2.1605676 1.7618157 1.3220199 2.3716972 2.7590020
  [155] 2.4316508 1.6330569 3.4147874 1.9498621 1.1601244 1.1225125 1.1066373
  [162] 1.4370032 1.6890713 0.7447765 1.1274882 1.9478114 1.3633691 1.9204090
  [169] 1.6304411 1.3524171 1.9243302 0.7273357 1.0652753 1.8228621 1.2456602
  [176] 1.4518025 1.4538523 0.8362821 2.0963866 1.0080791 0.6713447 1.0636077
  [183] 1.4791881 1.1904491 1.1870045 1.0396947 1.5040639 1.5731836 1.5695534
  [190] 0.9156188 1.3266457 1.0065876 1.3000065 1.3015447 1.5745860 1.6006694
  [197] 1.0580745 1.2710175 2.9791978 2.4800998 1.2695098 3.1668101 1.7378904
  [204] 1.9972535 2.4137444 2.5468252 3.6042256 1.4717315 2.7922169 2.9527206
  [211] 2.5884987 2.6014007 2.8436361 2.5801614 2.2264987 2.1089608 2.6993234
  [218] 1.7838152 3.1471393 3.0604249 3.2684433 3.5369816 3.4988059 3.0295049
  [225] 3.2537491 2.6970069 2.6917588 3.2800497 2.0942106 1.1849705 3.4723669
  [232] 1.4135250 3.7344672 2.2220955 3.3689865 3.4092348 1.0485190 2.0861813
  [239] 3.0201815 3.0113225 2.7322654 3.0003280 1.4637285 2.3295719 3.5091967
  [246] 2.7771097 1.5125480 1.7979500 2.9244196 3.3376114 2.5830055 1.9590032
  [253] 3.4725091 2.5490989 2.4087200 2.5711912 3.2949951 2.5100231 2.1616551
  [260] 2.1054265 2.8502586 2.5728537 3.2014625 3.3674811 2.5243434 2.7466387
  [267] 2.4336797 3.3893902 2.7731332 2.4174577 2.2428176 2.3223462 3.3351089
  [274] 2.2425977 2.1771939 2.6625136 3.1143125 1.3428138 2.0590778 2.3458747
  [281] 2.5946322 3.2588139 3.3265113 2.5997520 3.3913030 2.7113203 3.1706057
  [288] 3.9192899 2.1604858 2.6157786 3.6256481 1.7137460 2.2795961 3.0491078
  [295] 2.5586885 3.0085127 0.9608162 2.7740825 2.6143476 2.9267116 2.8524701
  [302] 3.1445379 2.4205774 2.9758319 2.3608300 2.3383360 2.1505163 2.5134292
  [309] 1.3514803 1.8157278 2.6388773 2.4659212 2.4440415 0.8848403 2.9461590
  [316] 2.3721997 2.4019264 3.0048582 2.7405241 2.7863188 2.3918034 1.3554962
  [323] 2.5593133 2.7928437 2.1904576 2.4473851 2.6175116 2.2495910 3.2811248
  [330] 1.6692440 2.4155666 3.4720835 3.5410358 3.4962322 3.2960773 2.2419209
  [337] 3.3382727 2.3790716 1.7665544 1.6184873 3.9824351 3.2787805 3.1998518
  [344] 2.1800052 2.7876074 2.1719141 1.9743818 1.8225846 2.2152057 2.0983104
  [351] 2.5235472 1.2751133 2.2358039 2.2358039 1.6192778 2.6458066 2.2554983
  [358] 2.1509408 1.4877078 2.3261065 2.3261065 1.8180164 2.3193538 2.2233584
  [365] 1.6660728 2.2793286 3.0649233 1.7444385 2.6724632 2.5194678 2.1047933
  [372] 2.5986394 1.7636468 2.4661981 2.5569073 2.3868521 2.3936612 2.3556473
  [379] 2.5025280 2.4784568 2.4561053 1.9462099 2.6152873 2.2431657 1.8412742
  [386] 1.9316767 2.4743058 1.6567228 2.0485558 3.1060369 1.9142338 1.9593263
  [393] 1.9593263 2.4963407 3.0827085 2.2349971 1.2065404 1.2707333 2.4583426
  [400] 2.7888665 2.7927469 2.4302920 2.6637440 2.3283961 2.3130165 1.5476922
  [407] 2.9980245 2.0554707 2.9981996 2.4605465 2.4022207 0.9868392 2.3426353
  [414] 2.0689695 2.8775371 1.7048747 1.7048747 2.9534985 2.8525187 2.2349077
  [421] 2.3576951 2.8931530 2.4439229 2.3725352 2.4183165 2.5650962 1.5911717
  [428] 2.3792530 2.1347539 1.5101280 1.7627391 2.9506868 2.9214525 2.6606684
  [435] 2.9853566 1.7334831 2.7051674 2.9788129 2.9093421 2.3745628 2.7914238
  [442] 2.6428102 2.2860513 2.2061420 2.5634075 2.9297449 2.0416717 2.4051244
  [449] 2.8818138 2.2625246 1.7841590 3.3480385 2.1734923 3.0920972 3.1044175
  [456] 2.4084740 2.4084740 2.5610953 2.9042866 2.7346900 2.4089552 3.1697849
  [463] 3.0281773 2.5915049 2.4504775 2.4837818 2.8635210 1.9301574 2.2094593
  [470] 2.3332356 2.1439448 2.2842016 2.7399615 2.5300473 2.7875399 2.3851924
  [477] 3.2370523 2.0464857 2.9181733 2.3818613 3.5041629 2.5349887 2.3416738
  [484] 1.9305376 1.5764006 2.8580526 2.6409780 2.0814535 2.9006649 2.9398596
  [491] 2.9862978 2.2282274 3.2991311 1.9077305 1.9838776 2.5755228 2.2619218
  [498] 3.1577579 1.9454731 2.2074264 2.4561293 2.4235984 2.1472258 2.2747729
  [505] 2.9597673 3.1408223 1.7408893 1.7301572 1.5960468 1.7998721 1.5637361
  [512] 3.0171418 3.0171418 0.4669657 1.8265701 2.4201712 1.4731906 1.0287494
  [519] 1.9959293 2.0957055 1.4641402 3.2605527 2.9373908 2.3799448 1.8546348
  [526] 1.7443160 2.6556736 1.7312467 1.7312467 3.2304259 2.8532659 1.9958383
  [533] 3.2342969 2.8429994 2.9853226 2.9853226 2.9560529 1.8902866 2.6046959
  [540] 2.5629607 2.3367199 2.3178370 2.0928657 3.3865243 3.0153820 2.6159794
  [547] 2.6582333 2.9536174 2.7221424 2.4649335 2.3541971 2.8806892 1.7295800
  [554] 2.8384646 1.8158017 2.9599834 2.6186977 2.0773352 1.8986437 2.6322639
  [561] 2.5197298 2.0866313 2.1959573 2.6272341 2.6552351 2.0810465 2.8327852
  [568] 2.1946683 2.5212859 2.2508204 2.2189634 3.0427448 3.1433500 2.2723366
  [575] 2.4651424 2.5212600 2.3935147 2.3404929 2.4943169 2.5352755 2.5159443
  [582] 1.9250570 2.1398219 2.3243224 2.9183873 3.1325705 2.8178381 3.1654357
  [589] 2.9870014 2.4155288 2.2953010 2.9546706 2.5998604 3.2457479 2.9500833
  [596] 2.9649660 2.1052907 3.1814099 2.3603524 2.0721566 3.1667367 2.4449566
  [603] 2.1958263 2.3366041 1.7855109 2.7390253 2.3096495 2.1329847 2.0333769
  [610] 2.0300485 1.7471703 1.8470890 1.6166408 2.2255484 2.1179015 1.7204090
  [617] 2.1308739 2.4854800 2.4854800 2.1187003 1.6260099 2.6486782 2.5429157
  [624] 2.1478420 1.0718340 1.9582076 1.5713792 2.1499366 2.0137265 2.2956720
  [631] 1.6839155 2.7488062 2.5061752 2.9715453 2.5279971 1.3478183 1.3892012
  [638] 1.8966997 1.7322140 1.8251758 1.8531558 2.5218733 2.5218733 1.6572992
  [645] 1.8126673 2.7845021 1.9824609 1.2010414 2.7662233 2.8235438 1.8351093
  [652] 2.4622723 1.6993467 2.5451466 3.1141090 2.5573837 2.1970708 1.8192176
  [659] 1.8456475 1.1060623 2.2620543 2.0484458 2.4045317 2.0988390 1.5278670
  [666] 2.7181506 2.1439699 2.7336842 2.9006649 1.8560113 2.0868512 2.0254753
  [673] 2.1721047 2.1237182 2.1108035 2.9584921 2.0322234 2.0031401 2.1736781
  [680] 1.4844397 2.4555912 1.4090634 1.8961753 2.7513358 1.9435050 1.6129065
  [687] 1.8214642 1.7677335 2.2074032 2.3165046 2.3178602 1.5041265 3.2003191
  [694] 2.7731163 2.7731163 3.0454150 2.8863926 2.3436167 2.3436167 1.6781905
  [701] 1.2651242 1.4864777 1.5618757 1.4802864 2.1096998 2.8006036 2.3988255
  [708] 3.5744976 1.4738897 2.9752137 1.3789003 3.0994786 2.6946075 1.6679750
  [715] 2.2221044 2.2838098 2.0665441 1.9225747 1.7455426 2.1900316 2.8451282
  [722] 3.3792272 2.1240902 2.0639809 2.1969407 2.6825981 2.5484070 2.6526367
  [729] 2.2007294 2.3266943 2.0964367 2.7904765 2.1041974 2.8815014 1.6993466
  [736] 2.1195995 2.2618555 1.9884185 2.4231596 2.5777992 2.2296911 2.5938987
  [743] 2.3302318 1.4390427 3.1563958 2.1387828 2.3548430 2.1162490 2.5746759
  [750] 2.4141179 2.1754187 2.6516745 2.7389358 1.9711480 1.9045733 2.9309281
  [757] 1.9243424 1.6586636 2.1265770 1.7389163 1.9815389 2.8911235 3.6710198
  [764] 1.9384783 2.1390697 2.7636430 2.1297583 2.3092864 2.2818271 2.4113951
  [771] 2.9068552 2.6616397 2.3579581 2.4360916 2.3940971 2.5793666 2.1872058
  [778] 2.0370772 2.8361860 1.7250681 2.3879541 2.1561587 2.2679661 1.6387773
  [785] 2.3641466 2.4933995 1.6094543 2.0422856 2.5612905 2.1291587 1.0397459
  [792] 2.4090593 3.1196676 1.9459278 3.0988601 2.2740634 1.9480434 3.2508196
  [799] 2.8432206 3.1766244 2.2723352 2.5808447 1.1147992 2.9055587 2.1122051
  [806] 1.8269349 1.7472169 1.3015546 1.3679612 1.8301997 1.5699470 1.4602867
  [813] 1.5656747 2.2492164 2.0157548 1.5832197 2.2316793 1.5210140 1.5661969
  [820] 2.1491829 2.3090554 2.9056729 2.4763433 2.3769089 3.2488157 3.5045569
  [827] 2.9116708 2.6753348 2.4744541 1.7904472 2.9383354 2.0986934 2.3376915
  [834] 2.3552075 1.5525719 1.5950841 1.5836394 2.7430727 2.9614789 2.0231742
  [841] 1.5166151 2.3011393 1.9683611 1.0444800 2.6212927 2.1689453 2.0860112
  [848] 3.0697195 1.8014009 3.0950101 2.2597341 2.5364601 2.5364601 1.9535827
  [855] 2.5456313 2.0423276 1.5003948 2.4590570 2.4590570 2.6374983 3.4878471
  [862] 1.9986001 2.2911071 3.0750839 2.7543442 2.4475119 2.1827778 2.1673759
  [869] 3.0554116 1.7546336 3.0254553 2.2826952 1.7009994 2.2730979 3.0775811
  [876] 2.3365827 3.0885038 1.9021167 1.6572893 3.3933584 2.1832034 2.5760914
  [883] 1.7818560 1.7807082 2.6271851 2.4012911 1.3182859 2.9190331 1.9564377
  [890] 2.7293133 3.3603525 2.6205559 2.1965734 1.9803941 2.0909562 2.4019748
  [897] 1.0508965 1.7555865 3.1779532 2.5732778 2.8996446 2.2843851 2.2211321
  [904] 2.3491940 1.6895576 1.7878092 1.8801653 1.9611810 3.1527900 2.6495451
  [911] 2.3411583 3.2698765 1.5947517 2.6017149 2.1612312 1.6652143 1.6713896
  [918] 2.3660024 2.4174517 1.8342046 3.4586986 2.1550530 2.3352715 2.4789148
  [925] 2.0126580 2.8600906 1.8096908 2.3429285 2.5777618 2.4596679 2.2544171
  [932] 1.7983277 2.2798365 1.5001984 3.0837987 2.7959777 2.7429406 3.1271088
  [939] 1.9552387 2.0028449 2.3828897 1.9196101 1.5013862 2.4461013 2.5500628
  [946] 2.2782941 2.8972467 1.9380046 2.3869467 2.7111194 3.0403470 2.5334303
  [953] 2.6208856 2.9281362 2.7873214 1.9003300 1.9003300 2.1670375 3.1163299
  [960] 2.0357901 2.5813708 2.4673265 1.7832637 1.7555011 1.8601067 2.6223057
  [967] 2.1187621 2.1575488 1.9838582 2.0350230 1.4731812 2.0304033 2.9881313
  [974] 2.2512340 3.3103292 2.8074785 1.3111966 2.5669427 1.9861937 2.0386161
  [981] 2.3113823 2.6843206 2.0575108 2.1234028 2.6927771 2.4692367 1.9023655
  [988] 1.7517320 1.6795633 1.9436920 1.9414576 2.2077207 2.2935816 3.2982426
  [995] 2.1331242 2.1200708 2.6097524 2.0918605 2.5581618 2.7563135 2.9238382
 [1002] 2.4281932 2.1299574 2.6768257 2.4940676 1.5791220 2.5231313 2.4129735
 [1009] 2.4129735 2.4814228 1.8815555 1.8506587 3.4191541 2.1982704 3.2357403
 [1016] 2.4054200 2.6482892 3.1064148 3.1064148 2.7574754 2.1419448 2.5726434
 [1023] 2.7131834 1.9754300 2.8374557 1.4098360 1.4098360 1.4463019 2.2959097
 [1030] 1.7813154 2.1506936 2.7701241 1.6642834 2.4244104 1.4201434 1.8474297
 [1037] 2.7752224 2.1813314 1.9071157 2.4306005 3.1640389 2.0090018 2.8814215
 [1044] 2.2569074 2.7313567 1.9354224 1.8286189 1.9482650 1.8100168 1.3296876
 [1051] 2.9006153 2.9755406 3.0286721 1.9760904 1.9143173 2.6430864 2.2664340
 [1058] 2.2149733 2.7859126 2.1328885 2.0493063 3.0021413 2.0009089 2.5043129
 [1065] 2.5043129 1.6631251 2.6960647 2.1699804 1.8204071 1.8204071 1.7066865
 [1072] 1.2332754 1.2563965 2.6744758 2.7099186 2.1970988 2.1970988 2.4793117
 [1079] 1.6323193 2.5017551 2.0175454 2.1451978 1.5349790 1.9662792 2.4357160
 [1086] 2.2444208 2.8277273 2.5972955 2.7525155 1.7154119 1.2139375 3.1711953
 [1093] 0.7960184 0.9586892 1.1352811 2.2355576 2.6600647 1.8338067 2.6367358
 [1100] 1.8078501 2.5017551 1.7479674 1.9273678 2.9255946 1.6028283 2.3004122
 [1107] 2.3927372 2.4298625 2.0080742 2.2278088 2.1547619 2.6357038 2.3633536
 [1114] 2.8254033 2.6069749 2.8890301 2.8755331 2.7456857 2.5082719 1.9620782
 [1121] 1.5183871 1.5611073 2.0271626 1.8218735 1.2477078 1.9223256 2.6156016
 [1128] 2.4555907 2.5566360 2.9466204 2.2050013 2.1789372 2.9410567 2.9251241
 [1135] 3.1647895 2.4771342 2.4005976 2.9782780 2.3285650 2.7558787 2.7762909
 [1142] 2.8153555 1.3119471 2.1457629 2.1457629 1.7049228 2.0231214 0.4148482
 [1149] 3.0637731 3.1593401 2.3424703 1.6750495 2.3079197 2.7044814 1.7823221
 [1156] 2.1030055 2.3532122 2.3087689 2.1157320 1.8305763 2.0489178 2.7132583
 [1163] 1.9613831 2.4369729 3.0119447 1.9400990 1.9538422 1.4815880 1.9377124
 [1170] 3.1100730 3.0722180 2.9819252 2.9328960 3.1596197 2.3718211 2.6273981
 [1177] 3.2989536 2.7609014 3.0620557 3.6551950 3.2701641 2.5474022 2.8693316
 [1184] 2.0430192 3.5611799 3.1679354 2.9458708 2.0345846 2.0043034 2.4385533
 [1191] 2.9342170 2.2177907 2.5151513 2.7821596 1.6368869 2.2485857 2.9324931
 [1198] 2.0006543 2.9944018 2.3739193 2.0188596 2.9454967 2.3844950 2.9917641
 [1205] 2.5234044 3.2639882 3.1627064 2.1722250 2.5205572 2.2014736 2.1495162
 [1212] 2.1168516 1.3019639 1.9439617 2.0962810 2.9182464 2.7527115 2.6842203
 [1219] 2.8622566 2.8352381 3.0542503 2.2589759 2.4623398 2.8583385 2.2390431
 [1226] 2.9379482 2.4170560 2.5818489 1.9654328 1.7725700 1.5407671 2.0984898
 [1233] 1.9658964 1.9658964 1.1132459 1.1132459 1.4416165 2.3903529 2.3903529
 [1240] 1.7664314 2.9566378 2.4756030 2.7294587 2.1163868 1.8015901 1.6694531
 [1247] 3.0811699 2.1393235 2.9594147 1.9118275 2.1552093 2.6261385 2.3532705
 [1254] 1.6475287 2.5911310 1.6216306 1.9692763 2.5642365 2.7524149 1.8316546
 [1261] 2.9430963 2.5850297 3.8845152 2.7094854 1.9146559 2.3106241 2.1052676
 [1268] 2.8206087 2.9493752 2.4082159 2.3385328 2.7726758 2.5940915 2.1520990
 [1275] 3.2132778 2.4341758 2.9250986 2.6448574 2.9942965 2.8248906 3.2239233
 [1282] 2.6437313 2.5816066 2.3913101 2.7897639 2.5774502 3.2030954 2.4458012
 [1289] 2.2131349 2.5665170 2.5101681 2.3716165 3.1710738 2.8115767 3.5578415
 [1296] 2.8027881 2.4073670 2.4165048 2.6760492 2.1229594 2.4018741 1.7246447
 [1303] 2.5682098 3.0632958 1.7341940 2.4698827 2.4974094 1.9719075 2.5593565
 [1310] 2.1590512 2.2074233 1.9363822 3.0228452 1.9205738 2.4325590 2.4537386
 [1317] 1.5261206 2.6500425 2.4393323 1.8230568 2.7565293 1.9230093 2.1208546
 [1324] 2.9048751 3.0804191 3.0276673 3.0628586 1.8854632 1.4843519 1.4843519
 [1331] 2.3001375 1.5981651 2.4812581 2.5304564 2.1526411 2.1619838 2.1438315
 [1338] 1.8052810 2.7142321 2.5548141 2.9150982 2.3203582 2.9531941 1.9890836
 [1345] 2.2368174 2.3295519 2.7370559 1.5945028 2.1308857 2.9520750 2.8796151
 [1352] 1.9943284 2.9926680 2.7644447 2.9757455 2.7703445 2.5913875 1.8367577
 [1359] 2.5285286 2.2896013 2.6788986 2.4880742 2.3772669 2.9193913 3.3767261
 [1366] 2.1691447 2.2595578 3.0715076 2.1269732 2.0412670 2.5427227 3.2137897
 [1373] 2.6260661 1.9664603 3.2169501 2.9144148 2.6641098 2.4970681 2.7729921
 [1380] 3.2082007 2.6634596 3.0856379 3.1123111 2.8616101 2.8979993 2.6431790
 [1387] 2.3023305 2.6318872 2.2435019 2.1126027 2.6383049 2.4006867 2.1608636
 [1394] 2.9672836 2.8507912 2.5824151 2.2083952 1.4308433 1.9128249 1.9760097
 [1401] 1.7777930 2.6454476 2.4174203 1.3544579 2.0926046 3.1108547 1.8179908
 [1408] 2.0868436 1.7716223 1.4580893 2.1878998 2.3623120 1.5193550 1.5908326
 [1415] 2.4642485 2.6285387 2.5157100 2.5102229 3.0032327 2.2492226 2.7980184
 [1422] 1.8951245 1.8094331 1.8094331 2.2684661 1.4465783 1.5850630 2.4354593
 [1429] 1.6857927 2.9006649 2.6589074 2.2027998 2.0447062 1.6448307 1.5249231
 [1436] 1.9455604 1.5653654 2.5999143 2.4034231 2.9447217 2.9300767 3.0586653
 [1443] 2.1119054 2.7704659 2.7704659 2.8979973 3.2936276 2.8209416 2.7319634
 [1450] 2.5462629 2.7234603 3.1100445 2.5413259 2.7962671 2.1825627 3.0857800
 [1457] 2.5954331 2.8520248 3.1473466 1.7430377 2.1212831 2.2807583 2.8981654
 [1464] 2.5372554 2.0933832 2.3188434 3.0228346 2.3816132 2.5421953 2.4156161
 [1471] 2.8892648 2.1440894 2.9541473 1.6524648 2.2744155 3.0024125 2.2093301
 [1478] 3.1422264 3.1094819 2.2708724 2.8917989 2.1335800 1.3927005 1.3574288
 [1485] 1.4442299 0.8453851 2.5983967 1.5803765 2.7383571 1.7795089 1.5981406
 [1492] 1.6157074 2.5466898 2.3177335 2.0670886 2.3403475 1.9792970 1.6364019
 [1499] 2.8732807 2.5338335 2.4607662 2.0703203 2.5714901 2.3151831 1.8778946
 [1506] 1.5648762 2.4305006 1.4072966 2.8902381 2.3509316 2.3509316 1.4323916
 [1513] 1.5856705 2.2737956 2.2394943 1.8042808 1.5636567 1.5754585 1.1425556
 [1520] 1.8156352 1.7703446 2.9682757 1.3980293 1.4735470 2.4985212 2.6476295
 [1527] 1.7992441 2.4401776 1.6740946 1.5799676 1.7482169 1.5479327 1.5423425
 [1534] 1.5915938 1.7080521 1.7269673 2.9541361 2.7513348 3.0146545 1.7338068
 [1541] 1.7323944 2.6578593 1.3812448 1.3425699 1.9873478 1.9059991 2.2159161
 [1548] 3.3111863 2.5085538 2.3223989 1.3108459 2.4543293 1.9937252 1.3412093
 [1555] 1.3050929 0.8274462 0.6407879 2.5834263 2.1444561 1.9381781 1.5631519
 [1562] 1.8997523 2.2336292 1.3636012 2.0800402 2.7078161 2.0282773 1.8230961
 [1569] 1.9817930 2.8648175 2.2957604 2.0282359 2.0288870 2.0949062 2.1427398
 [1576] 2.3288529 1.9341617 2.0314935 1.4331759 1.9775864 2.2408967 1.7030411
 [1583] 2.1524414 2.5087400 2.6539408 1.7217036 3.5282050 1.7519869 2.0137228
 [1590] 2.8141728 1.4091160 2.4559239 2.1685287 1.5692060 2.0649906 2.5576149
 [1597] 1.4409497 1.2140295 1.9720802 2.3225114 2.7861322 2.1214597 1.7566575
 [1604] 1.9111392 2.1612813 1.7207380 1.4280054 1.8818796 1.7250830 1.6525503
 [1611] 1.8450259 2.8424223 1.3550828 1.9992984 1.9840518 2.1858557 2.0172302
 [1618] 1.7707561 2.5847353 2.7356099 2.5195430 1.4252174 2.6882671 2.7022521
 [1625] 2.1283048 1.4057567 2.6806284 2.2183981 2.3038260 1.3141758 1.9107594
 [1632] 1.8038248 2.2729532 1.9808316 2.0757180 1.1531426 2.4022328 2.0856285
 [1639] 1.2295456 1.6536496 1.4981456 1.8064713 1.7837781 1.7159192 1.7181898
 [1646] 2.4740558 2.1645788 1.6149456 2.1906963 2.5655469 1.4642338 1.8948664
 [1653] 3.1719664 2.8531905 1.6767460 1.7474705 1.2851648 1.6667948 1.7942649
 [1660] 2.5401212 1.9328823 2.3239564 1.9828814 2.2113619 2.2075935 2.7523052
 [1667] 2.7820856 2.7837848 2.1011228 2.0780200 2.4726207 2.2660075 3.1794676
 [1674] 1.3303654 1.5766096 2.2202739 2.4036217 1.6707557 2.5022820 1.6697192
 [1681] 2.0836454 1.9459041 2.6539138 2.9038973 2.1884333 1.9858134 2.3643602
 [1688] 2.5762729 2.1990371 2.0189377 2.1086778 2.2275894 2.9602234 1.7087969
 [1695] 1.2009244 2.1464117 1.3199310 3.4165905 1.8427137 1.4498840 1.6668377
 [1702] 1.6102591 1.9675495 2.8107734 1.9479669 2.0274187 1.0767825 2.9583265
 [1709] 2.8268866 1.6375743 1.8635546 2.4197779 2.9514425 1.5847070 1.3989746
 [1716] 1.7557213 2.3561773 2.1168955 1.2522173 2.8152232 2.1495666 1.5003418
 [1723] 2.3739943 2.6091139 2.0562972 2.5414926 2.7722676 1.7062785 1.6964906
 [1730] 1.4550639 2.4649422 1.7992564 2.1822209 1.5602313 2.9688485 3.1514240
 [1737] 1.5146214 2.2714338 3.3506425 3.1658628 2.7605316 2.4024079 2.9346228
 [1744] 1.9046767 2.0443949 3.3903785 3.0972659 2.1984827 3.0680273 3.2256019
 [1751] 2.1678182 2.3835869 3.1025170 2.2246250 2.8557598 2.4867065 2.4925121
 [1758] 3.1541017 1.8453449 2.8210574 2.9405975 3.4686031 1.3778755 3.0219114
 [1765] 3.3284375 2.3738620 1.4335942 2.4083683 2.5483782 3.4307824 3.1366634
 [1772] 3.5756015 2.4581203 3.0536542 2.8521533 2.2467038 2.3928706 2.4514678
 [1779] 2.4432787 3.3572907 2.8848542 3.1562419 3.0060458 1.4027771 2.9726724
 [1786] 2.1125311 2.0827517 1.2039663 2.4066767 3.1743434 2.9644664 1.4147863

In [45]:
lgbclsmin

      [,1]       [,2]       [,3]       [,4]       [,5]
 [1,] 0.17213631 0.23578240 0.48562799 0.09869372 0.007759576
 [2,] 0.28779525 0.15844205 0.33630051 0.20003993 0.017422245
 [3,] 0.16686318 0.15671453 0.57916893 0.09025152 0.007001848
 [4,] 0.20263797 0.14865945 0.53019196 0.08813424 0.030376390
 [5,] 0.46342306 0.14797212 0.14301295 0.11437646 0.131215409
 [6,] 0.17649596 0.21378529 0.15050249 0.25941275 0.199803511
 [7,] 0.21634225 0.14265185 0.30874899 0.13745839 0.194798520
 [8,] 0.20660424 0.18877573 0.13433325 0.17582104 0.294465737
 [9,] 0.30788284 0.13558092 0.20204487 0.10589043 0.248600944
[10,] 0.17365901 0.16443626 0.18487890 0.20597654 0.271049292
[11,] 0.46857582 0.12096755 0.13539181 0.11009021 0.164974613
[12,] 0.24887334 0.19100259 0.26118302 0.11165419 0.187286854
[13,] 0.23806153 0.11165801 0.14675366 0.25364340 0.249883397
[14,] 0.10413701 0.11895972 0.17510134 0.34357080 0.258231141
[15,] 0.25697717 0.14350220 0.26262652 0.14891545 0.187978672
[16,] 0.09729386 0.10137946 0.18921573 0.26719490 0.344916051
[17,] 0.09627803 0.21687692 0.16926470 0.20204579 0.315534560
[18,] 0.21411633 0.16951032 0.27651081 0.15607430 0.183788236
[19,] 0.18592619 0.14589229 0.22918989 0.19878503 0.240206597
[20,] 0.13363575 0.13271938 0.14547791 0.17586202 0.412304947
[21,] 0.25927990 0.15559736 0.24184273 0.15990978 0.183370233
[22,] 0.11804294 0.14763638 0.15181492 0.24233510 0.340170656
[23,] 0.10256430 0.05941891 0.07761594 0.17836037 0.582040473
[24,] 0.23656139 0.35745306 0.09650827 0.12498720 0.184490076
[25,] 0.27000741 0.18874404 0.13797956 0.14526570 0.258003290
[26,] 0.17148394 0.18809375 0.21901790 0.23208548 0.189318939
[27,] 0.24663222 0.18921578 0.10398745 0.35083313 0.109331423
[28,] 0.10966700 0.13227402 0.13541000 0.22633289 0.396316099
[29,] 0.19108917 0.16191908 0.28877971 0.22395201 0.134260031
[30,] 0.34864254 0.12332056 0.20965874 0.16193285 0.156445309
[31,] ⋮          ⋮          ⋮          ⋮          ⋮
[32,] 0.06539165 0.10682410 0.15565438 0.31444931 0.3576806
[33,] 0.08923374 0.15946840 0.23079004 0.27138678 0.2491210
[34,] 0.05520607 0.08138460 0.21913453 0.19422895 0.4500458
[35,] 0.51835854 0.09880798 0.15754315 0.07842712 0.1468632
[36,] 0.28474537 0.18161015 0.18161444 0.21104547 0.1409846
[37,] 0.31807795 0.08462862 0.12153958 0.19013760 0.2856163
[38,] 0.04426502 0.12882835 0.27685409 0.25016848 0.2998841
[39,] 0.07950538 0.08288970 0.19501844 0.28858367 0.3540028
[40,] 0.08312053 0.08365069 0.19465473 0.25932538 0.3792487
[41,] 0.04606642 0.06256565 0.14763307 0.19494568 0.5487892
[42,] 0.10826748 0.14990155 0.18962484 0.28909523 0.2631109
[43,] 0.11455027 0.14884540 0.18828882 0.28705838 0.2612571
[44,] 0.13127922 0.09371291 0.41859488 0.15891216 0.1975008
[45,] 0.08312053 0.08365069 0.19465473 0.25932538 0.3792487
[46,] 0.02827542 0.05232969 0.30675158 0.37960105 0.2330423
[47,] 0.03007948 0.04959331 0.37260632 0.32686467 0.2208562
[48,] 0.08032818 0.06733154 0.10257929 0.21207334 0.5376877
[49,] 0.07588518 0.07091122 0.10525390 0.21760285 0.5303469
[50,] 0.01784640 0.03500115 0.05044934 0.14926209 0.7474410
[51,] 0.07263671 0.09462176 0.10571686 0.29782982 0.4291949
[52,] 0.11533293 0.08598306 0.11740702 0.34081487 0.3404621
[53,] 0.11470825 0.42169165 0.15587036 0.19153594 0.1161938
[54,] 0.04672280 0.09009493 0.04499681 0.26283756 0.5553479
[55,] 0.37923427 0.05951077 0.10531107 0.09652469 0.3594192
[56,] 0.01880469 0.08309022 0.35292799 0.33863038 0.2065467
[57,] 0.26222398 0.11767457 0.29997283 0.12578623 0.1943424
[58,] 0.08488726 0.07207201 0.15761663 0.30733548 0.3780886
[59,] 0.07477931 0.07309804 0.18461375 0.27073950 0.3967694
[60,] 0.19857994 0.13504360 0.38568407 0.17795783 0.1027346
[61,] 0.17102254 0.33016527 0.21852260 0.17624029 0.1040493

In [46]:
datalength=dim(data)[1]
lgbclsm=matrix(lgbclsmin,m,datalength)
lgbclsminr=matrix(0,datalength,1)
for(i in 1:datalength)
    {
    lgbclsminr[i,]=which.max(lgbclsm[,i])
}
lgbclsminr=lgbclsminr-1

In [47]:
lgbclsminr

      [,1]
 [1,] 4
 [2,] 3
 [3,] 0
 [4,] 2
 [5,] 4
 [6,] 4
 [7,] 2
 [8,] 4
 [9,] 0
[10,] 0
[11,] 4
[12,] 1
[13,] 2
[14,] 2
[15,] 4
[16,] 4
[17,] 2
[18,] 1
[19,] 1
[20,] 4
[21,] 2
[22,] 4
[23,] 3
[24,] 1
[25,] 1
[26,] 0
[27,] 4
[28,] 0
[29,] 4
[30,] 4
[31,] ⋮
[32,] 0
[33,] 2
[34,] 3
[35,] 2
[36,] 0
[37,] 1
[38,] 3
[39,] 1
[40,] 0
[41,] 1
[42,] 0
[43,] 2
[44,] 3
[45,] 4
[46,] 0
[47,] 3
[48,] 1
[49,] 2
[50,] 3
[51,] 3
[52,] 2
[53,] 4
[54,] 0
[55,] 4
[56,] 2
[57,] 4
[58,] 3
[59,] 3
[60,] 2
[61,] 2

In [48]:
xgbregmean=predict(xgb_mean_reg,alldataxgb)
xgbclsmean=predict(xgb_mean_cl,alldataxgb)
lgbregmean=predict(lgb_mean_reg,as.matrix(data))
lgbclsmean=predict(lgb_mean_cl,as.matrix(data))

In [49]:
lgbclsm=matrix(lgbclsmean,m,datalength)
lgbclsmeanr=matrix(0,datalength,1)
for(i in 1:datalength)
    {
    lgbclsmeanr[i,]=which.max(lgbclsm[,i])
}
lgbclsmeanr=lgbclsmeanr-1

In [50]:
preallmin=cbind(xgbclsmin,xgbregmin)
preallmin=cbind(preallmin,lgbclsminr)
preallmin=cbind(preallmin,lgbregmin)

In [51]:
colnames(preallmin)=c('xgbclsmin','xgbregmin','lgbclsmin','lgbregmin')
head(preallmin)

     xgbclsmin xgbregmin lgbclsmin lgbregmin
[1,] 2         1.678847  4         1.507120
[2,] 2         2.196492  3         1.596278
[3,] 2         2.039880  0         1.354261
[4,] 2         1.631919  2         1.392353
[5,] 0         1.130262  4         1.363482
[6,] 4         2.234442  4         1.973866

In [52]:
preallmean=cbind(xgbclsmean,xgbregmean)
preallmean=cbind(preallmean,lgbclsmeanr)
preallmean=cbind(preallmean,lgbregmean)

In [53]:
head(preallmean)

     xgbclsmean xgbregmean   lgbregmean
[1,] 1          1.405556   4 1.069478
[2,] 2          1.583426   4 1.256274
[3,] 2          1.417093   2 1.160063
[4,] 1          0.679006   3 1.199624
[5,] 0          0.529897   3 1.039940
[6,] 0          1.784399   4 1.722238

In [54]:
colnames(preallmean)=c('xgbclsmean','xgbregmean','lgbclsmean','lgbregmean')
head(preallmean)

     xgbclsmean xgbregmean lgbclsmean lgbregmean
[1,] 1          1.405556   4          1.069478
[2,] 2          1.583426   4          1.256274
[3,] 2          1.417093   2          1.160063
[4,] 1          0.679006   3          1.199624
[5,] 0          0.529897   3          1.039940
[6,] 0          1.784399   4          1.722238

In [55]:
end_time = Sys.time()
time_matrix[4,]=end_time-start_time

In [56]:
result_list=list(preallmin,preallmean,time_matrix)

In [57]:
save(result_list, file = "Quarterly_nnetar_opt_pre_result.RData")

In [58]:
time_matrix

     user_time system_time elapsed_time
[1,] 8.286007  8.286007    8.286007
[2,] 9.302883  9.302883    9.302883
[3,] 3.541730  3.541730    3.541730
[4,] 1.551108  1.551108    1.551108