In [1]:
library(forecast)
library(M4comp2018)
library(dplyr)

Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo


载入程辑包：‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [2]:
nnetarl=load('Weekly_nnetar_datalist.RData')
nnetar_datalist <- eval(parse(text = nnetarl))

In [3]:
nnetar_predh=nnetar_datalist[[2]]

In [4]:
nnetar_pred_res=nnetar_datalist[[1]]

In [5]:
nnetaroptl=load('Weekly_nnetar_opt_pre_result.RData')
nnetar_opt_pre_list<- eval(parse(text = nnetaroptl))

In [6]:
time_matrix <- matrix(0,ncol = 3, nrow =3)
colnames(time_matrix) <- c("user_time", "system_time", "elapsed_time")
start_time = Sys.time()

In [7]:
nnetar_pr_min=nnetar_opt_pre_list[[1]]
nnetar_pr_mean=nnetar_opt_pre_list[[2]]

In [8]:
head(nnetar_pr_min)

     xgbclsmin xgbregmin lgbclsmin lgbregmin
[1,] 4         3.9998839 4         3.8729042
[2,] 3         3.0023022 2         3.3909022
[3,] 3         3.0000095 1         3.3132155
[4,] 1         1.0013728 3         1.2361608
[5,] 1         0.9992362 1         0.7726074
[6,] 1         0.9997280 3         1.0258343

In [9]:
nnetar_pr_min=nnetar_pr_min+1
nnetar_pr_mean=nnetar_pr_mean+1

In [10]:
head(nnetar_pr_min)

     xgbclsmin xgbregmin lgbclsmin lgbregmin
[1,] 5         4.999884  5         4.872904
[2,] 4         4.002302  3         4.390902
[3,] 4         4.000010  2         4.313215
[4,] 2         2.001373  4         2.236161
[5,] 2         1.999236  2         1.772607
[6,] 2         1.999728  4         2.025834

In [11]:
round5=function(x)
    {
    l=round(x)
    for(i in 1:length(l))
    {
    if(l[i]>5)
        {
        l[i]=5
    }
    if(l[i]<1)
    {
        l[i]=1
    }
}
    return(l)
}

In [12]:
nnetar_pr_min[,2]=round5(nnetar_pr_min[,2])
nnetar_pr_min[,4]=round5(nnetar_pr_min[,4])

In [13]:
nnetar_pr_mean[,2]=round5(nnetar_pr_mean[,2])
nnetar_pr_mean[,4]=round5(nnetar_pr_mean[,4])

In [14]:
head(nnetar_pr_min)

     xgbclsmin xgbregmin lgbclsmin lgbregmin
[1,] 5         5         5         5
[2,] 4         4         3         4
[3,] 4         4         2         4
[4,] 2         2         4         2
[5,] 2         2         2         2
[6,] 2         2         4         2

In [15]:
Weekly_M4 <- Filter(function(l) l$period == "Weekly", M4)

In [16]:
data=Weekly_M4

In [17]:
datalength=length(data)
h=data[[1]]$h
m=5
n=4
freq=frequency(data[[1]]$x)

In [18]:
realxx=matrix(0,datalength,h)
for(i in 1:datalength){
    realxx[i,]=data[[i]]$xx
}

In [19]:
length5=matrix(0,datalength,m)
for(k in 1:datalength)
{
y = data[[k]]$x
y_l=length(y)
loc = 1:length(y)
loc_m = as.integer(loc*m/length(y))
filt_d = data.frame(y,loc_m)
filt_0=filter(filt_d ,loc_m==0)
m_l=count(filt_0)
m_l=as.integer(m_l)
length5[k,]=c(0,1*m_l,2*m_l,3*m_l,4*m_l)
    }

In [91]:
data[[3]]

$st
[1] "W3"

$x
Time Series:
Start = 261
End = 2438
Frequency = 1
   [1]  258.7  259.8  260.2  260.8  261.1  263.1  264.5  266.3  267.2  269.2
  [11]  270.7  271.7  273.6  275.1  276.1  276.2  276.9  277.6  278.9  279.5
  [21]  280.8  281.9  283.8  285.0  286.3  287.6  288.8  289.3  289.6  289.8
  [31]  290.0  290.7  290.4  290.6  291.4  291.8  291.4  291.4  292.2  293.4
  [41]  294.4  294.7  294.7  294.5  295.6  296.2  297.2  297.7  299.4  300.0
  [51]  300.5  301.2  302.5  305.0  306.3  308.3  309.8  312.5  314.0  314.9
  [61]  315.4  316.5  317.8  318.3  319.0  320.5  321.6  321.1  322.6  323.8
  [71]  325.4  326.5  327.1  327.2  327.6  327.5  327.0  327.1  328.0  329.3
  [81]  329.7  330.5  331.0  332.2  333.0  333.9  335.2  336.8  337.9  338.5
  [91]  339.6  341.5  343.6  344.6  346.3  346.9  348.1  348.3  349.2  350.0
 [101]  351.8  353.4  354.1  354.0  356.7  359.5  360.6  362.2  362.7  364.1
 [111]  365.3  366.4  367.4  369.0  370.9  372.1  373.2  375.4  376.5  375.6
 [121]  375.8  376.2  377.9  378.5  378.9  379.3  380.1  380.5  380.3  380.0
 [131]  381.0  381.9  381.6  381.7  381.5  381.9  382.0  381.8  381.7  382.0
 [141]  382.4  381.7  382.1  383.2  384.3  383.7  383.4  382.2  382.1  382.3
 [151]  382.4  382.2  382.6  383.0  382.0  382.5  385.1  386.8  387.1  387.2
 [161]  387.2  387.9  388.9  389.7  390.0  390.7  391.7  392.2  392.4  394.0
 [171]  394.7  393.8  393.3  393.0  394.0  394.9  395.3  396.0  396.4  396.7
 [181]  396.1  396.5  397.8  397.2  396.4  396.2  396.3  396.4  397.2  396.7
 [191]  397.1  398.7  399.0  399.1  399.9  401.9  403.8  402.3  401.0  400.4
 [201]  399.9  400.1  398.1  399.2  399.4  398.1  397.2  398.0  401.4  402.0
 [211]  401.4  401.1  400.7  400.8  401.7  401.8  401.6  401.9  403.3  403.7
 [221]  404.6  406.3  408.2  407.5  407.4  407.5  408.8  409.6  410.4  411.3
 [231]  412.7  414.2  414.5  414.6  415.0  416.8  417.5  418.2  418.5  419.6
 [241]  420.2  421.2  421.6  421.7  423.1  422.6  422.9  423.9  425.9  425.8
 [251]  425.9  425.4  425.8  426.3  426.3  426.1  426.5  427.7  427.5  427.7
 [261]  427.8  430.4  431.8  432.4  434.8  475.3  476.0  478.0  480.1  482.3
 [271]  485.6  486.8  488.3  489.1  491.8  492.5  491.2  491.6  492.0  494.9
 [281]  497.4  499.3  500.9  504.1  505.4  507.1  508.6  511.4  513.1  514.2
 [291]  514.9  516.1  517.6  517.7  518.9  518.7  519.7  520.1  522.1  520.9
 [301]  523.0  525.2  525.1  525.5 1182.7 1182.9 1183.7 1183.8 1184.0 1186.0
 [311] 1184.9 1183.5 1186.0 1190.6 1193.1 1194.7 1195.1 1197.7 1202.0 1204.4
 [321] 1206.5 1211.2 1215.2 1218.9 1222.6 1227.7 1234.3 1235.6 1232.5 1231.7
 [331] 1233.8 1236.6 1236.9 1237.3 1239.1 1243.1 1243.8 1244.1 1245.5 1253.5
 [341] 1255.1 1257.9 1259.8 1262.4 1265.7 1268.7 1270.5 1272.5 1276.8 1277.9
 [351] 1278.6 1282.0 1291.5 1296.0 1296.7 1297.7 1300.4 1303.7 1306.0 1306.0
 [361] 1309.2 1312.7 1313.9 1313.2 1312.4 1317.6 1321.6 1325.1 1326.4 1328.3
 [371] 1331.4 1332.6 1333.3 1335.4 1340.5 1343.8 1346.8 1351.4 1358.7 1359.3
 [381] 1355.6 1354.4 1356.0 1359.6 1363.1 1365.9 1370.4 1374.1 1376.1 1376.3
 [391] 1377.9 1384.9 1383.1 1384.5 1386.3 1388.9 1393.1 1395.8 1397.5 1399.1
 [401] 1401.9 1402.4 1401.9 1402.6 1408.3 1408.1 1409.5 1410.7 1412.2 1414.5
 [411] 1415.5 1416.7 1416.8 1417.6 1412.9 1429.8 1438.5 1452.3 1468.5 1480.9
 [421] 1488.8 1496.0 1505.5 1510.9 1513.8 1516.5 1522.5 1525.4 1527.4 1529.7
 [431] 1535.5 1537.6 1534.4 1530.7 1532.9 1535.3 1537.4 1540.0 1542.4 1547.9
 [441] 1550.5 1547.0 1546.2 1554.2 1558.1 1559.4 1560.0 1560.4 1563.5 1564.8
 [451] 1564.7 1564.3 1567.3 1568.9 1569.0 1569.6 1576.1 1582.7 1584.8 1586.6
 [461] 1588.1 1593.5 1596.3 1596.5 1596.9 1599.5 1601.0 1599.6 1598.9 1606.2
 [471] 1613.1 1616.4 1616.9 1613.7 1625.6 1629.8 1632.0 1633.3 1638.7 1643.2
 [481] 1645.0 1647.3 1655.7 1659.9 1657.8 1654.4 1651.6 1654.8 1659.4 1662.2
 [491] 1664.2 1668.8 1673.0 1672.7 1671.4 1678.0 1682.8 1685.1 1685.6 1685.8
 [501] 1688.6 1689.1 1689.7 1690.5 1693.5 1698.1 1699.9 1699.7 1706.7 1713.5
 [511] 1717.0 1718.4 1720.3 1727.2 1734.0 1737.1 1740.0 1745.6 1751.2 1753.2
 [521] 1754.1 1759.6 1770.0 1779.4 1781.2 1781.4 1785.2 1790.3 1792.0 1792.9
 [531] 1797.4 1800.9 1801.1 1802.0 1807.2 1810.5 1807.5 1802.5 1797.9 1800.3
 [541] 1804.5 1807.5 1810.4 1816.4 1825.0 1828.2 1829.9 1835.4 1840.8 1844.3
 [551] 1843.5 1842.8 1845.3 1848.2 1847.9 1847.6 1848.1 1850.7 1851.3 1849.0
 [561] 1852.3 1860.0 1862.4 1861.4 1860.3 1863.1 1866.5 1866.8 1868.0 1869.2
 [571] 1872.7 1871.0 1868.6 1869.9 1881.2 1885.2 1885.7 1884.7 1884.7 1889.2
 [581] 1889.2 1889.6 1892.9 1899.0 1902.4 1904.4 1910.9 1919.4 1921.6 1917.0
 [591] 1914.4 1916.7 1922.5 1925.4 1929.5 1932.5 1940.0 1943.3 1943.3 1945.2
 [601] 1955.2 1959.0 1960.5 1960.7 1963.6 1968.2 1967.7 1967.4 1968.2 1974.0
 [611] 1976.5 1977.8 1979.9 1989.6 1994.4 1992.9 1991.7 1992.9 1995.2 1996.7
 [621] 1997.6 1998.0 2000.3 2000.9 1999.1 2001.1 2013.7 2020.3 2017.5 2015.1
 [631] 2012.3 2018.2 2019.1 2018.1 2019.2 2024.8 2025.9 2023.9 2025.1 2033.1
 [641] 2034.7 2026.1 2019.4 2017.9 2018.2 2018.9 2021.5 2025.0 2032.3 2031.8
 [651] 2027.2 2026.2 2037.0 2040.4 2039.6 2038.7 2039.9 2044.6 2044.0 2043.4
 [661] 2042.2 2048.3 2052.3 2048.7 2045.8 2053.4 2057.6 2056.8 2060.8 2059.8
 [671] 2063.8 2066.3 2067.7 2067.6 2073.2 2075.1 2072.8 2070.4 2077.6 2088.5
 [681] 2095.3 2096.6 2100.7 2108.8 2113.6 2116.9 2119.1 2127.7 2133.2 2136.9
 [691] 2139.2 2147.9 2155.3 2148.5 2142.2 2139.2 2143.0 2146.4 2150.3 2150.7
 [701] 2156.0 2158.3 2155.3 2156.0 2163.2 2169.0 2170.7 2168.3 2167.7 2169.9
 [711] 2170.8 2171.1 2168.3 2170.8 2173.3 2171.4 2168.7 2174.7 2182.1 2184.5
 [721] 2181.8 2182.1 2193.5 2196.8 2199.0 2198.2 2199.0 2201.1 2198.5 2195.2
 [731] 2200.9 2208.2 2211.6 2209.2 2204.1 2208.8 2211.9 2212.8 2213.4 2219.8
 [741] 2224.8 2225.7 2227.1 2235.4 2242.5 2238.7 2228.7 2223.3 2225.6 2229.6
 [751] 2233.8 2234.6 2242.7 2251.3 2251.7 2251.8 2261.2 2274.0 2277.9 2277.9
 [761] 2279.7 2289.8 2295.6 2297.8 2299.2 2304.1 2309.5 2311.4 2308.6 2315.5
 [771] 2324.8 2327.0 2329.3 2330.2 2341.1 2347.8 2347.8 2349.2 2354.3 2358.2
 [781] 2356.7 2353.3 2358.3 2369.0 2373.4 2372.4 2370.0 2378.0 2384.9 2386.1
 [791] 2387.5 2391.2 2398.4 2400.1 2400.9 2406.2 2414.1 2410.3 2398.6 2394.1
 [801] 2392.3 2394.5 2390.8 2391.0 2397.5 2403.2 2406.7 2400.3 2405.0 2413.0
 [811] 2417.8 2414.3 2414.1 2419.7 2427.5 2428.1 2429.7 2431.8 2436.3 2434.5
 [821] 2429.1 2431.8 2441.0 2441.7 2437.7 2435.0 2436.9 2442.4 2442.0 2442.7
 [831] 2443.2 2447.1 2445.5 2439.7 2440.1 2448.2 2460.6 2462.4 2460.6 2465.2
 [841] 2474.0 2473.8 2477.8 2484.1 2491.6 2496.2 2496.7 2498.2 2507.9 2507.1
 [851] 2494.2 2484.6 2486.6 2491.8 2491.1 2490.8 2492.3 2498.5 2497.7 2488.3
 [861] 2488.5 2495.9 2499.8 2493.7 2487.6 2486.7 2491.8 2488.8 2487.8 2484.0
 [871] 2487.9 2486.7 2478.6 2472.4 2480.9 2485.3 2480.6 2476.0 2475.6 2481.9
 [881] 2480.6 2478.5 2474.6 2479.8 2482.1 2465.1 2456.9 2457.0 2470.4 2470.1
 [891] 2467.2 2468.0 2476.2 2476.4 2473.5 2474.7 2479.4 2478.9 2472.5 2468.8
 [901] 2476.0 2480.9 2462.7 2449.6 2447.3 2449.1 2447.0 2440.2 2439.5 2445.9
 [911] 2445.4 2433.7 2424.9 2430.0 2439.2 2430.8 2425.9 2424.5 2428.6 2428.3
 [921] 2424.5 2421.8 2424.7 2425.9 2415.7 2408.6 2411.4 2424.4 2420.2 2412.9
 [931] 2413.5 2418.5 2415.4 2406.7 2403.3 2407.3 2405.9 2392.4 2381.3 2383.5
 [941] 2393.3 2387.2 2377.5 2370.9 2378.4 2380.0 2378.4 2376.1 2382.9 2383.8
 [951] 2377.4 2375.0 2377.9 2386.7 2371.0 2360.4 2361.0 2369.9 2369.4 2366.0
 [961] 2366.1 2376.7 2379.0 2363.8 2353.5 2355.4 2368.3 2361.0 2352.8 2352.0
 [971] 2358.9 2356.5 2350.3 2343.2 2347.3 2354.4 2341.8 2336.1 2338.4 2348.9
 [981] 2341.9 2333.6 2335.7 2345.8 2348.5 2345.2 2340.6 2347.9 2353.6 2339.9
 [991] 2330.6 2329.4 2342.6 2346.1 2335.7 2326.7 2335.2 2339.4 2332.9 2331.3
[1001] 2342.7 2350.8 2347.7 2339.6 2348.3 2362.7 2352.3 2341.2 2336.3 2343.7
[1011] 2343.3 2342.2 2336.3 2339.5 2341.6 2330.1 2328.0 2332.0 2343.4 2342.3
[1021] 2336.4 2334.6 2340.6 2339.6 2336.6 2328.2 2329.2 2335.9 2329.7 2322.2
[1031] 2321.3 2332.7 2331.9 2325.7 2323.9 2331.1 2334.9 2334.5 2332.9 2335.4
[1041] 2339.0 2331.6 2324.5 2322.1 2331.6 2338.5 2334.7 2329.0 2333.5 2338.8
[1051] 2335.8 2336.9 2340.1 2351.1 2350.5 2351.3 2353.8 2367.7 2364.8 2354.2
[1061] 2348.3 2361.0 2364.9 2372.2 2377.8 2392.5 2406.8 2403.0 2398.2 2403.6
[1071] 2418.5 2423.3 2424.1 2422.7 2438.6 2443.4 2443.9 2443.5 2448.1 2455.5
[1081] 2454.6 2449.1 2453.7 2471.9 2469.4 2463.2 2461.2 2473.6 2483.1 2481.8
[1091] 2483.2 2490.7 2502.2 2501.3 2493.4 2492.6 2513.6 2531.7 2520.6 2512.4
[1101] 2522.4 2537.0 2541.5 2543.9 2556.8 2571.1 2575.3 2570.3 2575.2 2601.1
[1111] 2602.0 2580.6 2562.0 2573.0 2584.6 2579.4 2580.3 2588.6 2610.1 2609.4
[1121] 2595.6 2596.1 2622.6 2623.8 2621.0 2614.8 2632.1 2642.8 2643.0 2638.4
[1131] 2637.0 2659.0 2656.7 2641.6 2633.5 2670.0 2679.5 2673.0 2667.5 2681.4
[1141] 2702.8 2699.0 2695.3 2700.3 2731.2 2728.3 2719.7 2708.4 2732.9 2750.5
[1151] 2744.6 2725.7 2730.2 2758.3 2759.3 2748.4 2761.6 2796.7 2794.8 2787.5
[1161] 2784.7 2832.8 2843.1 2821.9 2784.9 2790.4 2804.4 2799.5 2798.5 2798.5
[1171] 2837.9 2830.5 2812.1 2800.8 2847.7 2849.1 2836.9 2825.0 2846.7 2874.1
[1181] 2875.0 2865.0 2865.8 2902.5 2905.8 2883.0 2863.5 2900.7 2916.8 2911.5
[1191] 2895.5 2897.3 2933.9 2933.4 2924.4 2925.2 2960.0 2952.3 2939.4 2925.6
[1201] 2951.0 2985.0 2978.1 2954.4 2955.2 3000.4 3002.8 2998.9 3006.8 3050.9
[1211] 3049.9 3037.0 3029.2 3083.8 3103.6 3082.4 3040.0 3040.7 3063.4 3056.9
[1221] 3051.5 3057.7 3102.9 3098.3 3079.3 3058.8 3106.8 3119.3 3105.7 3089.9
[1231] 3097.6 3147.8 3144.2 3130.8 3124.7 3187.9 3190.3 3166.6 3134.8 3176.3
[1241] 3207.3 3204.6 3189.2 3193.8 3245.6 3244.9 3225.6 3213.3 3275.5 3278.2
[1251] 3260.9 3244.3 3256.6 3310.6 3308.7 3274.4 3271.1 3324.7 3324.8 3310.0
[1261] 3310.5 3358.0 3352.2 3337.3 3322.2 3373.8 3399.4 3389.5 3344.7 3313.4
[1271] 3362.2 3356.4 3343.1 3344.7 3400.9 3399.7 3376.3 3347.6 3394.0 3420.4
[1281] 3407.9 3390.2 3391.9 3442.6 3439.8 3422.3 3411.9 3464.5 3473.5 3451.6
[1291] 3416.8 3443.8 3474.8 3471.8 3444.9 3446.6 3489.2 3489.6 3473.4 3461.6
[1301] 3510.9 3513.8 3502.3 3477.1 3478.8 3545.7 3546.3 3521.2 3507.0 3567.5
[1311] 3564.5 3554.3 3546.3 3599.0 3616.7 3617.8 3597.4 3622.2 3696.3 3695.5
[1321] 3652.9 3604.0 3626.4 3622.2 3605.9 3596.2 3649.5 3664.6 3641.9 3603.1
[1331] 3612.2 3670.4 3665.4 3643.1 3634.4 3708.0 3703.2 3693.4 3670.5 3715.6
[1341] 3757.9 3748.0 3701.9 3710.9 3767.6 3767.9 3731.7 3704.9 3773.2 3787.2
[1351] 3769.9 3753.1 3796.8 3829.2 3829.2 3808.4 3812.4 3884.2 3892.4 3859.2
[1361] 3812.6 3876.3 3902.9 3897.6 3888.7 3949.9 3976.8 3967.1 3952.1 3976.0
[1371] 4066.1 4071.9 4020.1 3946.5 3995.7 3993.3 3971.2 3945.1 4008.4 4039.4
[1381] 4030.2 3975.1 3986.1 4057.9 4049.2 4010.0 3993.5 4073.0 4081.0 4059.9
[1391] 4030.5 4047.7 4134.6 4166.2 4107.9 4097.2 4164.9 4165.6 4125.8 4097.9
[1401] 4178.4 4204.6 4197.1 4171.4 4192.2 4260.0 4260.1 4211.6 4196.1 4267.7
[1411] 4269.4 4232.1 4189.0 4240.9 4282.2 4268.2 4249.7 4292.8 4323.2 4308.3
[1421] 4259.9 4283.7 4357.8 4364.4 4302.7 4226.8 4300.1 4315.6 4294.1 4257.1
[1431] 4273.9 4350.4 4350.8 4286.6 4289.6 4375.7 4375.0 4338.4 4317.8 4424.0
[1441] 4445.3 4421.1 4373.4 4373.9 4484.2 4479.5 4408.5 4374.1 4488.9 4492.3
[1451] 4466.6 4418.2 4496.7 4546.5 4551.8 4487.5 4498.8 4569.2 4569.9 4512.4
[1461] 4475.1 4570.4 4586.2 4551.7 4489.9 4497.4 4593.4 4596.4 4544.5 4564.4
[1471] 4639.4 4643.1 4581.6 4575.2 4697.9 4700.2 4644.7 4581.7 4660.5 4679.6
[1481] 4643.9 4600.2 4629.8 4713.2 4715.9 4656.3 4635.5 4774.4 4756.5 4704.2
[1491] 4665.2 4759.5 4811.9 4804.0 4717.0 4722.9 4819.9 4808.3 4720.3 4658.5
[1501] 4765.6 4778.7 4745.0 4672.2 4688.8 4787.9 4797.0 4719.3 4728.3 4788.9
[1511] 4773.6 4723.0 4669.5 4747.2 4780.8 4738.8 4672.8 4685.7 4767.6 4770.9
[1521] 4738.1 4750.3 4832.8 4830.8 4791.2 4753.6 4877.2 4921.9 4884.7 4796.5
[1531] 4805.9 4926.8 4925.2 4846.6 4855.2 4957.1 4949.7 4885.0 4808.2 4924.5
[1541] 4965.7 4917.8 4845.7 4873.4 4967.6 4957.6 4889.6 4848.3 4992.2 5017.3
[1551] 4962.2 4877.2 4947.8 5011.0 5006.6 4918.7 4940.8 5041.7 5051.9 4985.9
[1561] 4929.3 5056.6 5071.8 5026.2 4952.9 4958.6 5082.2 5070.3 4977.6 4918.3
[1571] 5054.4 5042.2 5002.3 4978.7 5092.8 5094.1 5047.7 4996.8 5096.0 5176.2
[1581] 5157.0 5035.8 5014.8 5108.6 5103.5 5029.1 4986.3 5141.5 5154.1 5105.4
[1591] 5016.5 5104.5 5186.0 5157.1 5073.5 5101.9 5210.6 5191.2 5127.9 5061.0
[1601] 5206.4 5261.7 5212.7 5110.5 5147.0 5265.1 5284.6 5179.0 5142.4 5292.5
[1611] 5302.3 5247.4 5175.8 5283.7 5330.6 5293.9 5220.6 5242.9 5370.7 5358.1
[1621] 5285.7 5192.7 5330.2 5354.4 5330.2 5292.2 5417.5 5419.4 5372.5 5305.4
[1631] 5357.1 5500.1 5507.3 5391.1 5342.9 5417.2 5416.8 5357.0 5304.1 5452.6
[1641] 5493.3 5464.0 5372.1 5406.4 5539.7 5526.1 5429.4 5394.2 5544.1 5537.2
[1651] 5488.5 5416.3 5512.7 5598.6 5573.0 5470.9 5496.5 5615.8 5637.5 5539.8
[1661] 5483.6 5646.1 5668.9 5628.6 5570.6 5642.1 5718.1 5698.2 5634.5 5647.5
[1671] 5769.9 5751.7 5690.5 5596.0 5705.0 5749.8 5731.0 5705.1 5775.8 5821.6
[1681] 5812.1 5761.4 5796.9 5932.1 5944.3 5857.3 5747.6 5866.5 5867.0 5821.7
[1691] 5758.0 5856.2 5926.6 5924.8 5823.8 5833.9 5946.0 5929.3 5856.6 5810.4
[1701] 5950.9 5973.4 5957.1 5909.8 5910.6 6038.1 6033.8 5932.7 5929.6 6029.5
[1711] 6026.9 5953.1 5907.8 6010.2 6058.2 6059.5 5999.6 6020.3 6121.6 6117.5
[1721] 6045.5 6024.3 6138.8 6135.7 6087.6 6037.9 6127.4 6206.0 6190.8 6172.0
[1731] 6201.8 6304.1 6328.9 6272.3 6244.6 6404.5 6414.6 6349.8 6194.8 6262.4
[1741] 6318.3 6298.8 6237.6 6256.5 6345.7 6346.2 6262.4 6208.7 6348.5 6350.9
[1751] 6299.3 6220.6 6289.3 6359.4 6338.1 6260.8 6243.3 6346.9 6363.7 6375.3
[1761] 6293.8 6421.6 6497.1 6502.3 6347.8 6351.3 6484.9 6509.0 6438.7 6478.8
[1771] 6593.7 6607.1 6567.3 6512.8 6616.6 6696.7 6708.5 6635.8 6625.9 6735.8
[1781] 6747.9 6701.7 6727.7 6855.9 6891.8 6799.7 6723.7 6768.7 6885.7 6831.2
[1791] 6686.6 6744.7 6828.2 6806.1 6723.6 6736.8 6843.5 6829.1 6705.3 6609.2
[1801] 6765.8 6782.5 6725.0 6644.2 6651.6 6773.0 6750.5 6658.2 6628.1 6773.6
[1811] 6804.2 6719.3 6617.1 6729.6 6794.0 6770.7 6656.3 6670.5 6824.1 6853.0
[1821] 6760.8 6719.4 6868.3 6865.6 6781.1 6688.7 6712.8 6842.6 6803.2 6705.9
[1831] 6689.5 6808.2 6823.2 6778.4 6767.2 6877.0 6870.9 6787.6 6735.5 6892.9
[1841] 6943.3 6880.3 6752.6 6747.5 6886.2 6910.5 6797.0 6794.3 6932.2 6921.2
[1851] 6831.7 6718.6 6833.4 6899.0 6847.9 6748.5 6771.3 6902.6 6897.5 6797.7
[1861] 6746.0 6916.5 6964.8 6884.9 6775.0 6871.7 6966.5 6968.7 6836.9 6843.6
[1871] 6897.1 7002.7 6917.4 6843.2 6997.7 7030.6 6965.2 6873.2 6891.0 7061.3
[1881] 7052.6 6905.7 6835.6 7022.3 7046.5 6977.2 6941.6 7118.3 7131.2 7059.9
[1891] 6975.9 7084.9 7190.1 7168.7 7026.0 6982.9 7121.0 7132.2 7024.1 6969.4
[1901] 7149.1 7177.0 7129.0 7075.0 7193.8 7298.5 7277.8 7168.3 7216.5 7397.3
[1911] 7407.6 7315.2 7221.8 7386.1 7476.4 7400.0 7259.7 7281.0 7466.3 7492.9
[1921] 7344.1 7278.4 7483.7 7531.9 7436.2 7333.5 7485.9 7579.7 7520.2 7398.1
[1931] 7420.4 7632.5 7627.4 7486.9 7376.1 7564.8 7625.8 7563.0 7494.7 7645.3
[1941] 7717.3 7650.1 7536.0 7568.2 7778.6 7779.5 7576.3 7464.6 7676.6 7685.0
[1951] 7605.7 7501.2 7633.2 7757.2 7718.4 7554.6 7592.2 7748.7 7759.3 7627.4
[1961] 7543.7 7750.1 7797.0 7726.3 7616.1 7632.5 7869.7 7886.5 7712.4 7718.5
[1971] 7876.6 7907.2 7784.0 7671.6 7881.8 7979.9 7930.0 7821.8 7850.4 8053.7
[1981] 8084.3 7959.3 7917.1 8137.8 8126.1 7981.2 7837.0 7929.6 8062.3 8019.4
[1991] 7928.3 8067.3 8191.1 8163.0 8007.8 8023.5 8242.3 8230.8 8031.7 7853.7
[2001] 8079.0 8135.8 8046.0 7922.1 7968.4 8203.7 8189.7 7996.2 8014.8 8212.2
[2011] 8209.7 8086.9 7971.0 8174.3 8272.5 8201.2 8070.7 8074.4 8318.4 8323.3
[2021] 8174.3 8111.0 8362.7 8378.4 8310.5 8161.6 8289.2 8420.3 8395.4 8258.6
[2031] 8259.2 8460.1 8449.1 8323.3 8225.1 8432.2 8506.2 8395.7 8245.9 8219.8
[2041] 8482.2 8497.0 8381.7 8368.8 8562.9 8574.1 8430.4 8348.9 8635.2 8642.6
[2051] 8477.7 8281.8 8449.9 8553.0 8490.6 8369.9 8395.2 8592.2 8582.1 8411.6
[2061] 8339.4 8613.7 8629.6 8522.7 8391.3 8525.6 8693.7 8671.1 8527.4 8480.9
[2071] 8719.7 8727.1 8572.5 8433.9 8692.0 8759.5 8689.2 8534.7 8519.7 8813.7
[2081] 8828.5 8671.7 8653.2 8849.9 8843.1 8716.1 8589.4 8762.2 8929.9 8852.3
[2091] 8670.8 8657.2 8885.4 8899.3 8807.8 8808.1 8999.5 9013.2 8856.2 8763.8
[2101] 9074.9 9120.9 8966.7 8717.0 8829.0 8997.4 8967.9 8815.4 8818.3 9040.7
[2111] 9027.6 8865.1 8731.9 9027.3 9078.1 8965.8 8808.5 8819.9 9122.0 9123.9
[2121] 8983.0 8905.9 9201.7 9245.2 9094.1 8901.8 9119.2 9247.6 9181.2 9020.9
[2131] 9028.7 9302.0 9327.0 9167.1 9084.9 9368.2 9374.7 9268.0 9115.7 9146.0
[2141] 9529.4 9466.1 9284.9 9256.1 9459.5 9471.2 9385.7 9281.7 9586.3 9612.3
[2151] 9480.1 9349.9 9509.5 9696.4 9634.9 9363.2 9320.8 9564.6 9562.9 9421.9
[2161] 9321.0 9611.8 9675.5 9535.9 9355.5 9501.3 9708.9 9671.1 9498.5 9506.7
[2171] 9756.7 9737.7 9606.2 9457.8 9730.3 9886.8 9796.8 9573.5

$n
[1] 2178

$type
[1] Other
Levels: Demographic Finance Industry Macro Micro Other

$h
[1] 13

$period
[1] Weekly
Levels: Daily Hourly Monthly Quarterly Weekly Yearly

$xx
Time Series:
Start = 2439
End = 2451
Frequency = 1
 [1]  9602.4  9895.9  9915.9  9726.6  9626.5  9966.1 10008.5  9911.7  9760.7
[10]  9968.2 10089.1 10005.9  9823.3

$pt_ff
          [,1]     [,2]     [,3]     [,4]     [,5]     [,6]      [,7]     [,8]
 [1,] 9841.870 9929.782 9798.596 9630.768 9716.806 9987.374  9934.412 9744.142
 [2,] 9672.263 9871.002 9886.600 9700.110 9676.817 9839.982  9933.976 9817.569
 [3,] 9692.778 9794.692 9792.315 9742.141 9757.548 9766.803  9776.059 9785.314
 [4,] 9757.480 9808.607 9764.643 9676.845 9707.937 9835.352  9805.675 9756.373
 [5,] 9688.519 9780.150 9790.199 9709.281 9701.523 9776.747  9821.969 9772.891
 [6,] 9799.467 9887.906 9847.237 9704.667 9711.890 9913.615  9949.799 9810.124
 [7,] 9698.867 9775.873 9752.354 9684.552 9688.648 9779.017  9800.680 9759.115
 [8,] 9576.939 9580.356 9583.773 9587.191 9590.610 9594.029  9597.449 9600.870
 [9,] 9626.819 9662.092 9712.888 9654.633 9669.257 9757.046  9783.542 9696.548
[10,] 9712.961 9721.777 9730.600 9739.432 9748.271 9757.118  9765.974 9774.837
[11,] 9712.915 9721.700 9730.492 9739.293 9748.101 9756.918  9765.742 9774.574
[12,] 9674.064 9877.893 9857.235 9667.269 9655.059 9852.692  9928.370 9768.368
[13,] 9697.858 9701.784 9705.713 9709.644 9713.577 9717.513  9721.451 9725.390
[14,] 9745.631 9918.602 9851.842 9681.100 9735.688 9939.308  9925.879 9794.950
[15,] 9675.610 9871.316 9879.222 9706.089 9681.343 9866.212  9943.228 9849.611
[16,] 9758.313 9899.281 9843.672 9680.882 9689.969 9982.130 10009.242 9837.820
[17,] 9748.933 9758.723 9768.839 9778.145 9787.799 9797.669  9806.064 9815.371
[18,] 9691.885 9693.852 9695.819 9697.786 9699.752 9701.719  9703.686 9705.652
[19,] 9705.147 9710.901 9716.605 9722.260 9727.866 9733.423  9738.935 9744.400
[20,] 9672.263 9871.203 9887.685 9700.720 9677.376 9839.617  9934.759 9818.999
[21,] 9679.208 9879.533 9851.268 9657.688 9648.585 9853.779  9937.370 9782.324
[22,] 9711.191 9718.792 9726.242 9733.543 9740.698 9747.710  9754.582 9761.316
[23,] 9717.912 9727.579 9737.246 9746.913 9756.580 9766.246  9775.913 9785.580
[24,] 9712.268 9715.705 9719.242 9722.844 9726.501 9730.191  9733.907 9737.646
[25,] 9639.852 9936.486 9907.858 9705.821 9631.392 9852.794  9943.608 9803.618
          [,9]     [,10]     [,11]    [,12]    [,13]
 [1,] 9776.338  9995.254 10007.286 9818.312 9702.714
 [2,] 9727.415  9820.711  9948.944 9911.299 9805.750
 [3,] 9794.569  9803.825  9813.080 9822.335 9831.591
 [4,] 9737.728  9833.619  9832.798 9819.249 9731.963
 [5,] 9735.436  9779.056  9838.996 9825.401 9781.458
 [6,] 9768.226  9952.559  9974.400 9883.004 9787.063
 [7,] 9740.601  9809.958  9820.299 9817.760 9788.752
 [8,] 9604.291  9607.713  9611.135 9614.558 9617.982
 [9,] 9674.828  9763.687  9804.755 9726.843 9694.648
[10,] 9783.709  9792.589  9801.476 9810.372 9819.276
[11,] 9783.414  9792.263  9801.119 9809.983 9818.856
[12,] 9669.285  9816.033  9964.130 9871.908 9718.746
[13,] 9729.333  9733.277  9737.223 9741.172 9745.123

In [20]:
end_time = Sys.time()
time_matrix[1,]=end_time-start_time

In [21]:
end_time-start_time

Time difference of 19.35626 secs

## nnetar

In [22]:
start_time = Sys.time()

In [23]:
set.seed(100)
index = sample(2,length(data),replace = TRUE,prob=c(0.7,0.3))
testindex=c(1:length(data))[index==2]

In [24]:
meanpre=function(pred_array,opt_pr,h,testindex)
    {
    data_length=length(testindex)
    meanpreh=matrix(0,data_length,h)
    for (i in 1:data_length){
    index=testindex[i]
    loc=opt_pr[index]
    predh=pred_array[index,loc,,]
    predh=unique(predh)
    meanpreh[i,]=apply(predh,2,mean)
}
    return(meanpreh)
}

In [25]:
predres=function(pred_matrix,data,opt_pr,lengthmatrix,h,testindex)
    {
    data_length=length(testindex)
    pred_res=matrix(0,data_length,6)
    model=ets(data[[1]]$x)
    fore_l=forecast(model,h=h)
    freq=frequency(data[[1]]$x)
    for (i in 1:data_length){
    index=testindex[i]
    loc=opt_pr[index]
    start=lengthmatrix[i,loc]
    y_all=data[[index]]$x
    y=y_all[start:length(y_all)]
    fore_l$x=ts(y,frequency=freq,end=end(y_all))
    real=data[[index]]$xx
    fore_l$mean=ts(pred_matrix[i,],start=start(real),frequency=freq)
    res=accuracy(fore_l,real)
    pred_res[i,]=res[2,1:6]
    }
    return(pred_res)
    }

In [26]:
predres_mul=function(pred_matrix,data,opt_pr_mul,lengthmatrix,h,testindex)
    {
    data_length=length(testindex)
    pred_res=matrix(0,data_length,6)
    model=ets(data[[1]]$x)
    fore_l=forecast(model,h=h)
    freq=frequency(data[[1]]$x)
    for (i in 1:data_length){
    index=testindex[i]
    loc=min(opt_pr_mul[index,])
    start=lengthmatrix[i,loc]
    y_all=data[[index]]$x
    y=y_all[start:length(y_all)]
    fore_l$x=ts(y,frequency=freq,end=end(y_all))
    real=data[[index]]$xx
    fore_l$mean=ts(pred_matrix[i,],start=start(real),frequency=freq)
    res=accuracy(fore_l,real)
    pred_res[i,]=res[2,1:6]
    }
    return(pred_res)
    }

In [27]:
nnetarxgbcls_min=meanpre(nnetar_predh,nnetar_pr_min[,1],h,testindex)
nnetarxgbreg_min=meanpre(nnetar_predh,nnetar_pr_min[,2],h,testindex)
nnetarlgbcls_min=meanpre(nnetar_predh,nnetar_pr_min[,3],h,testindex)
nnetarlgbreg_min=meanpre(nnetar_predh,nnetar_pr_min[,4],h,testindex)

In [28]:
nnetarxgbcls_mean=meanpre(nnetar_predh,nnetar_pr_mean[,1],h,testindex)
nnetarxgbreg_mean=meanpre(nnetar_predh,nnetar_pr_mean[,2],h,testindex)
nnetarlgbcls_mean=meanpre(nnetar_predh,nnetar_pr_mean[,3],h,testindex)
nnetarlgbreg_mean=meanpre(nnetar_predh,nnetar_pr_mean[,4],h,testindex)

### The error of each improved prediction result

In [29]:
lengthtest=length5[testindex,]

In [30]:
nnetarminxgbclsres=predres(nnetarxgbcls_min,data,nnetar_pr_min[,1],lengthtest,h,testindex)
nnetarminxgbregres=predres(nnetarxgbreg_min,data,nnetar_pr_min[,2],lengthtest,h,testindex)
nnetarminlgbclsres=predres(nnetarlgbcls_min,data,nnetar_pr_min[,3],lengthtest,h,testindex)
nnetarminlgbregres=predres(nnetarlgbreg_min,data,nnetar_pr_min[,4],lengthtest,h,testindex)

Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”

In [31]:
nnetarmeanxgbclsres=predres(nnetarxgbcls_mean,data,nnetar_pr_mean[,1],lengthtest,h,testindex)
nnetarmeanxgbregres=predres(nnetarxgbreg_mean,data,nnetar_pr_mean[,2],lengthtest,h,testindex)
nnetarmeanlgbclsres=predres(nnetarlgbcls_mean,data,nnetar_pr_mean[,3],lengthtest,h,testindex)
nnetarmeanlgbregres=predres(nnetarlgbreg_mean,data,nnetar_pr_mean[,4],lengthtest,h,testindex)

Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”

In [80]:
dim(nnetarxgbcls_mean)

[1] 108  13

In [56]:
testindex

  [1]   7  12  15  22  24  27  28  32  34  36  39  42  43  44  47  48  63  74
 [19]  77  78  79  83  84  87  90  91  95 100 107 108 111 112 115 117 118 120
 [37] 127 128 132 133 144 146 147 152 156 157 158 161 168 169 170 174 175 177
 [55] 182 183 190 191 194 200 202 203 204 206 207 212 217 218 224 233 238 239
 [73] 240 242 244 246 252 255 256 260 262 264 265 266 269 270 272 276 287 288
 [91] 298 301 303 306 310 312 318 320 324 326 327 330 339 341 348 350 357 359

In [81]:

opt_pr=ddm
pred_matrix=nnetar_predh[testindex,1,1,]
data_length=length(testindex)
pred_res=matrix(0,data_length,6)
model=ets(data[[1]]$x)
fore_l=forecast(model,h=h)
freq=frequency(data[[1]]$x)
i=2
#for (i in 1:data_length){
index=testindex[i]
loc=opt_pr[index]
start=lengthtest[i,loc]
y_all=data[[index]]$x
y=y_all[start:length(y_all)]
fore_l$x=ts(y,frequency=freq,end=end(y_all))
real=data[[index]]$xx
fore_l$mean=ts(pred_matrix[i,],start=start(real),frequency=freq)
res=accuracy(fore_l,real)
pred_res[i,]=res[2,1:6]
#}

In [82]:
accuracy(fore_l,real)

             ME           RMSE        MAE         MPE          MAPE
Training set -21478.33961 24026.58321 21478.33961 -2027.789840 2027.789840
Test set         57.19977    61.88064    57.19977     5.318986    5.318986
             MASE        ACF1      Theil's U
Training set 1690.390553 0.9944919       NA
Test set        4.501742 0.5121544 3.895454

In [83]:
data[[index]]$xx

A Time Series:
 [1] 1092 1085 1078 1071 1064 1057 1050 1043 1092 1085 1078 1071 1064

In [84]:
data[[12]]$xx

A Time Series:
 [1] 1092 1085 1078 1071 1064 1057 1050 1043 1092 1085 1078 1071 1064

In [85]:
fore_l$mean

A Time Series:
 [1] 1034.8755 1028.0188 1019.0611 1010.1038 1037.6804 1040.6221 1024.2010
 [8] 1000.0991  988.0569 1008.2703 1012.1217 1001.5244  981.7680

In [86]:
nnetar_predh[12,1,1,]

 [1] 1034.8755 1028.0188 1019.0611 1010.1038 1037.6804 1040.6221 1024.2010
 [8] 1000.0991  988.0569 1008.2703 1012.1217 1001.5244  981.7680

In [75]:
ddm=matrix(1,dim(nnetar_pr_mean)[1],1)
dd=predres(nnetar_predh[testindex,1,1,],data,ddm,lengthtest,h,testindex)

In [76]:
ddm

      [,1]
 [1,] 1
 [2,] 1
 [3,] 1
 [4,] 1
 [5,] 1
 [6,] 1
 [7,] 1
 [8,] 1
 [9,] 1
[10,] 1
[11,] 1
[12,] 1
[13,] 1
[14,] 1
[15,] 1
[16,] 1
[17,] 1
[18,] 1
[19,] 1
[20,] 1
[21,] 1
[22,] 1
[23,] 1
[24,] 1
[25,] 1
[26,] 1
[27,] 1
[28,] 1
[29,] 1
[30,] 1
[31,] ⋮
[32,] 1
[33,] 1
[34,] 1
[35,] 1
[36,] 1
[37,] 1
[38,] 1
[39,] 1
[40,] 1
[41,] 1
[42,] 1
[43,] 1
[44,] 1
[45,] 1
[46,] 1
[47,] 1
[48,] 1
[49,] 1
[50,] 1
[51,] 1
[52,] 1
[53,] 1
[54,] 1
[55,] 1
[56,] 1
[57,] 1
[58,] 1
[59,] 1
[60,] 1
[61,] 1

In [87]:
accuracy(nnetar_predh[12,1,1,],data[[12]]$xx)

         ME       RMSE     MAE      MPE      MAPE     ACF1      Theil's U
Test set 57.19977 61.88064 57.19977 5.318986 5.318986 0.5121544 3.895454

In [78]:
dd

      [,1]          [,2]       [,3]        [,4]        [,5]       [,6]
 [1,]  -351.4983470 1238.10193 1096.15143  -21.3754200 33.6045425  0.6177059
 [2,]    57.1997661   61.88064   57.19977    5.3189863  5.3189863  4.5017420
 [3,]  1214.3300968 1482.07984 1214.33010   26.9965864 26.9965864 11.7910960
 [4,]    75.7462739  632.78313  501.22776   -0.6265714 14.0394922  0.4294924
 [5,] -1985.4237821 3265.18805 2399.58038  -27.6148961 30.2627157  1.1722343
 [6,]     6.0165255  510.09458  468.24867   -3.5520536 16.7999193  0.6606338
 [7,] -3433.1792938 4405.40274 3913.45673  -82.8721441 89.0350780  2.8841435
 [8,]    -0.7116396 1021.57061  835.97539   -2.1748742 14.2730020  0.8850738
 [9,]    25.3605310  285.59149  206.05942   -1.3244480 10.8495199  0.8991522
[10,]  2802.3848219 3678.77839 3013.60293   16.5763439 18.4005122  2.5898272
[11,]   -97.5814316  108.14430   97.58143   -1.6996056  1.6996056  3.6049806
[12,]  -175.2386522  187.01581  175.23865   -2.8816362  2.8816362  2.3337957
[13,]  -176.6831618  188.55500  176.68316   -2.9076037  2.9076037  2.3876027
[14,]   -94.7541099  104.76857   94.75411   -1.6527596  1.6527596  3.6055525
[15,]   112.8133611  137.49125  112.81336    3.6337776  3.6337776  5.4558027
[16,]   -37.0997659   50.10015   43.29613   -1.2869697  1.4935915  2.0743936
[17,]   -92.8045433  149.07994  105.46475   -1.5124724  1.7088893  1.5835057
[18,]  1775.2518151 1956.53701 1775.25182   39.4443545 39.4443545 21.8434319
[19,]  1216.3795470 1310.44582 1216.37955   26.9748357 26.9748357  6.6285441
[20,]   981.5222220 1082.64938  981.52222   21.8554655 21.8554655  4.3692743
[21,]  -253.9326949  384.89521  284.95643  -15.5966326 17.3596127  3.1385747
[22,]   -54.7761978   78.16455   63.10426   -0.9205053  1.0583454  1.7867758
[23,]    59.8648450   74.14319   64.63427    0.9962201  1.0767231  1.7109603
[24,]    11.1539845   11.66222   11.15398    1.0178096  1.0178096  1.1661442
[25,]    39.6146836   44.26762   39.61468    2.1239777  2.1239777  2.3974630
[26,]    41.4293520  195.35254  154.69809    0.2003565  0.7856946  1.2557332
[27,]   192.0463146  229.93253  194.94474   10.3145579 10.4933384  3.2594561
[28,]   169.2768029  226.43055  193.90969    1.4358705  1.6533810  3.5126496
[29,]  1191.5095718 1279.62066 1191.50957    4.8971126  4.8971126 26.6511856
[30,]   502.7090855  543.77287  502.70909    3.1340653  3.1340653 16.3816828
[31,] ⋮             ⋮          ⋮           ⋮           ⋮          ⋮
[32,]  -58.036577     84.76257   73.214947  -2.2508165  2.9072741 0.5661095
[33,]  -52.927785    225.28710  168.016352 -16.0192205 25.2613455 0.3120765
[34,]    8.104159     12.30335    8.743634   0.1843335  0.1989386 0.7141350
[35,]  155.678548    332.12715  265.169029   3.3271029  6.3422000 0.9974837
[36,] -120.831867    129.85626  120.831867  -6.0812409  6.0812409 1.7398940
[37,] -180.042738    191.66764  180.042738  -8.9300947  8.9300947 2.4218609
[38,] -113.676497    126.15657  113.863147  -9.2209933  9.2349700 1.9400101
[39,]  164.336108    264.00666  231.860349   1.9547505  2.8289511 1.0721087
[40,]  -29.998259     32.58233   29.998259  -3.1767326  3.1767326 4.2798690
[41,]  220.772571    396.42535  319.499394   1.8381244  2.7373620 1.5722781
[42,]   53.733153     75.03403   63.542224   2.2643854  2.7100119 2.7414182
[43,] -110.132456    120.02351  110.132456  -1.4132557  1.4132557 3.6165175
[44,]   31.828758    580.12483  422.224459  -3.2017023 14.8274383 0.7847669
[45,]  240.600860    360.46621  308.873193   7.8286133 10.8680928 0.9214872
[46,] -329.409547    831.93456  570.690632  -9.5412643 13.4738303 0.6941105
[47,]  -39.228729    411.95534  291.292132  -6.2955725 15.4866565 0.8218599
[48,]  284.371989    699.10051  565.555089   4.0263549 10.6477887 0.8147871
[49,]   11.455312    530.54960  423.427980  -1.0699565  9.4415394 0.9594381
[50,] -500.396091    574.87624  500.396091 -13.4127709 13.4127709 1.0010710
[51,]  -29.440036    515.69318  426.543810  -4.8514724 17.3290745 1.4634309
[52,]  655.068096    779.22916  657.635175  20.8115555 20.9277655 2.0958158
[53,]  510.464663    797.76207  608.806249  11.9295493 15.1106406 1.4278498
[54,] 1387.823897   1985.11124 1645.946739  12.5650143 16.4200719 1.4479771
[55,]  412.177004    663.17682  539.736480   9.2972624 14.3358736 1.1776828
[56,]   63.555187    568.83148  410.015974  -0.4246846 11.9693280 0.8456586
[57,]  591.827950    828.74353  677.708638   9.9100707 11.8235111 1.1577999
[58,]    2.315338    669.98588  537.923365  -2.8262030 13.6712888 1.0331351
[59,] -588.424330   1005.00592  761.726574 -13.8375338 16.5413599 0.5355106
[60,]  167.027264    511.25325  392.852024   2.6382691 11.7626282 0.9479614
[61,]  322.753572    734.98059  577.281564   5.3419511 14.2313458 1.3111360

In [79]:
end_time = Sys.time()
time_matrix[2,]=end_time-start_time

In [33]:
end_time-start_time

Time difference of 9.22244 secs

### The results of the two methods of determining labels are averaged respectively

In [34]:
nnetarallmin=(nnetarxgbcls_min+nnetarlgbcls_min+nnetarxgbreg_min+nnetarlgbreg_min)/4
nnetarallmean=(nnetarxgbcls_mean+nnetarlgbcls_mean+nnetarxgbreg_mean+nnetarlgbreg_mean)/4

In [35]:
nnetarallminres=predres_mul(nnetarallmin,data,nnetar_pr_min,lengthtest,h,testindex)
nnetarallmeanres=predres_mul(nnetarallmean,data,nnetar_pr_mean,lengthtest,h,testindex)

### Under the above classification, the improved forecast results of the classification and regression models are averaged respectively

In [36]:
nnetarclsmin=(nnetarxgbcls_min+nnetarlgbcls_min)/2
nnetarregmin=(nnetarxgbreg_min+nnetarlgbreg_min)/2
nnetarclsmean=(nnetarxgbcls_mean+nnetarlgbcls_mean)/2
nnetarregmean=(nnetarxgbreg_mean+nnetarlgbreg_mean)/2

In [37]:
nnetarclsminres=predres_mul(nnetarclsmin,data,nnetar_pr_min[,c(1,3)],lengthtest,h,testindex)
nnetarregminres=predres_mul(nnetarregmin,data,nnetar_pr_min[,c(2,4)],lengthtest,h,testindex)
nnetarclsmeanres=predres_mul(nnetarclsmean,data,nnetar_pr_mean[,c(1,3)],lengthtest,h,testindex)
nnetarregmeanres=predres_mul(nnetarregmean,data,nnetar_pr_mean[,c(2,4)],lengthtest,h,testindex)

Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”
Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”

### Random slice

In [38]:
nnetarpred_change<- aperm(nnetar_predh[1:datalength,1:m,1:n,1:h], c(1, 3, 2, 4))  
# 使用array函数将其转换为新的形状
nnetarpred_change <- array(nnetarpred_change, dim = c(datalength, m*n, h))

In [39]:
data$x

NULL

In [40]:
model <- nnetar(data[[1]]$x)
fore_l <- forecast(model, h = h)
nnetarrandomres <- matrix(0, datalength, 6)
for (i in 1:datalength) {
    random <- sample(m * n, n)
    minloc <- min(random)
    # 使用cut函数将数据分割为区间
    loc <- cut(minloc, breaks = seq(0, m * n, n), labels = FALSE)
    loc <- as.numeric(loc)
    nnetarrandompred <- apply(nnetarpred_change[i, random, ], 2, mean)
    start <- length5[i, loc]
    y_all <- data[[i]]$x
    y <- y_all[start:length(y_all)]
    fore_l$x <- ts(y, frequency = freq, end = end(y_all))
    real <- data[[i]]$xx
    fore_l$mean <- ts(nnetarrandompred, start = start(real), frequency = freq)
    res <- accuracy(fore_l, real)
    nnetarrandomres[i, ] <- res[2, 1:6]
}

Warning message in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]), :
“non-intersecting series”
Warning message in trainingaccuracy(object, test, d, D):
“test elements must be within sample”

In [41]:
mean1=function(x)
    {
# 使用is.finite函数检查哪些值是有限的
finite_values <- x[is.finite(x)]
# 计算有限值的平均值
d=mean(finite_values, na.rm = TRUE)
return(d)
}

In [42]:
print(apply(nnetar_pred_res[testindex,1,1,],2,mean1))
print(apply(nnetarminxgbclsres,2,mean1))
print(apply(nnetarminxgbregres,2,mean1))
print(apply(nnetarminlgbclsres,2,mean1))
print(apply(nnetarminlgbregres,2,mean1))

[1] 130.54199415 512.23095064 425.61613612  -0.07025813   9.91431760
[6]   3.85853878
[1] 102.7620311 441.1372500 364.3545118   0.4787209   8.7046243   2.2749928
[1]  92.0321634 432.0178368 361.2092742   0.5778983   8.7144272   2.2138996
[1] 102.349574 458.777808 379.859078   0.283773   8.825521   2.927185
[1]  66.4900177 428.7702156 360.1808107  -0.1471232   8.7188764   2.1698067

In [43]:
print(apply(nnetarmeanxgbclsres,2,mean1))
print(apply(nnetarmeanxgbregres,2,mean1))
print(apply(nnetarmeanlgbclsres,2,mean1))
print(apply(nnetarmeanlgbregres,2,mean1))

[1]  95.6192643 452.3279642 371.3381202   0.5718302   8.8853835   2.3136146
[1] 108.4158641 441.3149793 364.1451261   0.3907091   8.5495366   2.6128418
[1] 154.325081 476.628045 394.158677   0.943727   8.943917   2.885883
[1]  88.8014381 442.0213014 364.4406715   0.2490378   8.7797969   2.2738170

##  The actual results used in the paper

In [44]:
print(apply(nnetarallminres,2,mean1))
print(apply(nnetarallmeanres,2,mean1))

[1]  90.9084465 420.0108525 350.7146454   0.2983172   8.2600408   2.4020833
[1] 111.790412 437.747923 362.398033   0.538826   8.499255   2.556476

In [88]:
print(apply(dd,2,mean1))

[1] 130.54199415 512.23095064 425.61613612  -0.07025813   9.91431760
[6]   3.85853878

In [89]:
dd

      [,1]          [,2]       [,3]        [,4]        [,5]       [,6]
 [1,]  -351.4983470 1238.10193 1096.15143  -21.3754200 33.6045425  0.6177059
 [2,]    57.1997661   61.88064   57.19977    5.3189863  5.3189863  4.5017420
 [3,]  1214.3300968 1482.07984 1214.33010   26.9965864 26.9965864 11.7910960
 [4,]    75.7462739  632.78313  501.22776   -0.6265714 14.0394922  0.4294924
 [5,] -1985.4237821 3265.18805 2399.58038  -27.6148961 30.2627157  1.1722343
 [6,]     6.0165255  510.09458  468.24867   -3.5520536 16.7999193  0.6606338
 [7,] -3433.1792938 4405.40274 3913.45673  -82.8721441 89.0350780  2.8841435
 [8,]    -0.7116396 1021.57061  835.97539   -2.1748742 14.2730020  0.8850738
 [9,]    25.3605310  285.59149  206.05942   -1.3244480 10.8495199  0.8991522
[10,]  2802.3848219 3678.77839 3013.60293   16.5763439 18.4005122  2.5898272
[11,]   -97.5814316  108.14430   97.58143   -1.6996056  1.6996056  3.6049806
[12,]  -175.2386522  187.01581  175.23865   -2.8816362  2.8816362  2.3337957
[13,]  -176.6831618  188.55500  176.68316   -2.9076037  2.9076037  2.3876027
[14,]   -94.7541099  104.76857   94.75411   -1.6527596  1.6527596  3.6055525
[15,]   112.8133611  137.49125  112.81336    3.6337776  3.6337776  5.4558027
[16,]   -37.0997659   50.10015   43.29613   -1.2869697  1.4935915  2.0743936
[17,]   -92.8045433  149.07994  105.46475   -1.5124724  1.7088893  1.5835057
[18,]  1775.2518151 1956.53701 1775.25182   39.4443545 39.4443545 21.8434319
[19,]  1216.3795470 1310.44582 1216.37955   26.9748357 26.9748357  6.6285441
[20,]   981.5222220 1082.64938  981.52222   21.8554655 21.8554655  4.3692743
[21,]  -253.9326949  384.89521  284.95643  -15.5966326 17.3596127  3.1385747
[22,]   -54.7761978   78.16455   63.10426   -0.9205053  1.0583454  1.7867758
[23,]    59.8648450   74.14319   64.63427    0.9962201  1.0767231  1.7109603
[24,]    11.1539845   11.66222   11.15398    1.0178096  1.0178096  1.1661442
[25,]    39.6146836   44.26762   39.61468    2.1239777  2.1239777  2.3974630
[26,]    41.4293520  195.35254  154.69809    0.2003565  0.7856946  1.2557332
[27,]   192.0463146  229.93253  194.94474   10.3145579 10.4933384  3.2594561
[28,]   169.2768029  226.43055  193.90969    1.4358705  1.6533810  3.5126496
[29,]  1191.5095718 1279.62066 1191.50957    4.8971126  4.8971126 26.6511856
[30,]   502.7090855  543.77287  502.70909    3.1340653  3.1340653 16.3816828
[31,] ⋮             ⋮          ⋮           ⋮           ⋮          ⋮
[32,]  -58.036577     84.76257   73.214947  -2.2508165  2.9072741 0.5661095
[33,]  -52.927785    225.28710  168.016352 -16.0192205 25.2613455 0.3120765
[34,]    8.104159     12.30335    8.743634   0.1843335  0.1989386 0.7141350
[35,]  155.678548    332.12715  265.169029   3.3271029  6.3422000 0.9974837
[36,] -120.831867    129.85626  120.831867  -6.0812409  6.0812409 1.7398940
[37,] -180.042738    191.66764  180.042738  -8.9300947  8.9300947 2.4218609
[38,] -113.676497    126.15657  113.863147  -9.2209933  9.2349700 1.9400101
[39,]  164.336108    264.00666  231.860349   1.9547505  2.8289511 1.0721087
[40,]  -29.998259     32.58233   29.998259  -3.1767326  3.1767326 4.2798690
[41,]  220.772571    396.42535  319.499394   1.8381244  2.7373620 1.5722781
[42,]   53.733153     75.03403   63.542224   2.2643854  2.7100119 2.7414182
[43,] -110.132456    120.02351  110.132456  -1.4132557  1.4132557 3.6165175
[44,]   31.828758    580.12483  422.224459  -3.2017023 14.8274383 0.7847669
[45,]  240.600860    360.46621  308.873193   7.8286133 10.8680928 0.9214872
[46,] -329.409547    831.93456  570.690632  -9.5412643 13.4738303 0.6941105
[47,]  -39.228729    411.95534  291.292132  -6.2955725 15.4866565 0.8218599
[48,]  284.371989    699.10051  565.555089   4.0263549 10.6477887 0.8147871
[49,]   11.455312    530.54960  423.427980  -1.0699565  9.4415394 0.9594381
[50,] -500.396091    574.87624  500.396091 -13.4127709 13.4127709 1.0010710
[51,]  -29.440036    515.69318  426.543810  -4.8514724 17.3290745 1.4634309
[52,]  655.068096    779.22916  657.635175  20.8115555 20.9277655 2.0958158
[53,]  510.464663    797.76207  608.806249  11.9295493 15.1106406 1.4278498
[54,] 1387.823897   1985.11124 1645.946739  12.5650143 16.4200719 1.4479771
[55,]  412.177004    663.17682  539.736480   9.2972624 14.3358736 1.1776828
[56,]   63.555187    568.83148  410.015974  -0.4246846 11.9693280 0.8456586
[57,]  591.827950    828.74353  677.708638   9.9100707 11.8235111 1.1577999
[58,]    2.315338    669.98588  537.923365  -2.8262030 13.6712888 1.0331351
[59,] -588.424330   1005.00592  761.726574 -13.8375338 16.5413599 0.5355106
[60,]  167.027264    511.25325  392.852024   2.6382691 11.7626282 0.9479614
[61,]  322.753572    734.98059  577.281564   5.3419511 14.2313458 1.3111360

In [90]:
nnetar_pred_res[testindex,1,1,]

      [,1]          [,2]       [,3]        [,4]        [,5]       [,6]
 [1,]  -351.4983470 1238.10193 1096.15143  -21.3754200 33.6045425  0.6177059
 [2,]    57.1997661   61.88064   57.19977    5.3189863  5.3189863  4.5017420
 [3,]  1214.3300968 1482.07984 1214.33010   26.9965864 26.9965864 11.7910960
 [4,]    75.7462739  632.78313  501.22776   -0.6265714 14.0394922  0.4294924
 [5,] -1985.4237821 3265.18805 2399.58038  -27.6148961 30.2627157  1.1722343
 [6,]     6.0165255  510.09458  468.24867   -3.5520536 16.7999193  0.6606338
 [7,] -3433.1792938 4405.40274 3913.45673  -82.8721441 89.0350780  2.8841435
 [8,]    -0.7116396 1021.57061  835.97539   -2.1748742 14.2730020  0.8850738
 [9,]    25.3605310  285.59149  206.05942   -1.3244480 10.8495199  0.8991522
[10,]  2802.3848219 3678.77839 3013.60293   16.5763439 18.4005122  2.5898272
[11,]   -97.5814316  108.14430   97.58143   -1.6996056  1.6996056  3.6049806
[12,]  -175.2386522  187.01581  175.23865   -2.8816362  2.8816362  2.3337957
[13,]  -176.6831618  188.55500  176.68316   -2.9076037  2.9076037  2.3876027
[14,]   -94.7541099  104.76857   94.75411   -1.6527596  1.6527596  3.6055525
[15,]   112.8133611  137.49125  112.81336    3.6337776  3.6337776  5.4558027
[16,]   -37.0997659   50.10015   43.29613   -1.2869697  1.4935915  2.0743936
[17,]   -92.8045433  149.07994  105.46475   -1.5124724  1.7088893  1.5835057
[18,]  1775.2518151 1956.53701 1775.25182   39.4443545 39.4443545 21.8434319
[19,]  1216.3795470 1310.44582 1216.37955   26.9748357 26.9748357  6.6285441
[20,]   981.5222220 1082.64938  981.52222   21.8554655 21.8554655  4.3692743
[21,]  -253.9326949  384.89521  284.95643  -15.5966326 17.3596127  3.1385747
[22,]   -54.7761978   78.16455   63.10426   -0.9205053  1.0583454  1.7867758
[23,]    59.8648450   74.14319   64.63427    0.9962201  1.0767231  1.7109603
[24,]    11.1539845   11.66222   11.15398    1.0178096  1.0178096  1.1661442
[25,]    39.6146836   44.26762   39.61468    2.1239777  2.1239777  2.3974630
[26,]    41.4293520  195.35254  154.69809    0.2003565  0.7856946  1.2557332
[27,]   192.0463146  229.93253  194.94474   10.3145579 10.4933384  3.2594561
[28,]   169.2768029  226.43055  193.90969    1.4358705  1.6533810  3.5126496
[29,]  1191.5095718 1279.62066 1191.50957    4.8971126  4.8971126 26.6511856
[30,]   502.7090855  543.77287  502.70909    3.1340653  3.1340653 16.3816828
[31,] ⋮             ⋮          ⋮           ⋮           ⋮          ⋮
[32,]  -58.036577     84.76257   73.214947  -2.2508165  2.9072741 0.5661095
[33,]  -52.927785    225.28710  168.016352 -16.0192205 25.2613455 0.3120765
[34,]    8.104159     12.30335    8.743634   0.1843335  0.1989386 0.7141350
[35,]  155.678548    332.12715  265.169029   3.3271029  6.3422000 0.9974837
[36,] -120.831867    129.85626  120.831867  -6.0812409  6.0812409 1.7398940
[37,] -180.042738    191.66764  180.042738  -8.9300947  8.9300947 2.4218609
[38,] -113.676497    126.15657  113.863147  -9.2209933  9.2349700 1.9400101
[39,]  164.336108    264.00666  231.860349   1.9547505  2.8289511 1.0721087
[40,]  -29.998259     32.58233   29.998259  -3.1767326  3.1767326 4.2798690
[41,]  220.772571    396.42535  319.499394   1.8381244  2.7373620 1.5722781
[42,]   53.733153     75.03403   63.542224   2.2643854  2.7100119 2.7414182
[43,] -110.132456    120.02351  110.132456  -1.4132557  1.4132557 3.6165175
[44,]   31.828758    580.12483  422.224459  -3.2017023 14.8274383 0.7847669
[45,]  240.600860    360.46621  308.873193   7.8286133 10.8680928 0.9214872
[46,] -329.409547    831.93456  570.690632  -9.5412643 13.4738303 0.6941105
[47,]  -39.228729    411.95534  291.292132  -6.2955725 15.4866565 0.8218599
[48,]  284.371989    699.10051  565.555089   4.0263549 10.6477887 0.8147871
[49,]   11.455312    530.54960  423.427980  -1.0699565  9.4415394 0.9594381
[50,] -500.396091    574.87624  500.396091 -13.4127709 13.4127709 1.0010710
[51,]  -29.440036    515.69318  426.543810  -4.8514724 17.3290745 1.4634309
[52,]  655.068096    779.22916  657.635175  20.8115555 20.9277655 2.0958158
[53,]  510.464663    797.76207  608.806249  11.9295493 15.1106406 1.4278498
[54,] 1387.823897   1985.11124 1645.946739  12.5650143 16.4200719 1.4479771
[55,]  412.177004    663.17682  539.736480   9.2972624 14.3358736 1.1776828
[56,]   63.555187    568.83148  410.015974  -0.4246846 11.9693280 0.8456586
[57,]  591.827950    828.74353  677.708638   9.9100707 11.8235111 1.1577999
[58,]    2.315338    669.98588  537.923365  -2.8262030 13.6712888 1.0331351
[59,] -588.424330   1005.00592  761.726574 -13.8375338 16.5413599 0.5355106
[60,]  167.027264    511.25325  392.852024   2.6382691 11.7626282 0.9479614
[61,]  322.753572    734.98059  577.281564   5.3419511 14.2313458 1.3111360

In [45]:
print(apply(nnetarclsminres,2,mean1))
print(apply(nnetarregminres,2,mean1))
print(apply(nnetarclsmeanres,2,mean1))
print(apply(nnetarregmeanres,2,mean1))

[1] 102.5558025 429.7517987 355.5166670   0.3812469   8.3164139   2.4980986
[1]  79.2610905 425.5412369 357.0662976   0.2153875   8.5964011   2.1594899
[1] 124.9721726 450.5701198 373.4084309   0.7577786   8.6599098   2.5328651
[1]  98.6086511 435.5793270 358.9683798   0.3198735   8.5285168   2.4646000

In [46]:
print(apply(nnetarrandomres[testindex,],2,mean))

[1] 127.8319874 448.8477151 370.3941851   0.6034996   8.6255497   3.1012827

In [48]:
nnetarall <- matrix(0, 16, 6)
nnetarall[1, ] <- apply(nnetar_pred_res[testindex, 1, 1, ], 2, mean1)[1:6]
nnetarall[2, ] <- apply(nnetarminxgbclsres, 2, mean1)
nnetarall[3, ] <- apply(nnetarminxgbregres, 2, mean1)
nnetarall[4, ] <- apply(nnetarminlgbclsres, 2, mean1)
nnetarall[5, ] <- apply(nnetarminlgbregres, 2, mean1)
nnetarall[6, ] <- apply(nnetarmeanxgbclsres, 2, mean1)
nnetarall[7, ] <- apply(nnetarmeanxgbregres, 2, mean1)
nnetarall[8, ] <- apply(nnetarmeanlgbclsres, 2, mean1)
nnetarall[9, ] <- apply(nnetarmeanlgbregres, 2, mean1)
nnetarall[10, ] <- apply(nnetarallminres, 2, mean1)
nnetarall[11, ] <- apply(nnetarallmeanres, 2, mean1)
nnetarall[12, ] <- apply(nnetarclsminres, 2, mean1)
nnetarall[13, ] <- apply(nnetarregminres, 2, mean1)
nnetarall[14, ] <- apply(nnetarclsmeanres, 2, mean1)
nnetarall[15, ] <- apply(nnetarregmeanres, 2, mean1)
nnetarall[16, ] <- apply(nnetarrandomres[testindex, ], 2, mean)

In [49]:
nnetarall

      [,1]      [,2]     [,3]     [,4]        [,5]     [,6]
 [1,] 130.54199 512.2310 425.6161 -0.07025813 9.914318 3.858539
 [2,] 102.76203 441.1372 364.3545  0.47872087 8.704624 2.274993
 [3,]  92.03216 432.0178 361.2093  0.57789827 8.714427 2.213900
 [4,] 102.34957 458.7778 379.8591  0.28377300 8.825521 2.927185
 [5,]  66.49002 428.7702 360.1808 -0.14712318 8.718876 2.169807
 [6,]  95.61926 452.3280 371.3381  0.57183024 8.885383 2.313615
 [7,] 108.41586 441.3150 364.1451  0.39070912 8.549537 2.612842
 [8,] 154.32508 476.6280 394.1587  0.94372699 8.943917 2.885883
 [9,]  88.80144 442.0213 364.4407  0.24903784 8.779797 2.273817
[10,]  90.90845 420.0109 350.7146  0.29831724 8.260041 2.402083
[11,] 111.79041 437.7479 362.3980  0.53882605 8.499255 2.556476
[12,] 102.55580 429.7518 355.5167  0.38124693 8.316414 2.498099
[13,]  79.26109 425.5412 357.0663  0.21538755 8.596401 2.159490
[14,] 124.97217 450.5701 373.4084  0.75777862 8.659910 2.532865
[15,]  98.60865 435.5793 358.9684  0.31987348 8.528517 2.464600
[16,] 127.83199 448.8477 370.3942  0.60349963 8.625550 3.101283

In [50]:
write.csv(nnetarall,'nnetar_Weekly_final_res.csv')