In [2]:
library(xgboost)
library("Matrix")
library('Ckmeans.1d.dp')
library('lightgbm')

载入程辑包：‘lightgbm’


The following object is masked from ‘package:xgboost’:

    slice

## Read data and process data labels

In [3]:
time_matrix <- matrix(0,ncol = 3, nrow =4)
colnames(time_matrix) <- c("user_time", "system_time", "elapsed_time")
start_time = Sys.time()

In [4]:
data=read.csv('Yearly_features_matrix.csv')
data=data[,2:dim(data)[2]]

In [5]:
dim(data)

[1] 23000    23

In [6]:
head(data)

  frequency nperiods seasonal_period trend     spike        linearity
1 1         0        1               0.9903832 1.535759e-07  5.174030
2 1         0        1               0.7455956 1.919834e-04 -2.797630
3 1         0        1               0.9993711 1.038094e-09  5.497375
4 1         0        1               0.9991043 5.484677e-09  5.514672
5 1         0        1               0.9941526 1.000137e-07  5.421624
6 1         0        1               0.9642112 2.683180e-05  4.078327
  curvature   e_acf1      e_acf10   entropy   ⋯ diff1_acf10 diff2_acf1
1 -0.94405361  0.47491778 0.6782989 0.3751645 ⋯ 0.28707837  -0.1820491
2  2.13419228  0.27486845 0.4580795 0.8010614 ⋯ 0.22214291  -0.3185895
3 -0.01972653  0.20035534 0.4491332 0.3055037 ⋯ 0.37277176  -0.6280637
4 -0.12400209 -0.18881555 0.3260450 0.3087948 ⋯ 0.60342537  -0.7758825
5  0.72042474  0.15921568 0.4025341 0.3435267 ⋯ 0.16237458  -0.5492186
6  0.73445937  0.02824047 0.1412002 0.5294464 ⋯ 0.08313085   0.1296658
  diff2_acf10 length user_time  system_time elapsed_time user_time.1
1 0.22316867  31     0.01651573 0.01651573  0.01651573   0
2 0.37163112  31     0.01546788 0.01546788  0.01546788   0
3 1.00110959  31     0.01541162 0.01541162  0.01541162   0
4 1.24511944  31     0.01328015 0.01328015  0.01328015   0
5 0.61790122  31     0.01211190 0.01211190  0.01211190   0
6 0.09734006  19     0.01194334 0.01194334  0.01194334   0
  system_time.1 elapsed_time.1
1 0             0
2 0             0
3 0             0
4 0             0
5 0             0
6 0             0

In [7]:
dlist= load('Yearly_nnetar_datalist.RData')
datalist=eval(parse(text = dlist ))
res=datalist[[1]]
MASE=res[,,,6]
m=5

In [8]:
dim(MASE)

[1] 23000     5     4

In [9]:
whichmin<-function(x){
    minx=min(x[x>0])
    loc=which(x==minx)[1]-1
    loc
}

meanunique=function(x)
    {
    mean(unique(x))
}

In [10]:
nanum=c()
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    a=apply(count,1,min)
    if(sum(is.na(a))>0)
        {
        nanum=append(nanum,i)
    }
    }

In [11]:
nanum

NULL

In [12]:
realbestmin=matrix(0,dim(MASE)[1],1)
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    min_value=apply(count,1,min)
    if (max(min_value,na.rm = TRUE)==0){
        realbestmin[i,]=0
        }
    else
        {
        min_value[is.na(min_value)]=100 
        realbestmin[i,]= whichmin(min_value)
    }
    }

In [13]:
table(realbestmin)

realbestmin
   0    1    2    3    4
3429 2358 2940 4357 9916

In [14]:
realbestmean=matrix(0,dim(MASE)[1],1)
for(i in seq(1,dim(MASE)[1]))
    {
    count=MASE[i,,]
    mean_value=apply(count,1,meanunique)
    if (max(mean_value,na.rm = TRUE)==0){
        realbestmean[i,]=0
        }
    else
        {
        mean_value[is.na(mean_value)]=100 
        realbestmean[i,]= whichmin(mean_value)
    }
    }

In [15]:
realbestmean

      [,1]
 [1,] 0
 [2,] 0
 [3,] 1
 [4,] 3
 [5,] 0
 [6,] 4
 [7,] 4
 [8,] 4
 [9,] 4
[10,] 2
[11,] 4
[12,] 4
[13,] 4
[14,] 4
[15,] 2
[16,] 4
[17,] 3
[18,] 4
[19,] 4
[20,] 4
[21,] 4
[22,] 4
[23,] 2
[24,] 2
[25,] 4
[26,] 4
[27,] 4
[28,] 4
[29,] 3
[30,] 4
[31,] ⋮
[32,] 3
[33,] 0
[34,] 2
[35,] 4
[36,] 4
[37,] 0
[38,] 2
[39,] 4
[40,] 1
[41,] 2
[42,] 1
[43,] 1
[44,] 3
[45,] 2
[46,] 2
[47,] 2
[48,] 4
[49,] 4
[50,] 2
[51,] 3
[52,] 3
[53,] 3
[54,] 2
[55,] 4
[56,] 4
[57,] 3
[58,] 0
[59,] 2
[60,] 4
[61,] 3

In [16]:
head(data)

  frequency nperiods seasonal_period trend     spike        linearity
1 1         0        1               0.9903832 1.535759e-07  5.174030
2 1         0        1               0.7455956 1.919834e-04 -2.797630
3 1         0        1               0.9993711 1.038094e-09  5.497375
4 1         0        1               0.9991043 5.484677e-09  5.514672
5 1         0        1               0.9941526 1.000137e-07  5.421624
6 1         0        1               0.9642112 2.683180e-05  4.078327
  curvature   e_acf1      e_acf10   entropy   ⋯ diff1_acf10 diff2_acf1
1 -0.94405361  0.47491778 0.6782989 0.3751645 ⋯ 0.28707837  -0.1820491
2  2.13419228  0.27486845 0.4580795 0.8010614 ⋯ 0.22214291  -0.3185895
3 -0.01972653  0.20035534 0.4491332 0.3055037 ⋯ 0.37277176  -0.6280637
4 -0.12400209 -0.18881555 0.3260450 0.3087948 ⋯ 0.60342537  -0.7758825
5  0.72042474  0.15921568 0.4025341 0.3435267 ⋯ 0.16237458  -0.5492186
6  0.73445937  0.02824047 0.1412002 0.5294464 ⋯ 0.08313085   0.1296658
  diff2_acf10 length user_time  system_time elapsed_time user_time.1
1 0.22316867  31     0.01651573 0.01651573  0.01651573   0
2 0.37163112  31     0.01546788 0.01546788  0.01546788   0
3 1.00110959  31     0.01541162 0.01541162  0.01541162   0
4 1.24511944  31     0.01328015 0.01328015  0.01328015   0
5 0.61790122  31     0.01211190 0.01211190  0.01211190   0
6 0.09734006  19     0.01194334 0.01194334  0.01194334   0
  system_time.1 elapsed_time.1
1 0             0
2 0             0
3 0             0
4 0             0
5 0             0
6 0             0

In [17]:
set.seed(100)
index = sample(2,nrow(data),replace = TRUE,prob=c(0.7,0.3))

In [18]:
train_data=data[index==1,]
test_data=data[index==2,]
train_label_min=realbestmin[index==1,]
test_label_min=realbestmin[index==2,]
train_label_mean=realbestmean[index==1,]
test_label_mean=realbestmean[index==2,]

In [19]:
head(train_data)

  frequency nperiods seasonal_period trend     spike        linearity
1 1         0        1               0.9903832 1.535759e-07  5.174030
2 1         0        1               0.7455956 1.919834e-04 -2.797630
3 1         0        1               0.9993711 1.038094e-09  5.497375
4 1         0        1               0.9991043 5.484677e-09  5.514672
5 1         0        1               0.9941526 1.000137e-07  5.421624
6 1         0        1               0.9642112 2.683180e-05  4.078327
  curvature   e_acf1      e_acf10   entropy   ⋯ diff1_acf10 diff2_acf1
1 -0.94405361  0.47491778 0.6782989 0.3751645 ⋯ 0.28707837  -0.1820491
2  2.13419228  0.27486845 0.4580795 0.8010614 ⋯ 0.22214291  -0.3185895
3 -0.01972653  0.20035534 0.4491332 0.3055037 ⋯ 0.37277176  -0.6280637
4 -0.12400209 -0.18881555 0.3260450 0.3087948 ⋯ 0.60342537  -0.7758825
5  0.72042474  0.15921568 0.4025341 0.3435267 ⋯ 0.16237458  -0.5492186
6  0.73445937  0.02824047 0.1412002 0.5294464 ⋯ 0.08313085   0.1296658
  diff2_acf10 length user_time  system_time elapsed_time user_time.1
1 0.22316867  31     0.01651573 0.01651573  0.01651573   0
2 0.37163112  31     0.01546788 0.01546788  0.01546788   0
3 1.00110959  31     0.01541162 0.01541162  0.01541162   0
4 1.24511944  31     0.01328015 0.01328015  0.01328015   0
5 0.61790122  31     0.01211190 0.01211190  0.01211190   0
6 0.09734006  19     0.01194334 0.01194334  0.01194334   0
  system_time.1 elapsed_time.1
1 0             0
2 0             0
3 0             0
4 0             0
5 0             0
6 0             0

In [20]:
end_time = Sys.time()

In [21]:
time_matrix[1,]=end_time-start_time

In [22]:
end_time-start_time

Time difference of 10.12041 secs

## Target the interval where the actual error is minimum

In [23]:
start_time = Sys.time()

In [24]:
dtrain_xg_min_reg <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(train_label_min)) 
dtrain_xg_min_cl <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_min)) )

In [25]:
dtrain_lg_min_reg <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(train_label_min))
dtrain_lg_min_cl <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_min)))

In [26]:
xgb_min_reg <- xgboost(data = dtrain_xg_min_reg, nround=100)

[1]	train-rmse:2.054349
[2]	train-rmse:1.711905
[3]	train-rmse:1.511460
[4]	train-rmse:1.394788
[5]	train-rmse:1.332264
[6]	train-rmse:1.293268
[7]	train-rmse:1.268623
[8]	train-rmse:1.256257
[9]	train-rmse:1.247049
[10]	train-rmse:1.238409
[11]	train-rmse:1.233591
[12]	train-rmse:1.228891
[13]	train-rmse:1.226931
[14]	train-rmse:1.222875
[15]	train-rmse:1.221130
[16]	train-rmse:1.214927
[17]	train-rmse:1.205064
[18]	train-rmse:1.200693
[19]	train-rmse:1.198064
[20]	train-rmse:1.196013
[21]	train-rmse:1.191804
[22]	train-rmse:1.184007
[23]	train-rmse:1.178860
[24]	train-rmse:1.175367
[25]	train-rmse:1.169202
[26]	train-rmse:1.167569
[27]	train-rmse:1.161780
[28]	train-rmse:1.158237
[29]	train-rmse:1.152403
[30]	train-rmse:1.149482
[31]	train-rmse:1.146164
[32]	train-rmse:1.144756
[33]	train-rmse:1.138348
[34]	train-rmse:1.133116
[35]	train-rmse:1.129023
[36]	train-rmse:1.128036
[37]	train-rmse:1.125749
[38]	train-rmse:1.121791
[39]	train-rmse:1.120184
[40]	train-rmse:1.118878
[41]	train-rmse:1.115170
[42]	train-rmse:1.107607
[43]	train-rmse:1.102036
[44]	train-rmse:1.100662
[45]	train-rmse:1.096918
[46]	train-rmse:1.092366
[47]	train-rmse:1.086567
[48]	train-rmse:1.084301
[49]	train-rmse:1.081164
[50]	train-rmse:1.079486
[51]	train-rmse:1.078999
[52]	train-rmse:1.074189
[53]	train-rmse:1.071559
[54]	train-rmse:1.068380
[55]	train-rmse:1.065369
[56]	train-rmse:1.063208
[57]	train-rmse:1.061779
[58]	train-rmse:1.057170
[59]	train-rmse:1.056357
[60]	train-rmse:1.050811
[61]	train-rmse:1.049777
[62]	train-rmse:1.048851
[63]	train-rmse:1.047234
[64]	train-rmse:1.042368
[65]	train-rmse:1.039363
[66]	train-rmse:1.034368
[67]	train-rmse:1.031570
[68]	train-rmse:1.029843
[69]	train-rmse:1.026500
[70]	train-rmse:1.022606
[71]	train-rmse:1.014552
[72]	train-rmse:1.011943
[73]	train-rmse:1.007765
[74]	train-rmse:1.005785
[75]	train-rmse:1.003778
[76]	train-rmse:1.001127
[77]	train-rmse:0.999569
[78]	train-rmse:0.995156
[79]	train-rmse:0.993297
[80]	train-rmse:0.991992
[81]	train-rmse:0.987929
[82]	train-rmse:0.984643
[83]	train-rmse:0.980435
[84]	train-rmse:0.976578
[85]	train-rmse:0.973426
[86]	train-rmse:0.968932
[87]	train-rmse:0.967400
[88]	train-rmse:0.963507
[89]	train-rmse:0.961058
[90]	train-rmse:0.955759
[91]	train-rmse:0.952618
[92]	train-rmse:0.946754
[93]	train-rmse:0.944292
[94]	train-rmse:0.941314
[95]	train-rmse:0.936856
[96]	train-rmse:0.933844
[97]	train-rmse:0.931013
[98]	train-rmse:0.930060
[99]	train-rmse:0.927028
[100]	train-rmse:0.924421

Warning message in sprintf(save_name, env$iteration):
“one argument not used by format 'xgboost.model'”

In [27]:
xgb_min_cl <- xgboost(data = dtrain_xg_min_cl, nround=100, objective='multi:softmax',num_class=5)

[1]	train-merror:0.507709
[2]	train-merror:0.494943
[3]	train-merror:0.485383
[4]	train-merror:0.480942
[5]	train-merror:0.475207
[6]	train-merror:0.467374
[7]	train-merror:0.461823
[8]	train-merror:0.459109
[9]	train-merror:0.448871
[10]	train-merror:0.444492
[11]	train-merror:0.439928
[12]	train-merror:0.435365
[13]	train-merror:0.431972
[14]	train-merror:0.425867
[15]	train-merror:0.419946
[16]	train-merror:0.415443
[17]	train-merror:0.410201
[18]	train-merror:0.406377
[19]	train-merror:0.404404
[20]	train-merror:0.400086
[21]	train-merror:0.395522
[22]	train-merror:0.392439
[23]	train-merror:0.387628
[24]	train-merror:0.383681
[25]	train-merror:0.381399
[26]	train-merror:0.376650
[27]	train-merror:0.373936
[28]	train-merror:0.369187
[29]	train-merror:0.362711
[30]	train-merror:0.359812
[31]	train-merror:0.356790
[32]	train-merror:0.354200
[33]	train-merror:0.347724
[34]	train-merror:0.344702
[35]	train-merror:0.341557
[36]	train-merror:0.339583
[37]	train-merror:0.335759
[38]	train-merror:0.332614
[39]	train-merror:0.329160
[40]	train-merror:0.322252
[41]	train-merror:0.319539
[42]	train-merror:0.317688
[43]	train-merror:0.314605
[44]	train-merror:0.311151
[45]	train-merror:0.309362
[46]	train-merror:0.305538
[47]	train-merror:0.303133
[48]	train-merror:0.298446
[49]	train-merror:0.293943
[50]	train-merror:0.292402
[51]	train-merror:0.288824
[52]	train-merror:0.286296
[53]	train-merror:0.283274
[54]	train-merror:0.279450
[55]	train-merror:0.276428
[56]	train-merror:0.271926
[57]	train-merror:0.269088
[58]	train-merror:0.266190
[59]	train-merror:0.265573
[60]	train-merror:0.263599
[61]	train-merror:0.260022
[62]	train-merror:0.256568
[63]	train-merror:0.253731
[64]	train-merror:0.251449
[65]	train-merror:0.247379
[66]	train-merror:0.245899
[67]	train-merror:0.241890
[68]	train-merror:0.238066
[69]	train-merror:0.237141
[70]	train-merror:0.232947
[71]	train-merror:0.228938
[72]	train-merror:0.225978
[73]	train-merror:0.222215
[74]	train-merror:0.220365
[75]	train-merror:0.218823
[76]	train-merror:0.216480
[77]	train-merror:0.214938
[78]	train-merror:0.212779
[79]	train-merror:0.210065
[80]	train-merror:0.207783
[81]	train-merror:0.207167
[82]	train-merror:0.204453
[83]	train-merror:0.200382
[84]	train-merror:0.196744
[85]	train-merror:0.194215
[86]	train-merror:0.192858
[87]	train-merror:0.189651
[88]	train-merror:0.186567
[89]	train-merror:0.183853
[90]	train-merror:0.182435
[91]	train-merror:0.180276
[92]	train-merror:0.179290
[93]	train-merror:0.174787
[94]	train-merror:0.171888
[95]	train-merror:0.169853
[96]	train-merror:0.168065
[97]	train-merror:0.166153
[98]	train-merror:0.164056
[99]	train-merror:0.162884
[100]	train-merror:0.160109

Warning message in sprintf(save_name, env$iteration):
“one argument not used by format 'xgboost.model'”

In [28]:
lgb_min_reg <- lgb.train(data = dtrain_lg_min_reg, nrounds = 100)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011209 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4167
[LightGBM] [Info] Number of data points in the train set: 16214, number of used features: 17
[LightGBM] [Info] Start training from score 2.652399

In [29]:
params <- list(objective = "multiclass",
               num_class = 5, 
               metric = "multi_logloss")
lgb_min_cl <- lgb.train(data = dtrain_lg_min_cl,nrounds = 100,params=params)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008868 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4167
[LightGBM] [Info] Number of data points in the train set: 16214, number of used features: 17
[LightGBM] [Info] Start training from score -1.916676
[LightGBM] [Info] Start training from score -2.267677
[LightGBM] [Info] Start training from score -2.047277
[LightGBM] [Info] Start training from score -1.658675
[LightGBM] [Info] Start training from score -0.844260

In [30]:
end_time = Sys.time()
time_matrix[2,]=end_time-start_time

## Target the interval where the average error is minimum

In [31]:
start_time = Sys.time()

In [32]:
dtrain_xg_mean_reg <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(train_label_mean)) 
dtrain_xg_mean_cl <- xgb.DMatrix(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_mean)) )

In [33]:
dtrain_lg_mean_reg <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(train_label_mean))
dtrain_lg_mean_cl <- lgb.Dataset(data = as.matrix(train_data),label = as.matrix(as.factor(train_label_mean)))

In [34]:
xgb_mean_reg <- xgboost(data = dtrain_xg_mean_reg, nround=100)

[1]	train-rmse:1.920613
[2]	train-rmse:1.644886
[3]	train-rmse:1.484312
[4]	train-rmse:1.393533
[5]	train-rmse:1.342271
[6]	train-rmse:1.312164
[7]	train-rmse:1.293278
[8]	train-rmse:1.282288
[9]	train-rmse:1.271284
[10]	train-rmse:1.264118
[11]	train-rmse:1.258175
[12]	train-rmse:1.253278
[13]	train-rmse:1.243774
[14]	train-rmse:1.239803
[15]	train-rmse:1.236503
[16]	train-rmse:1.230590
[17]	train-rmse:1.223937
[18]	train-rmse:1.220326
[19]	train-rmse:1.219071
[20]	train-rmse:1.210975
[21]	train-rmse:1.205520
[22]	train-rmse:1.202294
[23]	train-rmse:1.195994
[24]	train-rmse:1.194886
[25]	train-rmse:1.192270
[26]	train-rmse:1.185378
[27]	train-rmse:1.179589
[28]	train-rmse:1.178442
[29]	train-rmse:1.171602
[30]	train-rmse:1.165134
[31]	train-rmse:1.162903
[32]	train-rmse:1.158683
[33]	train-rmse:1.154459
[34]	train-rmse:1.152630
[35]	train-rmse:1.146795
[36]	train-rmse:1.139733
[37]	train-rmse:1.137205
[38]	train-rmse:1.133121
[39]	train-rmse:1.127206
[40]	train-rmse:1.126117
[41]	train-rmse:1.119656
[42]	train-rmse:1.117554
[43]	train-rmse:1.115792
[44]	train-rmse:1.111899
[45]	train-rmse:1.110376
[46]	train-rmse:1.106942
[47]	train-rmse:1.104145
[48]	train-rmse:1.102339
[49]	train-rmse:1.099568
[50]	train-rmse:1.093145
[51]	train-rmse:1.088475
[52]	train-rmse:1.084443
[53]	train-rmse:1.079551
[54]	train-rmse:1.078664
[55]	train-rmse:1.074002
[56]	train-rmse:1.073132
[57]	train-rmse:1.069292
[58]	train-rmse:1.068909
[59]	train-rmse:1.064725
[60]	train-rmse:1.061347
[61]	train-rmse:1.059957
[62]	train-rmse:1.054207
[63]	train-rmse:1.051297
[64]	train-rmse:1.050300
[65]	train-rmse:1.047031
[66]	train-rmse:1.042712
[67]	train-rmse:1.038044
[68]	train-rmse:1.034539
[69]	train-rmse:1.030482
[70]	train-rmse:1.024793
[71]	train-rmse:1.020259
[72]	train-rmse:1.018408
[73]	train-rmse:1.014301
[74]	train-rmse:1.013733
[75]	train-rmse:1.011801
[76]	train-rmse:1.008290
[77]	train-rmse:1.004293
[78]	train-rmse:1.001170
[79]	train-rmse:0.999705
[80]	train-rmse:0.997977
[81]	train-rmse:0.993400
[82]	train-rmse:0.992701
[83]	train-rmse:0.990198
[84]	train-rmse:0.987024
[85]	train-rmse:0.983264
[86]	train-rmse:0.979750
[87]	train-rmse:0.976762
[88]	train-rmse:0.972943
[89]	train-rmse:0.968449
[90]	train-rmse:0.966559
[91]	train-rmse:0.964838
[92]	train-rmse:0.963437
[93]	train-rmse:0.958781
[94]	train-rmse:0.957130
[95]	train-rmse:0.954632
[96]	train-rmse:0.950368
[97]	train-rmse:0.946276
[98]	train-rmse:0.942904
[99]	train-rmse:0.937818
[100]	train-rmse:0.934027

Warning message in sprintf(save_name, env$iteration):
“one argument not used by format 'xgboost.model'”

In [35]:
xgb_mean_cl <- xgboost(data = dtrain_xg_mean_cl, nround=100, objective='multi:softmax',num_class=5)

[1]	train-merror:0.554644
[2]	train-merror:0.531269
[3]	train-merror:0.520970
[4]	train-merror:0.514247
[5]	train-merror:0.503577
[6]	train-merror:0.498026
[7]	train-merror:0.489392
[8]	train-merror:0.480696
[9]	train-merror:0.469471
[10]	train-merror:0.463242
[11]	train-merror:0.456642
[12]	train-merror:0.449365
[13]	train-merror:0.445171
[14]	train-merror:0.437646
[15]	train-merror:0.432096
[16]	train-merror:0.425743
[17]	train-merror:0.420624
[18]	train-merror:0.414703
[19]	train-merror:0.410694
[20]	train-merror:0.407981
[21]	train-merror:0.400456
[22]	train-merror:0.395954
[23]	train-merror:0.391452
[24]	train-merror:0.383681
[25]	train-merror:0.378500
[26]	train-merror:0.375046
[27]	train-merror:0.370544
[28]	train-merror:0.368200
[29]	train-merror:0.363205
[30]	train-merror:0.358887
[31]	train-merror:0.354015
[32]	train-merror:0.347909
[33]	train-merror:0.345196
[34]	train-merror:0.342728
[35]	train-merror:0.340385
[36]	train-merror:0.338226
[37]	train-merror:0.335266
[38]	train-merror:0.330640
[39]	train-merror:0.324411
[40]	train-merror:0.322561
[41]	train-merror:0.318675
[42]	train-merror:0.314975
[43]	train-merror:0.311644
[44]	train-merror:0.306155
[45]	train-merror:0.302886
[46]	train-merror:0.301036
[47]	train-merror:0.297644
[48]	train-merror:0.294499
[49]	train-merror:0.292648
[50]	train-merror:0.290305
[51]	train-merror:0.286604
[52]	train-merror:0.284569
[53]	train-merror:0.282349
[54]	train-merror:0.277970
[55]	train-merror:0.271987
[56]	train-merror:0.270445
[57]	train-merror:0.269829
[58]	train-merror:0.267115
[59]	train-merror:0.263168
[60]	train-merror:0.260577
[61]	train-merror:0.256753
[62]	train-merror:0.253793
[63]	train-merror:0.251203
[64]	train-merror:0.248119
[65]	train-merror:0.245159
[66]	train-merror:0.243802
[67]	train-merror:0.242136
[68]	train-merror:0.239053
[69]	train-merror:0.236647
[70]	train-merror:0.233194
[71]	train-merror:0.231343
[72]	train-merror:0.229061
[73]	train-merror:0.226348
[74]	train-merror:0.225299
[75]	train-merror:0.220673
[76]	train-merror:0.218083
[77]	train-merror:0.216665
[78]	train-merror:0.213519
[79]	train-merror:0.210559
[80]	train-merror:0.207537
[81]	train-merror:0.204453
[82]	train-merror:0.201554
[83]	train-merror:0.200259
[84]	train-merror:0.198717
[85]	train-merror:0.196188
[86]	train-merror:0.192365
[87]	train-merror:0.189959
[88]	train-merror:0.186382
[89]	train-merror:0.183853
[90]	train-merror:0.182928
[91]	train-merror:0.180276
[92]	train-merror:0.177439
[93]	train-merror:0.175034
[94]	train-merror:0.172197
[95]	train-merror:0.169607
[96]	train-merror:0.168065
[97]	train-merror:0.166523
[98]	train-merror:0.164673
[99]	train-merror:0.163439
[100]	train-merror:0.160849

Warning message in sprintf(save_name, env$iteration):
“one argument not used by format 'xgboost.model'”

In [36]:
lgb_mean_reg <- lgb.train(data = dtrain_lg_mean_reg,nrounds = 100)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008785 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4167
[LightGBM] [Info] Number of data points in the train set: 16214, number of used features: 17
[LightGBM] [Info] Start training from score 2.345936

In [37]:
params <- list(objective = "multiclass",
               num_class = 5, 
               metric = "multi_logloss")
lgb_mean_cl <- lgb.train(data = dtrain_lg_mean_cl,params=params,nrounds = 100)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008948 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4167
[LightGBM] [Info] Number of data points in the train set: 16214, number of used features: 17
[LightGBM] [Info] Start training from score -1.672703
[LightGBM] [Info] Start training from score -2.054951
[LightGBM] [Info] Start training from score -1.884901
[LightGBM] [Info] Start training from score -1.536547
[LightGBM] [Info] Start training from score -1.148238

In [38]:
end_time = Sys.time()
time_matrix[3,]=end_time-start_time

In [39]:
end_time-start_time

Time difference of 2.409725 mins

## predict

In [40]:
start_time = Sys.time()

In [41]:
alldatalgb <- lgb.Dataset(data = as.matrix(data))
alldataxgb <- xgb.DMatrix(data = as.matrix(data))

In [42]:
xgbregmin=predict(xgb_min_reg,alldataxgb)
xgbclsmin=predict(xgb_min_cl,alldataxgb)
lgbregmin=predict(lgb_min_reg,as.matrix(data))
lgbclsmin=predict(lgb_min_cl,as.matrix(data))

In [43]:
xgbregmin

    [1]  2.337117e+00  1.792584e+00  1.255076e+00  2.551001e+00  2.596719e+00
    [6]  3.629522e+00  3.500438e+00  3.002187e+00  3.194767e+00  2.068563e+00
   [11]  3.329474e+00  2.666197e+00  3.643165e+00  2.764925e+00  2.296299e+00
   [16]  3.686271e+00  2.630901e+00  3.086411e+00  3.618511e+00  3.699216e+00
   [21]  3.726438e+00  3.014001e+00  1.547159e+00  6.633423e-01  3.779645e+00
   [26]  3.802778e+00  2.966493e+00  2.529742e+00  2.959569e+00  2.302070e+00
   [31]  9.342448e-01  3.201997e+00  2.745774e+00  2.815695e+00  3.594579e+00
   [36]  3.294819e+00  3.254361e+00  2.787058e+00  3.086627e+00  3.903009e+00
   [41]  3.219532e+00  1.747046e+00  1.406562e+00  1.663616e+00  1.826777e+00
   [46]  2.842401e+00  2.318129e+00  1.846675e+00  1.965235e+00  3.212933e+00
   [51]  3.346107e+00  2.787450e+00  4.191940e+00  4.083189e+00  3.504032e+00
   [56]  3.358683e+00  3.492638e+00  3.520531e+00  3.173833e+00  1.131840e+00
   [61]  3.714710e+00  3.267852e+00  3.914485e+00  3.178482e+00  3.006138e+00
   [66]  7.974321e-01  3.065506e+00  3.666938e+00  9.751269e-01  2.170453e+00
   [71]  2.993667e+00  3.030483e+00  1.891991e+00  2.900696e+00  3.792015e+00
   [76]  2.954782e+00  1.634407e+00  2.142831e+00  2.252886e+00  3.387010e+00
   [81]  3.079561e+00  4.018930e+00  2.461036e+00  2.314431e+00  1.144438e+00
   [86]  1.890475e+00  2.549591e+00  2.023514e+00  2.741017e+00  2.790500e+00
   [91]  1.195132e+00  2.371398e+00  1.863128e+00  3.121369e+00  1.665464e+00
   [96]  2.593374e+00  3.061486e+00  1.816560e+00  1.389577e+00  3.007826e+00
  [101]  1.970663e+00  2.542882e+00  1.903293e+00  2.384448e+00  1.230826e+00
  [106]  1.240252e+00  3.463725e-01  7.647082e-01  2.063627e+00  1.282611e+00
  [111]  1.941984e+00  2.044716e+00  3.887691e+00  7.309366e-01  1.663749e+00
  [116]  2.651313e+00  2.277994e+00  1.237767e+00  1.937222e+00  2.231965e+00
  [121]  2.118497e+00  1.861477e-01  2.782454e+00 -2.073485e-02  1.315456e+00
  [126]  3.771583e+00  2.040295e+00  2.225394e+00  2.797046e+00  2.783177e+00
  [131]  1.685492e+00  2.786710e+00  2.829902e+00  3.040083e+00  2.797736e+00
  [136]  3.832246e+00  3.304077e+00  3.102925e+00  2.420967e+00  3.475736e+00
  [141]  3.388039e+00  3.069445e+00  3.648266e+00  2.636831e+00  2.925277e+00
  [146]  3.025911e+00  3.165095e+00  3.253419e+00  3.695413e+00  2.547302e+00
  [151]  3.093494e+00  2.387420e+00  3.897276e+00  2.101495e+00  3.159014e+00
  [156]  2.147984e+00  3.489786e+00  2.519903e+00  2.762679e+00  2.662913e+00
  [161]  1.197287e+00  3.574236e+00  2.757144e+00  3.396778e+00  3.312926e+00
  [166]  3.489110e+00  3.265203e+00  1.649781e+00  1.749197e+00  1.779194e+00
  [171]  3.925676e+00  1.974084e+00  3.580540e+00  1.588349e+00  3.291673e+00
  [176]  1.377104e+00  2.016789e+00  1.795020e+00  1.948019e+00  3.724228e+00
  [181]  1.938262e+00  2.766421e+00  2.073862e+00  3.111390e+00  2.137681e+00
  [186]  2.360147e+00  9.150612e-01  3.722993e+00  3.560652e+00  1.858587e+00
  [191]  1.105842e+00  9.324335e-01  2.614937e+00  3.572067e+00  3.280902e+00
  [196]  2.863076e+00  9.331343e-01  2.512778e+00  1.497829e+00  3.274244e+00
  [201]  1.018695e+00  2.714927e+00  1.686126e+00  1.990806e+00  1.020031e+00
  [206]  1.993692e+00  1.653709e+00  3.467434e+00  1.108664e+00  3.974845e-01
  [211]  1.716845e+00  1.953380e+00  2.013638e+00  1.155925e+00  3.257348e+00
  [216]  2.782368e+00  6.131570e-01  9.080986e-01  2.178839e+00  3.298423e+00
  [221]  2.345844e+00  2.741657e+00  3.041255e+00  2.381347e+00  3.305056e+00
  [226]  1.952596e+00  2.715669e+00  1.655272e+00  3.361460e-01  2.011889e+00
  [231]  1.717308e+00  6.025215e-01  1.049529e+00  2.172374e+00  2.710884e-01
  [236]  3.284312e+00  2.074889e+00  1.401742e+00  1.069374e+00  4.030000e+00
  [241]  3.716665e+00  3.063015e+00  6.035996e-01  2.129334e+00  3.507771e+00
  [246]  3.802054e+00  3.012206e+00  3.089272e+00  2.263217e+00  3.387040e+00
  [251]  3.417131e+00  2.675101e+00  1.724598e+00  1.873122e+00  6.774582e-01
  [256]  2.338383e+00  3.592538e+00  3.510987e+00  2.550652e+00  2.326888e+00
  [261]  2.428090e+00  7.486382e-01  3.769139e+00  1.542081e+00  1.775285e+00
  [266]  7.946924e-01  2.296872e+00  1.723291e+00  3.620701e+00  1.731145e+00
  [271]  2.087114e+00  2.321882e+00  4.158171e+00  2.078578e+00  3.148417e+00
  [276]  3.538763e+00  7.092929e-01  2.640991e+00  3.189811e+00  3.311466e+00
  [281]  2.255571e+00  2.419322e+00  3.372140e+00  3.001915e+00  3.248650e+00
  [286]  2.110281e+00  2.101465e+00  1.956773e+00  2.349843e+00  2.769900e+00
  [291]  2.428090e+00  3.678946e+00  3.740371e+00  2.105195e+00  4.399928e-01
  [296]  2.813240e+00  2.058125e+00  2.298434e+00  1.724694e+00  4.155408e+00
  [301]  2.387187e+00  2.548799e+00  1.407502e+00  2.801093e+00  1.215154e+00
  [306]  1.889487e-01  1.452481e+00  1.144071e+00  1.241032e+00  1.790562e+00
  [311]  1.750790e+00  1.356334e+00  1.638902e+00  9.814477e-01  1.985134e+00
  [316]  1.799936e+00  2.756778e+00  6.330611e-01  3.183308e+00  1.424381e+00
  [321]  3.379472e+00  2.597044e+00  2.809342e+00  2.695174e+00  2.027292e+00
  [326]  8.571240e-01  8.037639e-01  2.078400e+00  3.718024e+00  1.601044e+00
  [331]  3.747896e+00  2.193143e+00  1.994822e+00  3.150905e+00  2.050959e+00
  [336]  3.143467e+00  2.565025e+00  2.655837e+00  2.927898e+00  2.232932e+00
  [341]  1.924003e+00  5.385501e-01  2.051444e+00  3.110315e+00  3.299869e+00
  [346]  2.899797e+00  1.631753e+00  3.284166e+00  2.669050e+00  2.453921e+00
  [351]  2.526763e+00  2.087174e+00  1.588336e+00  3.637320e+00  2.371902e+00
  [356]  3.025309e+00  2.373982e-01  1.567928e+00  1.366607e+00  2.037360e+00
  [361]  2.116319e+00  3.133814e+00  2.042599e+00  2.058626e+00  3.274841e+00
  [366]  3.972241e-01  3.264737e+00  3.892884e+00  2.942334e+00  1.000678e+00
  [371]  2.126358e+00  3.280642e+00  3.720169e+00  2.473786e+00  3.103534e+00
  [376]  2.315096e+00  3.896605e+00  3.053362e+00  3.996501e+00  2.785677e+00
  [381]  2.941221e+00  3.955065e+00  3.370999e+00  2.726199e+00  1.713382e+00
  [386]  2.919240e+00  3.516881e+00  2.764610e+00  1.621716e+00  3.696746e+00
  [391]  3.112904e+00  3.825656e+00  2.784020e+00  3.597429e+00  3.670887e+00
  [396]  9.581959e-01  3.890939e+00  1.173111e+00  2.022019e+00  2.519127e+00
  [401]  3.165049e+00  3.678170e+00  2.225239e+00  3.897440e+00  1.885719e+00
  [406]  3.187634e+00  3.396472e+00  3.136559e+00  3.258105e+00  3.368599e+00
  [411]  4.294507e+00  3.993726e+00  4.234086e+00  2.963343e-01  2.429613e+00
  [416]  2.708458e+00  3.415800e+00  1.886588e+00  2.078993e+00  3.841220e+00
  [421]  3.178340e+00  3.637959e+00  3.279841e+00  2.678018e+00  3.063451e+00
  [426]  1.815275e+00  1.960895e+00  2.341887e+00  3.714210e+00  2.372233e+00
  [431]  1.884374e+00  3.108335e+00  2.186265e+00  3.578284e+00  1.896572e+00
  [436]  1.383991e+00  1.136596e+00  1.249860e+00  3.128510e+00  3.682630e+00
  [441]  1.945721e+00  2.222668e+00  2.819780e+00  3.490550e+00  3.444085e+00
  [446]  2.278032e+00  3.927508e+00  3.430209e+00  1.593629e+00  2.962184e+00
  [451]  2.978649e+00  3.681046e+00  3.524623e+00  1.473278e+00  1.646133e+00
  [456]  2.944673e+00  2.455266e+00  3.242330e+00  1.042560e+00  3.395053e+00
  [461]  2.044203e+00  9.675390e-01  2.749751e+00  1.086308e+00  3.757063e+00
  [466]  2.312412e+00  2.726253e+00  3.221145e+00  3.327250e+00  2.052805e+00
  [471]  1.582981e+00  2.070823e+00  1.947544e+00  2.814502e+00  5.777856e-01
  [476]  3.728196e+00  3.844526e+00  2.714687e+00  3.682153e+00  3.313394e+00
  [481]  2.902050e+00  1.654589e+00  7.963543e-01  3.754335e+00  3.126412e+00
  [486]  1.256103e+00  1.963995e+00  2.758930e+00  6.761534e-01  1.726602e+00
  [491]  2.498020e+00  3.482680e+00  3.234540e+00  3.979697e+00  3.781049e+00
  [496]  3.679943e+00  3.534216e+00  3.710213e+00  9.923515e-02  2.953660e+00
  [501]  2.778828e+00  3.316239e-01  1.989423e+00  3.405026e+00  3.659487e+00
  [506]  3.498702e+00  3.521854e+00  3.496417e+00  1.990548e+00  2.977853e+00
  [511]  2.422704e+00  2.907098e+00  6.355769e-01  3.961225e+00  2.798360e+00
  [516]  3.854807e+00  2.906792e+00  2.570451e+00  2.420464e+00  1.911644e+00
  [521]  3.493006e+00  2.418703e+00  3.661067e+00  2.626444e+00  8.247879e-01
  [526]  2.565289e+00  3.955730e+00  1.618489e+00  1.477011e+00  2.983098e+00
  [531]  3.704109e+00  4.803821e-01  1.561266e+00  2.696218e+00  3.169821e+00
  [536]  3.550920e+00  2.229133e+00  1.396499e+00  3.608375e+00  3.608375e+00
  [541]  2.870761e+00  1.335523e+00  1.750276e+00  2.673675e+00  1.424902e+00
  [546]  3.591815e+00  1.882381e+00  3.843798e+00  3.412151e+00  1.340663e+00
  [551]  2.910809e+00  3.876069e+00  2.993264e+00  2.100418e+00  3.649413e+00
  [556]  2.754537e+00  4.113053e+00  3.808760e+00  2.431838e+00  1.374469e+00
  [561]  1.673024e+00  3.636176e+00  3.678262e+00  3.091897e+00  3.120339e+00
  [566]  3.723768e+00  2.739189e+00  3.692675e+00  2.627973e+00  3.190936e+00
  [571]  3.766128e+00  2.956053e+00  3.419004e+00  2.842041e+00  3.451595e+00
  [576]  3.451595e+00  4.042634e+00  3.668059e+00  3.782189e+00  3.910568e+00
  [581]  1.550813e+00  2.836602e+00  2.839386e-01  1.546472e+00  8.434373e-01
  [586]  2.426980e+00  1.560774e+00  1.740862e+00  4.038549e+00  1.694211e+00
  [591]  2.426591e+00  3.395542e+00  2.989934e+00  2.840395e+00  1.219777e+00
  [596]  1.657525e+00  2.657637e+00  8.530058e-01  6.460699e-01  1.533188e+00
  [601]  3.346882e+00  1.496602e+00  1.126423e+00  3.054247e+00  2.279317e+00
  [606]  1.933849e+00  3.406256e+00  3.559483e+00  3.756701e+00  2.707996e+00
  [611]  1.850831e+00  3.089078e+00  1.801258e+00  1.993389e+00  9.014795e-01
  [616]  2.731371e+00  3.267967e+00  2.979562e+00  3.304052e+00  2.378432e+00
  [621]  2.687430e+00  2.295768e+00  3.225203e+00  3.412402e+00  3.152864e+00
  [626]  2.837682e+00  2.321669e+00  9.056771e-01  2.030359e+00  2.656047e+00
  [631]  1.184715e+00  1.683141e+00  2.196190e+00  3.380145e+00  2.820523e+00
  [636]  3.005481e+00  3.080488e+00  1.515317e+00  2.128791e+00  6.969378e-01
  [641]  3.646507e+00  2.615586e+00  3.333558e+00  2.911460e+00  2.623103e+00
  [646]  3.521497e+00  2.053473e+00  2.752747e+00  1.432302e+00  2.750797e+00
  [651]  3.298892e+00  1.755437e+00  2.808743e+00  5.990902e-01  2.943552e+00
  [656]  1.379634e+00  1.206641e+00  1.578544e+00  3.886538e+00  1.318810e+00
  [661]  2.279134e+00  4.733864e-01  1.639581e+00  1.606642e+00  1.357251e+00
  [666]  1.846716e+00  1.533266e+00  2.123825e+00  1.463682e+00  2.424945e+00
  [671]  2.218904e+00  2.298507e+00  2.613607e+00  2.966082e+00  3.272386e+00
  [676]  2.250540e+00  3.209732e+00  3.118944e+00  3.598228e+00  3.313047e+00
  [681]  1.575771e+00  3.757296e+00  2.951235e+00  2.674955e+00  3.845099e+00
  [686]  1.661633e+00  2.876501e+00  3.158483e+00  2.325325e+00  3.534690e+00
  [691]  2.049016e-01  5.180710e-01  2.505043e+00  1.788088e+00  2.459371e+00
  [696]  1.248244e+00  3.540114e+00  7.579025e-01  3.172575e-01  2.352733e+00
  [701]  2.619101e+00  2.253112e+00  3.029434e+00  1.411328e+00  1.342775e+00
  [706]  1.636003e+00  1.230417e+00  3.323946e+00  2.257100e+00  3.045929e+00
  [711]  3.370868e+00  1.495426e+00  1.054162e+00  2.982335e+00  2.819547e+00
  [716]  1.073603e+00  2.399616e+00  1.050370e+00  1.444353e+00  2.698075e+00
  [721]  1.622791e+00  3.133628e+00  2.073585e+00  3.095888e+00  2.788253e+00
  [726]  2.460037e+00  1.419266e+00  2.484126e+00  2.252891e+00  1.601147e+00
  [731]  3.011043e+00  2.348362e+00  1.537994e+00  3.183101e+00  3.239435e+00
  [736]  9.839938e-01  1.486499e+00  2.888252e+00  1.664845e+00  1.034961e+00
  [741]  1.842978e+00  2.032399e+00  6.378082e-01  1.912470e+00  1.841817e+00
  [746]  1.139324e+00  8.652371e-01  1.793349e+00  2.831358e+00  5.504976e-01
  [751]  2.736968e+00  2.684547e+00  3.555844e+00  3.153195e+00  3.159054e+00
  [756]  3.920659e+00  3.835297e+00  2.367059e+00  3.422339e+00  1.547928e+00
  [761]  9.391197e-01  2.208668e+00  3.953724e+00  2.717357e+00  2.170757e+00
  [766]  2.793175e+00  2.798706e+00  6.869456e-01  1.708398e+00  1.973132e+00
  [771]  1.445224e+00  3.132698e+00  7.858282e-01  1.826460e+00  2.806388e+00
  [776]  1.687669e+00  5.557063e-01  2.263895e+00  2.421854e+00  3.640778e+00
  [781]  3.269772e+00  2.242170e+00  2.692750e+00  3.460552e+00  2.633162e+00
  [786]  9.388900e-01  1.830647e+00  2.243683e+00  2.315383e+00  2.623676e+00
  [791]  2.757112e+00  6.912478e-01  1.632680e+00  2.540694e+00  1.196254e+00
  [796]  1.778884e+00  8.173211e-01  2.645131e+00  1.351863e+00  1.759187e+00
  [801]  7.799956e-01  2.052917e+00  2.822564e+00  6.311546e-01  2.433561e+00
  [806]  2.316964e+00  3.509569e+00  2.351262e+00  3.221875e+00  3.731419e-01
  [811]  1.900655e+00  3.720859e+00  3.973172e+00  2.917766e+00  1.539069e+00
  [816]  2.559680e+00  1.723905e+00  2.527651e+00  1.122346e+00  2.439923e+00
  [821]  9.660263e-01  2.525780e+00  7.590671e-01  2.453890e+00  1.321953e+00
  [826]  1.213729e+00  3.303766e+00  1.221866e+00  1.876180e+00  3.099784e+00
  [831]  2.684539e+00  1.550908e+00  3.213950e+00  1.753079e+00  3.806751e+00
  [836]  3.137099e+00  1.240245e+00  2.242114e+00  1.452856e+00  9.317136e-01
  [841]  1.115304e+00  2.533503e+00  1.948717e+00  1.228317e+00  2.390387e+00
  [846]  1.517712e+00  2.485085e+00  1.455553e+00  1.166279e+00  2.542691e+00
  [851]  2.419037e+00  2.880089e+00  2.986644e+00  3.533530e+00  2.433851e+00
  [856]  4.014524e+00  1.384148e+00  3.155240e+00  4.597482e-01  1.859364e+00
  [861]  1.459688e+00  3.215919e+00  3.403415e+00  8.209772e-01  2.527821e+00
  [866]  2.603871e+00  1.016103e+00  1.331784e+00  2.549008e+00  2.195752e+00
  [871]  1.766676e+00  3.383872e+00  1.640446e+00  3.587162e+00  1.466695e+00
  [876]  3.060812e+00  1.712606e+00  3.413110e+00  3.244573e+00  3.040963e+00
  [881]  2.563515e+00  1.277102e+00  2.746722e+00  3.488275e+00  2.944551e+00
  [886]  1.344265e+00  3.782425e+00  1.865354e+00  2.686771e+00  1.645326e+00
  [891]  2.389698e+00  5.489057e-01  2.742349e+00  2.651430e+00  2.060284e+00
  [896]  1.486996e+00  1.398974e+00  2.750410e+00  1.505814e+00  3.022643e+00
  [901]  3.198468e+00  1.249212e+00  2.919225e+00  3.677673e+00  2.491483e+00
  [906]  1.796881e+00  3.356399e+00  3.629575e+00  3.109964e+00  2.028773e+00
  [911]  1.632319e+00  3.287904e+00  3.220993e+00  1.659302e+00  3.194939e+00
  [916]  3.641037e+00  2.390354e+00  2.064270e+00  3.420864e+00  2.704743e+00
  [921]  2.116744e+00  1.327892e+00  2.810123e+00  1.836879e+00  2.908589e+00
  [926]  1.529530e+00  1.693338e+00  2.409086e+00  2.748167e+00  1.872734e+00
  [931]  3.347182e+00  1.831577e+00  2.782131e+00  3.025762e+00  2.568750e+00
  [936]  1.992053e+00  2.239448e+00  1.921424e+00  2.835851e+00  2.896186e+00
  [941]  2.804928e+00  1.118839e+00  2.812990e+00  2.640246e+00  1.869671e+00
  [946]  2.406085e+00  3.872804e+00  1.850779e+00  3.351241e+00  2.609757e+00
  [951]  2.026988e+00  8.647879e-01  2.624416e+00  2.207088e+00  1.183354e+00
  [956]  1.933632e+00  1.669952e+00  2.582049e+00  2.720334e+00  2.106886e+00
  [961]  1.859011e+00  1.281417e+00  1.207428e+00  1.438970e+00  2.091894e+00
  [966]  1.885678e+00  2.986499e+00  2.019586e+00  3.632551e+00  7.453096e-01
  [971]  1.190663e+00  2.418899e+00  2.951441e+00  2.157471e+00  2.704111e+00
  [976]  9.904528e-02  9.688507e-01  2.543904e+00  2.252011e+00  2.892507e+00
  [981] -1.294775e-01  2.321450e+00  2.867409e+00  8.933718e-01  1.837077e+00
  [986]  1.419056e+00  2.186531e+00  2.420421e+00  1.840305e+00  2.440493e+00
  [991]  1.824399e+00  3.818246e+00  1.923463e+00  2.526808e+00  2.503804e+00
  [996]  1.100397e+00  2.299722e+00  2.742912e+00  2.946105e+00  1.715081e+00
 [1001]  3.464011e+00  1.193282e+00  3.646938e+00  2.985084e+00  2.675666e+00
 [1006]  2.769335e+00  3.409386e+00  2.801581e+00  3.169583e+00  1.273165e+00
 [1011]  3.055362e+00  3.060626e+00  2.519234e+00  3.005177e+00  1.600575e+00
 [1016]  2.869930e+00  3.667524e+00  1.527234e+00  3.088179e+00  2.898334e+00
 [1021]  3.294327e+00  3.173523e+00  2.472576e+00  2.977808e+00  2.586469e+00
 [1026]  2.720164e+00  3.197366e+00  2.823802e+00  1.147476e+00  2.337626e+00
 [1031]  5.743668e-01  1.969150e+00  3.556129e+00  1.877538e+00  3.065803e+00
 [1036]  2.181883e+00  1.907146e+00  2.591160e+00  3.607292e+00  3.170757e+00
 [1041]  2.883863e+00  1.708757e+00 -1.968302e-01  2.418848e+00  3.367340e+00
 [1046]  2.037570e+00  2.036567e+00  2.140121e+00  1.898351e+00  2.331368e+00
 [1051]  1.307012e+00  2.446898e+00  1.158812e+00  1.244753e+00  4.087019e+00
 [1056]  6.513206e-01  1.586913e+00  1.291672e+00  2.221603e+00  2.243731e+00
 [1061]  2.834965e+00  2.244046e+00  1.912272e+00  3.629807e+00  1.283486e+00
 [1066]  2.688078e+00  3.104038e+00  1.702839e+00  3.054762e+00  2.127829e+00
 [1071]  2.538550e+00  3.728154e+00  1.697153e+00  2.197231e+00  2.101445e+00
 [1076]  2.166994e+00  1.499761e+00  5.860574e-01  1.869676e+00  9.982467e-01
 [1081]  2.084572e+00  2.522041e+00  2.337161e+00  1.748720e+00  3.032916e+00
 [1086]  1.487659e+00  2.171524e+00  7.162169e-01  2.647847e+00  1.435650e+00
 [1091]  2.217146e+00  1.085538e+00  2.303257e+00  3.500770e+00  2.799151e+00
 [1096]  2.093522e+00  2.064373e+00  3.508150e+00  1.891081e+00  3.291134e+00
 [1101]  2.293409e+00  2.211857e+00  1.991119e+00  2.307567e+00  1.339653e+00
 [1106]  3.916120e+00  3.441402e+00  7.771614e-01  1.006967e+00  3.065837e+00
 [1111]  2.326131e+00  4.029704e+00  2.737188e+00  8.224703e-01  3.069014e+00
 [1116]  1.296090e+00  2.572024e+00  2.150162e+00  6.558847e-01  1.850619e+00
 [1121]  2.267208e+00  3.106937e+00  9.493428e-01  2.962785e+00  3.414176e+00
 [1126]  3.732007e+00  3.129821e+00  1.748494e+00  2.348207e+00  2.792322e+00
 [1131]  2.437197e+00  1.761593e+00  2.414915e+00  2.485983e+00  2.071197e+00
 [1136]  2.632880e+00  1.413102e+00  5.159891e-01  1.243060e+00  4.335098e-01
 [1141]  3.646158e+00  2.985650e+00  3.328670e+00  1.838739e+00  2.953626e+00
 [1146]  3.106821e+00  1.628342e+00  2.848633e+00  3.790348e+00  2.545282e+00
 [1151]  2.245657e+00  3.141162e+00  2.880406e+00  2.434547e+00  3.340207e+00
 [1156]  2.460317e+00  2.389820e+00  2.032866e+00  2.312451e+00  2.338566e+00
 [1161]  9.892653e-01  1.998092e+00  1.050803e+00  3.454809e+00  2.561704e+00
 [1166]  2.812756e+00  2.199128e+00  1.320100e+00  1.766805e+00  9.635705e-01
 [1171]  2.892182e+00  3.479029e+00  2.074824e+00  3.618463e+00  4.128908e+00
 [1176]  3.369642e+00  1.097453e+00  3.433394e+00  2.596985e+00  2.082951e+00
 [1181]  2.324350e+00  2.633476e+00  6.540458e-01  1.413436e+00  2.195400e+00
 [1186]  2.026657e+00  1.536860e+00  2.889345e+00  2.124820e+00  2.840650e+00
 [1191]  3.222675e+00  3.399528e+00  1.150385e+00  2.244726e+00  2.295655e+00
 [1196]  1.047988e+00  2.877847e+00  2.247935e+00  8.412883e-01  2.506243e+00
 [1201]  3.080606e+00  2.831047e+00  3.962517e+00  3.223932e+00  3.383610e+00
 [1206]  3.017317e+00  2.387476e+00  2.853876e+00  3.282053e+00  1.515647e+00
 [1211]  1.385677e+00  3.451454e+00  3.231845e+00  2.990829e+00  2.403180e+00
 [1216]  2.946076e+00  3.243108e+00  3.863602e+00  3.664995e+00  1.337605e+00
 [1221]  1.021095e+00  2.703434e+00  2.113395e+00  2.319276e+00  2.131280e+00
 [1226]  1.947196e+00  2.992144e+00  3.977486e+00  2.905143e+00  3.124545e+00
 [1231]  2.871345e+00  3.842574e+00  3.802280e+00  2.771232e+00  2.938203e+00
 [1236]  2.746809e+00  1.329360e+00  3.797015e+00  2.319708e+00  2.207980e+00
 [1241]  4.535995e+00  2.881529e+00  2.696352e+00  1.244018e+00  2.735034e+00
 [1246]  3.676051e+00  4.159261e+00  2.485312e+00  2.428125e+00  2.121479e+00
 [1251]  2.081991e+00  1.678324e+00  1.906555e+00  1.043497e-01  6.533958e-01
 [1256]  2.035065e+00  2.141824e+00  1.299356e+00  1.361437e+00  2.263935e+00
 [1261]  3.420958e+00  1.114710e+00  2.058751e+00  1.938509e+00  3.822152e-01
 [1266]  8.466862e-01  3.353544e+00  2.516357e+00  2.716187e+00  2.886009e+00
 [1271]  3.453170e+00  2.505746e+00  2.248096e+00  1.804322e+00  2.060362e+00
 [1276]  3.289169e+00  3.189682e+00  3.613341e+00  3.560271e+00  4.049686e+00

In [44]:
xgbclsmin

    [1] 3 0 1 3 4 4 4 4 4 2 4 4 4 4 1 4 4 4 4 4 4 4 2 4 4 4 4 4 4 4 1 4 4 4 4 4
   [37] 4 3 4 4 4 3 4 4 1 4 4 4 0 3 4 2 4 4 4 3 4 4 3 0 4 4 4 4 4 0 4 4 0 2 4 4
   [73] 1 4 4 4 4 4 4 4 4 4 4 4 1 2 4 4 3 2 3 2 4 4 2 3 4 2 1 4 2 3 4 4 0 0 4 1
  [109] 2 0 2 3 4 0 0 2 2 0 2 4 2 0 2 0 2 4 4 1 4 4 0 4 4 3 4 4 4 3 2 4 4 3 4 4
  [145] 4 2 4 4 4 2 4 4 4 3 1 3 4 4 4 3 2 4 2 4 4 4 4 2 4 4 4 2 3 3 4 0 4 2 1 4
  [181] 0 4 4 3 2 2 1 4 4 2 0 1 4 4 2 3 0 2 2 4 1 4 1 3 0 0 2 4 0 0 2 2 1 0 4 3
  [217] 0 4 2 4 4 4 4 0 4 2 4 1 0 2 1 1 0 4 0 4 2 2 0 4 4 3 0 3 4 4 3 3 0 4 4 4
  [253] 4 0 0 4 4 4 3 4 2 0 4 3 1 0 2 1 4 2 4 2 4 2 4 4 0 4 4 4 2 3 4 4 4 4 3 1
  [289] 1 4 2 4 4 1 0 4 4 4 0 4 4 4 2 4 1 2 1 0 2 2 1 0 1 1 1 0 4 2 4 2 4 4 4 4
  [325] 1 4 0 0 4 1 4 4 2 3 4 4 4 4 2 3 4 0 1 4 4 4 0 4 2 3 4 2 2 4 1 4 2 1 1 2
  [361] 4 3 4 3 3 0 4 4 4 4 4 3 4 2 2 0 4 3 4 3 4 4 4 4 4 4 4 2 4 4 3 4 4 4 4 1
  [397] 4 0 4 2 4 4 1 4 4 4 4 4 4 4 4 4 4 2 3 4 4 4 4 4 4 4 4 4 4 1 4 1 4 3 4 4
  [433] 3 4 1 1 1 3 3 4 2 4 4 4 4 4 4 4 1 4 4 4 4 1 4 3 4 4 0 4 2 1 4 1 4 4 3 4
  [469] 4 0 1 0 2 2 0 4 4 3 4 4 3 1 1 4 3 1 2 4 0 1 4 4 4 4 4 4 4 4 0 3 4 1 1 4
  [505] 4 4 4 4 4 3 4 3 0 4 4 4 2 4 2 4 4 3 4 4 0 1 4 3 1 4 4 4 3 4 3 4 3 1 4 4
  [541] 4 1 0 4 2 4 2 4 4 1 4 4 4 4 4 4 4 4 2 0 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4 4
  [577] 4 4 4 4 1 3 0 2 0 4 0 4 4 1 4 4 3 4 4 4 4 0 0 2 3 0 0 4 4 1 4 4 4 2 1 4
  [613] 2 2 0 4 4 4 4 0 4 4 4 4 4 4 1 0 2 2 0 2 4 4 4 4 4 2 4 0 4 4 4 4 4 4 2 4
  [649] 0 4 3 4 4 1 4 0 1 4 4 0 4 0 1 0 0 4 0 4 2 3 1 4 3 4 3 4 4 4 4 3 4 4 4 4
  [685] 4 1 4 4 4 3 2 0 4 1 4 2 4 0 0 1 4 4 4 1 1 0 0 4 4 4 4 1 1 4 3 0 4 0 0 4
  [721] 0 3 4 4 4 4 2 4 2 0 4 2 1 4 4 0 0 4 1 3 0 3 0 2 1 1 1 1 4 1 4 4 4 4 3 4
  [757] 4 4 4 4 0 4 4 3 2 3 3 4 1 0 4 4 0 4 4 4 1 2 4 4 4 4 1 4 4 0 0 4 4 4 4 0
  [793] 1 3 0 2 0 3 2 4 1 4 1 0 1 0 4 2 4 1 4 4 4 4 0 4 4 3 4 3 4 4 0 2 3 2 4 0
  [829] 1 1 4 0 4 1 4 4 0 4 0 0 0 3 1 0 4 4 3 0 1 4 2 3 4 4 3 4 1 4 0 0 1 4 4 0
  [865] 4 2 4 1 4 4 4 4 2 4 2 4 4 4 4 4 3 1 4 4 4 0 4 4 4 3 4 2 3 4 0 0 2 3 1 4
  [901] 4 0 4 4 4 1 4 4 4 2 0 4 3 4 4 4 2 4 4 4 4 2 4 0 4 0 0 4 3 1 4 4 4 4 1 3
  [937] 4 4 3 3 4 2 4 4 4 3 4 0 4 3 4 1 3 1 1 2 2 4 4 4 1 1 4 0 4 2 3 4 4 2 0 0
  [973] 4 4 4 4 0 4 2 4 3 1 3 0 4 4 4 4 0 4 2 4 4 4 4 4 0 4 4 4 4 4 4 3 4 4 4 4
 [1009] 4 4 4 3 4 4 4 3 4 0 3 1 4 4 2 4 4 4 4 3 4 4 0 4 4 4 2 2 0 3 4 4 4 4 0 1
 [1045] 4 4 4 4 1 3 0 4 0 2 4 0 1 0 2 4 4 4 3 4 4 4 3 4 4 2 3 4 1 3 0 4 1 0 4 0
 [1081] 4 3 3 1 4 1 3 2 4 0 3 1 4 4 3 3 3 4 0 4 2 1 3 3 1 4 4 3 1 4 4 4 4 0 4 0
 [1117] 3 2 0 2 3 4 4 4 4 4 3 0 3 1 4 4 4 0 2 3 4 1 0 0 4 4 4 1 4 3 3 3 4 4 3 4
 [1153] 2 4 4 4 4 2 3 4 1 4 1 4 2 3 3 0 1 0 3 4 2 4 4 4 4 4 4 2 2 4 4 0 1 2 3 4
 [1189] 4 2 4 4 0 1 4 0 4 2 2 4 4 4 4 4 3 3 4 3 4 1 1 4 4 2 3 4 3 4 4 1 0 4 4 4
 [1225] 1 4 2 4 4 4 4 4 4 3 4 3 1 3 1 3 4 4 3 0 3 4 4 2 4 4 1 4 4 0 0 4 2 2 4 3
 [1261] 4 0 2 0 0 0 4 4 4 4 4 4 2 2 4 4 4 4 4 4 4 3 3 4 4 4 3 0 1 4 4 4 1 4 4 4
 [1297] 4 4 2 4 4 2 4 4 4 4 4 3 4 0 4 4 4 4 4 3 4 4 0 4 1 4 3 4 3 4 4 4 3 3 0 3
 [1333] 4 4 1 4 4 4 3 4 4 4 4 3 4 4 4 4 3 4 1 4 3 4 0 3 4 3 4 4 4 4 4 3 3 3 3 0
 [1369] 3 4 4 2 4 4 3 3 1 4 3 4 4 4 3 3 4 0 4 4 3 4 4 4 1 0 4 4 4 1 4 4 4 0 4 4
 [1405] 4 4 1 4 4 0 4 4 4 4 4 4 1 2 4 4 0 4 4 2 4 4 4 4 0 2 4 1 0 4 2 4 3 4 3 1
 [1441] 3 1 4 3 4 4 4 2 4 4 4 4 4 3 3 4 4 4 0 4 4 4 4 4 4 4 4 4 4 2 4 4 1 4 4 4
 [1477] 4 2 4 4 2 4 4 4 4 4 0 4 4 2 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4 4
 [1513] 4 4 4 4 3 4 2 4 4 4 4 3 3 4 4 4 4 4 0 1 4 4 0 4 4 4 4 4 4 0 4 3 4 4 0 4
 [1549] 4 4 4 4 4 4 2 4 3 3 4 4 4 4 1 2 4 4 4 4 4 4 4 4 4 4 3 4 4 4 2 3 4 4 4 4
 [1585] 1 4 4 4 4 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4 4 4 4 3 3 4 4 4 3
 [1621] 4 4 4 2 2 3 4 4 4 4 2 2 2 2 4 4 4 4 4 1 0 1 4 4 4 0 2 0 4 0 4 2 2 3 4 4
 [1657] 1 4 4 4 4 4 4 4 4 0 0 2 4 0 3 4 4 4 4 4 0 4 4 4 4 2 4 1 0 4 4 3 3 4 4 2
 [1693] 4 4 4 4 4 3 0 3 3 2 1 4 4 4 4 3 4 3 4 4 1 4 4 4 3 3 4 4 2 4 4 4 4 4 4 4
 [1729] 2 4 4 4 4 4 4 4 4 1 1 1 1 2 4 4 2 2 4 4 4 0 4 1 4 4 4 2 4 3 4 4 3 2 3 4
 [1765] 4 2 2 4 4 2 2 2 4 2 4 4 4 4 4 4 0 4 4 4 4 4 4 4 1 2 4 0 3 3 4 3 4 4 4 4
 [1801] 3 4 3 3 2 0 4 4 4 3 4 4 4 4 3 3 4 4 4 3 4 4 3 4 4 4 2 4 3 3 2 3 2 3 2 2
 [1837] 4 4 4 3 4 4 3 4 4 3 4 2 4 4 4 3 4 4 2 4 4 3 1 4 3 2 4 4 3 4 4 3 4 4 4 4
 [1873] 4 3 2 2 2 4 2 4 4 4 4 4 4 4 4 2 2 4 4 4 4 4 4 4 4 3 4 4 4 3 4 4 2 3 4 4
 [1909] 3 4 4 4 4 4 2 4 4 4 4 4 4 4 4 4 4 4 4 4 2 4 3 1 2 2 2 4 3 4 4 4 3 2 2 4
 [1945] 4 4 3 4 2 3 2 0 3 4 4 4 4 3 4 3 3 3 4 4 4 3 4 4 1 4 2 4 4 4 4 4 1 4 4 1
 [1981] 0 4 3 2 4 1 4 0 4 0 4 3 4 4 2 4 4 3 4 3 3 1 2 4 4 4 4 4 2 4 4 4 4 2 4 4
 [2017] 2 4 4 4 2 3 4 1 4 4 3 4 4 4 4 1 4 3 4 4 3 2 1 2 4 3 3 4 4 4 0 4 4 4 4 3
 [2053] 4 4 4 4 3 4 4 4 3 3 3 4 0 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 4 4 3 3 2 4 2 0
 [2089] 3 2 2 3 3 3 2 4 4 3 4 3 3 4 4 4 3 4 4 4 4 2 4 4 0 4 4 2 3 4 4 3 2 2 3 4
 [2125] 3 4 2 3 4 4 4 3 4 4 4 4 4 4 2 0 4 2 2 2 3 2 2 3 2 3 4 4 4 3 1 2 2 2 4 3
 [2161] 4 2 3 4 3 4 2 1 3 4 4 4 4 4 4 1 4 2 2 4 4 3 4 4 3 3 4 2 4 4 2 2 4 4 4 1
 [2197] 4 4 4 4 0 0 4 2 4 4 4 1 2 4 3 3 0 4 1 4 1 0 4 3 3 1 3 4 2 1 4 2 4 4 4 3
 [2233] 1 4 2 3 4 4 0 0 4 4 3 4 3 4 0 4 1 4 2 4 3 4 4 1 4 2 4 4 3 3 4 3 2 3 3 4
 [2269] 4 3 2 4 3 2 4 4 4 4 2 4 3 4 4 1 0 2 0 0 4 4 4 4 2 1 4 2 4 1 4 3 3 4 4 4
 [2305] 3 3 3 0 0 0 1 4 4 4 4 4 3 4 4 4 0 4 4 1 2 3 1 0 0 0 4 4 2 1 3 2 4 4 4 4
 [2341] 1 4 4 4 4 4 4 2 4 4 4 2 4 0 4 4 0 3 4 4 4 4 0 2 0 0 4 3 1 4 4 4 3 4 0 4
 [2377] 2 0 4 4 0 2 4 4 4 0 4 0 1 4 0 4 4 4 4 4 4 2 2 3 1 4 4 4 0 1 4 0 0 0 4 0
 [2413] 1 0 4 0 0 4 4 4 1 0 0 4 4 0 4 0 1 3 1 4 0 4 1 3 4 0 1 4 2 2 4 2 3 4 2 4
 [2449] 0 3 1 4 4 4 1 0 4 4 0 4 0 0 4 4 4 4 4 4 2 0 4 4 4 0 3 1 0 0 1 4 4 4 4 4
 [2485] 1 0 0 2 3 4 4 4 4 4 3 0 0 4 4 0 1 4 4 2 1 4 4 4 4 2 1 4 4 2 4 4 0 2 4 1
 [2521] 0 4 3 0 1 3 4 3 3 3 4 4 4 2 4 4 4 4 4 3 0 4 0 1 0 1 4 3 1 1 4 3 4 2 2 4
 [2557] 2 4 4 0 1 2 4 1 3 2 2 2 2 4 0 3 4 1 1 3 2 4 4 2 1 2 1 4 2 1 2 0 4 3 1 3
 [2593] 4 4 1 4 2 2 4 3 1 4 1 3 2 3 4 0 4 4 4 1 1 3 2 4 0 4 4 2 0 1 1 0 1 1 4 0
 [2629] 0 2 4 4 4 0 4 4 4 3 2 4 4 4 0 4 4 4 2 4 4 2 4 2 4 1 2 0 0 4 0 4 1 4 3 1
 [2665] 0 4 3 2 4 3 4 3 0 4 4 4 4 4 4 4 4 4 2 3 3 4 0 3 4 4 4 2 4 0 2 3 3 3 4 4
 [2701] 4 3 2 2 3 1 4 4 4 3 0 2 4 4 4 0 4 0 4 4 4 0 3 4 4 0 0 0 3 2 4 1 4 3 2 0
 [2737] 4 4 4 0 4 4 1 3 4 1 4 1 1 4 4 3 3 0 1 4 1 4 4 4 4 4 1 4 4 4 1 4 4 2 0 4
 [2773] 4 4 4 4 3 1 4 4 4 4 3 3 4 4 1 2 4 4 4 4 4 4 4 4 1 4 4 0 4 4 4 4 4 2 4 4
 [2809] 4 4 4 4 4 4 4 4 4 4 0 3 4 2 4 2 4 3 4 4 4 4 4 4 4 3 4 2 3 4 4 4 4 4 3 4
 [2845] 4 3 4 2 3 3 4 0 0 4 4 4 0 3 4 4 4 4 4 4 1 4 4 4 4 0 3 2 0 1 1 3 4 4 0 4
 [2881] 3 4 3 4 4 4 3 0 4 3 1 4 1 1 4 1 4 4 4 4 4 1 4 4 3 4 4 4 2 4 4 0 3 1 4 4
 [2917] 3 1 4 4 4 4 3 1 0 0 2 0 4 3 3 4 4 3 4 3 4 4 4 4 4 4 4 4 4 4 4 4 1 4 4 0
 [2953] 4 4 4 4 2 2 4 4 4 4 4 1 4 4 4 4 4 3 3 4 4 1 2 2 1 3 4 4 4 4 4 2 4 4 0 4
 [2989] 4 4 4 4 4 4 1 3 4 2 2 2 3 4 4 2 4 4 4 4 3 4 4 3 4 4 4 4 1 4 4 4 4 2 0 4
 [3025] 4 4 4 3 4 4 4 4 4 1 2 4 4 1 4 3 2 1 4 4 3 4 4 4 1 2 2 0 3 4 0 0 4 1 4 4
 [3061] 1 2 0 2 4 4 3 0 4 3 0 4 4 4 0 4 4 4 3 0 2 1 4 4 4 2 4 4 1 4 4 4 4 4 0 4
 [3097] 4 4 4 3 4 0 4 2 4 4 1 0 2 2 4 0 0 1 4 0 4 4 4 4 1 3 4 1 0 1 4 0 4 4 4 4
 [3133] 4 4 3 0 4 4 4 3 0 2 4 4 3 4 2 4 4 4 4 0 4 1 3 4 1 2 4 4 4 4 0 1 4 1 3 2
 [3169] 4 3 1 0 4 0 4 1 1 2 1 3 4 2 1 1 4 0 0 4 4 2 4 0 0 4 2 4 2 1 4 4 4 2 0 0
 [3205] 0 4 1 4 0 1 1 4 4 0 4 4 0 2 1 4 0 4 4 1 3 3 4 4 4 4 2 4 0 4 4 4 3 4 4 4
 [3241] 4 0 4 3 0 4 4 1 4 3 4 4 1 4 4 4 4 3 4 3 2 3 4 4 4 4 1 0 2 2 1 3 2 2 1 4
 [3277] 4 4 4 0 4 3 0 4 4 2 2 3 4 3 3 1 0 4 4 3 4 4 0 2 4 3 3 4 4 4 0 4 4 4 4 4
 [3313] 4 4 4 1 2 2 1 4 0 4 2 4 4 4 4 4 0 1 4 4 4 4 4 4 0 2 0 4 2 4 3 2 0 2 4 0
 [3349] 4 0 4 4 0 4 2 4 4 4 4 2 2 4 4 3 2 4 1 0 4 0 4 4 0 4 4 0 4 4 1 4 4 2 1 4
 [3385] 1 3 4 0 4 0 3 4 1 2 2 4 0 0 4 0 4 4 4 4 1 2 2 4 4 4 3 4 4 4 3 4 4 4 0 0
 [3421] 3 4 4 4 1 4 0 0 1 1 4 1 4 2 1 2 4 2 4 4 4 4 4 4 4 4 0 1 4 4 2 3 1 4 4 2
 [3457] 4 4 0 2 4 4 4 4 4 4 0 4 1 4 4 4 4 2 4 4 1 4 0 4 4 4 0 4 0 1 4 4 4 4 4 2
 [3493] 4 2 4 4 4 3 0 2 4 4 2 4 1 4 3 4 3 4 4 1 1 4 4 4 4 3 4 3 4 4 2 4 4 4 4 4
 [3529] 0 1 2 4 4 1 4 4 4 0 3 4 4 3 4 4 4 3 2 4 4 2 4 2 4 1 4 4 2 0 4 0 4 1 0 4
 [3565] 4 1 4 2 4 3 4 4 1 0 4 4 4 1 4 4 4 1 4 4 4 4 4 4 4 0 4 4 0 2 4 4 3 4 4 4
 [3601] 4 1 4 4 4 4 2 4 4 4 4 4 1 4 0 4 4 4 4 4 4 4 4 4 4 0 4 4 4 4 4 1 4 1 1 1
 [3637] 4 2 1 4 3 0 4 4 4 4 4 4 4 2 4 4 1 4 4 4 4 4 0 4 2 4 4 4 4 4 4 4 4 4 4 4
 [3673] 4 0 4 0 0 4 4 4 4 1 4 4 4 4 4 4 3 3 0 4 2 4 4 0 4 4 2 4 4 4 4 4 4 4 2 1
 [3709] 0 1 2 3 4 4 4 0 0 3 4 4 2 4 3 4 4 3 0 4 1 4 4 4 3 4 2 4 3 3 4 4 4 4 0 4
 [3745] 3 4 4 4 1 2 4 4 4 4 1 1 4 4 2 0 0 4 0 0 1 4 4 0 2 0 4 4 0 3 4 2 4 2 2 4
 [3781] 0 0 0 1 0 0 2 0 2 4 1 4 4 2 4 1 4 2 4 4 4 3 4 4 2 4 4 4 1 0 2 1 4 4 4 4
 [3817] 4 4 4 4 4 3 4 4 4 4 3 4 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 [3853] 4 4 0 4 2 4 2 2 4 4 4 3 4 4 4 4 4 4 1 1 3 4 4 4 4 2 4 4 4 4 4 1 2 1 4 4
 [3889] 4 4 4 0 4 4 0 2 4 4 2 4 4 4 1 1 4 1 3 1 4 3 0 4 2 2 4 4 4 2 4 4 0 3 3 4
 [3925] 4 4 4 4 4 1 4 4 1 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 0 3 4 3 4 4
 [3961] 4 4 4 2 4 4 4 1 4 2 4 4 1 4 3 1 4 1 4 4 1 0 2 1 3 3 4 3 4 4 4 4 4 2 2 2
 [3997] 0 2 3 4 4 4 3 4 4 4 4 3 3 1 4 3 4 2 0 3 3 3 4 4 4 4 4 4 4 3 4 4 4 4 3 4
 [4033] 4 4 4 3 1 4 0 0 4 4 1 1 1 4 4 4 0 4 1 4 2 4 4 3 4 0 1 0 1 4 1 3 1 0 3 4
 [4069] 4 0 0 4 0 4 1 4 4 4 2 2 4 4 4 4 4 4 4 4 3 3 4 3 2 4 3 1 4 4 4 4 1 4 4 3
 [4105] 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 3 4 3 4 4 4 0 4 3 4 4 4 0 4 4 4 1 4 4 0
 [4141] 4 2 4 3 4 4 4 0 0 4 4 4 1 4 2 4 4 4 4 4 2 4 1 4 4 4 2 4 4 2 4 4 4 4 4 4
 [4177] 4 1 4 4 4 2 4 0 3 3 4 2 2 0 4 2 0 3 4 4 4 3 4 2 4 4 2 4 4 4 4 4 3 4 4 4
 [4213] 4 4 3 4 4 4 0 0 4 3 1 1 1 1 4 4 4 4 4 4 4 4 4 4 2 4 4 4 4 0 4 4 4 3 4 3
 [4249] 4 4 4 1 4 4 2 4 4 0 4 0 4 4 4 4 4 4 4 4 4 3 3 0 1 4 3 4 0 1 1 1 2 4 0 0
 [4285] 2 1 2 1 3 4 4 2 4 1 4 4 4 1 2 4 4 4 1 4 4 2 0 1 4 1 2 0 0 2 4 0 4 4 2 4
 [4321] 4 4 3 4 4 3 4 4 4 0 1 4 4 3 4 4 1 2 4 1 4 4 1 0 2 4 2 4 2 4 4 4 4 4 4 4
 [4357] 4 4 4 2 3 4 4 4 4 4 4 4 4 4 0 1 4 1 4 4 1 1 4 1 4 3 4 3 0 4 4 4 4 3 1 0
 [4393] 4 4 4 4 4 4 4 0 0 4 4 4 4 4 0 4 4 4 1 0 4 4 2 4 4 4 4 4 3 4 4 0 3 4 3 3
 [4429] 4 1 2 3 4 4 1 1 4 4 4 0 0 4 4 3 3 3 4 0 3 4 0 4 3 2 4 4 4 4 4 4 2 3 4 3
 [4465] 4 4 3 4 4 0 4 4 3 4 4 4 4 4 4 3 4 3 4 4 4 4 4 1 4 4 4 4 3 3 3 1 4 4 3 4
 [4501] 4 4 4 4 3 4 3 4 0 4 4 4 4 4 4 4 4 4 0 4 1 4 4 4 3 4 0 3 3 3 4 4 4 4 0 0
 [4537] 3 0 3 1 2 2 1 4 0 1 4 4 4 4 4 4 4 4 1 1 3 2 4 2 4 1 4 3 4 1 3 4 4 4 4 0
 [4573] 2 0 4 3 1 1 4 4 4 4 2 4 4 4 4 2 2 4 4 4 4 4 2 4 4 4 3 1 4 3 4 4 4 4 4 1
 [4609] 0 4 3 2 4 0 2 2 4 4 4 3 1 0 2 4 4 4 4 4 4 3 4 4 4 1 0 4 2 4 4 4 3 3 3 4
 [4645] 4 4 4 3 4 4 4 4 4 4 4 4 4 4 2 4 4 4 3 4 4 4 4 2 4 3 4 3 4 4 1 0 4 4 0 1
 [4681] 1 4 4 1 0 4 4 0 0 4 4 2 4 4 0 0 4 0 4 0 4 4 4 4 0 3 4 1 4 3 4 4 4 3 4 4
 [4717] 4 4 1 4 1 4 4 4 3 4 2 4 3 3 4 1 4 4 4 4 4 0 4 3 3 4 3 4 3 4 4 4 4 4 4 3
 [4753] 4 4 4 4 4 4 4 3 3 4 3 4 3 3 4 0 4 4 1 4 4 4 4 3 4 4 2 4 4 0 0 0 4 4 4 2
 [4789] 1 4 2 1 1 4 4 2 1 0 4 4 4 4 4 4 4 4 4 4 4 4 4 1 4 0 4 1 4 4 4 1 4 4 3 4
 [4825] 4 1 4 3 2 2 4 3 3 3 3 4 4 2 4 4 3 2 1 4 3 4 4 4 4 4 4 3 2 4 4 3 2 3 4 4
 [4861] 3 4 3 4 3 3 4 4 4 4 3 4 3 2 3 3 1 4 4 3 4 2 1 3 3 1 4 4 4 3 4 4 4 4 4 2
 [4897] 4 4 3 4 4 4 2 4 0 4 4 3 3 4 2 4 3 4 3 4 1 3 4 2 4 3 4 1 3 2 3 3 4 4 0 0
 [4933] 4 3 3 2 3 4 4 4 3 1 4 4 1 3 2 3 2 4 4 1 4 1 0 2 4 1 4 2 4 1 3 4 3 4 0 3
 [4969] 0 1 4 3 4 4 1 4 4 4 0 4 4 4 4 4 0 4 1 4 4 4 1 4 2 2 4 4 1 4 4 4 1 4 4 0
 [5005] 4 4 3 4 4 2 4 4 4 0 4 4 4 0 4 4 4 1 4 4 4 0 0 4 4 0 4 4 4 2 0 2 4 4 0 1
 [5041] 4 0 4 4 1 4 3 0 0 0 0 0 0 4 1 4 4 3 4 3 1 3 2 4 4 4 4 4 4 1 4 4 1 4 4 4
 [5077] 1 1 4 4 4 4 4 0 4 4 1 4 4 4 4 4 2 4 4 0 4 4 4 0 0 4 4 4 4 1 3 1 1 0 1 0
 [5113] 4 1 4 4 4 0 1 3 4 4 1 0 4 4 4 2 4 3 3 3 4 4 2 3 3 4 3 4 1 4 1 0 3 1 3 3
 [5149] 4 3 4 3 3 2 4 4 3 4 3 0 4 1 1 2 3 0 3 3 4 2 4 1 3 1 4 4 1 3 3 4 0 3 3 3
 [5185] 3 3 4 4 3 3 2 0 4 4 0 4 1 4 0 4 0 0 4 4 4 4 0 1 4 4 3 2 4 4 4 4 4 4 4 0
 [5221] 4 4 1 4 4 4 0 1 4 1 4 3 1 4 4 2 3 4 4 1 2 0 4 0 1 4 4 4 4 4 4 4 2 4 4 4
 [5257] 4 0 4 4 4 4 4 4 4 4 4 0 4 4 0 0 0 4 3 3 4 4 1 1 1 4 4 0 4 4 4 4 4 0 2 2
 [5293] 4 4 4 4 4 4 4 3 4 4 4 4 4 4 0 4 0 4 4 1 4 0 4 1 4 4 1 4 1 1 4 0 4 3 0 1
 [5329] 4 4 4 4 4 4 0 1 4 1 4 4 4 4 4 3 4 4 4 4 4 4 4 3 4 4 4 0 4 1 4 4 4 4 4 4
 [5365] 4 4 4 4 1 4 4 4 3 3 4 4 0 4 4 4 4 4 3 4 4 4 4 4 4 4 3 4 0 4 0 4 4 4 1 0
 [5401] 4 3 0 4 4 0 0 1 0 4 2 2 4 1 4 3 4 4 1 4 4 3 3 1 4 2 4 4 4 0 3 1 1 3 3 3
 [5437] 1 4 4 0 0 1 4 4 1 4 3 3 0 4 3 3 3 1 4 0 4 3 2 0 3 4 4 3 4 2 1 4 4 3 4 2
 [5473] 4 4 4 1 4 1 4 3 4 2 3 4 4 4 4 4 4 1 4 4 4 4 4 1 4 4 4 2 0 1 4 4 4 4 4 4
 [5509] 4 4 4 4 4 4 4 4 4 4 3 4 1 4 4 4 4 2 3 2 4 4 4 1 4 4 4 4 4 4 4 4 4 4 3 4
 [5545] 4 4 4 4 4 4 4 4 4 1 3 4 1 4 4 4 2 0 1 4 2 4 3 3 4 4 4 3 3 4 3 4 3 3 4 4
 [5581] 4 4 2 1 2 4 0 0 0 3 4 2 0 4 4 4 2 2 4 4 4 4 4 0 3 3 3 4 2 4 3 4 4 4 3 3
 [5617] 1 0 0 2 2 4 4 0 0 3 4 1 1 4 4 4 3 3 3 4 4 4 4 3 4 4 1 4 4 0 1 3 4 4 4 3
 [5653] 1 0 1 4 4 0 0 4 4 4 0 4 0 0 2 0 1 4 0 3 3 1 4 3 2 2 3 4 3 2 3 3 2 3 3 4
 [5689] 1 1 3 0 2 4 3 2 3 1 3 3 2 4 2 4 4 1 0 4 1 3 3 0 3 3 4 4 3 3 2 0 3 4 2 3
 [5725] 0 3 3 4 3 4 3 4 3 2 3 4 3 0 0 1 4 0 4 0 1 3 3 1 0 4 0 0 4 0 0 0 0 0 3 4
 [5761] 4 1 0 1 1 4 1 4 4 3 4 4 1 0 4 3 0 3 4 0 1 4 3 4 4 4 3 4 4 0 4 4 4 3 4 4
 [5797] 3 4 0 4 0 0 4 3 4 2 4 0 3 4 0 4 4 4 4 4 3 4 0 0 4 0 4 4 3 4 4 4 4 3 3 4
 [5833] 4 4 4 3 4 4 4 4 4 2 2 4 3 3 4 4 4 4 4 4 3 4 4 4 1 1 4 4 1 4 0 1 4 4 4 1
 [5869] 2 4 4 0 4 4 3 2 4 1 4 4 4 4 4 3 4 4 1 3 4 4 4 4 4 4 4 2 4 3 4 4 4 4 4 4
 [5905] 4 2 3 4 4 4 4 4 4 4 4 4 4 4 0 4 4 4 4 4 4 1 4 4 4 0 4 4 4 4 2 3 4 0 1 4
 [5941] 4 4 4 4 1 4 4 4 4 4 4 3 4 4 4 4 4 4 4 4 1 1 1 4 4 4 4 3 4 1 0 4 4 4 4 4
 [5977] 4 4 4 4 4 4 4 2 0 4 4 1 4 4 4 4 2 3 4 1 2 3 4 4 4 4 1 2 4 3 4 4 4 2 0 0
 [6013] 0 2 4 4 0 4 4 4 4 0 4 4 0 4 4 4 4 4 0 4 4 1 4 0 4 4 4 4 4 4 4 4 4 4 3 2
 [6049] 3 4 4 4 4 4 4 4 4 4 4 0 4 4 4 4 4 4 4 4 3 4 3 4 4 4 4 4 4 4 4 4 3 4 4 4
 [6085] 3 0 3 4 4 4 4 4 4 2 2 1 4 0 1 4 4 4 2 4 0 3 4 4 4 4 0 4 4 4 4 4 4 0 1 4
 [6121] 0 4 4 0 4 0 4 4 4 4 0 2 4 4 4 4 4 4 4 4 4 0 4 4 1 4 1 4 4 4 3 1 4 4 4 3
 [6157] 0 2 4 1 4 3 4 4 0 4 4 3 4 4 4 3 4 3 4 4 1 1 2 4 3 1 1 0 4 1 0 2 0 0 3 2
 [6193] 3 1 0 4 3 2 4 4 4 4 4 2 1 3 4 3 4 4 4 4 4 3 4 1 4 4 4 4 4 4 4 4 0 4 4 1
 [6229] 1 4 4 4 4 4 1 4 3 3 0 4 0 4 4 1 1 0 4 4 4 0 1 0 4 4 4 1 0 2 4 1 4 0 1 4
 [6265] 0 0 0 1 3 1 4 0 3 1 0 0 3 0 0 1 4 3 1 4 1 4 0 0 4 4 4 1 2 0 1 4 4 0 4 1
 [6301] 4 4 2 2 1 1 4 0 2 3 0 4 0 0 4 2 4 0 3 0 4 4 4 4 3 3 3 4 4 3 2 3 1 3 3 4
 [6337] 4 3 4 2 3 3 2 4 3 4 3 4 0 2 3 3 1 1 3 4 4 4 4 4 3 3 4 3 3 4 4 4 4 0 4 1
 [6373] 4 4 3 3 4 3 2 2 4 3 2 1 4 4 2 4 0 3 4 3 4 4 4 0 4 4 1 0 1 4 4 4 4 4 0 4
 [6409] 4 1 4 4 4 4 4 4 4 4 0 4 0 4 4 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 [6445] 4 4 4 4 4 3 4 4 4 4 4 4 4 2 4 3 3 1 1 4 2 3 1 3 3 4 3 2 1 1 3 3 4 3 4 4
 [6481] 3 1 4 4 4 4 4 4 2 2 3 3 1 3 3 1 1 4 3 2 2 4 3 4 2 1 2 3 4 0 0 3 3 3 0 0
 [6517] 3 3 4 2 3 4 4 1 0 3 1 3 1 1 4 4 1 4 0 3 0 4 0 1 0 0 1 4 4 0 4 1 1 3 4 3
 [6553] 2 3 4 1 4 4 2 1 4 3 1 4 4 4 4 4 4 4 4 3 4 2 4 2 4 4 4 4 4 4 4 4 4 4 4 4
 [6589] 3 4 4 4 4 4 4 4 4 4 4 4 4 4 1 4 0 4 4 3 4 1 1 1 4 4 4 4 3 4 1 4 4 4 2 4
 [6625] 4 4 4 4 2 4 4 4 2 4 2 4 4 3 4 4 3 0 3 4 4 4 4 4 4 4 4 0 4 4 4 0 4 4 4 3
 [6661] 4 4 1 3 3 4 4 3 1 2 3 0 1 4 0 1 4 4 1 3 3 4 4 4 4 4 2 0 0 3 4 3 1 4 4 1
 [6697] 4 4 1 4 4 4 1 1 4 4 0 4 1 4 1 4 2 2 1 1 4 4 4 1 1 4 1 4 4 2 2 4 4 3 4 1
 [6733] 4 0 0 4 4 3 4 4 2 0 4 0 0 3 4 3 4 4 4 1 4 4 3 4 4 3 4 4 0 3 4 3 2 3 4 4
 [6769] 1 2 3 4 3 4 4 2 2 2 4 3 4 2 3 1 1 4 4 0 4 0 4 4 4 4 4 4 0 4 4 4 4 4 4 4
 [6805] 4 4 4 4 4 4 4 4 4 4 4 3 4 4 4 3 4 4 4 4 4 3 4 3 3 4 4 4 4 4 4 4 4 4 4 4
 [6841] 3 4 4 4 4 3 0 4 0 2 4 0 4 4 4 4 4 2 2 4 2 3 2 1 3 3 4 2 3 1 3 3 3 4 3 0
 [6877] 1 3 1 2 3 4 4 1 4 4 4 2 3 3 1 4 3 3 2 4 4 4 4 3 4 0 4 4 4 2 3 2 4 3 3 4
 [6913] 3 4 4 3 4 4 4 1 4 4 4 4 1 4 0 4 4 4 4 3 4 4 4 3 2 1 4 3 4 0 0 2 3 4 4 0
 [6949] 2 1 1 4 4 4 4 4 0 1 0 4 4 1 0 3 2 3 4 3 4 4 3 4 4 0 4 4 4 4 1 4 4 3 4 4
 [6985] 4 4 4 4 4 4 3 4 4 1 1 1 1 0 4 4 4 3 4 4 4 4 4 0 4 4 4 4 0 4 4 2 4 0 4 4
 [7021] 3 4 3 1 4 4 1 4 4 1 4 1 1 2 1 4 4 4 4 4 1 0 4 4 4 4 4 0 4 3 0 4 4 4 4 4
 [7057] 0 4 4 4 3 3 4 4 4 0 0 4 4 4 3 3 4 4 1 3 4 0 4 4 4 4 4 1 4 4 4 4 4 0 4 4
 [7093] 4 2 4 4 0 4 4 0 4 4 0 3 4 4 4 4 4 4 4 4 0 4 0 0 4 4 4 4 0 1 0 4 4 3 4 2
 [7129] 4 4 4 4 4 4 4 4 4 1 4 1 4 4 0 4 2 4 4 4 4 4 2 1 1 3 0 1 4 4 4 4 4 4 1 1
 [7165] 4 4 4 0 4 4 4 1 4 4 4 4 4 1 1 4 4 4 0 1 4 1 4 4 1 4 4 1 0 4 4 0 1 0 4 1
 [7201] 4 4 4 4 4 4 4 4 4 3 3 4 4 4 4 4 4 1 4 4 4 0 4 4 4 4 4 4 4 0 4 4 4 4 4 4
 [7237] 4 4 3 1 3 4 4 4 4 4 3 3 4 4 0 4 4 4 1 4 0 3 4 4 4 0 4 3 3 4 4 4 1 4 1 3
 [7273] 1 4 4 3 4 4 4 3 4 4 4 3 1 4 4 3 3 4 0 0 0 1 4 3 4 4 4 4 4 3 4 4 4 4 0 0
 [7309] 4 4 1 3 3 3 3 4 4 4 1 4 4 1 4 1 3 4 4 4 4 4 4 4 4 4 0 0 2 3 1 4 1 4 1 2
 [7345] 3 0 4 4 4 0 4 4 4 3 3 4 2 4 4 4 4 4 4 4 4 4 0 1 4 4 0 4 4 4 0 0 4 4 4 0
 [7381] 1 1 4 1 4 4 1 4 4 4 4 4 4 4 0 4 4 2 4 4 0 4 4 3 4 4 4 1 4 4 0 4 4 4 4 4
 [7417] 4 4 4 4 0 4 4 4 4 4 4 4 4 4 4 4 0 0 4 4 4 1 2 1 0 0 1 4 1 1 4 2 1 4 4 0
 [7453] 1 4 0 1 3 4 3 4 3 3 3 4 4 3 4 3 3 4 4 3 4 2 4 3 0 4 4 4 0 4 3 4 4 4 3 3
 [7489] 3 3 4 0 0 3 4 4 4 3 3 4 4 4 4 4 0 0 1 4 4 1 1 0 1 4 4 3 4 4 0 2 0 4 3 1
 [7525] 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 3 3 4 3 2 3 3 3 4 3 4 3 3 3 4
 [7561] 1 4 0 0 0 1 1 4 4 4 3 4 4 4 2 4 4 0 4 4 4 4 4 3 0 0 4 4 4 1 4 4 4 4 4 4
 [7597] 3 4 4 4 4 4 4 2 3 4 2 1 4 1 3 1 0 4 2 3 2 4 4 4 4 4 0 4 4 4 4 4 4 0 1 4
 [7633] 3 3 4 4 4 3 4 4 0 3 3 3 3 4 3 1 1 4 4 4 4 4 4 4 4 4 4 1 4 4 2 0 4 4 4 2
 [7669] 4 0 4 3 4 4 4 4 4 4 1 4 1 4 4 4 1 4 3 4 4 4 4 3 0 2 3 4 4 4 4 0 0 4 1 2
 [7705] 0 3 1 2 4 4 4 4 2 4 4 4 4 0 4 4 0 4 4 0 4 4 3 4 4 4 4 2 1 4 2 1 4 4 3 4
 [7741] 4 4 3 4 4 4 4 0 3 4 2 3 4 4 4 4 3 1 4 4 1 0 4 4 4 3 4 3 1 3 1 4 0 3 3 4
 [7777] 4 2 4 3 4 3 3 3 4 4 4 3 4 4 1 4 0 4 3 0 4 4 4 3 4 0 4 4 2 4 4 4 4 4 4 4
 [7813] 4 4 4 4 2 4 3 3 3 4 4 4 4 4 4 4 3 4 2 4 3 4 4 4 4 3 4 4 4 4 4 4 4 1 4 4
 [7849] 4 1 3 4 4 4 4 4 4 4 4 0 3 4 3 1 3 4 4 3 4 4 4 4 4 4 4 4 2 3 3 4 0 3 3 4
 [7885] 4 2 0 4 4 4 3 3 3 4 0 4 4 4 4 4 4 2 4 3 3 4 2 4 4 2 3 4 4 3 4 4 4 4 4 4
 [7921] 4 4 4 4 1 4 4 3 0 4 4 4 4 2 4 4 4 3 4 4 4 4 4 4 3 4 4 2 4 4 4 3 3 4 4 4
 [7957] 0 4 2 2 4 2 2 1 4 4 4 4 4 4 4 4 2 1 3 4 4 3 2 4 3 4 3 3 4 2 4 4 4 0 4 0
 [7993] 0 4 4 2 4 4 4 4 1 4 4 4 4 4 0 1 2 2 3 1 4 4 1 2 0 4 4 4 1 4 3 4 2 1 3 0
 [8029] 4 4 0 3 4 1 4 1 4 3 1 4 1 4 4 4 1 2 4 4 0 1 1 1 0 4 4 4 4 0 4 4 4 4 4 1
 [8065] 1 1 4 3 3 4 3 4 4 2 4 3 4 2 2 4 4 2 4 4 4 3 4 3 0 2 0 2 4 3 3 4 3 4 4 4
 [8101] 2 1 4 3 3 2 1 4 3 4 4 4 4 4 4 3 4 0 1 4 4 2 2 3 4 1 4 1 4 3 4 4 1 4 2 0
 [8137] 1 4 4 3 4 4 4 3 4 3 4 4 4 3 3 4 2 3 4 4 4 2 2 4 4 4 4 3 4 4 4 4 4 2 3 4
 [8173] 4 3 3 3 3 4 2 2 2 4 4 4 2 4 4 4 4 4 3 4 1 1 3 0 4 4 4 4 1 4 0 2 3 4 0 4
 [8209] 2 1 3 4 4 2 2 3 4 4 4 3 3 4 3 3 4 3 4 4 1 4 2 2 4 4 4 2 4 1 4 3 3 4 4 4
 [8245] 3 3 4 4 3 3 3 4 4 4 4 1 4 2 4 3 4 3 3 1 0 1 0 4 3 4 3 4 4 4 4 4 2 4 4 3
 [8281] 2 2 4 4 3 2 4 2 4 2 4 1 4 0 4 4 4 3 4 3 3 4 4 3 4 4 4 4 4 4 3 4 3 2 3 4
 [8317] 4 2 3 3 3 4 1 1 2 4 4 4 3 4 4 4 4 3 2 4 2 4 4 3 3 4 3 3 4 4 4 4 4 3 4 3
 [8353] 4 3 4 4 4 4 1 4 4 4 2 3 4 4 4 0 3 3 4 3 4 4 0 4 0 1 4 4 3 1 3 1 2 2 1 2
 [8389] 4 4 4 4 4 4 3 4 4 4 3 4 3 2 3 4 4 2 4 4 4 2 2 3 3 4 4 2 3 3 2 2 4 3 4 1
 [8425] 4 4 4 4 4 4 4 1 3 4 4 4 4 4 3 4 2 4 4 1 3 3 4 4 4 4 4 4 3 4 4 4 4 4 4 3
 [8461] 3 4 4 3 4 3 4 4 4 3 4 4 4 2 4 4 2 3 1 4 2 1 2 2 4 3 4 4 2 4 3 2 2 2 4 3
 [8497] 4 2 4 4 2 4 1 0 1 3 3 4 4 4 2 3 4 4 4 0 0 1 1 4 0 4 2 4 4 4 3 4 4 4 4 3
 [8533] 3 4 3 4 0 4 4 1 0 4 3 4 4 4 4 4 2 3 3 4 3 3 4 4 4 3 0 0 4 2 4 3 4 0 1 1
 [8569] 4 3 3 4 4 4 4 3 4 3 3 4 4 4 4 2 4 4 3 4 4 4 3 4 2 4 4 3 4 4 4 4 2 4 4 2
 [8605] 3 4 4 4 4 4 4 4 4 4 3 3 4 4 4 3 4 3 3 2 4 2 4 4 4 1 4 3 3 4 3 4 4 4 4 4
 [8641] 3 4 4 4 3 4 2 3 4 3 3 4 2 4 3 4 3 4 3 4 3 3 1 3 2 3 4 2 1 4 4 2 3 3 3 2
 [8677] 3 4 4 4 4 4 2 3 3 4 4 2 3 3 3 3 4 3 3 4 3 4 4 4 3 1 0 2 4 3 4 4 4 3 3 4
 [8713] 3 3 4 4 4 3 3 4 3 4 4 3 4 3 4 4 4 1 4 3 2 2 2 3 4 3 4 4 4 2 3 3 3 4 3 4
 [8749] 4 4 4 3 2 4 4 4 4 4 3 3 3 2 4 3 3 4 4 3 4 3 3 2 4 4 4 4 3 1 4 4 2 3 4 4
 [8785] 3 3 3 3 4 4 4 3 3 4 3 2 4 4 4 2 4 4 4 3 3 4 4 4 4 4 4 1 4 1 4 2 4 4 4 1
 [8821] 3 0 1 3 4 1 3 2 2 4 4 4 4 4 4 4 0 2 0 1 4 3 4 4 4 1 4 2 4 4 3 0 4 0 4 4
 [8857] 3 2 4 4 4 4 4 4 4 3 3 4 4 4 4 3 2 3 0 1 3 0 3 4 3 4 4 4 2 3 4 4 4 4 0 2
 [8893] 4 2 4 4 4 3 0 4 0 1 2 0 3 4 1 0 3 0 2 3 3 4 3 4 2 3 3 4 4 3 4 3 3 4 4 2
 [8929] 4 1 4 2 2 4 2 4 4 4 1 1 2 1 2 3 4 3 2 4 3 4 4 2 4 4 2 4 4 4 4 2 3 0 3 4
 [8965] 2 4 1 0 4 3 1 4 4 4 0 4 0 0 3 3 2 3 4 4 4 2 3 4 4 4 3 4 4 4 3 4 4 4 4 4

In [45]:
lgbregmin

    [1] 2.0940595 1.9779081 1.5594698 2.4796076 2.4899747 3.5399693 3.3242246
    [8] 2.6342503 3.1362022 2.3389487 3.1727935 3.1004212 3.5412325 1.9371410
   [15] 2.5606435 3.7123772 2.3518069 2.9517368 3.7133360 3.3710457 3.3187945
   [22] 3.2659890 1.5227444 0.9820881 3.3788747 3.2160074 3.1312969 3.4008380
   [29] 3.3204317 2.3367371 1.3329351 3.2092280 2.9540785 3.2592203 3.4371401
   [36] 3.3917249 3.3837020 3.0576098 3.4268718 3.5125774 3.6076439 2.4200612
   [43] 2.7420555 2.6729015 2.1742214 2.9078252 2.7851128 2.5046209 2.4368083
   [50] 2.9523967 2.9874834 3.0953358 4.0651579 3.3653389 3.1203165 3.5848219
   [57] 3.2840717 2.9307718 3.2932973 1.3561421 3.4729559 2.6735770 3.4847676
   [64] 2.6623221 2.8015423 1.9338655 3.0428946 3.2987712 1.1472544 2.0590516
   [71] 2.6611292 2.8480096 1.4791450 3.2841219 3.2558043 2.9961081 2.5193103
   [78] 2.9150473 3.3681465 3.6426015 3.1514662 3.6468864 3.3122183 2.1326338
   [85] 2.1683849 2.3851594 2.6381347 2.5571194 2.8188910 2.5163185 2.3844720
   [92] 2.3167313 2.1165191 2.8798532 1.7152165 2.4644542 2.1772166 1.6843476
   [99] 1.6006858 2.8278911 1.8396769 2.7566325 2.0682096 2.0852323 1.6167453
  [106] 1.9859638 1.6522854 1.3082557 2.4739149 2.0437541 2.4023379 1.5636377
  [113] 2.9574477 1.9037848 1.5337991 2.6771970 1.9281762 1.3487445 2.0776899
  [120] 2.4513323 2.1671474 1.0735235 2.6663658 1.2210907 1.5939357 2.4294550
  [127] 2.7461317 2.8577666 2.0477647 2.6845889 2.3742809 2.4974325 2.9157602
  [134] 3.3143452 2.7833060 3.3619884 3.0174957 2.8302664 2.6942198 3.4199886
  [141] 3.4961131 3.1885472 3.3385128 3.1409742 2.8154046 2.5069257 3.1649218
  [148] 3.0027439 3.1829882 2.5303644 2.8355470 3.4306223 2.9903963 2.0736013
  [155] 3.2388331 3.0986166 3.1605310 3.0686403 2.3611701 3.0703736 2.3896112
  [162] 3.4943451 3.2890951 3.0086095 3.4768555 3.0369620 2.9702069 2.2700360
  [169] 2.1902311 3.0381627 3.4777118 1.9627914 3.4051620 2.7447369 3.1686060
  [176] 1.1054048 3.1081102 2.0258252 2.7721812 3.2632660 2.3613917 2.9305753
  [183] 3.0595791 2.4585989 2.1309083 2.1881745 2.1642189 2.3329662 2.5359619
  [190] 2.2330057 1.2159994 1.4309694 2.3149476 3.3753747 3.1470246 2.6431306
  [197] 1.6917326 2.4074160 1.6518761 2.4312044 1.6991146 1.9758222 1.8334380
  [204] 1.9962000 1.6395483 1.8816822 1.5395854 3.4373171 1.9656119 1.7335992
  [211] 1.8024130 1.8155500 2.1044018 1.5265164 2.4170142 2.4288374 2.0632218
  [218] 2.2709959 2.6519527 3.1522462 2.9678180 3.0081028 2.3487223 1.8316609
  [225] 2.8494635 2.0654089 2.5255766 1.9758443 1.1965622 2.0740844 1.5297039
  [232] 1.2297390 1.8352907 2.3067531 2.0924917 2.6705568 2.6543748 1.5355691
  [239] 2.5449240 3.5380468 3.7051488 3.2169130 1.3876431 3.4588617 3.4428312
  [246] 3.4828788 3.5355857 3.1559201 2.0201425 3.2516059 3.3339492 3.3166233
  [253] 2.6191952 2.8667111 0.8632401 2.5590516 2.8120692 2.9966521 2.3506475
  [260] 3.0591853 2.3645514 1.5289661 3.0859671 2.6334617 2.6950548 0.9098828
  [267] 2.6530490 2.1102500 3.1274746 1.9496420 1.8960421 1.9993984 3.3806761
  [274] 2.3860758 3.4711219 3.1174485 1.2411146 2.8136522 3.1344118 2.4769353
  [281] 2.2617363 2.2663235 3.3144583 1.9506372 2.9426903 2.2602982 1.9172145
  [288] 2.7069549 2.1737069 2.2661249 2.3170739 3.5055136 3.7789457 1.9269461
  [295] 1.0743571 2.7440195 2.3996853 3.2829021 1.7313292 3.4710587 3.1196649
  [302] 3.2612102 2.2491854 2.6304589 1.4603118 1.7521018 2.2731717 2.5332442
  [309] 1.3017693 1.8585739 2.0097877 1.4201390 1.6482368 1.6260111 1.8142612
  [316] 1.8668869 2.3312665 1.4243153 2.2812202 1.9383815 3.2807771 2.7908353
  [323] 3.0887569 1.9515848 1.6206782 2.1499664 1.6383211 2.3858575 3.3351065
  [330] 1.3898530 3.3634296 1.9083181 2.1768271 3.0992969 2.2170299 2.5555021
  [337] 2.5241709 2.9633109 3.1428352 1.9142970 2.2473307 1.5428013 1.9956715
  [344] 2.0420314 3.2300339 2.5194608 1.5038721 3.1088844 2.3290728 3.1472076
  [351] 2.3073497 1.5520962 1.8169431 3.4488060 2.4831723 2.3261621 1.6521554
  [358] 1.8174196 1.5513073 2.1357588 2.8232992 3.2146294 1.9884001 2.0112289
  [365] 3.2644715 1.3531397 3.1485311 3.7932802 3.2815815 1.1089336 3.0874363
  [372] 2.9872442 3.5076659 2.2058953 3.2408885 3.3220927 3.9643391 3.0803816
  [379] 2.9121788 2.8338928 3.3241124 3.8604749 3.3511007 2.7643091 3.1946283
  [386] 3.3618600 3.3431014 2.7655479 1.8317008 3.8063499 2.8885458 3.5018790
  [393] 3.1958132 3.5937140 3.8092644 1.9623264 3.6092039 1.9147218 2.6282448
  [400] 2.8249511 3.2067315 3.5500781 2.9521561 3.5928774 3.2243915 3.2570549
  [407] 3.3408018 3.0941122 3.3323334 3.2188523 3.7426569 2.7159493 3.6314330
  [414] 1.9274669 2.0926152 3.5981526 2.9125492 2.8040500 2.8833572 3.6568440
  [421] 3.3107461 3.7039764 3.0675622 3.0585148 3.4523374 3.1950339 2.7915770
  [428] 1.6276403 3.5154961 2.1210335 3.0460350 3.3086797 2.3744068 3.5740665
  [435] 2.4354853 2.2338942 1.9553651 1.6622057 2.7193076 3.2698234 1.7559030
  [442] 3.2000272 3.4197038 3.2347428 3.7402199 2.5319540 3.6377282 3.7940802
  [449] 1.8390774 2.3292078 3.0936927 3.0350212 3.6598739 2.2093547 2.3295139
  [456] 2.6146492 2.2950267 3.2282775 2.1574855 3.4488567 2.0125790 1.7817560
  [463] 2.8097839 2.1726670 3.5068605 2.5482761 2.5934324 3.1941380 3.2790949
  [470] 1.9347388 2.0069338 2.0945291 2.2254608 2.9342046 1.5066729 3.4676484
  [477] 3.4731569 2.3057036 2.4053114 3.0771036 2.8457268 1.7640107 1.5538377
  [484] 3.6503491 3.0814698 1.5459643 2.1820487 2.7037677 1.5388493 1.8783273
  [491] 2.8007467 3.3121141 2.6974204 3.7539683 3.7113189 3.0807418 3.4347239
  [498] 3.5497569 1.4596985 2.4602557 2.9153536 1.1059998 2.4859868 3.0781242
  [505] 3.5259335 3.4788038 3.2987835 2.9296512 2.6336639 2.8457268 3.3424241
  [512] 2.5714179 1.3029621 3.6758477 3.1736203 3.5372928 3.0221424 2.5407730
  [519] 2.9060411 2.4184199 3.3481275 3.1245202 3.2844328 2.8453292 1.3154365
  [526] 2.1171308 3.5979303 2.8086754 1.3816412 2.7757234 3.5486451 1.3354173
  [533] 2.2830018 2.4580192 3.3286443 3.2004069 1.9741373 2.0413879 3.0821177
  [540] 3.0821177 2.8379743 1.5047609 3.0555656 3.1349489 2.8090501 3.7831050
  [547] 1.7333443 3.5462661 3.4084232 2.1199977 2.3835854 3.4002467 2.5467603
  [554] 2.7576095 3.2975753 3.2275156 3.3864024 3.5138130 2.6971815 2.3305211
  [561] 2.6478816 3.6571383 3.4621582 2.7784278 3.6429191 3.6065495 3.4226338
  [568] 3.3768884 3.2774850 3.2466394 3.3969322 3.1309766 3.2698266 3.0755799
  [575] 3.3872615 3.4132029 3.1631556 3.4709934 3.6243927 3.3608603 1.8606698
  [582] 2.6591039 1.5120476 1.7046330 1.5335634 2.8382789 2.3569216 1.7549505
  [589] 3.7030743 1.7962257 1.5094706 3.0144560 2.8455466 3.2633634 1.7334730
  [596] 2.7687880 2.8942124 0.8412198 1.5094096 1.4620217 3.2818494 1.6325913
  [603] 1.4334614 3.3087977 2.2845957 2.5904995 3.1442457 2.9694660 3.5794369
  [610] 2.9028947 2.6167674 2.7153841 1.7616884 2.6199045 1.0691300 2.8131875
  [617] 2.7097949 2.8934189 3.0994914 2.2447474 2.6082653 2.1762087 2.6888015
  [624] 2.8412143 2.8199623 3.0505466 2.2635317 1.3133783 2.7533049 2.2298744
  [631] 1.2041574 1.9104753 2.4041615 2.8966515 2.2164984 2.7428595 2.1313235
  [638] 2.0128379 2.5573228 1.6474273 2.1720294 2.8017521 3.2476011 2.6503655
  [645] 2.2570032 3.6430347 2.5133243 2.8016091 2.1113913 2.7122328 3.4492966
  [652] 3.2682719 3.2196351 1.3797109 2.6672625 1.5414409 1.6298765 2.1926717
  [659] 2.6162715 1.6650290 2.1565531 0.9001786 1.8855940 2.1579860 1.7928256
  [666] 1.8975417 1.6538789 1.5141337 1.3272779 2.3331195 2.2950663 2.4795986
  [673] 2.7923587 2.9909847 2.9654212 2.8038433 2.3873210 2.8644046 3.4011682
  [680] 3.1649215 2.5270385 3.4273210 3.2322225 3.0736998 3.1638571 1.5290621
  [687] 2.7531345 3.0710944 2.0259372 3.3470098 1.1997903 1.2130572 2.2747162
  [694] 2.0599962 1.9571051 1.1440109 2.9731368 1.5090969 2.0086092 2.7679630
  [701] 2.7707332 2.5883927 2.8092844 1.1706410 1.6669789 1.3212811 1.2819581
  [708] 3.1022172 2.8963675 2.8348168 3.0286160 1.9985628 1.5150274 2.6820551
  [715] 3.0666458 1.9248979 2.6507008 1.5940798 1.9038339 2.9867676 1.5118997
  [722] 3.2592060 2.7220962 2.7157178 3.0039869 2.9259399 1.8503064 2.9373707
  [729] 1.6480367 2.0148170 2.7292070 2.2798356 2.4706063 3.0224177 3.0406995
  [736] 1.7966161 1.5617994 2.8411016 1.4416733 1.9538181 1.7800081 2.0401392
  [743] 1.3644811 2.2451731 1.9285687 1.7756510 1.4028912 2.5790125 3.0938362
  [750] 0.8957389 2.3716805 2.5802969 2.1087019 3.2174591 3.1520044 3.5053292
  [757] 3.0428924 2.7991778 2.7518617 2.2459295 1.6438974 2.3420165 3.2849593
  [764] 2.7709770 2.2825130 2.7901906 2.6383242 1.3350924 1.9696609 1.7543405
  [771] 2.1584731 2.8964703 1.6454030 2.3281942 3.0203183 2.3019050 1.6523927
  [778] 2.2050954 2.5127360 3.1844895 2.5851401 2.7488690 2.5347450 2.6019948
  [785] 2.9359931 1.7105321 1.7591707 2.4332383 2.5130731 2.2979660 3.1090338
  [792] 2.3460551 2.5050675 2.7440379 1.6143895 1.8659527 1.6115260 2.1803676
  [799] 1.8913936 2.1662835 1.8317313 2.3672316 3.0643982 1.9217047 2.4221262
  [806] 2.4381514 3.4648685 2.3094937 2.8064858 1.5259921 2.1998830 3.0185761
  [813] 2.0307302 3.0583095 1.5890957 1.9985811 1.9533013 1.9111602 2.1670805
  [820] 2.1581103 1.4355476 2.4744544 0.9362870 2.2825282 2.4266066 2.1674029
  [827] 3.5194322 1.9347941 1.8205457 2.3709660 2.5015085 1.5887396 3.0722239
  [834] 1.7527891 3.5169337 3.1393971 1.6270091 2.0550559 1.4233544 0.7592360
  [841] 1.1089603 3.0085028 1.8881545 1.8432659 2.0906926 2.2990573 1.9166543
  [848] 1.7941684 1.9709971 2.8592332 2.7470647 2.8905207 3.0306339 3.0441539
  [855] 2.5002573 3.6399779 2.0335534 3.2447827 1.4629558 1.5467656 2.3345887
  [862] 3.0489446 2.8783342 1.3454033 2.9779345 2.6823352 2.3946786 1.5354020
  [869] 2.4626180 2.0780877 2.1725144 3.1483635 1.8316979 3.4026118 1.7920609
  [876] 3.1195774 2.5362737 3.0827882 3.1735937 2.8189872 3.0830575 1.7297642
  [883] 2.5779142 2.7114584 3.0618905 1.2895629 2.8972267 2.9613651 2.9203530
  [890] 2.3267499 2.9143453 0.9622214 2.7939374 1.7742701 2.3606073 2.1076663
  [897] 1.7606961 2.5802204 1.9369189 2.1384391 2.4172437 2.1344424 2.8849139
  [904] 2.6793681 3.0388339 2.2362257 2.8035159 2.8128390 3.0349504 2.4048117
  [911] 1.9608834 2.4858741 2.4607695 1.9229242 2.6238230 2.9285604 2.2667409
  [918] 2.1768570 2.7824099 2.5144556 2.3981136 1.8974582 2.5570073 1.8916866
  [925] 2.7731940 2.3575719 1.6485262 2.3432507 2.6217770 2.0794687 3.0226228
  [932] 2.1742956 2.4907967 2.6103841 2.4860848 2.4821162 2.1390446 2.2712095
  [939] 2.6900752 2.0657231 2.3981674 2.5134419 2.5697471 2.4017548 2.6173158
  [946] 2.5400629 2.9443018 1.9854659 2.8251571 2.3932502 1.9098024 1.5551436
  [953] 2.8794873 2.5384916 1.4254246 2.3001523 1.6241540 2.4256182 3.0601374
  [960] 3.0897449 2.1498605 2.0762388 2.1983793 1.5958365 1.7731258 2.4032981
  [967] 2.5711397 2.0355286 3.4243982 1.1124915 1.6067508 2.8327270 3.3011691
  [974] 2.5485981 2.7131479 1.0620316 1.6861522 2.5807225 2.2402322 2.2959449
  [981] 1.4967742 2.6367977 2.3368393 1.3894195 2.3791113 2.3917012 2.2388312
  [988] 2.0703645 1.7987320 2.6142003 2.4026397 3.1289387 2.0244637 2.2755780
  [995] 2.0753663 1.7956980 2.2318030 2.6460451 2.5447341 1.8138809 3.0456630
 [1002] 2.6334020 2.8560818 2.3690655 2.2663626 2.6452347 1.8059716 2.5385105
 [1009] 2.4710310 2.7967591 2.8664053 2.4713974 2.3160058 2.7670403 2.2142020
 [1016] 2.5507908 3.1014790 1.9022917 2.4607639 1.9998348 2.8862403 2.8892757
 [1023] 2.7497828 2.2080059 2.8936537 2.4819940 3.1571657 3.1771557 2.2984900
 [1030] 2.2678407 0.9343424 2.4500673 3.2980833 1.6874633 3.0672698 1.9249744
 [1037] 1.9236232 3.0455033 3.4642249 2.8693876 2.9557392 1.9751310 0.5445977
 [1044] 2.9280355 2.7398202 1.6671833 2.9416320 2.4589823 1.7812372 2.4444751
 [1051] 1.5466159 2.7473933 1.7172808 2.0799670 3.0279089 0.6774469 2.5672021
 [1058] 1.2250017 2.3010305 2.6400168 2.3252097 2.8972295 2.2050439 3.4164804
 [1065] 2.3024201 2.4085643 2.7068919 2.1476864 2.8604794 2.3534876 2.5197714
 [1072] 3.2814874 1.7735386 1.8014055 1.8860172 2.9292478 2.3094117 1.9855414
 [1079] 1.8565557 1.6782372 2.3558752 2.2443055 2.5210967 2.4712540 1.9367722
 [1086] 2.1881465 2.0276585 1.1407124 2.4699784 1.4397885 1.8535171 1.7879903
 [1093] 2.6462735 3.5216945 3.1219855 2.8739068 2.9309977 3.0376739 2.1525974
 [1100] 3.7133812 2.6604478 2.2739455 2.4313762 2.7902845 2.8737398 3.4547364
 [1107] 3.2285865 1.5062330 1.5244404 3.1550948 2.2675540 3.4890574 3.1022212
 [1114] 1.1639248 2.8434350 2.3123439 2.9240444 2.0464932 1.3561154 2.1180547
 [1121] 2.8292436 3.3097143 2.4376692 2.1685810 2.9045888 3.7332412 3.1246308
 [1128] 1.2701671 3.0535744 2.2991332 2.6165214 1.5747329 2.2117997 1.5864105
 [1135] 2.0045185 2.6066194 2.6256021 1.6388619 0.9671069 0.7421583 3.5147900
 [1142] 2.8058137 2.9516822 2.9914320 2.6264237 2.6930250 2.2931143 2.5345688
 [1149] 3.8104181 2.7424128 2.8620298 2.7476385 2.5302296 2.4551224 3.5230554
 [1156] 2.5879537 2.6696975 2.8878368 3.0458450 1.7217462 1.2856262 1.7205391
 [1163] 1.2000090 3.6907521 2.1874643 2.2452445 2.9864533 1.3128655 2.1168894
 [1170] 2.0271507 2.7229622 1.9118839 2.1835649 3.8399318 3.5380686 3.3394611
 [1177] 2.1311248 3.3046826 2.1870875 1.8844152 2.4244386 2.7524921 2.9688464
 [1184] 1.5395613 2.6134278 2.3705548 1.7996520 2.2750729 2.6074467 2.9295752
 [1191] 2.3282887 2.3938939 1.3430870 2.7586264 2.7289184 1.6843156 3.0989655
 [1198] 1.8272173 1.1074125 2.5461623 3.2678143 2.9426098 3.7183949 3.3481922
 [1205] 3.3828787 2.9444220 2.7379976 2.5207835 3.5629919 2.1670025 1.7950793
 [1212] 3.4324257 3.4816848 2.1877665 2.6471085 2.6677935 2.9266140 2.7548915
 [1219] 3.4315803 1.7613494 1.1543332 2.5283817 2.7303032 2.8376519 1.9176018
 [1226] 3.0626356 2.8826072 3.7425145 2.8353899 2.8521749 3.5363606 3.9558352
 [1233] 3.7478423 2.5235253 2.8587293 2.0146790 1.7982485 3.4939223 2.5547921
 [1240] 2.2752285 3.5367164 2.4102626 2.5574442 1.5733883 2.3045405 3.2977914
 [1247] 3.2394201 2.2193091 1.9247409 2.3648900 2.9023154 1.5782050 2.3782126
 [1254] 1.4644366 0.6639160 2.4599726 2.1951550 1.9920448 2.1957475 2.1587827
 [1261] 2.6568457 1.8776240 1.8962344 1.8891772 1.1079908 1.7537795 2.4487390
 [1268] 2.7157344 2.9439179 3.5524909 3.4903422 3.0585736 2.0310048 2.5892417
 [1275] 3.5075123 3.2289242 3.0967815 3.7783059 3.5263394 3.9337804 3.2521695
 [1282] 2.6014042 3.5791883 3.5007182 3.4399537 3.5316862 3.5170422 2.1719693
 [1289] 2.6462389 3.4599210 3.2436554 3.6093880 2.1570800 3.2722100 4.1317622
 [1296] 3.8862508 3.5780957 2.4170661 1.8851326 3.9571919 2.7088602 2.4191423
 [1303] 3.3135455 3.2037899 3.4022412 2.4820402 3.0910321 3.1662389 3.9622758
 [1310] 1.9419104 3.2990843 2.6481855 3.3347477 3.7774252 2.9885322 3.4232184
 [1317] 3.7426047 3.0893767 1.0059239 2.7069121 1.5177636 3.7325711 3.2511442
 [1324] 3.4773098 3.0375519 3.5503550 2.8502212 3.0064001 2.9929557 3.3574097
 [1331] 1.0536409 3.3292496 2.8094856 3.1793501 2.4037737 3.6650651 3.2655291
 [1338] 2.6249346 2.9371572 3.9032591 3.3977975 3.0667390 3.0989960 2.7597298
 [1345] 3.9026443 2.7553624 3.6072402 3.2724948 2.9182359 3.6010559 1.6409924
 [1352] 4.0712306 2.9755158 2.8094603 2.2270696 2.7371297 2.2213522 3.5561549
 [1359] 3.3207489 3.4856612 2.3880733 2.9557726 3.4439259 2.7498859 2.9454212
 [1366] 3.3779428 3.1048730 1.0868511 3.1331326 3.6160485 3.2177990 3.4224795
 [1373] 3.4143373 3.1786661 2.9234241 2.2211183 2.0651114 1.7633632 1.6530273
 [1380] 3.7548824 3.1559965 3.5525847 3.1422276 1.7431905 3.4647664 1.0787591
 [1387] 3.4272167 2.6377452 2.6348871 3.3753983 2.7856438 3.2402978 1.8702083
 [1394] 1.1004942 2.7788562 2.1269452 2.4942475 2.7742723 2.6257781 3.6499516
 [1401] 3.8737778 1.2285918 3.1233411 3.5108207 2.1541784 2.9961953 2.1231328
 [1408] 3.1757294 2.6899299 1.9058935 3.2515500 3.0921384 3.1972468 3.1787663
 [1415] 2.6245523 3.5637276 2.1024651 2.0758384 3.3144622 3.4707013 1.6799377
 [1422] 3.0782105 3.5442774 1.6385922 3.6863351 2.3751206 3.7043644 3.2680263
 [1429] 1.8803743 2.6018279 2.5401457 2.0641076 2.6127335 3.2632935 2.8967723
 [1436] 3.0237220 2.5782638 2.8002307 2.0743066 1.8497991 2.6818745 2.6004074
 [1443] 2.0450442 2.4795157 3.6653326 3.4842164 3.2689485 2.0534449 3.1678532
 [1450] 2.9707220 3.7044171 3.6321496 3.5831813 3.2287182 2.9710750 3.1316666
 [1457] 3.6019581 3.0830206 1.5140466 3.0577689 2.8551446 3.4484473 2.7656002
 [1464] 2.7732869 3.3453714 3.3701435 3.1884839 3.2785078 3.7826114 2.4441101
 [1471] 3.3162199 3.5671032 1.6983231 1.7306434 3.0122578 3.1884839 3.5889084
 [1478] 1.7335317 3.3816748 3.4339223 2.7012007 3.3470844 2.8077104 3.0792706
 [1485] 3.2891299 3.6453543 1.4871165 2.2736528 3.6766561 2.5877931 3.2258634
 [1492] 2.7952382 3.4711537 3.4228139 3.6159909 3.5677401 3.0408122 2.6874971
 [1499] 3.4011037 3.8117482 3.0824026 3.5038632 3.3595052 3.7921236 3.4203053
 [1506] 3.3721737 2.3107856 2.9398554 3.2802166 3.3229336 3.7222463 3.3183598
 [1513] 3.2843257 3.5280705 3.2643110 3.7043061 2.9994370 3.1601698 2.0830648
 [1520] 3.3037633 3.6925135 2.0701151 3.7556183 3.0728896 1.8493590 2.6739214
 [1527] 3.8056735 3.5897297 3.4552300 3.2325330 1.2027799 1.9579065 2.9277439
 [1534] 2.4664052 2.2278576 2.8272300 3.1855938 2.1991434 3.0726385 3.0102151
 [1541] 2.4617772 1.8873557 2.4762026 1.9342104 2.4003258 3.0287236 2.0423137
 [1548] 2.5370059 2.2653131 3.3462018 3.4929021 3.2733827 3.3912430 3.3437876
 [1555] 2.3891520 3.0255421 3.0457641 2.9580029 2.5907857 3.1062263 3.2607411
 [1562] 3.2033088 1.4236340 2.3844672 3.2464374 3.2872780 2.8143854 3.5121780
 [1569] 3.5002751 3.4760078 2.9095685 2.7756970 3.4802892 3.3393247 2.7040653
 [1576] 3.3492825 3.0128091 3.5073936 1.4876247 2.5579708 3.5414239 3.7140049
 [1583] 3.4781806 2.9793690 1.2874309 2.5634660 2.8359411 3.1228249 2.5385223
 [1590] 2.8941774 3.2176125 3.3028205 2.9283834 2.0447967 3.8897586 3.0762877
 [1597] 3.0047918 3.0912861 3.5185525 3.4514142 3.4368896 3.2460854 3.3799381
 [1604] 3.2496600 3.0319602 3.0729852 3.2167880 3.2673985 3.3769024 3.5093117
 [1611] 3.4272281 3.4725247 3.4389515 2.8360105 2.2393367 2.7442374 2.8709782
 [1618] 2.9387086 3.3787225 3.0665788 2.1779110 2.6051977 2.5202462 1.7523134
 [1625] 1.8548872 2.5171733 3.4258274 3.2632298 2.7010808 2.7582711 1.5395239
 [1632] 0.7858226 1.9147766 1.9869836 3.0946375 1.8147156 2.7843473 3.1128862
 [1639] 3.5704553 1.3051322 1.2616327 1.3698696 2.1142176 3.3835350 3.0451520
 [1646] 1.2216861 1.3150318 1.7349146 3.7059744 1.3050717 2.9753102 2.0017727
 [1653] 2.1266042 2.7796287 2.7197335 2.5851992 2.3355348 3.2161066 1.9750372
 [1660] 2.5141893 1.9488899 3.5527922 3.1137879 2.8614142 2.8722386 1.4944354
 [1667] 1.2918183 1.6006985 3.0130308 2.0142883 3.0563887 2.1277991 3.5365467
 [1674] 2.9917402 3.1677145 3.5691144 1.8295926 2.8246993 2.7860663 2.8948673
 [1681] 3.2260973 1.4550936 2.0753052 2.6304488 1.8608994 3.2017722 3.4031481
 [1688] 1.9972234 3.5478337 3.4020607 3.3355869 2.8433351 3.3546837 3.2354782
 [1695] 2.7661971 3.0540133 1.4518979 1.3861092 1.1842742 2.5880784 2.3512160
 [1702] 2.5484988 1.8300120 2.8699344 2.5977379 3.2259832 2.9740325 3.1658068
 [1709] 3.4080479 3.2017467 3.4346097 3.2886522 2.0313503 3.0683867 3.6917212
 [1716] 3.6595438 3.1095132 2.9553614 3.4329994 3.2847228 2.6869383 3.3842662
 [1723] 3.4561461 3.3358350 3.3077115 2.6911317 3.5581730 3.2013851 2.7476046
 [1730] 3.4168988 3.4589632 3.6794062 3.1561234 2.9267909 2.0341396 3.0337838
 [1737] 3.1885078 2.6907472 1.4352748 1.4658284 2.0269429 1.9085489 3.4037683
 [1744] 3.1117458 2.7266899 2.4998178 2.9937409 3.1244987 2.8899369 1.8125429
 [1751] 3.0916582 2.0489016 2.3695580 2.4670323 2.0683055 1.4533661 3.0524548
 [1758] 3.3002126 3.4917107 3.3508219 3.2049611 2.5842681 2.7315151 3.5421101
 [1765] 3.4188828 2.5222682 2.7208148 2.5663863 2.9506538 1.8951478 1.6761245
 [1772] 1.5841235 2.9241847 2.9708232 3.2722881 3.0163465 3.6152499 2.5532694
 [1779] 1.8599096 3.0754380 1.2047338 2.3727580 3.2952216 2.2028415 3.1658688
 [1786] 2.4204717 3.5932643 2.7828379 2.0900971 2.8794133 2.6522717 1.0043834

In [46]:
lgbclsmin

      [,1]        [,2]       [,3]        [,4]        [,5]
 [1,] 0.11820129  0.11073954 0.12212549  0.40273598  0.2461977
 [2,] 0.39125011  0.06710329 0.07239889  0.11725205  0.3519957
 [3,] 0.10023454  0.43481672 0.16374003  0.17030878  0.1308999
 [4,] 0.08339521  0.12985937 0.16171648  0.43100016  0.1940288
 [5,] 0.07780959  0.18311479 0.08733764  0.29398670  0.3577513
 [6,] 0.05651462  0.06881728 0.02057611  0.04011412  0.8139779
 [7,] 0.05893760  0.10527460 0.01260033  0.07721942  0.7459681
 [8,] 0.16010521  0.05311854 0.06826877  0.09769072  0.6208168
 [9,] 0.06156876  0.04802166 0.07550915  0.12387367  0.6910268
[10,] 0.15719416  0.05137750 0.36746719  0.09079477  0.3331664
[11,] 0.09607358  0.03233565 0.04057739  0.05989839  0.7711150
[12,] 0.07658105  0.12113250 0.05617501  0.14701878  0.5990927
[13,] 0.05177457  0.03334238 0.03296535  0.05337061  0.8285471
[14,] 0.15892178  0.14073573 0.20270488  0.11483924  0.3827984
[15,] 0.06405133  0.27590678 0.11128209  0.18006278  0.3686970
[16,] 0.09327559  0.01564244 0.01446392  0.03069247  0.8459256
[17,] 0.12768361  0.14257364 0.10830288  0.08786699  0.5335729
[18,] 0.17197023  0.05829245 0.05324816  0.10382016  0.6126690
[19,] 0.02762755  0.01926824 0.02221867  0.07518980  0.8556957
[20,] 0.10924153  0.03293726 0.02522590  0.10972050  0.7228748
[21,] 0.07841157  0.03311741 0.02026995  0.07955438  0.7886467
[22,] 0.08898512  0.01660146 0.02245561  0.13050857  0.7414492
[23,] 0.36841925  0.05106683 0.35475764  0.05352872  0.1722276
[24,] 0.52268771  0.09054486 0.04820966  0.03973052  0.2988272
[25,] 0.07448586  0.01987260 0.02656585  0.11009890  0.7689768
[26,] 0.13695069  0.02055392 0.08170115  0.06755172  0.6932425
[27,] 0.04148323  0.01457269 0.01983238  0.05220017  0.8719115
[28,] 0.04562710  0.02465910 0.01721667  0.06034499  0.8521521
[29,] 0.10109551  0.03540899 0.04039176  0.19978702  0.6233167
[30,] 0.14513645  0.17361763 0.10169026  0.08104449  0.4985112
[31,] ⋮           ⋮          ⋮           ⋮           ⋮
[32,] 0.270128963 0.11428889 0.372794635 0.125264001 0.1175235
[33,] 0.325012382 0.09323247 0.329205614 0.131355760 0.1211938
[34,] 0.188003964 0.06905402 0.336377653 0.260153504 0.1464109
[35,] 0.268265229 0.24589382 0.080272755 0.113358950 0.2922092
[36,] 0.077364891 0.02447019 0.034104178 0.076914097 0.7871466
[37,] 0.521364705 0.02508011 0.081284539 0.086645511 0.2856251
[38,] 0.059864182 0.05230448 0.057112711 0.543095532 0.2876231
[39,] 0.062482422 0.03926003 0.066454480 0.147521100 0.6842820
[40,] 0.705266290 0.05624221 0.034851850 0.084709076 0.1189306
[41,] 0.140345032 0.08619147 0.311008177 0.091882349 0.3705730
[42,] 0.669153739 0.04564687 0.048802874 0.117043473 0.1193530
[43,] 0.455755935 0.11128284 0.050114445 0.117310160 0.2655366
[44,] 0.086040045 0.24379879 0.501681130 0.037125436 0.1313546
[45,] 0.217252968 0.21909993 0.293506705 0.068063231 0.2020772
[46,] 0.137155226 0.18133918 0.457033188 0.072533611 0.1519388
[47,] 0.126523947 0.38315776 0.212189657 0.115533406 0.1625952
[48,] 0.030518688 0.04039652 0.047666514 0.029864498 0.8515538
[49,] 0.008159029 0.01819247 0.017192797 0.138901244 0.8175545
[50,] 0.027332951 0.03957995 0.087992206 0.488427427 0.3566675
[51,] 0.068964928 0.05811915 0.050090330 0.089856342 0.7329692
[52,] 0.021072588 0.05741769 0.067215259 0.232497383 0.6217971
[53,] 0.003128048 0.01359815 0.006875338 0.006284126 0.9701143
[54,] 0.016555056 0.06378306 0.408333134 0.187873123 0.3234556
[55,] 0.028101861 0.01987477 0.033840856 0.061129596 0.8570529
[56,] 0.013706693 0.09088446 0.106490825 0.208440978 0.5804770
[57,] 0.024652762 0.05557207 0.074649635 0.150884128 0.6942414
[58,] 0.167199487 0.33084965 0.188485238 0.127865035 0.1856006
[59,] 0.093707964 0.36679390 0.127530902 0.207283915 0.2046833
[60,] 0.058097214 0.02456441 0.057888394 0.186262832 0.6731872
[61,] 0.075465349 0.11575376 0.084247999 0.239421752 0.4851111

In [47]:
datalength=dim(data)[1]
lgbclsm=matrix(lgbclsmin,m,datalength)
lgbclsminr=matrix(0,datalength,1)
for(i in 1:datalength)
    {
    lgbclsminr[i,]=which.max(lgbclsm[,i])
}
lgbclsminr=lgbclsminr-1

In [48]:
lgbclsminr

      [,1]
 [1,] 1
 [2,] 2
 [3,] 3
 [4,] 2
 [5,] 3
 [6,] 4
 [7,] 0
 [8,] 2
 [9,] 1
[10,] 3
[11,] 4
[12,] 4
[13,] 3
[14,] 0
[15,] 2
[16,] 3
[17,] 3
[18,] 2
[19,] 2
[20,] 1
[21,] 4
[22,] 1
[23,] 3
[24,] 2
[25,] 3
[26,] 3
[27,] 0
[28,] 3
[29,] 4
[30,] 4
[31,] ⋮
[32,] 3
[33,] 0
[34,] 2
[35,] 3
[36,] 1
[37,] 4
[38,] 2
[39,] 2
[40,] 4
[41,] 3
[42,] 1
[43,] 3
[44,] 4
[45,] 1
[46,] 4
[47,] 4
[48,] 0
[49,] 3
[50,] 2
[51,] 2
[52,] 3
[53,] 3
[54,] 1
[55,] 4
[56,] 4
[57,] 2
[58,] 1
[59,] 1
[60,] 1
[61,] 0

In [49]:
xgbregmean=predict(xgb_mean_reg,alldataxgb)
xgbclsmean=predict(xgb_mean_cl,alldataxgb)
lgbregmean=predict(lgb_mean_reg,as.matrix(data))
lgbclsmean=predict(lgb_mean_cl,as.matrix(data))

In [50]:
lgbclsm=matrix(lgbclsmean,m,datalength)
lgbclsmeanr=matrix(0,datalength,1)
for(i in 1:datalength)
    {
    lgbclsmeanr[i,]=which.max(lgbclsm[,i])
}
lgbclsmeanr=lgbclsmeanr-1

In [51]:
preallmin=cbind(xgbclsmin,xgbregmin)
preallmin=cbind(preallmin,lgbclsminr)
preallmin=cbind(preallmin,lgbregmin)

In [52]:
colnames(preallmin)=c('xgbclsmin','xgbregmin','lgbclsmin','lgbregmin')
head(preallmin)

     xgbclsmin xgbregmin lgbclsmin lgbregmin
[1,] 3         2.337117  1         2.094060
[2,] 0         1.792584  2         1.977908
[3,] 1         1.255076  3         1.559470
[4,] 3         2.551001  2         2.479608
[5,] 4         2.596719  3         2.489975
[6,] 4         3.629522  4         3.539969

In [53]:
preallmean=cbind(xgbclsmean,xgbregmean)
preallmean=cbind(preallmean,lgbclsmeanr)
preallmean=cbind(preallmean,lgbregmean)

In [54]:
head(preallmean)

     xgbclsmean xgbregmean   lgbregmean
[1,] 0          1.123992   1 1.339693
[2,] 0          1.363831   2 1.414877
[3,] 1          1.152056   3 1.256118
[4,] 3          2.121927   1 2.138096
[5,] 0          1.961321   2 1.753921
[6,] 4          3.597152   4 3.627251

In [55]:
colnames(preallmean)=c('xgbclsmean','xgbregmean','lgbclsmean','lgbregmean')
head(preallmean)

     xgbclsmean xgbregmean lgbclsmean lgbregmean
[1,] 0          1.123992   1          1.339693
[2,] 0          1.363831   2          1.414877
[3,] 1          1.152056   3          1.256118
[4,] 3          2.121927   1          2.138096
[5,] 0          1.961321   2          1.753921
[6,] 4          3.597152   4          3.627251

In [56]:
end_time = Sys.time()
time_matrix[4,]=end_time-start_time

In [57]:
result_list=list(preallmin,preallmean,time_matrix)

In [58]:
save(result_list, file = "Yearly_nnetar_opt_pre_result.RData")

In [59]:
time_matrix

     user_time system_time elapsed_time
[1,] 10.120406 10.120406   10.120406
[2,]  2.415596  2.415596    2.415596
[3,]  2.409725  2.409725    2.409725
[4,]  1.677931  1.677931    1.677931